### ISSUE TITLE
有关浮动体过多产生的不良后果

### ISSUE THREAD

**Issue by muyuuuu** [CTeX-org/forum#10]
## 编译环境：Windows10+texlive2018+xelatex

文档类：ctexart。

问题描述：
原谅我此时可能提供不了MWE，十分抱歉。但是可否讨论一下下？

在一页中使用了较多的浮动体的情况下(4,5个左右)，为什么有的图片没显示出来，没有报错但是就是不显示。

我在那堆浮动体中央强行`\newpage`了一下，那个不显示的图片在新的一页才重新显示出来。

当时在比赛，时间紧迫也没来得及问，后来代码也被修改了，实在提供不了MWE，抱歉。可否讨论下这种现象出现的原因？

**Comment by muyuuuu** [comment]
记得Lshort上只说过一句：一页默认不超过3个浮动体，是这个原因嘛
![image](https://user-images.githubusercontent.com/43681138/52318401-49056380-29ff-11e9-8ce6-cb4a8c718905.png)

**Comment by Liam0205** [comment]
@muyuuuu 可以参考一下：https://liam.page/series/#LaTeX-%E4%B8%AD%E7%9A%84%E6%B5%AE%E5%8A%A8%E4%BD%93

**Comment by muyuuuu** [comment]
涨姿势了，我以后注意这方面的编程习惯。
