### ISSUE TITLE
pdf view出现问题 修改后无法更新

### ISSUE THREAD

**Issue by bowendufe** [CTeX-org/forum#100]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
 
  - [ ] MiKTeX <MiKTeX 2.9.6840 64-bit>

## 最小工作示例（MWE）

```latex
\documentclass{article}
\begin{document}
hello world
\end{document}

（用 XeLaTeX 编译后）输出

```latex
Process started

This is BibTeX, Version 0.99d (MiKTeX 2.9.6840 64-bit) The top-level auxiliary file: hi.aux I found no \citation commands---while reading file hi.aux I found no \bibdata command---while reading file hi.aux I found no \bibstyle command---while reading file hi.aux (There were 3 error messages)

Process exited with error(s)
```
log文件：
This is pdfTeX, Version 3.14159265-2.6-1.40.19 (MiKTeX 2.9.6840 64-bit) (preloaded format=pdflatex 2020.3.2)  3 MAR 2020 10:48
entering extended mode
**./hi.tex
(hi.tex
LaTeX2e <2018-04-01> patch level 5

("C:\Users\Thinkpad\AppData\Local\Programs\MiKTeX 2.9\tex\latex\base\article.cl
s"
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
("C:\Users\Thinkpad\AppData\Local\Programs\MiKTeX 2.9\tex\latex\base\size10.clo
"
File: size10.clo 2014/09/29 v1.4h Standard LaTeX file (size option)
)
\c@part=\count80
\c@section=\count81
\c@subsection=\count82
\c@subsubsection=\count83
\c@paragraph=\count84
\c@subparagraph=\count85
\c@figure=\count86
\c@table=\count87
\abovecaptionskip=\skip41
\belowcaptionskip=\skip42
\bibindent=\dimen102
) (hi.aux)
\openout1 = `hi.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 2.
LaTeX Font Info:    ... okay on input line 2.
 [1

{C:/Users/Thinkpad/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}] (hi.aux)
 ) 
Here is how much of TeX's memory you used:
 203 strings out of 494870
 2246 string characters out of 3177165
 54026 words of memory out of 3000000
 3917 multiletter control sequences out of 15000+200000
 3640 words of font info for 14 fonts, out of 3000000 for 9000
 14 hyphenation exceptions out of 8191
 23i,4n,17p,128b,107s stack positions out of 5000i,500n,10000p,200000b,50000s
<C:/Users/Thinkpad/AppData/Local/Programs/MiKTeX 2.9/fonts/type1/public/amsfo
nts/cm/cmr10.pfb>
Output written on hi.pdf (1 page, 11899 bytes).
PDF statistics:
 10 PDF objects out of 1000 (max. 8388607)
 0 named destinations out of 1000 (max. 500000)
 1 words of extra memory for PDF output out of 10000 (max. 10000000)

**Comment by OsbertWang** [comment]
有点奇怪。问题描述说用 `xelatex`，但是你的 `log` 文件显示是` pdftex`

**Comment by bowendufe** [comment]
那个问题描述可能是忘了删了，是用的pdflatex

OsbertWang <notifications@github.com> 于2020年3月3日周二 下午5:08写道：

**Comment by muzimuzhi** [comment]
@bowendufe 
请问，你的问题是否仍未得到解决？

**Comment by bowendufe** [comment]
已经解决了，我换了Texstudio 就可以了。谢谢！

muzimuzhi <notifications@github.com> 于2020年3月9日周一 下午9:36写道：
