### ISSUE TITLE
浮动体插图位置问题

### ISSUE THREAD

**Issue by mybelovedlz** [CTeX-org/forum#101]
[test.zip](https://github.com/CTeX-org/forum/files/4288352/test.zip)
xelatex texlive2019 win10 
第一组图使用h!作为参数时位置会放在倒数第二页，并且会导致接下来的浮动体位置错误，但选择htbp时会放在当前页，编译通过无报错无警告，求教其中原理。

[test.zip](https://github.com/CTeX-org/forum/files/4288299/test.zip)

**Comment by Liam0205** [comment]
原理都在这儿：<https://liam.page/series/#LaTeX-%E4%B8%AD%E7%9A%84%E6%B5%AE%E5%8A%A8%E4%BD%93>

**Comment by muzimuzhi** [comment]
1. 使用 `htbp` 时，第一个浮动体因为足够高，所以独占一页（`p`, float page）
1. 使用 `h!` 时，第一个浮动体因为太高，直到文字部分结束后才输出。第一个浮动体只包含两个子图、缩减高度后，就能看到「你预期的」效果。同类浮动体（这里是 `figure`）一定是按输入顺序输出的，这影响了第二个浮动体的输出位置。
1. 另外，你的图片白边很宽，建议去除（以下例子中用 `trim=..., clip` 去了白边）；例子中的 `\vspace{-10pt}`，使第一个浮动体中子图 a 的小标题被子图 b 覆盖，b 的小标题又被图 c 覆盖，属于错误的用法。

建议改成这样
```tex
\begin{figure}[h!]
  \centering
  \subfloat[Now]{
    \includegraphics[scale=0.2, trim=0 130 0 180, clip]{31.jpg}
    \label{fig31}}
  \par
  \subfloat[Has policy implications in 2050]{
    \includegraphics[scale=0.2, trim=0 130 0 180, clip]{32.jpg}
    \label{fig32}}
  \par
  \subfloat[No policy implications in 2050]{
    \fbox{\includegraphics[scale=0.2, trim=0 130 0 180, clip]{33.jpg}}
    \label{fig33}}
\end{figure}
```

**Comment by RuixiZhang42** [comment]
@Liam0205 
我的 Chrome 打开链接只能看到「古诗词文赏析」啊，没有跳到「LaTeX 中的浮动体」……不如直接放第一篇「基础篇」的链接？

**Comment by Liam0205** [comment]
@RuixiZhang42 这就尴尬了……
