### ISSUE TITLE
如何在列表中使用带圈数字作为序号？

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#102]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

参考了[[LaTeX 中文使用] 用带圈数字编号脚注](https://zhuanlan.zhihu.com/p/74515148)，我想实现在列表中使用带圈数字作为序号，发现输出的带圈数字不是正确的带圈数字，猜测是因为 `\textcircled{\arabic{enumi}}` 没有正确输出的原因

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\usepackage{xpatch,xunicode-addon}
\xeCJKDeclareCharClass{Default}{"24EA, "2460->"2473, "3251->"32BF}
\newfontfamily\EnclosedNumbers{Source Han Serif SC}
\AtBeginUTFCommand[\textcircled]{\begingroup\EnclosedNumbers}
\AtEndUTFCommand[\textcircled]{\endgroup}
\def\theenumi{\textcircled{\arabic{enumi}}}
\begin{document}
\begin{enumerate}
	\item \textcircled{1}
\end{enumerate}
\end{document}
```

（用 XeLaTeX 编译后）输出
![1](https://user-images.githubusercontent.com/49770925/76088064-57eb8a80-5ff2-11ea-8735-8d5fbb2e93e3.png)

## 链接

- 知乎：[[LaTeX 中文使用] 用带圈数字编号脚注](https://zhuanlan.zhihu.com/p/74515148)

**Comment by stone-zeng** [comment]
这里 `\arabic` 没有展开，可以把 `\theenumi` 的定义修改为：

```tex
\def\theenumi{\expandafter\textcircled\expanded{\arabic{enumi}}}
```

或者 LaTeX3 写法：

```tex
\ExplSyntaxOn
\cs_set_nopar:Npn \theenumi
  { \exp_args:Ne \textcircled { \arabic{enumi} } }  % \exp_args:Nx 也可以
\ExplSyntaxOff
```

**Comment by muzimuzhi** [comment]
重定义 `\textcircled` 让它先完全展开 `#1` 也行。（会不会有用户希望支持 int expression。）
