### ISSUE TITLE
搭建一个 Overleaf，需要什么预备知识？

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#103]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 描述问题

以后想尝试搭建一个 Overleaf，但是基本看不懂 [Quick Start Guide](https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide) 的内容，需要些什么预备知识？有什么教程推荐？有什么建议？

## 链接

- Overleaf: https://github.com/overleaf/overleaf/wiki/Quick-Start-Guide

**Comment by muzimuzhi** [comment]
参考 Harry Chen 的博文《[科学地部署自己的 Overleaf 服务](http://harrychen.xyz/2020/02/15/self-host-overleaf-scientifically/)》

**Comment by sikouhjw** [comment]
> 参考 Harry Chen 的博文《[科学地部署自己的 Overleaf 服务](http://harrychen.xyz/2020/02/15/self-host-overleaf-scientifically/)》

这个比 Overleaf 官方给的还简略...

**Comment by muzimuzhi** [comment]
按步骤操作，卡在哪一步就针对那一步提问。问得太宽泛了不容易得到回应。
