### ISSUE TITLE
 beamer 模板无法编译成功的问题

### ISSUE THREAD

**Issue by XianweiYuan** [CTeX-org/forum#105]
[Flux beamer.zip](https://github.com/CTeX-org/forum/files/4419085/Flux.beamer.zip)
## 检查

- [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] --> Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [ ] TeX Live 
  - [x] --> MiKTeX 
  - [ ] CTeX

## 描述问题

源文件添加"\usepackage{bookmark}"之后，使用vscode中的latex workshop中的latexmk进行编译，出现
![image](https://user-images.githubusercontent.com/53900740/78214964-077c2580-74e9-11ea-9647-1cc6f6757c50.png)
Label(s) may have changed. Rerun to get cross-references right.

## 最小工作示例（MWE）

```



## 链接

<!-- 请在此处填写相关链接（如果有的话） -->

- TeX.SX:
- GitHub:https://github.com/pvanberg/flux-beamer

**Comment by muzimuzhi** [comment]
再编译一次。

> 使用vscode中的latex workshop中的latexmk进行编译

这个描述不够准确，尝试把问题分成三步骤：
 1. （清除辅助文件后）手动编译，执行 `pdflatex -> bibtex -> pdflatex -> pdflatex` 之后，该警告是否仍然出现？
 1. （清除辅助文件后）在命令行执行 `latexmk -pdf <tex filename>`，该警告是否出现？
 1. （清除辅助文件后）在 latex-workshop 里按 latexmk 的编译菜单项，该警告是否出现？latexmk 输出的日志中，pdflatex 执行了几次？

------
关于那个警告
```
LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.
```
这个警告是在 `\end{document}` 处抛出的。

编译时，
 - 在 `\begin{document}` 处，读入（上次编译写入的）旧 aux 文件，旧 label 和 bibitem 条目得到定义，以供后面的 `\ref` 和 `\cite` 系列命令使用。
 - 在 `document` 环境内部，收集 `\label` 和 `\bibitem` 定义的（新）条目信息
 - 在 `\end{document}` 处，收集的内容写入新 aux（覆盖之前内容），然后读入一次新 aux。如果新 aux 中包含了旧 aux 未定义的 label 或 cite 条目，就抛出上述警告。

具体可以看 `\enddocument` 和 `\@testdef` 的源码，并注意 boolean `@tempswa`。

**Comment by OsbertWang** [comment]
给个提示：Miktex 默认是不能用 `latexmk` 的，需要用户自己安装 `perl`，见 [camusecao 的博客](https://camusecao.top/1970-01-01-/MiKTeX/)

**Comment by XianweiYuan** [comment]
> 再编译一次。
> 
> > 使用vscode中的latex workshop中的latexmk进行编译
> 
> 这个描述不够准确，尝试把问题分成三步骤：
> 
> 1. （清除辅助文件后）手动编译，执行 `pdflatex -> bibtex -> pdflatex -> pdflatex` 之后，该警告是否仍然出现？
> 2. （清除辅助文件后）在命令行执行 `latexmk -pdf <tex filename>`，该警告是否出现？
> 3. （清除辅助文件后）在 latex-workshop 里按 latexmk 的编译菜单项，该警告是否出现？latexmk 输出的日志中，pdflatex 执行了几次？
> 
> 关于那个警告
> 
> ```
> LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.
> ```
> 
> 这个警告是在 `\end{document}` 处抛出的。
> 
> 编译时，
> 
> * 在 `\begin{document}` 处，读入（上次编译写入的）旧 aux 文件，旧 label 和 bibitem 条目得到定义，以供后面的 `\ref` 和 `\cite` 系列命令使用。
> * 在 `document` 环境内部，收集 `\label` 和 `\bibitem` 定义的（新）条目信息
> * 在 `\end{document}` 处，收集的内容写入新 aux（覆盖之前内容），然后读入一次新 aux。如果新 aux 中包含了旧 aux 未定义的 label 或 cite 条目，就抛出上述警告。
> 
> 具体可以看 `\enddocument` 和 `\@testdef` 的源码，并注意 boolean `@tempswa`。

**Comment by XianweiYuan** [comment]
> 再编译一次。
> 
> > 使用vscode中的latex workshop中的latexmk进行编译
> 
> 这个描述不够准确，尝试把问题分成三步骤：
> 
> 1. （清除辅助文件后）手动编译，执行 `pdflatex -> bibtex -> pdflatex -> pdflatex` 之后，该警告是否仍然出现？
> 2. （清除辅助文件后）在命令行执行 `latexmk -pdf <tex filename>`，该警告是否出现？
> 3. （清除辅助文件后）在 latex-workshop 里按 latexmk 的编译菜单项，该警告是否出现？latexmk 输出的日志中，pdflatex 执行了几次？
> 
> 关于那个警告
> 
> ```
> LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.
> ```
> 
> 这个警告是在 `\end{document}` 处抛出的。
> 
> 编译时，
> 
> * 在 `\begin{document}` 处，读入（上次编译写入的）旧 aux 文件，旧 label 和 bibitem 条目得到定义，以供后面的 `\ref` 和 `\cite` 系列命令使用。
> * 在 `document` 环境内部，收集 `\label` 和 `\bibitem` 定义的（新）条目信息
> * 在 `\end{document}` 处，收集的内容写入新 aux（覆盖之前内容），然后读入一次新 aux。如果新 aux 中包含了旧 aux 未定义的 label 或 cite 条目，就抛出上述警告。
> 
> 具体可以看 `\enddocument` 和 `\@testdef` 的源码，并注意 boolean `@tempswa`。

你说的我都试过了，别人的电脑上用的texshop就好使，我用的VScode就不行，配置是按照QQ群里进行配置的，是我用miktex的问题吗

**Comment by OsbertWang** [comment]
> 你说的我都试过了，别人的电脑上用的texshop就好使，我用的VScode就不行，配置是按照QQ群里进行配置的，是我用miktex的问题吗
若希望解决问题，需要提供更加详细的信息，例如你执行了上述哪一步，系统反馈了什么内容。
当然，我不排除是 miktex 的原因，具体见上面的回复

**Comment by muzimuzhi** [comment]
> > 这个描述不够准确，尝试把问题分成三步骤：
> >
> > 1. （清除辅助文件后）手动编译，执行 `pdflatex -> bibtex -> pdflatex -> pdflatex` 之后，该警告是否仍然出现？
> > 2. （清除辅助文件后）在命令行执行 `latexmk -pdf <tex filename>`，该警告是否出现？
> > 3. （清除辅助文件后）在 latex-workshop 里按 latexmk 的编译菜单项，该警告是否出现？latexmk 输出的日志中，pdflatex 执行了几次？
> 你说的我都试过了，别人的电脑上用的texshop就好使，我用的VScode就不行，配置是按照QQ群里进行配置的，是我用miktex的问题吗

请给清晰的反馈信息，例如
 - 第一个步骤试过后，得到 xx 结果。第二个步骤试过后……第一个步骤不涉及任何编辑器，不需要提及 texshop 或 vscode

请给可追溯的信息来源，或信息原文，例如
 - 不要说「配置是按照QQ群里进行配置的」
 - 说「我是按照 xx 的教程进行配置的，教程可以通过这个链接看到」
 - 说「我现在是这样配置的，（提供完整配置文件，是一个 json 格式的文本）」

**Comment by OsbertWang** [comment]
刚刚得到消息，提问的这个用户换用 texlive 了。问题可以关闭了……
