### ISSUE TITLE
如何在系统工程理论与实践给的LATEX中插入图片

### ISSUE THREAD

**Issue by pionner** [CTeX-org/forum#106]
## 检查

- [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [x] CTeX

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\begin{document}
Hello, \LaTex!
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
! Undefined control sequence.
l.3 Hello, \LaTex
                 !
?
```

## 链接

- TeX.SX:
- GitHub:

**Comment by stone-zeng** [comment]
提问请依照模板提供有关信息。

**Comment by pionner** [comment]
不好意思，第一次使用这个，上传了tex文件，不知道为什么没有上传成功




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiangdong Zeng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 凌晨0:28
收件人:&nbsp;"CTeX-org/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"1318808516"<1318808516@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CTeX-org/forum] 如何在系统工程理论与实践给的LATEX中插入图片 (#106)





 
提问请依照模板提供有关信息。
