### ISSUE TITLE
编译成功，但是有部分乱码

### ISSUE THREAD

**Issue by stargazer1sdh** [CTeX-org/forum#109]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [x] CTeX

## 描述问题

使用CTEX2.9.2.164(就是最后更新的稳定版)编译一个计算机学报的模板latex, 能编译过，得到的pdf大部分是正确的，但是会有一些特定的汉字出现莫名其妙的乱码，如"么“字成了这样：
![image](https://user-images.githubusercontent.com/24764272/79597307-9ce7fe00-8114-11ea-977c-66e1bf7c8753.png)，”没“字成了这样：
![image](https://user-images.githubusercontent.com/24764272/79598285-3c59c080-8116-11ea-8d4d-dff2b8cdd650.png)。

编译的文档链接：[LatexTemplet.zip](https://github.com/CTeX-org/forum/files/4494506/LatexTemplet.zip)，下载后直接编译其中的CjC_template_tex.tex。

使用的是CTEX套装的所有默认设置，PDFTeXify编译无问题。

## 我的其它努力：
后尝试过很多其它工具，像Texlive, MikTex等等，全都不行连编译都不过了，老是会报什么font gbk36 not found.  可是我真的去找，Texlive下面明明有gbk36文件啊。能装的包都装了，什么CJK,ctex,还是不行。

求各位大神帮忙，拜托了。

**Comment by Liam0205** [comment]
MacTeX 2020 + [zhfzfotns.tex](https://liam.page/2020/04/17/using-CJK-on-macTeX-step-by-step/) 编译无问题。

![image](https://user-images.githubusercontent.com/3348485/79711373-37edfd00-82fa-11ea-9abb-9905e7c6b248.png)

几个问题。

1. CTeX 套装已过时，不建议用。
2. `CjC_template_tex.tex` 文件编码是 GBK，但载入的宏包是 `CJKutf8`。二者不匹配。建议载入 `CJK` 宏包替代。
3. 提示 `font gbk36 not found` 是因为 CJK 宏包默认提供的中文字体只有 `gbsn` 和 `gbkai`。但你需要 `song`。后者的 sub-fonts 默认在 TeX Live 和 MiKTeX 当中是没有的。——CTeX 套装里提供了，所以你用 CTeX 套装编译不会报着个错。要在 TeX Live 或 MiKTeX 当中编译，要不然你需要自行安装 sub-fonts，要不然利用 `zhmetrics` 技术绕过这个坑。在 Windows 上，可用 `zhwinfonts`，在 macOS 或者 Linux 上可用我写的 `zhfzfonts`。
