### ISSUE TITLE
\RenewDocumentCommand修改计数器会导致相对引用出错

### ISSUE THREAD

**Issue by zsben2** [CTeX-org/forum#110]
## 检查

- [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 最小工作示例（MWE）

```latex
\documentclass[UTF8]{ctexart}
\RenewDocumentCommand\thefigure{}{\arabic{figure}}
% \renewcommand{\thefigure}{\arabic{figure}}
\begin{document}
在上面引用图\ref{fig:1}

\begin{figure}[h]
\framebox[\linewidth]{普通图}
\caption{普通图}
\label{fig:1}
\end{figure}

在下面引用图\ref{fig:1}
\end{document}
```

用 XeLaTeX 编译后输出

![](https://wenda.latexstudio.net/data/ueditor/php/upload/image/20200420/1587367448466715.png)

**Comment by muzimuzhi** [comment]
用 `\RenewExpandableDocumentCommand` 代替 `\RenewDocumentCommand`。

### 解释

`\NewDocumentCommand` 系列定义的命令总是 protected 的，即在 `\edef` 中免于展开。这导致 `\thefigure` 在写入 aux 之前没有得到展开（可以从 aux 文件看出差异），于是 `\ref{fig:1}` 相当于使用了 `\thefigure`。此时计数器 `figure` 没有递增过，于是输出 0。

参考 `texdoc xparse`, sec. 2 的第二段落，
> The interface-building commands are the preferred method for creating documentlevel
functions in LaTeX3. All of the functions generated in this way are naturally robust
(using the "-TEX \protected mechanism).

**Comment by Liam0205** [comment]
`xparse` 提供的 `\NewDocumentCommand` 一组命令，定义的都是所谓 robust 命令。这牵扯到 LaTeX 中所谓的「脆弱命令」的问题。

你这种写法，导致 `\thefigure` 在写入 `aux` 文件之前还没展开。于是看到「图 0」这样子。

使用 `etoolbox` 的 `\robustify` 加固 `\thefigure` 或者换用同一宏包定义的 `\renewrobustcmd` 也会观察到相同的现象。

```tex
\documentclass[UTF8]{ctexart}
% \RenewDocumentCommand\thefigure{}{\arabic{figure}}
% \renewcommand{\thefigure}{\arabic{figure}}
\usepackage{etoolbox}
% \robustify{\thefigure}
\renewrobustcmd{\thefigure}{\arabic{figure}}
\begin{document}
在上面引用图\ref{fig:1}

\begin{figure}[h]
\framebox[\linewidth]{普通图}
\caption{普通图}
\label{fig:1}
\end{figure}

在下面引用图\ref{fig:1}
\end{document}
```
