### ISSUE TITLE
关于多行标题居中悬挂对齐在目录中的换行问题

### ISSUE THREAD

**Issue by lingr7** [CTeX-org/forum#111]
为了实现多行标题的居中悬挂对齐:
```tex
\usepackage{varwidth} %% 提供 varwidth 环境
\ctexset{
chapter/name = {第,回},
chapter/titleformat = \chaptertitleformat
}
\newcommand\chaptertitleformat[1]{%% 以标题内容为参数
\begin{varwidth}[t]{.7\linewidth}#1\end{varwidth}}
......
\chapter{情中情因情感妹妹\\错里错以错劝哥哥}
```
以上代码来自cetx.pdf（Texlive2019携带的文档）
正文效果挺好，回目我用`chapter/name = {\kaishu 第,回},`。
![红楼梦第一回](https://user-images.githubusercontent.com/37898999/71794772-f81e4500-307d-11ea-95a2-d20d9f7cae46.png)

`\@writefile{toc}{\contentsline {chapter}{\numberline {第一回\hspace  {.3em}}甄士隐梦幻识通灵\\贾雨村风尘怀闺秀}{3}{chapter.1}\protected@file@percent }`
在chapter01.aux文件中的`\\`换行符造成在正式目录中，也出现了一个换行效果。

![文档](https://user-images.githubusercontent.com/37898999/71794564-10419480-307d-11ea-95cd-7a95576842f3.png)
![目录换行了](https://user-images.githubusercontent.com/37898999/71794580-22233780-307d-11ea-90f4-807313425f45.png)
[红楼梦排版的github仓库地址](https://github.com/lingr7/HongLouMeng-ZhiPingBen)
想问一下是否有办法解决目录中也换行了这个问题。

**Comment by Liam0205** [comment]
另外，用 `chapter/name = {\kaishu 第,回}` 来解决 chapter name 的楷书不是个好做法。因为它把内容和格式混一起了。

**Comment by muzimuzhi** [comment]
@lingr7 
> 目前是目录还是有点小问题，比如“目录”二字和章回标题对齐。

* @Liam0205 的回复解决了「目录」二字的问题，让它们保持了居中。
* 目录中的章回标题对齐效果是受 ctex/ctexheading 宏包影响后的效果（参考[此文](https://zhuanlan.zhihu.com/p/63233033)）， 但 ctex 包未提供完整的目录条目样式定制功能。可以引入 `tocloft` 宏包处理
```tex
\usepackage[titles]{tocloft}
\setlength{\cftchapnumwidth}{5\ccwd}
```

完整例子
```tex
\documentclass{ctexbook}
\usepackage[showframe]{geometry}

\usepackage[titles]{tocloft}
\setlength{\cftchapnumwidth}{5\ccwd}

\ctexset{
  chapter = {
    format += \centering,
    name = {第,回},
    nameformat += \kaishu,
    titleformat = \chaptertitleformat
  }
}

\newcommand{\chaptertitleformat}[1]{%
  \CTEXifname{\parbox[t]{8\ccwd}{#1}}{#1}}

\begin{document}

\tableofcontents

\chapter{甄士隱夢幻識通靈\hspace{.5em}賈雨村風塵懷閨秀}
\chapter{賈夫人仙逝揚州城\hspace{.5em}冷子興演說榮國府}
\chapter{金陵城起複賈雨村\hspace{.5em}榮國府收養林黛玉}
\addtocounter{chapter}{10}
\chapter{薄命女偏逢薄命郎\hspace{.5em}葫蘆僧亂判葫蘆案}
\chapter{開生面夢演紅樓夢\hspace{.5em}立新場情傳幻境情}
\chapter{賈寶玉初試雨雲情\hspace{.5em}劉姥姥一進榮國府}

\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/80120922-41a78700-85be-11ea-8277-5fecce6ea9dc.png)

**Comment by muzimuzhi** [comment]
> 手写 `\hspace` 比较暴力，但总之是能用的。觉得不好，也可以加点代码处理一下。

提供一种用正则把 `\\` 替换为 `\hspace{...}` 的尝试。
* 因为需要同时影响目录和页眉，所以选择 `\@chapter` 作为修改的入口。
* 正则的执行效率显著慢于 tex 中判断 if x in y 的典型方式（例如 [`keyval.sty`](https://github.com/latex3/latex2e/blob/master/required/graphics/keyval.dtx) 中 `\KV@split` 的定义办法），但比较通用。

从 `\chapter` 到 `\@chapter` 的展开逻辑
```tex
\chapter ::=
    <some staff>
    if next char == "*"       % \chapter*{title}
        \@schapter{title}
    else if next char == "["  % \chapter[short title]{title}
        \@chapter[short title]{title}
    else                      % \chapter{title}
        \@chapter[title]{title}
    end if
```

完整例子
```tex
\documentclass{ctexbook}
\usepackage[showframe]{geometry}
\usepackage{varwidth}


%% 设置 \chapter 的样式
\ctexset{
  chapter = {
    format += \centering,
    name = {第,回},
    nameformat += \kaishu,
    titleformat = \chaptertitleformat
  }
}

% 因为对 \@chapter 的修改，此处可恢复使用 varwidth 环境
\newcommand{\chaptertitleformat}[1]{%
  \CTEXifname{\begin{varwidth}[t]{.7\linewidth}#1\end{varwidth}}{#1}}


%% 增加 \chapter 对应目录项的 numwidth
\usepackage[titles]{tocloft}
\setlength{\cftchapnumwidth}{5\ccwd}


\ExplSyntaxOn
\makeatletter

%% 在 \chapter 的可选和必选参数的值相同时，把可选参数中的 "\\<任意个空白字符>" 
%% 替换为 "\hspace{0.5\ccwd}"，间接影响在目录和页眉显示的章标题
\cs_set_eq:NN \@chapter:wn \@chapter

\cs_set_nopar:Npn \@chapter [#1]#2
  {
    \tl_set:Nn \l_tmpa_tl {#1}
    \tl_set:Nn \l_tmpb_tl {#2}
    \tl_if_eq:NNT \l_tmpa_tl \l_tmpb_tl
      { 
        \regex_replace_once:nnN { \s*\c{\x5C}\s* } { \c{hspace} \cB\{ 0\.5 \c{ccwd} \cE\} } \l_tmpa_tl
      }
    \@chapter:wn [\l_tmpa_tl] {\l_tmpb_tl}
  }

\makeatother
\ExplSyntaxOff

\begin{document}

\tableofcontents

\chapter{甄士隱夢幻識通靈\\ 賈雨村風塵懷閨秀}
\chapter{賈夫人仙逝揚州城\\ 冷子興演說榮國府}
\chapter{金陵城起複賈雨村\\ 榮國府收養林黛玉}
\addtocounter{chapter}{10}
\chapter{薄命女偏逢薄命郎\\ 葫蘆僧亂判葫蘆案}
\chapter{開生面夢演紅樓夢\\ 立新場情傳幻境情}
\chapter{賈寶玉初試雨雲情\\ 劉姥姥一進榮國府}

\end{document}
```

**Comment by lingr7** [comment]
感谢大家，目录已经修好了，已经release了一个全本红楼梦pdf文件
![目录](https://picture-1258475985.cos.ap-chengdu.myqcloud.com/imgimage-20200427142625952.png)


![第六回](https://picture-1258475985.cos.ap-chengdu.myqcloud.com/img20200427143158.png)

**Comment by Liam0205** [comment]
@lingr7 赞。项目地址在哪里？

**Comment by lingr7** [comment]
红楼梦排版的github仓库地址 https://github.com/lingr7/HongLouMeng-ZhiPingBen
