### ISSUE TITLE
如何让 lshort-zh-cn 的 example 环境中的代码部分变为用 minted 宏包排版？

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#113]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

想让 lshort-zh-cn 的 example 环境中的代码部分用 minted 宏包排版，尝试将 `\small\verbatiminput{\example@name}%` 改为 `\small\inputminted{latex}{\example@name}%
`，效果看起来没什么问题，但
```latex
\def\verbatim@processline{\immediate\write\example@out{\the\verbatim@line}}%
\verbatim@start}%
```
这一行出现了 `verbatim` 的字样，看不懂这些代码，想问问如何将其修改为 minted 的语法（即不依赖 `verbatim` 宏包）

## 最小工作示例（MWE）
编译方式：`xelatex --shell-escape`
```latex
\documentclass{ctexart}
\usepackage{verbatim,minted}
\usepackage{sourcecodepro}
\usepackage{xcolor}

\makeatletter
\newwrite\example@out
\newlength\savefboxrule
\newlength\savefboxsep
\edef\example@name{\jobname-example.aux}
\newenvironment{example}%
{\begingroup\@bsphack
  \immediate\openout\example@out=\example@name
  \let\do\@makeother\dospecials\catcode`\^^M\active
  \def\verbatim@processline{\immediate\write\example@out{\the\verbatim@line}}%
  \verbatim@start}%
{\immediate\closeout\example@out\@esphack\endgroup%
  \trivlist\item\relax
  \setlength{\savefboxrule}{\fboxrule}%
  \setlength{\savefboxsep}{\fboxsep}%
  \setlength{\fboxsep}{0.015\textwidth}%
  \setlength{\fboxrule}{0.4pt}%
  \fcolorbox[gray]{0}{0.95}{%
    \begin{minipage}[c]{0.45\textwidth}%
      \setlength{\fboxrule}{\savefboxrule}%
      \setlength{\fboxsep}{\savefboxsep}%
      % \small\verbatiminput{\example@name}%
      \small\inputminted{latex}{\example@name}%
    \end{minipage}%
  }%
  \hfill%
  \fbox{%
    \begin{minipage}[c]{0.45\textwidth}%
      \setlength{\fboxrule}{\savefboxrule}%
      \setlength{\fboxsep}{\savefboxsep}%
      \setlength{\parskip}{1ex plus 0.4ex minus 0.2ex}%
      \normalsize\input{\example@name}%
    \end{minipage}%
  }%
  \endtrivlist
}
\makeatother
\begin{document}
  \begin{example}
    $\int f(x) \mathrm{d}x$
    $\sum_{0}^{+\infty}$
    \begin{center}
      1
    \end{center}
  \end{example}
\end{document}
```

**Comment by Liam0205** [comment]
这里就是借 verbatim 宏包的技术，把 example 的内容打到外部文件。但之后不管是 minted 的排版还是实际内容的排版，都跟 verbatim 宏包无关。

如果要借 minted 宏包的工具来改的话，我看了一下，应该是借 `\minted@FVB@VerbatimOut` 和 `\minted@FVE@VerbatimOut` 来做这件事。但是改起来还蛮复杂。

总体来说我觉得没必要非得改这里。

**Comment by Liam0205** [comment]
收回刚才的话，改起来不复杂。

```tex
\documentclass{ctexart}
\usepackage{minted}
\usepackage{sourcecodepro}
\usepackage{xcolor}

\makeatletter
\newlength\savefboxrule
\newlength\savefboxsep
\edef\example@name{\jobname-example.aux}
\newenvironment{example}%
{%
\renewcommand{\minted@FVB@VerbatimOut}[1]{%
  \@bsphack
  \begingroup
    \FV@DefineWhiteSpace
    \def\FV@Space{\space}%
    \FV@DefineTabOut
    \let\FV@ProcessLine\minted@write@detok
    \immediate\openout\FV@OutFile ##1\relax
    \let\FV@FontScanPrep\relax
    \let\@noligs\relax
    \FV@Scan}
\minted@FVB@VerbatimOut{\example@name}}%
{\minted@FVE@VerbatimOut%
  \trivlist\item\relax
  \setlength{\savefboxrule}{\fboxrule}%
  \setlength{\savefboxsep}{\fboxsep}%
  \setlength{\fboxsep}{0.015\textwidth}%
  \setlength{\fboxrule}{0.4pt}%
  \fcolorbox[gray]{0}{0.95}{%
    \begin{minipage}[c]{0.45\textwidth}%
      \setlength{\fboxrule}{\savefboxrule}%
      \setlength{\fboxsep}{\savefboxsep}%
      % \small\verbatiminput{\example@name}%
      \small\inputminted{latex}{\example@name}%
    \end{minipage}%
  }%
  \hfill%
  \fbox{%
    \begin{minipage}[c]{0.45\textwidth}%
      \setlength{\fboxrule}{\savefboxrule}%
      \setlength{\fboxsep}{\savefboxsep}%
      \setlength{\parskip}{1ex plus 0.4ex minus 0.2ex}%
      \normalsize\input{\example@name}%
    \end{minipage}%
  }%
  \endtrivlist
}
\makeatother
\begin{document}
\begin{example}
$\int f(x) \mathrm{d}x$
$\sum_{0}^{+\infty}$
\begin{center}
  1
\end{center}
\end{example}
\end{document}
```

这样就好了。

**Comment by sikouhjw** [comment]
> 
> 
> 收回刚才的话，改起来不复杂。
> 
> ```
> \documentclass{ctexart}
> \usepackage{minted}
> \usepackage{sourcecodepro}
> \usepackage{xcolor}
> 
> \makeatletter
> \newlength\savefboxrule
> \newlength\savefboxsep
> \edef\example@name{\jobname-example.aux}
> \newenvironment{example}%
> {%
> \renewcommand{\minted@FVB@VerbatimOut}[1]{%
>   \@bsphack
>   \begingroup
>     \FV@DefineWhiteSpace
>     \def\FV@Space{\space}%
>     \FV@DefineTabOut
>     \let\FV@ProcessLine\minted@write@detok
>     \immediate\openout\FV@OutFile ##1\relax
>     \let\FV@FontScanPrep\relax
>     \let\@noligs\relax
>     \FV@Scan}
> \minted@FVB@VerbatimOut{\example@name}}%
> {%
>   \renewcommand{\minted@FVE@VerbatimOut}{%
>     \immediate\closeout\FV@OutFile\endgroup\@esphack}%
>   \minted@FVE@VerbatimOut%
>   \trivlist\item\relax
>   \setlength{\savefboxrule}{\fboxrule}%
>   \setlength{\savefboxsep}{\fboxsep}%
>   \setlength{\fboxsep}{0.015\textwidth}%
>   \setlength{\fboxrule}{0.4pt}%
>   \fcolorbox[gray]{0}{0.95}{%
>     \begin{minipage}[c]{0.45\textwidth}%
>       \setlength{\fboxrule}{\savefboxrule}%
>       \setlength{\fboxsep}{\savefboxsep}%
>       % \small\verbatiminput{\example@name}%
>       \small\inputminted{latex}{\example@name}%
>     \end{minipage}%
>   }%
>   \hfill%
>   \fbox{%
>     \begin{minipage}[c]{0.45\textwidth}%
>       \setlength{\fboxrule}{\savefboxrule}%
>       \setlength{\fboxsep}{\savefboxsep}%
>       \setlength{\parskip}{1ex plus 0.4ex minus 0.2ex}%
>       \normalsize\input{\example@name}%
>     \end{minipage}%
>   }%
>   \endtrivlist
> }
> \makeatother
> \begin{document}
> \begin{example}
> $\int f(x) \mathrm{d}x$
> $\sum_{0}^{+\infty}$
> \begin{center}
>   1
> \end{center}
> \end{example}
> \end{document}
> ```
> 
> 这样就好了。

感谢

**Comment by Liam0205** [comment]
感谢提供素材。

https://liam.page/2020/04/29/combine-minted-and-its-layout-as-example/

**Comment by muzimuzhi** [comment]
试试 `tcolorbox` 宏包：
```tex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{minted, skins}

% 重定义环境用 \renewtcblisting
\newtcblisting{example}{
  skin=empty, 
  borderline horizontal={.4pt}{0pt}{black},
  sidebyside
}

\begin{document}
Hello \LaTeX{}.

\begin{example}
\[ E = mc^2. \]
\end{example}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/80587121-988edf80-8a48-11ea-8f60-63b5ec825e01.png)

**Comment by Liam0205** [comment]
好！
