### ISSUE TITLE
如何在 texstudio 中写 latex+dvipdfmx 的魔法注释？

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#114]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

如何在 texstudio 中写 latex+dvipdfmx 的魔法注释？如果分步进行太麻烦了

**Comment by Liam0205** [comment]
用 LaTeXmk 吧……

https://liam.page/2020/04/24/using-LaTeXmk-with-LaTeXworkshop-with-VSCode/

可以看其中关于 `-e` 参数的描述。

**Comment by muzimuzhi** [comment]
配置部分
![image](https://user-images.githubusercontent.com/6376638/81048056-2d348a00-8eee-11ea-99e8-864be6ff16b9.png)

文档里
```
% !TeX TS-program = user3
```

参考
 - TeXstudio 文档，[_Advanced header usage_ 一节](http://texstudio.sourceforge.net/manual/current/usermanual_en.html#SECTION_TEXCOM) （不同版本的文档里，这一节的编号有差异）
 - 详细步骤：知乎文章《[[LaTeX 编辑器] 在 TeXstudio 里自定义一个工具栏按钮](https://zhuanlan.zhihu.com/p/60996450)》

**Comment by muzimuzhi** [comment]
PS：texstudio 源码中和 magic comment 有关的部分

 - https://github.com/texstudio-org/texstudio/blob/master/src/latexdocument.cpp
    - `splitMagicComment`，在用法 `% ! <name> = <val>` 中，根据等号分成 `<name>` 和 `<val>`
    - `parseMagicComment`，支持的 `<name>` 种类
 - https://github.com/texstudio-org/texstudio/blob/master/src/buildmanager.cpp#L2008-L2026
在 `<val> == TS-program | ...` 时，支持的 `<val>` 种类

**Comment by OsbertWang** [comment]
Win 系统写成
```
% !TeX TXS-program:compile = txs:///latexmk/{}[-e "$dvipdf='dvipdfmx %%O -o %%D %%S'" -latex -pdfdvi ?me"]
```
另外，我猜测 Unix 或者 Linux 系统应该写成
```
% !TeX TXS-program:compile = txs:///latexmk/{}[-e '$dvipdf=q/dvipdfmx %%O -o %%D %%S/' -latex -pdfdvi ?me"]
```

**Comment by sikouhjw** [comment]
感谢各位
