### ISSUE TITLE
如何将 tikz 中的 || 命令依赖于 minted 宏包？

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#115]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

在 tikz 源码中存在这一种输入方式
```latex
|\tikz \draw (0pt,0pt) -- (20pt,6pt);|
```
效果为 `\verb|\tikz \draw (0pt,0pt) -- (20pt,6pt);|`，具体设置代码为
https://github.com/pgf-tikz/pgf/blob/6e8397b58f2b9dbf110ca0da12c9791c9cbdd191/doc/generic/pgf/macros/pgfmanual-en-macros.tex#L29-L34
想将 `\verb` 改为 `\mint{tex}`，但是报错了，如何解决？

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\usepackage{minted}
\catcode`\|=12
\gdef\pgfmanualnormalbar{|}
\catcode`\|=13
\AtBeginDocument{\gdef|{\ifmmode\pgfmanualnormalbar\else\expandafter\mint{tex}\expandafter|\fi}}
\begin{document}
|a|

$|a|$
\end{document}
```

（用 `xelatex --shell-escape` 编译后）输出

```latex
ABD: EverySelectfont initializing macros
Runaway argument?
|\fi a| 
d:/TeX/ceshi/1/1.tex:9: Paragraph ended before \mint@ii was complete.
<to be read again> 
                   \par 
l.9 
    
)
Runaway argument?
|\fi a|$ \end{document} 
! File ended while scanning use of \mint@ii.
<inserted text> 
                \par 
<*> d:/TeX/ceshi/1/1
                    
! Emergency stop.
<*> d:/TeX/ceshi/1/1
                    
No pages of output.
Transcript written on 1.log.
system returned with code 1
```

## 链接

- [用||夹着代码表示引用代码，pgf manual.pdf里是如何实现的？](https://wenda.latexstudio.net/answer/1976/3078.html)

**Comment by muzimuzhi** [comment]
一个尝试
```tex
\documentclass{article}
\usepackage{minted}

\makeatletter
\catcode`\|=12
\def\pgfmanualnormalbar{|}

\catcode`\|=\active
\def\minted@inline@x#1|{\mintinline{tex}|#1|}
\AtBeginDocument{%
  \gdef|{\ifmmode\pgfmanualnormalbar\else\expandafter\minted@inline@x\fi}}
\makeatother

\begin{document}
|\alpha some|

$|\alpha some|$
\end{document}
```
输出
![image](https://user-images.githubusercontent.com/6376638/81195877-f72bfe80-8ff0-11ea-9c97-a94a8d008f8c.png)

PS：根据 https://tex.stackexchange.com/q/45756/79060 ，`minted` 的作者和维护者们故意不支持这种用法，因为 active character 太容易让事情变复杂。

**Comment by sikouhjw** [comment]
> 首先，`\mint` 用于单行的 `\being{minted}`，行内高亮命令是 `\mintinline`。
> 
> 然后，你引用的 [`pgfmanual-en-macros.tex`](https://github.com/pgf-tikz/pgf/blob/6e8397b58f2b9dbf110ca0da12c9791c9cbdd191/doc/generic/pgf/macros/pgfmanual-en-macros.tex#L29-L34) 中使用的 `\expandafter`
> 
> ```
> \AtBeginDocument{\gdef|{\ifmmode\pgfmanualnormalbar\else\expandafter\verb\expandafter|\fi}}
> ```
> 
> 是为了先展开 `\fi`，然后展开 `\verb` 和 `|`。按照这个思路，在你的例子中，要抑制 `\else` 之后 `\fi` 之前每一个 token 的展开。因为 `\expandafter` 只能作用于其后的单个 token，直接写需要写成
> 
> ```
> \AtBeginDocument{\gdef|{%
>   \ifmmode
>     \pgfmanualnormalbar
>   \else
>     \expandafter\mint
>     \expandafter{%
>     \expandafter t%
>     \expandafter e%
>     \expandafter x%
>     \expandafter}%
>     \expandafter|%
>   \fi}}
> ```
> 
> 可以把 `\mint{tex}|` 存在一个宏里，写成
> 
> ```
> \def\mintinlineprefix{\mintinline{tex}|}
> \AtBeginDocument{\gdef|{\ifmmode\pgfmanualnormalbar\else\expandafter\mintinlineprefix\fi}}
> ```
> 
> 完整例子
> 
> 一个尝试
> 
> ```
> \documentclass{ctexart}
> \usepackage{minted}
> 
> \catcode`\|=12
> \gdef\pgfmanualnormalbar{|}
> 
> \catcode`\|=13
> \def\mintinlineprefix{\mintinline{tex}|}
> \AtBeginDocument{\gdef|{\ifmmode\pgfmanualnormalbar\else\expandafter\mintinlineprefix\fi}}
> 
> \begin{document}
> |\alpha + some|
> 
> $|\alpha + some|$
> \end{document}
> ```
> 
> 输出
> ![image](https://user-images.githubusercontent.com/6376638/81195877-f72bfe80-8ff0-11ea-9c97-a94a8d008f8c.png)

感谢

> PS：根据 https://tex.stackexchange.com/q/45756/79060 ，`minted` 的作者和维护者们故意不支持这种用法，因为 active character 太容易让事情变复杂。

我感觉挺好玩的，就试了试，未来写东西的时候再看看用不用这个

> PS 2：指定一个符号，把它用于 delimiter of inline verbatim，使得 `<delim><code><delim>` 相当于输入了 `<inline verb command><delim><code><delim>`，这是 `shortvrb` 和 `fancyvrb` 等宏包提供的既有功能。`<inline verb command>` 可以是 `\verb` 和 `\Verb`。

我更喜欢 `minted`，不用怎么配置就能好看
