### ISSUE TITLE
官方英文期刊的latex模板异常错误

### ISSUE THREAD

**Issue by huiliu-overleaf** [CTeX-org/forum#116]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 最小工作示例（MWE）

见压缩包：[spe_template_main_manuscript_tex.zip](https://github.com/CTeX-org/forum/files/4631724/spe_template_main_manuscript_tex.zip)

## 链接

- TeX.SX:
- GitHub:

**Comment by Liam0205** [comment]
是 LaTeX 而不是 LaTex。

**Comment by huiliu-overleaf** [comment]
什么意思？模本运行错误在哪里？怎么修改呢？

**Comment by sikouhjw** [comment]
> 什么意思？模本运行错误在哪里？怎么修改呢？

你回头看你提问了什么东西，你给了一个压缩包，MWE 是 `\LaTex` 拼写错误。要按模板填写你的问题

**Comment by huiliu-overleaf** [comment]
我给一个压缩包的原因是因为我不知道这个错误是怎么导致，它这是一个期刊模本，里面含有.tex、.cls和sty文件，所以也不知道怎么制作“最小”的mwe文件，只能把官方下载的latex源文件上传。你只需要下载解压然后运行一下里面的.tex文件看看错误是什么导致的就行，不是很复杂。谢谢了。

**Comment by sikouhjw** [comment]
> 我给一个压缩包的原因是因为我不知道这个错误是怎么导致，它这是一个期刊模本，里面含有.tex、.cls和sty文件，所以也不知道怎么制作“最小”的mwe文件，只能把官方下载的latex源文件上传。你只需要下载解压然后运行一下里面的.tex文件看看错误是什么导致的就行，不是很复杂。谢谢了。

那也得描述一下问题
- 我在投稿，我的发行版是 xx，操作系统是 xx，编译方式 pdflatex，编译不了期刊模板
- 期刊模板如下
- 报错为
```tex
! Missing = inserted for \ifnum.
<to be read again>
                   v
l.4 \templatetype
                 {SPEmain}
?
```
按照投稿模板去填写内容，我只是举例子

**Comment by Liam0205** [comment]
……无力吐槽

**Comment by huiliu-overleaf** [comment]
已经按照要求提问

**Comment by Liam0205** [comment]
你模板在哪下载的？给个链接。

**Comment by Liam0205** [comment]
> 已经按照要求提问

那是我给你改的……

**Comment by huiliu-overleaf** [comment]
模本是这个
[spe_template_main_manuscript_tex.zip](https://github.com/CTeX-org/forum/files/4631832/spe_template_main_manuscript_tex.zip)

**Comment by Liam0205** [comment]
我知道是这个。我不是要模板本身，我是要看你是在哪下载的。我要看下载页面上是否有其他说明。

**Comment by sikouhjw** [comment]
> 你模板在哪下载的？给个链接。

帮他回复..[https://www.spe.org/en/authors/resources/](https://www.spe.org/en/authors/resources/)

**Comment by huiliu-overleaf** [comment]
对的，是这个链接

**Comment by Liam0205** [comment]
那就是模板的锅。发邮件给编辑部吧= =

**Comment by huiliu-overleaf** [comment]
哦哦

**Comment by muzimuzhi** [comment]
模板中有两处错误：
 - `SPEmain.cls` 第 3 行，日期错误。把 `2020/21/2` 改成合法日期，例如 `2020/02/21` 即可。
   - 根据 `texdoc clsguide`，sec. 3.1，日期必须是 yyyy/mm/dd 形式的。
 - `SPEmain.sty` 第 40 行，三处 `\href{<URL>}{<text>}` 中 `<URL>` 里的 `#` 改成 `\#` 即可。
   - 为了方便直接输入 url，`\href` 会先改变 catcode 然后读入第一个参数。但在 `SPEmain.sty` 中，`\href{... # ...}{...}` 被置于 `\newcommand\instructionspage{...}` 内，于是 `#` 被以 parameter character 的 catcode 读入，引发报错 `Illegal parameter number in definition of \instructionspage`。

这两处问题解决后，模板能使用 pdflatex 正常编译。

------

* 期刊模板有问题，值得（重新确认后）发邮件给期刊编辑部。

> 你回头看你提问了什么东西
> from https://github.com/CTeX-org/forum/issues/116#issuecomment-628964961

* 交流时，个人建议少用反问或语气强烈的句子。

**Comment by huiliu-overleaf** [comment]
不仅完美解决了问题，还知道了导致错误的原因，又学到了新东西，非常非常感谢你们的帮助！

**Comment by muzimuzhi** [comment]
> * 期刊模板有问题，值得（重新确认后）发邮件给期刊编辑部。

确认了问题，邮件已发。

**Comment by huiliu-overleaf** [comment]
好的，我已经把模本问题发给期刊，让他们给修改一下，避免别人遇到相同问题。
