### ISSUE TITLE
官方期刊自带模本运行异常错误

### ISSUE THREAD

**Issue by huiliu-overleaf** [CTeX-org/forum#117]
## 检查

- [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x ] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 最小工作示例（MWE）

<!--
请在此处填写最小工作示例，要求：

因为是一个完整期刊模本，里面有.clc，sty和tex文件，不适合也无法做成MWE,压缩包是这个期刊的模本完整文件，解压后直接运行会出现以下错误。
![image](https://user-images.githubusercontent.com/57052860/82001537-f1d45100-968d-11ea-86c2-52bd89806fb8.png)

Latex压缩包：
[spe_template_main_manuscript_tex.zip](https://github.com/CTeX-org/forum/files/4631795/spe_template_main_manuscript_tex.zip)

**Comment by Liam0205** [comment]
你这叫按要求提问了……？自己再看看吧……

转回 #116

**Comment by Liam0205** [comment]
@huiliu-overleaf 哦，写在注释里了……

**Comment by huiliu-overleaf** [comment]
我还是latex新手，好多用法和简称不太知道，还请见谅......
