### ISSUE TITLE
TeX Live 2020 更新后报错 ! Undefined control sequence. l.74 \__kernel_quark_new_conditional:Nn

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#119]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

更新全部宏包，编译MWE

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\begin{document}
  文字
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
(c:/texlive/2020/texmf-dist/tex/latex/l3packages/xtemplate/xtemplate.sty
! Undefined control sequence.
l.74 \__kernel_quark_new_conditional:Nn
                                        \__xtemplate_quark_if_nil:N { F }
? 
```
`xtemplate` 宏包版本为
```tex
\ProvidesExplPackage{xtemplate}{2020-05-15}{}
  {L3 Experimental prototype document functions}
```

**Comment by stone-zeng** [comment]
应该是 format 没有更新。试一下 `fmtutil-sys --all`（需要管理员权限）。

**Comment by sikouhjw** [comment]
> 应该是 format 没有更新。试一下 `fmtutil-sys --all`（需要管理员权限）。

可以了，感谢
