### ISSUE TITLE
插入图片时出现 Dimension too large 错误

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/forum#12]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
    - [x] Windows 7/8/10
    - [x] macOS
    - [ ] Linux

- TeX 发行版
    - [x] TeX Live 2018
    - [ ] MiKTeX 
    - [ ] CTeX

## 描述问题

图片本身没有问题，但加上 `width=0.75\textwidth` 之后数字溢出。并不是十分理解这个图片的尺寸是如何确定的。

## 最小工作示例（MWE）

```latex
\documentclass{article}
\usepackage{graphicx}

\begin{document}
\includegraphics{QQ20190224-0.jpg}

\includegraphics[width=0.75\textwidth]{QQ20190224-0.jpg}
\end{document}
```

图片链接：[QQ20190224-0.jpg](https://user-images.githubusercontent.com/18233088/53295862-78113700-383f-11e9-8f18-f6dbbc76a769.png)
完整测试文件打包：[test.zip](https://github.com/CTeX-org/forum/files/2897645/test.zip)

用 pdfLaTeX 编译后输出
```latex
pdfTeX warning: pdflatex: arithmetic: number too big
[1{/usr/local/texlive/2018/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
Overfull \vbox (10796.3625pt too high) has occurred while \output is active
[2 <./QQ20190224-0.jpg>]
! Dimension too large.
<to be read again> 
                   b
l.7 ...ics[width=0.75\textwidth]{QQ20190224-0.jpg}
                                                  
? 
```

用 XeLaTeX 编译后输出

```latex
Overfull \vbox (10796.36215pt too high) has occurred while \output is active
[2]
! Dimension too large.
<to be read again> 
                   b
l.7 ...ics[width=0.75\textwidth]{QQ20190224-0.jpg}
                                                  
? 
```

## 链接

- TeX.SX:
  - [Dimension too large. error from pdflatex when using \includegraphics](https://tex.stackexchange.com/q/257153)
  - [how to solve dimension too large error in \includegraphics without changing resolution](https://tex.stackexchange.com/q/347962)

**Comment by sd44** [comment]
https://tex.stackexchange.com/questions/207348/anybody-ever-encountered-arithmetic-number-too-big-when-importing-an-image

图片density属性问题，示例图片与上述链接问题图片density属性一致，均为1x1，也就是1 DPI。

`fuck.jpg: JPEG image data, JFIF standard 1.01, resolution (DPI), density 1x1, segment length 16, progressive, precision 8, 563x157, components 3`

查看log，TeX因此将其认为是一个 宽度为(563*72)pt的图片，超出LaTeX图片最大pt数 \maxdimen (16384pt)。因此导致溢出……

最简单的办法，直接另存为png吧，哈哈，或其他修改图片DPI的办法。

**Comment by RuixiZhang42** [comment]
@sd44 
> 宽度为(563*72)pt的图片 [……]

是 563*72.27 pt 哦，Adobe 的那个点才是 1in = 72bp (big point)，TeX 的点是 1in = 72.27pt。
