### ISSUE TITLE
关于以前的一个中文书籍模板问题，qingkuan模板在gentoo中折腾纪实

### ISSUE THREAD

**Issue by yangninghua** [CTeX-org/forum#121]
qingkuan模板在gentoo中折腾纪实
自己使用texlive2020 出现了很多很多问题，想找到之前这个博客的信息，还有希望吗
之前的地址：
http://bbs.ctex.org/viewthread.php?tid=68692&extra=page%3D1

我下载的地方：
https://www.latexstudio.net/archives/1654.html

**Comment by Liam0205** [comment]
@yangninghua @qinglee

**Comment by muzimuzhi** [comment]
> 自己使用texlive2020 出现了很多很多问题，想找到之前这个博客的信息，还有希望吗
> 之前的地址：
> http://bbs.ctex.org/viewthread.php?tid=68692&extra=page%3D1

web.archive.org 在 2012 年 3 月 8 日备份过该帖，见 
 - https://web.archive.org/web/20120308033506/http://bbs.ctex.org/viewthread.php?tid=68692&extra=page%3D1

code.google.com 上的源码和 PDF 也仍可下载，分别见
 - https://code.google.com/archive/p/sobenlee/source/default/source?page=7
 - https://code.google.com/archive/p/sobenlee/downloads

**Comment by stone-zeng** [comment]
## `MA-Book.cls`

- 中文字体可以用 `ctexbook` 文档类提供的功能：删掉 `LoadClass` 后面的 `nofonts` 选项。
- `\RequireXeTeX` 命令不存在，定义为空
- 补充以下宏包：`\RequirePackage{xcolor,graphicx,xeCJKfntef}`

## `MA-FontSet.def`

- 如果你把他调的字体都装了，那可以忽略，要不然就把所有字体声明全部注释掉，字体命令定义为空（e.g. `\def\MZDF{}`）
- 注释掉 `\renewcommand*\CJKunderlinecolor{}`
- 字号的定义全部注释掉

## `MA-Title.def`

- 由于 `interfaces` 年久失修，似乎没有同步 `titlesec` 的更新，所以 `shape=block` 不能用，`shape=display` 可以勉强编译通过。

另外还有一堆过时命令，不影响编译就没管了。总之这种十年没有维护的文档会有很多兼容性问题，这些调整只负责让它通过编译，效果的一致性还需要再做修改。

**Comment by Liam0205** [comment]
@stone-zeng the future.

**Comment by muzimuzhi** [comment]
> * `\RequireXeTeX` 命令不存在，定义为空

可以加载 `iftex` 宏包补上

**Comment by qinglee** [comment]
这些模板并不好，属于本人黑历史系列。现在强烈不推荐使用了。

**Comment by yangninghua** [comment]
收到，谢谢各位大佬的回复
