### ISSUE TITLE
奇偶页眉与章节编号问题

### ISSUE THREAD

**Issue by krisfans** [CTeX-org/forum#122]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

我的需求是
- 奇偶页不同页眉，其中奇数页中间显示章的标题，偶数页中间显示论文标题，
-  奇数页的左边和偶数页的右边显示页码。这里的问题是需要**摘要和目录不编号也不出现在目录里面**，然后后续章节正常编号，**参考文献与致谢不编号但是需要出现在目录**。
### 方法1
使用`\chapter*{}`，手动制作页眉和书签。如果直接用`\chapter*{}`环境的话，可以不编号，但是**不能正确生成页眉信息**，**没有生成pdf书签**，虽说可以手工用`\addcontentsline`把这项加入目录但是 `hyperref`超链接定位不准。这个思路的问题是如何**制作定位准的pdf书签**以及**包含章节标题的页眉**？
### 方法2
直接用编号的环境`\chapter{}`，但是不显示编号。如果`\setcounter{secnumdepth}{-1}`抑制编号输出的话，可以解决超链接定位以及页眉信息的问题，但是**摘要又会出现在目录中,这是不需要的**，这个思路的工作在怎么**使一个编号的章节不出现在目录中**？
## 最小工作示例（MWE）

```latex
%!TEX program = xelatex
\documentclass[a4paper,zihao=-4,UTF8]{ctexbook}
\usepackage[inner=3cm,outer=2cm,top=3cm,bottom=2cm,showframe]{geometry}%页面

\usepackage{fancyhdr} %页眉页脚
\pagestyle{fancy}
\fancyhead[EL,OR]{\songti\zihao{-5}\thepage}
\fancyhead[ER,OL]{}
\fancyhead[OC]{\zihao{5}{\leftmark}}
\fancyhead[EC]{\zihao{5}天线设计}
\fancyfoot{} % clear all footer fields
\setlength{\headsep}{1cm}
\renewcommand{\headrulewidth}{0.75pt}
\renewcommand{\footrulewidth}{0pt}

%章节标题格式
\ctexset {
    chapter = {
        beforeskip = 36pt ,
        afterskip = 28pt ,
        pagestyle = fancy
    }
}
\usepackage[colorlinks,bookmarksnumbered]{hyperref}%书签
\usepackage{zhlipsum,lipsum}%假文

\begin{document}
{\setcounter{secnumdepth}{-1}}%抑制编号
\chapter{摘要} %摘要
\fancyhead[EL,OR]{}%不需要页码
\zhlipsum[1]
{\textbf{关键词： 甲\quad 乙\quad 丙}}
\chapter{\rmfamily Abstract}%摘要
\lipsum[1]
{\textbf{Keywords: A\quad B\quad C}}

{\setcounter{secnumdepth}{2}}%正常编号
\tableofcontents %目录
\fancyhead[EL,OR]{\songti\zihao{-5}\thepage}
\pagenumbering{Roman}%页码

\chapter{绪论}%正文
\pagenumbering{arabic}
\section{意义}
\zhlipsum[1]
\section{现状}
\zhlipsum
\section{总结}
\chapter{理论}
\zhlipsum[1]
\end{document}
```

## 链接
LaTeX 如何让不编号的章节标题显示在目录中？ - 刘海洋的回答 - 知乎
https://www.zhihu.com/question/29413517/answer/44358389
链接里面说了一些思路，但是没展开

## 附件
![Snipaste_2020-05-30_15-00-51](https://user-images.githubusercontent.com/57793534/83327758-d33aa080-a2b0-11ea-91a6-b3dc471d5c37.png)

**Comment by sikouhjw** [comment]
> 摘要和目录不编号也不出现在目录里面
```tex
%!TEX program = xelatex
\documentclass[a4paper,zihao=-4,UTF8]{ctexbook}
\usepackage[colorlinks,bookmarksnumbered]{hyperref}%书签
\usepackage{zhlipsum,lipsum}%假文
\usepackage{bookmark}
\begin{document}
\chapter*{摘要}
\bookmark[dest=\HyperLocalCurrentHref, level=1]{摘要}
\chapter*{\rmfamily Abstract}
\bookmark[dest=\HyperLocalCurrentHref, level=1]{Abstract}

\tableofcontents

\chapter{绪论}
\section{意义}
\zhlipsum[1]
\section{现状}
\zhlipsum
\section{总结}
\chapter{理论}
\zhlipsum[1]
\end{document}
```
原理参考《[[LaTeX] 把不编号章节加进目录和 PDF 书签](https://zhuanlan.zhihu.com/p/66434387)》

**Comment by krisfans** [comment]
> 
> 
> > 摘要和目录不编号也不出现在目录里面
> 
> ```
> %!TEX program = xelatex
> \documentclass[a4paper,zihao=-4,UTF8]{ctexbook}
> \usepackage[colorlinks,bookmarksnumbered]{hyperref}%书签
> \usepackage{zhlipsum,lipsum}%假文
> \usepackage{bookmark}
> \begin{document}
> \chapter*{摘要}
> \bookmark[dest=\HyperLocalCurrentHref, level=1]{摘要}
> \chapter*{\rmfamily Abstract}
> \bookmark[dest=\HyperLocalCurrentHref, level=1]{Abstract}
> 
> \tableofcontents
> 
> \chapter{绪论}
> \section{意义}
> \zhlipsum[1]
> \section{现状}
> \zhlipsum
> \section{总结}
> \chapter{理论}
> \zhlipsum[1]
> \end{document}
> ```
> 
> 原理参考《[[LaTeX] 把不编号章节加进目录和 PDF 书签](https://zhuanlan.zhihu.com/p/66434387)》

这样做可以解决不编号章节的书签以及定位不准的问题，代码也比较简洁，但是不编号章节的页眉还是不符合要求。

**Comment by sikouhjw** [comment]
给个建议，别用 `\pagenumbering`，用 `\frontmatter` 和 `\mainmatter`

**Comment by muzimuzhi** [comment]
> 我的需求是
> 
> * 奇偶页不同页眉，其中奇数页中间显示章的标题，偶数页中间显示论文标题，
> * 奇数页的左边和偶数页的右边显示页码。这里的问题是需要**摘要和目录不编号也不出现在目录里面**，然后后续章节正常编号，**参考文献与致谢不编号但是需要出现在目录**。

所有编号和不编号的章，章标题都要出现在页眉，是吗？

**Comment by krisfans** [comment]
是的。目前感觉偏向使用无编号的章节手工制作书签和页眉的情形。

**Comment by krisfans** [comment]
> 
> 
> 给个建议，别用 `\pagenumbering`，用 `\frontmatter` 和 `\mainmatter`

我试试

**Comment by sikouhjw** [comment]
> > 给个建议，别用 `\pagenumbering`，用 `\frontmatter` 和 `\mainmatter`
> 
> 我试试

这个建议只是让文章结构鲜明，对问题应该没帮助

**Comment by krisfans** [comment]
> 
> 
> > 我的需求是
> > 
> > * 奇偶页不同页眉，其中奇数页中间显示章的标题，偶数页中间显示论文标题，
> > * 奇数页的左边和偶数页的右边显示页码。这里的问题是需要**摘要和目录不编号也不出现在目录里面**，然后后续章节正常编号，**参考文献与致谢不编号但是需要出现在目录**。
> 
> 所有编号和不编号的章，章标题都要出现在页眉，是吗？

是的，所有编号和不编号的章，章标题都要出现在页眉。目前感觉偏向使用无编号的章节手工制作书签和页眉的情形。

**Comment by krisfans** [comment]
> 
> 
> > > 给个建议，别用 `\pagenumbering`，用 `\frontmatter` 和 `\mainmatter`
> > 
> > 
> > 我试试
> 
> 这个建议只是让文章结构鲜明，对问题应该没帮助

不过这样做就没法定制页码格式了

**Comment by muzimuzhi** [comment]
### 手动

```tex
% 手动把 `\chapter*` 加入页眉、目录和 PDF 书签
\chapter*{标题}
\chaptermark{标题}
\addcontentsline{toc}{chapter}{标题}

% 手动把 `\chapter*` 加入页眉和 PDF 书签，但不加入目录
\chapter*{标题}
\chaptermark{标题}
\bookmark[dest=\HyperLocalCurrentHref, level=0]{标题}
```

### 一个半自动的尝试

```tex
\documentclass{ctexbook}
\usepackage{fancyhdr}
\usepackage{lipsum}
\usepackage{tocbibind}

\usepackage[colorlinks,bookmarksnumbered]{hyperref}
\usepackage{bookmark}

\pagestyle{fancy}
\fancyhead{}
\fancyfoot{}
\fancyhead[EL,OR]{\thepage}
\fancyhead[OC]{\leftmark}
\fancyhead[EC]{Title}

\makeatletter
\ctexset{
  % 令所有 \chapter* 都出现在页眉
  chapter/aftertitle+={%
    \CTEXifname{}{\chaptermark{\@currentlabelname}}%
  }
}

\newif\if@addtoc

\newcommand{\addTocAndBookmark}{%
  \@addtoctrue
  \expandafter\@getHrefName\@currentHref\@nil
}

\newcommand{\addBookmark}{%
  \@addtocfalse
  \expandafter\@getHrefName\@currentHref\@nil
}

\def\@getHrefName#1.#2\@nil{%
  \edef\@tempa{\detokenize{#1}}%
  \edef\@tempb{\detokenize{chapter*}}%
  \ifx\@tempa\@tempb
    \if@addtoc
      \edef\@tempa{\noexpand\addcontentsline{toc}{chapter}{\@currentlabelname}}%
    \else
      % use "level=0" or "level=chapter"
      \edef\@tempa{\noexpand\bookmark[dest=\HyperLocalCurrentHref, level=0]{\@currentlabelname}}%
    \fi
    \@tempa
  \fi
}
\makeatother

\begin{document}
\chapter*{不编号、无目录条目、出现在页眉、生成PDF书签}
\addBookmark

text\newpage text\newpage text

\chapter*{不编号、有目录条目、出现在页眉、生成PDF书签}
\addTocAndBookmark

text\newpage text\newpage text

\tableofcontents
\end{document}
```

**Comment by muzimuzhi** [comment]
@sikouhjw `\chapter` 对应的层级是 0，`\section` 对应的层级是 1。那篇知乎文章里用 `\section*` 举例，所以用的是 `level=1`。当前 issue 里需要给 `\chapter*` 加书签，应该用 `\bookmark[..., level=0]{}`。`bookmark` 宏包也支持直接写 `level=[section|chapter]`。

**Comment by sikouhjw** [comment]
> @sikouhjw `\chapter` 对应的层级是 0，`\section` 对应的层级是 1。那篇知乎文章里用 `\section*` 举例，所以用的是 `level=1`。当前 issue 里需要给 `\chapter*` 加书签，应该用 `\bookmark[..., level=0]{}`。`bookmark` 宏包也支持直接写 `level=[section|chapter]`。

啊我没细看，因为编译出来的书签是同等级的，没注意，可能是因为 `\section` 无法在前面没有 `\chapter` 的情况下单独为第二层书签

**Comment by krisfans** [comment]
> 
> ### 手动
> 
> ```
> % 手动把 `\chapter*` 加入页眉、目录和 PDF 书签
> \chapter*{标题}
> \chaptermark{标题}
> \addcontentsline{toc}{chapter}{标题}
> 
> % 手动把 `\chapter*` 加入页眉和 PDF 书签，但不加入目录
> \chapter*{标题}
> \chaptermark{标题}
> \bookmark[dest=\HyperLocalCurrentHref, level=0]{标题}
> ```
> 
> ### 一个半自动的尝试
> 
> ```
> \documentclass{ctexbook}
> \usepackage{fancyhdr}
> \usepackage{lipsum}
> \usepackage{tocbibind} % 把 \tableofcontents 的标题加入目录和书签
> 
> \usepackage[colorlinks,bookmarksnumbered]{hyperref}
> \usepackage{bookmark}
> 
> \pagestyle{fancy}
> \fancyhead{}
> \fancyfoot{}
> \fancyhead[EL,OR]{\thepage}
> \fancyhead[OC]{\leftmark}
> \fancyhead[EC]{Title}
> 
> \makeatletter
> \ctexset{
>   % 令所有 \chapter* 都出现在页眉
>   chapter/aftertitle+={%
>     \CTEXifname{}{\chaptermark{\@currentlabelname}}%
>   }
> }
> 
> \newif\if@addtoc
> 
> \newcommand{\addTocAndBookmark}{%
>   \@addtoctrue
>   \expandafter\@getHrefName\@currentHref\@nil
> }
> 
> \newcommand{\addBookmark}{%
>   \@addtocfalse
>   \expandafter\@getHrefName\@currentHref\@nil
> }
> 
> \def\@getHrefName#1.#2\@nil{%
>   \edef\@tempa{\detokenize{#1}}%
>   \edef\@tempb{\detokenize{chapter*}}%
>   \ifx\@tempa\@tempb
>     \if@addtoc
>       \edef\@tempa{\noexpand\addcontentsline{toc}{chapter}{\@currentlabelname}}%
>     \else
>       % use "level=0" or "level=chapter"
>       \edef\@tempa{\noexpand\bookmark[dest=\HyperLocalCurrentHref, level=0]{\@currentlabelname}}%
>     \fi
>     \@tempa
>   \fi
> }
> \makeatother
> 
> \begin{document}
> \chapter*{不编号、无目录条目、出现在页眉、生成PDF书签}
> \addBookmark
> 
> text\newpage text\newpage text
> 
> \chapter*{不编号、有目录条目、出现在页眉、生成PDF书签}
> \addTocAndBookmark
> 
> text\newpage text\newpage text
> 
> \tableofcontents
> \end{document}
> ```

感觉还是手动写入页眉书签目录好一点。

**Comment by muzimuzhi** [comment]
为了简化最终的输入（半自动或自动），内部实现多少要复杂一些。

**Comment by qinglee** [comment]
大家都想复杂了，直接在目录中合理设置 `tocdepth` 就可以了。

```TeX
%!TEX program = xelatex
\documentclass[a4paper,zihao=-4,UTF8]{ctexbook}
\usepackage[inner=3cm,outer=2cm,top=3cm,bottom=2cm,headsep=1cm,showframe]{geometry}

\usepackage{fancyhdr}

\usepackage{zhlipsum,lipsum}
\usepackage[colorlinks]{hyperref}
\usepackage{bookmark}

\bookmarksetup {
  open     = true ,
  numbered = true ,
  depth    = subparagraph ,
}

\fancyhead{}
\fancyfoot{}
\fancyhead[OC]{\zihao{5}{\leftmark}}
\fancyhead[EC]{\zihao{5}天线设计}
\renewcommand{\headrulewidth}{0.75pt}
\renewcommand{\footrulewidth}{0pt}
\fancypagestyle{abstract}{%
  \fancyhead[EL,OR]{}}
\fancypagestyle{main}{%
  \fancyhead[EL,OR]{\zihao{-5}\thepage}}

\ctexset {
    chapter = {
        beforeskip = 36pt ,
        afterskip  = 28pt ,
        pagestyle  = fancy
    }
}

\makeatletter
\protected\def\SETTOCDEPTH#1{%
  \setcounter{tocdepth}{#1}}
\g@addto@macro\frontmatter{%
  \addtocontents{toc}{\SETTOCDEPTH{-10}\protected@file@percent}}
\let\abstractmatter\frontmatter
\g@addto@macro\abstractmatter{%
  \pagestyle{abstract}}
\g@addto@macro\frontmatter{%
  \pagestyle{main}%
  \pagenumbering{Roman}}
\g@addto@macro\mainmatter{%
  \pagestyle{main}%
  \addtocontents{toc}{\SETTOCDEPTH{2}\protected@file@percent}}
\renewcommand\tableofcontents{%
  \chapter{\contentsname}%
  \@starttoc{toc}}
\makeatother

\begin{document}

\abstractmatter

\chapter{摘要}
\zhlipsum[1]

\chapter{Abstract}
\lipsum[1]

\frontmatter

\tableofcontents

\mainmatter

\chapter{绪论}
\section{意义}
\zhlipsum[1]
\section{现状}
\zhlipsum
\section{总结}
\chapter{理论}
\zhlipsum[1]

\end{document}

```

**Comment by krisfans** [comment]
> 
> 
> 大家都想复杂了，直接在目录中合理设置 `tocdepth` 就可以了。
> 
> ```
> %!TEX program = xelatex
> \documentclass[a4paper,zihao=-4,UTF8]{ctexbook}
> \usepackage[inner=3cm,outer=2cm,top=3cm,bottom=2cm,headsep=1cm,showframe]{geometry}
> 
> \usepackage{fancyhdr}
> 
> \usepackage{zhlipsum,lipsum}
> \usepackage[colorlinks]{hyperref}
> \usepackage{bookmark}
> 
> \bookmarksetup {
>   open     = true ,
>   numbered = true ,
>   depth    = subparagraph ,
> }
> 
> \fancyhead{}
> \fancyfoot{}
> \fancyhead[OC]{\zihao{5}{\leftmark}}
> \fancyhead[EC]{\zihao{5}天线设计}
> \renewcommand{\headrulewidth}{0.75pt}
> \renewcommand{\footrulewidth}{0pt}
> \fancypagestyle{abstract}{%
>   \fancyhead[EL,OR]{}}
> \fancypagestyle{main}{%
>   \fancyhead[EL,OR]{\zihao{-5}\thepage}}
> 
> \ctexset {
>     chapter = {
>         beforeskip = 36pt ,
>         afterskip  = 28pt ,
>         pagestyle  = fancy
>     }
> }
> 
> \makeatletter
> \protected\def\SETTOCDEPTH#1{%
>   \setcounter{tocdepth}{#1}}
> \g@addto@macro\frontmatter{%
>   \addtocontents{toc}{\SETTOCDEPTH{-10}\protected@file@percent}}
> \let\abstractmatter\frontmatter
> \g@addto@macro\abstractmatter{%
>   \pagestyle{abstract}}
> \g@addto@macro\frontmatter{%
>   \pagestyle{main}%
>   \pagenumbering{Roman}}
> \g@addto@macro\mainmatter{%
>   \pagestyle{main}%
>   \addtocontents{toc}{\SETTOCDEPTH{2}\protected@file@percent}}
> \renewcommand\tableofcontents{%
>   \chapter{\contentsname}%
>   \@starttoc{toc}}
> \makeatother
> 
> \begin{document}
> 
> \abstractmatter
> 
> \chapter{摘要}
> \zhlipsum[1]
> 
> \chapter{Abstract}
> \lipsum[1]
> 
> \frontmatter
> 
> \tableofcontents
> 
> \mainmatter
> 
> \chapter{绪论}
> \section{意义}
> \zhlipsum[1]
> \section{现状}
> \zhlipsum
> \section{总结}
> \chapter{理论}
> \zhlipsum[1]
> 
> \end{document}
> ```

谢谢，问题解决了。这样做的原理是不是让编号的章节只是不出现在目录？
