### ISSUE TITLE
ctexbeamer 更改字体问题

### ISSUE THREAD

**Issue by muyuuuu** [CTeX-org/forum#123]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [x] Linux（Manjaro）

- TeX 发行版
  - [ ] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

是这样的，我的目标是：在`ctexart`中使用`palatino`字体，但数学字体也随之更改的很丑。我参考了lshort，在文档类中加入`no-math`选项，但并没有用。

# MWE

## no-math 选项和效果展示

![image](https://user-images.githubusercontent.com/43681138/83860854-66148880-a752-11ea-9a79-1318f0e5d332.png)

附MWE：
```tex
\documentclass[no-math]{ctexbeamer}
\usepackage{amsmath}
\setCJKmainfont{SourceHanSansCN-Normal}
\setmainfont{texgyrepagella-regular.otf}

\mode<presentation>
{
  \usetheme{Madrid}       % or try default, Darmstadt, Warsaw, ...
  \usecolortheme{default} % or try albatross, beaver, crane, ...
  \usefonttheme{serif}    % or try default, structurebold, ...
%   \setbeamertemplate{navigation symbols}{}
  \setbeamertemplate{caption}[numbered]
} 

% Here's where the presentation starts, with the info for the title slide
\title[\LaTeX{} Program]{论文报告}
\author{兰铃}
\institute{失业了}
\date{\today}

\begin{document}

\begin{frame}
  \titlepage
\end{frame}


\section{测试}

\begin{frame}{参考文献}
    文字

    English

    公式：$a+b=c$
\end{frame}

\end{document}
```

如果去掉`setmainfont`，公式就正常了，效果如下：

![image](https://user-images.githubusercontent.com/43681138/83860977-978d5400-a752-11ea-9e20-59d4b99b8775.png)

MWE如下：
```tex
\documentclass[no-math]{ctexbeamer}
\usepackage{amsmath}
\setCJKmainfont{SourceHanSansCN-Normal}

\mode<presentation>
{
  \usetheme{Madrid}       % or try default, Darmstadt, Warsaw, ...
  \usecolortheme{default} % or try albatross, beaver, crane, ...
  \usefonttheme{serif}    % or try default, structurebold, ...
%   \setbeamertemplate{navigation symbols}{}
  \setbeamertemplate{caption}[numbered]
} 

% Here's where the presentation starts, with the info for the title slide
\title[\LaTeX{} Program]{论文报告}
\author{兰铃}
\institute{失业了}
\date{\today}

\begin{document}

\begin{frame}
  \titlepage
\end{frame}


\section{测试}

\begin{frame}{参考文献}
    文字

    English

    公式：$a+b=c$
\end{frame}

\end{document}
```

所以，我的需求是英文字体设置为`palatino`，但不影响数学公式的正常显示。

**Comment by stone-zeng** [comment]
```tex
\documentclass{ctexbeamer}
\usepackage{amsmath}

\usefonttheme{serif}

\setCJKmainfont{Source Han Sans SC}
\setmainfont{texgyrepagella.otf}[
  Extension      = .otf,
  UprightFont    = *-regular,
  BoldFont       = *-bold,
  ItalicFont     = *-italic,
  BoldItalicFont = *-bolditalic,
]

\usepackage{unicode-math}
\setmathfont{texgyrepagella-math.otf}

\title[\LaTeX{} Program]{论文报告}
\author{兰铃}
\institute{失业了}
\date{\today}

\begin{document}

\maketitle

\begin{frame}{参考文献}
文字 English 公式：$a^2+b^2=c^2 \int \sum \sin x \mathrm{d}x$
\end{frame}

\end{document}
```

![](https://user-images.githubusercontent.com/18233088/83862674-da502b80-a754-11ea-94d9-b9dcb538c539.png)

**Comment by muyuuuu** [comment]
可能是我表达有误：英文字体`palatino`，数学字体就用哪种正常的，emmm，非专业人士不知道如何描述正常的数学字体了。意思是这样的[字体](https://user-images.githubusercontent.com/43681138/83860977-978d5400-a752-11ea-9e20-59d4b99b8775.png)，别问为啥用URL，问就是图片文件传不上来...

我在本地测试了一下，`\setmathfont{texgyrepagella-math.otf}`似乎对我有点多余，按照字面意思我猜去掉这句话不会影响我的其他内容。

不愧是你:satisfied:，我没有其它问题了，可以close。

**Comment by stone-zeng** [comment]
数学（公式里面的）字体也分：变量、算符、数字、文本等。e.g. 那个 sin 要用 palatino 还是 latin modern 呢？

**Comment by muyuuuu** [comment]
> 那个 sin 要用 palatino 还是 latin modern 呢？

我知识贫瘠表达不清的锅，用latin modern。

**Comment by sikouhjw** [comment]
> 我知识贫瘠表达不清的锅，用latin modern。

`\setmathfont{Latin Modern Math}`

**Comment by muyuuuu** [comment]
> \setmathfont{Latin Modern Math}
多谢。

**Comment by sikouhjw** [comment]
> > \setmathfont{Latin Modern Math}
> 
> 多谢。

解决不了算符的问题，还是等别人吧

**Comment by stone-zeng** [comment]
```tex
\usefonttheme{professionalfonts}
% 注意下面要用 sans
\setCJKsansfont{Source Han Sans SC}
\setsansfont{texgyrepagella.otf}[
  Extension      = .otf,
  UprightFont    = *-regular,
  BoldFont       = *-bold,
  ItalicFont     = *-italic,
  BoldItalicFont = *-bolditalic,
]
% 不需要 unicode-math
```

![image](https://user-images.githubusercontent.com/18233088/83882002-121a9b80-a774-11ea-821b-b039d12f0f51.png)

另外，用**字体文件名**调用的时候，必须手动指定 bold/italic 等，`fontspec` 不会自动选择。所以尽量用**字体名**（除非是 mac 调 TEXMF 里面的字体）。
