### ISSUE TITLE
在MiKTeX下使用BibTeX编译参考文献乱码

### ISSUE THREAD

**Issue by krisfans** [CTeX-org/forum#124]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [ ] TeX Live 
  - [x] MiKTeX  `2.9.7440 64-bit`
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题
在Windows下使用bibtex编译参考文献乱码，主要是是**版本**乱码。如图

这是用`MiKTex 2.9`的输出结果
![Snipaste_2020-06-07_21-28-07](https://user-images.githubusercontent.com/57793534/83970114-7e2d0900-a906-11ea-8fad-60710b984c33.png)

这是`TeX Live 2020`
![Snipaste_2020-06-07_21-29-46](https://user-images.githubusercontent.com/57793534/83970144-9e5cc800-a906-11ea-8a21-17c283717880.png)

## 最小工作示例（MWE）

```latex
% !TEX program = xelatex
\documentclass[a4paper,UTF8]{ctexbook}

\usepackage{gbt7714}%参考文献
\bibliographystyle{gbt7714-numerical} % 角标数字顺序编码
\usepackage{zhlipsum,lipsum}
\begin{document}
\nocite{*}
\bibliography{1}
\end{document}
```

参考文献`bib`文件
```tex
@book{lhmdcc237,
	author = {路宏敏 and 赵永久 and 朱满座},
	edition = {2},
	title = {电磁场与电磁波基础},
	publisher = {科学出版社},
	address = {北京},
	pages = {237},
	year = {2012},
}
@book{lchjmwb,
	author = {梁昌洪 and 谢拥军 and 官伯然},
	edition = {1},
	title = {简明微波},
	publisher = {高等教育出版社},
	address = {北京},
	pages = {172-172},
	year = {2006},
}
@book{edahfss,
	author = {易迪拓培训 and 李明洋 and 刘敏},
	edition = {1},
	title = {HFSS电磁仿真设计从入门到精通},
	publisher = {人民邮电出版社},
	address = {北京},
	pages = {123},
	year = {2013},
}
@ARTICLE{6491434,
	author={B. {Li} and S. {Liao} and Q. {Xue}},
	journal={IEEE Antennas and Wireless Propagation Letters},
	title={Omnidirectional Circularly Polarized Antenna Combining Monopole and Loop Radiators},
	year={2013},
	volume={12},
	number={},
	pages={607-610},
}

@ARTICLE{6310031,
	author={Y. {Pan} and K. W. {Leung}},
	journal={IEEE Transactions on Antennas and Propagation},
	title={Wideband Circularly Polarized Dielectric Bird-Nest Antenna With Conical Radiation Pattern},
	year={2013},
	volume={61},
	number={2},
	pages={563-570},
}

```

## 附件
编译日志
[1.log](https://github.com/CTeX-org/forum/files/4742134/1.log)
bbl文件
[1.bbl](https://github.com/CTeX-org/forum/files/4742135/1.txt)

**Comment by zepinglee** [comment]
同 https://github.com/CTeX-org/gbt7714-bibtex-style/issues/57

**Comment by krisfans** [comment]
> 
> 
> 同 [CTeX-org/gbt7714-bibtex-style#57](https://github.com/CTeX-org/gbt7714-bibtex-style/issues/57)

这么说来就是这个包的问题了，下个包就好了。我还以为是miktex的bibtex出了问题。

**Comment by krisfans** [comment]
前几次更新解决了
