### ISSUE TITLE
minted 环境内 xeCJK 中西文与汉字的胶与 luatexja 中汉字字体问题

### ISSUE THREAD

**Issue by tanukihee** [CTeX-org/forum#125]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题
在 xeCJK 下的 minted 环境中，代码的 `"` 与中文间会自动插入胶；而在 luatexja 下，代码字体的配置又会出现问题。

## 最小工作示例（MWE）

xeCJK 下
```latex
\documentclass{ctexart}
\setCJKmainfont{Source Han Serif CN}
\setCJKmonofont{Sarasa Mono SC}
\setmonofont{Sarasa Mono SC}
\usepackage{minted}

\begin{document}
\begin{minted}{py}
    print("你好世界 Hello World")
    # 你好世界 Hello World
\end{minted}
\end{document}
```

用 XeLaTeX 编译后效果
![image](https://user-images.githubusercontent.com/34062491/83991686-27fcac00-a980-11ea-91f6-f4cc6ed1f190.png)

luatexja 下
```LaTeX
\documentclass{ltjarticle}
\usepackage{luatexja-fontspec}

\setmainjfont{Source Han Serif CN}
\setmonojfont{Sarasa Mono SC}
\setmonofont{Sarasa Mono SC}

\usepackage{minted}
\begin{document}
\begin{minted}{py}
    print("你好世界 Hello World")
    # 你好世界 Hello World
\end{minted}
\end{document}
```

用 LuaLaTeX 编译后效果
![image](https://user-images.githubusercontent.com/34062491/83991728-51b5d300-a980-11ea-8122-51c428b7179a.png)

可见，xeCJK 下，代码的字体正常，而 `"` 与汉字间却被插入了一个胶，拉开了其间的距离。

而在 luatexja 下，`"` 与汉字间的胶虽然没有了，但中文字体又出现了问题。

**Comment by qinglee** [comment]
请仔细看文档。

1. `\setminted{formatcom=\xeCJKVerbAddon}`
2. `\usepackage[match]{luatexja-fontspec}`

**Comment by tanukihee** [comment]
解决了，感谢
