### ISSUE TITLE
xeCJK：同一字体无法分别使用横排和竖排

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/forum#127]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [x] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

问题来源于尝试用仿宋在文档的不同位置分别使用横排和竖排。

```latex
\documentclass{article}
\usepackage{xeCJK}

\newCJKfontfamily\fangsong{FandolFang-Regular.otf}
\newCJKfontfamily\fangsongvert{FandolFang-Regular.otf}[RawFeature={vertical}]

\newcommand\testa{%
  \begingroup
    \fangsong
    劳仑衣普桑\par
  \endgroup
}

\newcommand\testb{%
  \begingroup
    \fangsongvert
    % \fangsong\addCJKfontfeatures*{RawFeature={vertical}}%
    认至将指点\par
  \endgroup
}

\begin{document}
\testa
\testb
\end{document}

```
编译的结果是
<img width="130" alt="Screen Shot 2020-06-10 at 22 56 17" src="https://user-images.githubusercontent.com/12290822/84283505-a5d1da80-ab6d-11ea-8d8d-026c60fa8ce1.png">

但是如果交换 `\testa` 和 `\textb` 的位置，结果是：
<img width="155" alt="Screen Shot 2020-06-10 at 22 57 52" src="https://user-images.githubusercontent.com/12290822/84283665-d74aa600-ab6d-11ea-87f0-3e2c32db1923.png">

所以在同一字体上定义的两个命令，虽然设置了不同的 RawFeature，但是只有第一个才会启用。
那么有没有办法在两处分别使用横排和竖排？

**Comment by sikouhjw** [comment]
这个问题应该已经修复了，我用 `This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022)` 这个版本的 `xelatex` 编译，效果是正确的。
![图片](https://user-images.githubusercontent.com/49770925/195981694-0e9a3b80-f94f-4a9a-8043-bb75963edc62.png)

**Comment by zepinglee** [comment]
> 这个问题应该已经修复了，我用 `This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022)` 这个版本的 `xelatex` 编译，效果是正确的。 ![图片](https://user-images.githubusercontent.com/49770925/195981694-0e9a3b80-f94f-4a9a-8043-bb75963edc62.png)

确实已经修复。

**Comment by muzimuzhi** [comment]
没找到是哪个提交修复的……
https://github.com/TeX-Live/texlive-source/commits/trunk/texk/web2c/xetexdir
