### ISSUE TITLE
tikz画图问题

### ISSUE THREAD

**Issue by xiaohe6** [CTeX-org/forum#130]
\documentclass{standalone}

\usepackage{tikz}
\usetikzlibrary{calc}

\begin{document}

	\begin{tikzpicture}[scale=3,declare function={f(\x)=((1-(\x)^(2))^(0.5);}]
	\node[left] at (0,.5) {$\frac{1}{2}$};
	\node[below] at (0.86602540378443,0) {$\frac{\sqrt{3}}{2}$};
	\node[below] at (1,0) {$1$};
	\node[left] at (0,1) {$1$};
	\node[above] at (0.8,0.85) {$y=\sqrt{1-x^2}$};
	\coordinate (a) at (0.86602540378443,0);
	\coordinate (b) at (0,.5);
	\draw[dashed] (0.86602540378443,0) -- (0.86602540378443,0 |- b);

	\draw[dashed] (0,.5) -- (0,.5 -| a);
	\draw [-latex] (-0.3,0) -- (1.3,0) node (xaxis) [below] {$x$};
	\draw [-latex] (0,-0.3) -- (0,1.3) node [left] {$y$};
	\draw[domain=0:1,samples=500,variable=\x,red,-,thick] plot ({\x},{f(\x)});  

	\end{tikzpicture}
\end{document}

各位大佬，为何X轴处未连接上

**Comment by sunmy2019** [comment]
取样点是有误差的，内部计算精度也没那么高

**Comment by sunmy2019** [comment]
至于你这个问题，可以把 sample 改成 8000

**Comment by xiaohe6** [comment]
解决了，感谢大佬！

**Comment by muzimuzhi** [comment]
可以用 `samples at` 选项，根据函数图像在 x = 1 附近斜率趋于无穷的特征，在接近 x = 1 时增加采样密度
```tex
\draw[domain=0:1,samples at={0,0.01,...,0.99,0.9925,0.995,0.9975,1},variable=\x,red,thick] 
  plot (\x, {f(\x)});
```
还可以用参数方程绘图（此处采用极坐标，在 0--90 度范围内均匀采样）
```tex
\draw[domain=0:90,samples=500,variable=\t,red,thick] 
  plot ({sin(\t)}, {cos(\t)});
```

**Comment by xiaohe6** [comment]
参数方程，多了一种思路。感谢大佬。（抱歉，issue关早了）

**Comment by RuixiZhang42** [comment]
参数方程+1，而且一旦用参数了，取样点也就不需要这么多了，可以 `samples=50` 搭配 `smooth` 使用：
```latex
\draw[domain=0:90,samples=50,smooth,variable=\t,red,thick] 
  plot ({sin(\t)}, {cos(\t)});
```

另，双曲线也可以这么干：https://tex.stackexchange.com/a/449058
