### ISSUE TITLE
macos系统中的texpad编译后PDF莫名多出一页

### ISSUE THREAD

**Issue by kuku1993** [CTeX-org/forum#133]
## 检查

- [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [x] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

 ：将\cortext[cor1]{Corresponding author}注释掉，则页数正常。但是达不到我想要的效果。

## 最小工作示例（MWE）

最小的MWE的
![编译后的错误提示](https://user-images.githubusercontent.com/54982333/87844283-4d20fa80-c8ee-11ea-8bef-c45dc8b7e490.jpg)
源代码在压缩包中
\documentclass[a4paper, longmktitle]{cas-sc}
\usepackage[authoryear]{natbib}
\usepackage{lineno}
\begin{document}
\title [mode = title]{An Embedded Discrete }                      
\author{H}[
orcid=00]
\cormark[1]
\fnmark[1]
\ead{li}
\cortext[cor1]{Corresponding author}
\maketitle
\end{document}
\endinput

（用 PdfLaTeX 编译后）输出

在上传的
[test.zip](https://github.com/CTeX-org/forum/files/4941041/test.zip)
![编译后的PDF结果](https://user-images.githubusercontent.com/54982333/87844279-41353880-c8ee-11ea-973c-1422aad9dbb7.jpg)

图片中

## 链接

- TeX.SX:
- GitHub:

**Comment by muzimuzhi** [comment]
在 `Manuscript.tex` 的开头，加上一行
```tex
\RequirePackage[undo-recent-deprecations]{expl3} % 新加的一行
\documentclass[a4paper, longmktitle]{cas-sc}
```

PS：这说明 `els-cas-templates` 该更新了。

**Comment by kuku1993** [comment]
厉害，感谢感谢！

**Comment by muzimuzhi** [comment]
提醒，若编译报错，则无论输出是否符合预期，都应提及第一条报错信息。

![image](https://user-images.githubusercontent.com/6376638/87844687-34b2df00-c8f2-11ea-8cf0-eb7d6a8d568a.png)

**Comment by kuku1993** [comment]
哦哦

**Comment by muzimuzhi** [comment]
> PS：这说明 `els-cas-templates` 该更新了。

@kuku1993 
前面我说错了。
 - `cas-sc.cls` 属于 CTAN 包 [`els-cas-templates`](https://ctan.org/pkg/els-cas-templates)，该包的最新版是 v2.1 2020-03-14，expl3 deprecated functions 的问题已经解决
 - 你例子里提供的 `cas-sc.cls` 是 v1.0 2018/09/22

所以是你应该使用最新的 `els-cas-templates`。

**Comment by kuku1993** [comment]
哦哦，谢谢！
