### ISSUE TITLE
用 CTeX 套装编译《系统工程学报》LaTeX 模板出现奇怪的问题

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#134]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [x] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [x] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

群里有人编译《系统工程学报》LaTeX 模板出现问题，报错为
```tex
! LaTeX Error: Missing \begin{document}.
```
我先让他替换 `gb.cap` 和 `gb.cpx`，发现无效，远程第一次，没找到问题。

我将在我电脑上能编译的[文件](https://github.com/CTeX-org/forum/files/4943587/JSETemplate0719.txt)发给他，报错变成了
```latex
! Package CJK Error: Invalid character code.

See the CJK package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.32 ...on" content="\LaTeX 中文模版收集。.
                                                   Contribute to DeathKing/L...

? x
```
这是用 `pdflatex` 编译报错的[完整文件](https://github.com/CTeX-org/forum/files/4943579/JSETemplate0719.zip)，请问可能是什么原因造成的？

**Comment by muzimuzhi** [comment]
> 这是用 `pdflatex` 编译报错的[完整文件](https://github.com/CTeX-org/forum/files/4943579/JSETemplate0719.zip)，请问可能是什么原因造成的？

JSETemplate0719.zip 里的 log 不是原始 log，因为它包含了
 - html tag，例如
    ```
     (D:\E\software\CTeX\MiKTeX\tex\latex\cjk\GB\GB.cpx
     Overfull \hbox (65.43634pt too wide) in paragraph at lines 6--17
     []\OT1/ptm/m/n/10 <!DOCTYPE htm-l> <htm-l lang="en"> <head> <meta charset="utf-
     8"> <link rel="dns-prefetch" hre-f="https://github.githubassets.com">
      []
 - 在 tex 文件里不存在的内容，例如报错信息
    ```
    l.32 ...on" content="\LaTeX 中文模版收集。.
                                                       Contribute to DeathKing/L...
    ```

请提供真正和 tex 文件对应的 log。

**Comment by sikouhjw** [comment]
> 
> 
> > 这是用 `pdflatex` 编译报错的[完整文件](https://github.com/CTeX-org/forum/files/4943579/JSETemplate0719.zip)，请问可能是什么原因造成的？
> 
> JSETemplate0719.zip 里的 log 不是原始 log，因为它包含了
> 
>     * html tag，例如
>       ```
>        (D:\E\software\CTeX\MiKTeX\tex\latex\cjk\GB\GB.cpx
>        Overfull \hbox (65.43634pt too wide) in paragraph at lines 6--17
>        []\OT1/ptm/m/n/10 <!DOCTYPE htm-l> <htm-l lang="en"> <head> <meta charset="utf-
>        8"> <link rel="dns-prefetch" hre-f="https://github.githubassets.com">
>         []
>       ```
> 
>     * 在 tex 文件里不存在的内容，例如报错信息
>       ```
>       l.32 ...on" content="\LaTeX 中文模版收集。.
>                                                          Contribute to DeathKing/L...
>       ```
> 
> 
> 请提供真正和 tex 文件对应的 log。

在第二次远程的时候，我用 `pdflatex` 编译，报出的 `log` 文件就是这个，不知道是 `winedt` 还是哪个地方出的问题，等会我试试命令行编译，看结果是否一致

**Comment by sikouhjw** [comment]
让他用命令行编译了一次，结果如下
![1](https://user-images.githubusercontent.com/49770925/88049706-2a117780-cb88-11ea-9f68-21d60b05dfa9.jpg)
询问了他有没有改动 CTeX 套装，回答是只新安装了 winedt 10.3，对命令行编译没有影响，我只能猜测是操作系统 / 其它未知的问题了，我让他换一台电脑试试了。
