### ISSUE TITLE
 File `ctexbook.cls' not found.

### ISSUE THREAD

**Issue by memento1** [CTeX-org/forum#136]
## 检查

- [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ x] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [ x] macTeX
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\begin{document}
Hello, \LaTex!
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
! Undefined control sequence.
l.3 Hello, \LaTex
                 !
?
```

## 链接

- TeX.SX:
- GitHub:

**Comment by muzimuzhi** [comment]
1. issue 标题里写的报错信息是 "File `ctexbook.cls' not found."，mwe 里提供的报错信息是 "! Undefined control sequence. l.3 Hello, \LaTex"，两者不同。遇到的具体是哪个问题？
1. 对编译 mwe 得到的报错，mwe 里应该改成 `\LaTeX`，注意 `X` 是大写。
