### ISSUE TITLE
用 xelatex 编译 graphics 文档源码时报错 xdvipdfmx:fatal: pdf_link_obj(): passed invalid object.

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#137]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

我在用 xelatex 编译 graphics 文档源码时报错，我整理了一份 MWE 复现问题

## 最小工作示例（MWE）

[mwe.zip](https://github.com/CTeX-org/forum/files/4954281/mwe.zip)

（用 XeLaTeX 编译后）输出

```latex
xdvipdfmx:fatal: pdf_link_obj(): passed invalid object.

No output PDF file written.
xelatex.exe: fwrite: Broken pipe
```

## 链接

- pipermail: [https://tug.org/pipermail/xetex/2011-July/020957.html](https://tug.org/pipermail/xetex/2011-July/020957.html)

**Comment by muzimuzhi** [comment]
直接用 xdvipdfmx，还能多看到一条信息（但 "endobj" 的数量是对的）
```
xdvipdfmx:warning: Didn't find "endobj".
```

用 lualatex 也编不过
```
! error:  (file a.pdf) (pdf inclusion): reading image failed
!  ==> Fatal error occurred, no output PDF file produced!%
```

用 Adobe Reader 打开 `a.pdf`，会提示另存为；试了几个在线的 pdf validator，报了一些不一致的问题。只能猜测这个手写的 pdf 文件（或者是 gs 生成后手动修改）不严格符合规范，恰好 pdftex 的检查比较松。

**Comment by sikouhjw** [comment]
> 直接用 xdvipdfmx，还能多看到一条信息（但 "endobj" 的数量是对的）
> 
> ```
> xdvipdfmx:warning: Didn't find "endobj".
> ```
> 
> 用 lualatex 也编不过
> 
> ```
> ! error:  (file a.pdf) (pdf inclusion): reading image failed
> !  ==> Fatal error occurred, no output PDF file produced!%
> ```
> 
> 用 Adobe Reader 打开 `a.pdf`，会提示另存为；试了几个在线的 pdf validator，报了一些不一致的问题。只能猜测这个手写的 pdf 文件（或者是 gs 生成后手动修改）不严格符合规范，恰好 pdftex 的检查比较松。
> 
> PS：根据 `graphics` bundle 的编译脚本和 CI 日志，它只用 pdflatex 编文档。

好的，我回去试试自己画一个图片，再看能不能编译通过。

**Comment by sikouhjw** [comment]
我用 Acrobat Reader DC 将 `a.pdf` 另存为另一个 pdf 文件，再插入就可以了

**Comment by stone-zeng** [comment]
见 <https://github.com/latex3/latex2e/issues/357>。

**Comment by sikouhjw** [comment]
> 见 [latex3/latex2e#357](https://github.com/latex3/latex2e/issues/357)。

ok，我先绕过这个问题继续写东西
