### ISSUE TITLE
去掉 \part 的标题后导致目录中的顺序错误

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/forum#138]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [x] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 最小工作示例（MWE）

我的目的是将 `\part` 只加入目录中，但不出现 `\part` 的标题内容。

```latex
\documentclass{book}
\usepackage{filecontents}

\makeatletter
% 这里去掉 \part 的标题，只加入目录
\renewcommand\part[1]{%
  \cleardoublepage
  \addcontentsline{toc}{part}{#1}%
}
\makeatother

\begin{document}

\begin{filecontents}{test-1.tex}
\chapter{Foo Chapter}
\end{filecontents}

\frontmatter
\tableofcontents

\mainmatter
\part{Foo Part}
% 如果用 \include 的方式，会导致目录中的顺序错误
\include{test-1}
% 直接用 \chapter 并不会出现这个问题
% \chapter{Foo Chapter}
\chapter{Bar Chapter}
\end{document}
```

编译结果：目录中的“Foo Part”出现在了“Foo Chapter”后面。
<img width="321" alt="Screen Shot 2020-07-23 at 22 28 11" src="https://user-images.githubusercontent.com/12290822/88298482-ce83ed00-cd33-11ea-8702-9eea5995c73c.png">

这是由于“Part Foo”和“Chapter Foo”在同一页，但是 `test.aux` 中强行先 `\@input{test-1.aux}`：
```latex
\relax 
\@input{test-1.aux}
\@writefile{toc}{\contentsline {part}{Foo Part}{1}\protected@file@percent }
\@writefile{toc}{\contentsline {chapter}{\numberline {2}Bar Chapter}{3}\protected@file@percent }
\@writefile{lof}{\addvspace {10\p@ }}
\@writefile{lot}{\addvspace {10\p@ }}
```

有没有其他解决方案？

**Comment by muzimuzhi** [comment]
- `\addcontentsline` 内部使用 `\protected@write`，最终使用 `\write`，也就是在下一次 `\shipout` 时 `\write` 才执行；
 - `\include` 内部使用 `\immediate\write`，立即执行。
这导致 `test.aux` 里 toc 条目的顺序，和正文中的不同。

让 `\addcontentsline` 也（有条件地）`\immediate\write` 就行了。

```tex
\begin{filecontents}[force]{test-1.tex}
\chapter{Foo Chapter}
\end{filecontents}

\documentclass{book}
\usepackage{xpatch}

\makeatletter
\newif\if@immediate@write@

\xpatchcmd\protected@write
  {\edef\reserved@a{\write#1{#3}}}
  {%
    \if@immediate@write@
      \edef\reserved@a{\immediate\write#1{#3}}
      \@immediate@write@false
    \fi
  }
  {}{\fail}

% 这里去掉 \part 的标题，只加入目录
\renewcommand\part[1]{%
  \cleardoublepage
  \@immediate@write@true
  \addcontentsline{toc}{part}{#1}%
}
\makeatother

\begin{document}

\frontmatter
\tableofcontents

\mainmatter
\part{Foo Part}
\include{test-1}

\chapter{Bar Chapter}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/88341106-8f738d00-cd6f-11ea-8d72-e8c27796acfd.png)


PS：自 latex2e 2019-10 开始，latex2e 已直接包含原 `filecontents` 宏包的功能，`filecontetns` 包标记为 obsolete。详见 [LaTeX News Issue 30](https://www.latex-project.org/news/latex2e-news/ltnews30.pdf)。

**Comment by zepinglee** [comment]
> * `\addcontentsline` 内部使用 `\protected@write`，最终使用 `\write`，也就是在下一次 `\shipout` 时 `\write` 才执行；
> * `\include` 内部使用 `\immediate\write`，立即执行。
>   这导致 `test.aux` 里 toc 条目的顺序，和正文中的不同。

@muzimuzhi 感谢指导！
