### ISSUE TITLE
\ExplSyntaxOn 后如何让 \patchcmd 准确生效？

### ISSUE THREAD

**Issue by CamuseCao** [CTeX-org/forum#141]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [x] Linux ArchLinux

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

我需要在开了 `\ExplSyntaxOn` 后让 `\patchcmd{\slideentry}{\advance\beamer@xpos by1\relax}{}{}{}
\def\beamer@subsectionentry#1#2#3#4#5{\advance\beamer@xpos by1\relax}` 奏效，但是失败了。请问如何修改，或者有别的什么方法可以达到这个目的？

## 最小工作示例（MWE）

```latex
% https://tex.stackexchange.com/questions/64333/one-navigation-bullet-per-subsection-with-subsection-false-in-custom-beamer-them

\documentclass[compress,UTF8]{ctexbeamer}
\useoutertheme[subsection=false]{miniframes}
\usepackage{etoolbox}
\ExplSyntaxOn
\makeatletter
% \patchcmd{\slideentry}{\advance\beamer@xpos~by1\relax}{}{}{}
% \def\beamer@subsectionentry#1#2#3#4#5{\advance\beamer@xpos~by1\relax}
\patchcmd{\slideentry}{\advance\beamer@xpos by1\relax}{}{}{}
\def\beamer@subsectionentry#1#2#3#4#5{\advance\beamer@xpos by1\relax}
\makeatother
\ExplSyntaxOff
\begin{document}
\section{1}
\subsection{1.1}
\begin{frame}
1
\end{frame}
\subsection{1.2}
\begin{frame}
2
\end{frame}
\begin{frame}
3
\end{frame}
\end{document}
```

（用 XeLaTeX 编译后）得到 pdf ，但是并不是预期的，没有实现一整个 `subsection` 在 `miniframe` 上面就一个圈。

## 链接

- TeX.SX: https://tex.stackexchange.com/questions/64333/one-navigation-bullet-per-subsection-with-subsection-false-in-custom-beamer-them

**Comment by muzimuzhi** [comment]
把
```tex
\patchcmd{\slideentry}{\advance\beamer@xpos by1\relax}{}{}{}
```
改成
```tex
\patchcmd{\slideentry}{\advance\beamer@xpos by1\relax}{}{}{\fail}
```
也就是在 patch 失败时，执行一个未定义的命令，可以由报错知道这里的 patch 不成功。

`\slideentry` 的定义里（见源文件 [`beamerbasenavigation.sty`](https://github.com/josephwright/beamer/blob/master/base/beamerbasenavigation.sty)），因为用到了包含空格的 beamer template 名字，所以定义/重定义 `\slideenetry` 时需要空格有正常 catcode（10，space）。`\ExplSyntaxOn` 把空格的 catcode 改成 9 ignore 了，手动改过来就好。

```tex
\documentclass[compress]{ctexbeamer}
\useoutertheme[subsection=false]{miniframes}

\ExplSyntaxOn
\makeatletter

\catcode`\ =10\relax
\patchcmd\slideentry
  {\advance\beamer@xpos by1\relax}
  {}
  {}{\fail}
\catcode`\ =9\relax

\def\beamer@subsectionentry#1#2#3#4#5{%
  \advance\beamer@xpos by1\relax}

\makeatother
\ExplSyntaxOff

\begin{document}
\section{1}
\subsection{1.1}
\begin{frame}
  1
\end{frame}

\subsection{1.2}
\begin{frame}
  2
\end{frame}
\begin{frame}
  3
\end{frame}
\end{document}
```

PS：`etoolsbox` 已经由 `beamer` 调用，不用手动加载了。

**Comment by CamuseCao** [comment]
感谢！确实是这个问题，另外 @stone-zeng 提到可以使用 
```tex
\ctex_patch_cmd:Nnn \slideentry{ 
    \advance\beamer@xpos by1\relax }{
}
```
处理。
