### ISSUE TITLE
Noto (Serif/Sans) CJK 与 Source Han (Serif/Sans) 有什么区别？一般下载 / 使用哪个？

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#142]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [x] Raspberry Pi OS

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

准备给树莓派安装字体了，之前查过一些资料，找到
> Google公司将此字体另起名为Noto Sans CJK发布，属于Noto字体家族，但字形本身（包括西文、数字）和Adobe的版本完全一样，仅是字体和字重的称呼不一样而已。

听说还和操作系统有关，不同的操作系统一般对应使用哪个呢？

## 链接

- wiki: [思源黑体](https://zh.wikipedia.org/wiki/%E6%80%9D%E6%BA%90%E9%BB%91%E9%AB%94)

**Comment by Harry-Chen** [comment]
使用上没什么区别。Debian 系的 Linux 打包了 Noto 系列字体（叫做 `fonts-noto{,-cjk,-cjk-extra}`），安装起来会简单一点。
