### ISSUE TITLE
miktex expl3 too old

### ISSUE THREAD

**Issue by zhaofeng-shu33** [CTeX-org/forum#146]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [ ] TeX Live 
  - [x] MiKTeX 4.0
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

尝试在 miktex-console 包管理器寻找 expl3 无果

## 最小工作示例（MWE）
```latex
\documentclass{ctexart}
\begin{document}
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
! Package ctex Error: Support package `expl3' too old.

For immediate help type H <return>.
 ...                                              
                                                  
l.49 ...or:nnn { ctex } { l3-too-old } { expl3 } }
                                                  
? 
```

**Comment by sikouhjw** [comment]
升级宏包啊，这么明显的报错

**Comment by stone-zeng** [comment]
升级 `l3kernel`、`l3packages`、`l3experimental`、`l3backend`。当然，直接升级所有宏包就好了。

**Comment by zhaofeng-shu33** [comment]
已解决，谢谢
