### ISSUE TITLE
XeLaTeX编译《LaTeX入门》的俄语示例，PDF文件里面却没有俄语

### ISSUE THREAD

**Issue by CyrusYip** [CTeX-org/forum#148]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [x] Linux（Kubuntu 20.04）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

### 出现的情况

我编译了《入门》2-1-1中的示例代码，但是输出的PDF文件却没有俄语。TeX live 2020是完整安装的，安装完后执行了`sudo tlmgr update --self --all`更新了宏。我还把Windows 10 2004 的所有字体复制到Ubuntu使用了。Ubuntu的语言是American English。

### 复现步骤

把下面的代码以UTF8保存到test.tex，用`xelatex test.tex`编译。PDF中没有`χαϊδεύης Крюкова`。

```latex
\documentclass{article}

\begin{document}

hicafé\quad Gödel\quad Antonín Dvořák

χαϊδεύης\qquad Крюкова

\end{document}
```

输出结果：

```latex
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-09-06>
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-xetex.def)
(./test.aux) (/usr/local/texlive/2020/texmf-dist/tex/latex/base/ts1cmr.fd)
[1] (./test.aux) )
(see the transcript file for additional information)
Output written on test.pdf (1 page).
Transcript written on test.log.
```

test.log已上传。
[test.log](https://github.com/CTeX-org/forum/files/5218199/test.log)

截图：

![result](https://user-images.githubusercontent.com/60951091/93081892-8a252580-f6c2-11ea-82c4-b6b3ef4867fa.png)

## 尝试

我是在vscode编写tex文件的，用LaTeXmk编译，不过在前面的复现例子中我用的是`xelatex test.tex`。用的是这个配置：[在 VSCode 的 LaTeXworkshop 插件中使用 LaTeXmk](https://liam.page/2020/04/24/using-LaTeXmk-with-LaTeXworkshop-with-VSCode/)

在vscode用latexmk编译了几次，LuaLaTeX 和XeLaTeX结果一样，LaTeXmk-DVIPDFMx和pdfLaTeXmk都会编译失败。upLaTeXmk-DVIPDFMx编译成功，出现了部分显示错误的俄语。

uplatex编译结果：

![uplatex](https://user-images.githubusercontent.com/60951091/93082777-1552eb00-f6c4-11ea-9b74-caea41c12607.png)

**Comment by tanukihee** [comment]
默认的 latin modern 只有 latin 部分的字母，若要使用希腊西里尔字母，请使用 cmu 系列的字体。

```LaTeX
\documentclass{article}
\usepackage{fontspec}
\setmainfont{CMU Serif}

\begin{document}

hicafé\quad Gödel\quad Antonín Dvořák

χαϊδεύης\qquad Крюкова

\end{document}
```
![image](https://user-images.githubusercontent.com/34062491/93084161-39173080-f6c6-11ea-85e1-a71808943e39.png)

**Comment by muzimuzhi** [comment]
字体缺字。log 文件里有相应信息

```
Missing character: There is no χ in font [lmroman10-regular]:mapping=tex-text;!
Missing character: There is no α in font [lmroman10-regular]:mapping=tex-text;!
Missing character: There is no ϊ in font [lmroman10-regular]:mapping=tex-text;!
```

这是 xetex 引擎产生的错误信息，它不符合编辑器通常会 parse 的 tex/latex 报错的格式，所以编辑器往往缺乏提示。

**Comment by CyrusYip** [comment]
> 默认的 latin modern 只有 latin 部分的字母，若要使用希腊西里尔字母，请使用 cmu 系列的字体。
> 
> ```
> \documentclass{article}
> \usepackage{fontspec}
> \setmainfont{CMU Serif}
> 
> \begin{document}
> 
> hicafé\quad Gödel\quad Antonín Dvořák
> 
> χαϊδεύης\qquad Крюкова
> 
> \end{document}
> ```
> 
> ![image](https://user-images.githubusercontent.com/34062491/93084161-39173080-f6c6-11ea-85e1-a71808943e39.png)

谢谢你的回复。用XeLaTeX编译了你的代码，还是不行，生成了一个Okular打不开的PDF。真的是不知所措了。

输出结果：

```latex
~/Desktop xelatex test.tex
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-09-06>
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2020/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-xetex.def))
(/usr/local/texlive/2020/texmf-dist/tex/latex/l3packages/xparse/xparse-generic.
tex)) (/usr/local/texlive/2020/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/fontenc.sty)
(/usr/local/texlive/2020/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
No file test.aux.
(/usr/local/texlive/2020/texmf-dist/tex/latex/base/ts1cmr.fd) [1] (./test.aux) 

xdvipdfmx:fatal: This font using the "seac" command for accented characters...

No output PDF file written.
)
Error 256 (driver return code) generating output;
file test.pdf may not be valid.
Transcript written on test.log.
```

log文件：
[test.log](https://github.com/CTeX-org/forum/files/5218395/test.log)

我刚刚找到了一个[解决方法](https://tex.stackexchange.com/questions/395219/error-with-cmu-serif-font)：

用下面的代码代替`\setmainfont{CMU Serif}`就能编译了。
```latex
\setmainfont{cmun}[
  Extension=.otf,
  UprightFont=*rm,
  ItalicFont=*ti,
  BoldFont=*bx,
  BoldItalicFont=*bi,
]
\setsansfont{cmun}[
  Extension=.otf,
  UprightFont=*ss,
  ItalicFont=*si,
  BoldFont=*sx,
  BoldItalicFont=*so,
]
\setmonofont{cmun}[
  Extension=.otf,
  UprightFont=*btl,% light version
  ItalicFont=*bto,%  light version
  BoldFont=*tb,
  BoldItalicFont=*tx,
]
```

可是我的系统似乎已经有CMU字体了，直接用`\setmainfont{CMU Serif}`却不行。怎么样才能直接用`\setmainfont{CMU Serif}`呢？

![DeepinScreenshot_plasmashell_20200914203443](https://user-images.githubusercontent.com/60951091/93086537-daec4c80-f6c9-11ea-9f97-bfa03fac9b7a.png)

**Comment by tanukihee** [comment]
>怎么样才能直接用 \setmainfont{CMU Serif} 呢？

除了windows已构建缓存的字体外，其他系统似乎都要使用字体名调用字体……

**Comment by CyrusYip** [comment]
> > 怎么样才能直接用 `\setmainfont{CMU Serif}` 呢？
> 
> 除了 windows 已构建缓存的字体外，其他系统似乎都要使用字体文件名调用字体……

我发现用lualatex可以编译你的代码，不需要用文件名。xelatex不行，也不知道怎么回事。

**Comment by stone-zeng** [comment]
看 <https://stone-zeng.github.io/2019-07-06-use-opentype-fonts-ii/#字体名调用-vs-文件名调用>

**Comment by CyrusYip** [comment]
[fontspec文档](http://mirrors.ctan.org/macros/latex/contrib/fontspec/fontspec.pdf) 2.2 By file name 这一部分就有提到XeTeX不能以字体名调用字体。

This technique is also necessary in XeTeX when loading
OpenType fonts that are present within your TEX distribution, such as /usr/local/texlive/
2013/texmf-dist/fonts/opentype/public. **Fonts in such locations are visible to XeTeX
but cannot be loaded by font name, only file name; LuaTEX does not have this restriction.**

**Comment by sikouhjw** [comment]
> 看 [https://stone-zeng.github.io/2019-07-06-use-opentype-fonts-ii/#字体名调用-vs-文件名调用](https://stone-zeng.github.io/2019-07-06-use-opentype-fonts-ii/#%E5%AD%97%E4%BD%93%E5%90%8D%E8%B0%83%E7%94%A8-vs-%E6%96%87%E4%BB%B6%E5%90%8D%E8%B0%83%E7%94%A8)

当时看没什么感悟（看不太懂），现在看又有了新的感悟（我好菜啊）
