### ISSUE TITLE
编译问题

### ISSUE THREAD

**Issue by DUYANG2020** [CTeX-org/forum#149]
## 检查

- [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\begin{document}
	我醉了
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
行 77: LaTeX3 Error: Mismatched LaTeX support files detected. \ExplLoaderFileDate{expl3.sty}}
行 109: Undefined control sequence. \sys_if_output_pdf:TF
行 111: LaTeX3 Error: Control sequence \ifctexpdf already defined. { \cs_new_eq:NN \ifctexpdf
: No file example-document.aux.
```

## 链接

- TeX.SX:
- GitHub:

**Comment by DUYANG2020** [comment]
![image](https://user-images.githubusercontent.com/69193660/94656446-acf64180-0332-11eb-9c31-88be37bcb72e.png)

**Comment by sikouhjw** [comment]
升级全部宏包 or https://github.com/CTeX-org/forum/issues/119

**Comment by DUYANG2020** [comment]
今天上午刚刚升级完

**Comment by DUYANG2020** [comment]
就是升级完宏包之后，导致的不可用

**Comment by DUYANG2020** [comment]
![image](https://user-images.githubusercontent.com/69193660/94657565-365a4380-0334-11eb-97cd-a9118b37f296.png)

**Comment by DUYANG2020** [comment]
![image](https://user-images.githubusercontent.com/69193660/94657646-525de500-0334-11eb-84c0-aecd74b6042e.png)

**Comment by zepinglee** [comment]
估计是某个包升级失败了；建议把 log 文件的版本信息贴一下

**Comment by DUYANG2020** [comment]
![image](https://user-images.githubusercontent.com/69193660/94658008-d617d180-0334-11eb-9984-a1c03c5927b2.png)

**Comment by DUYANG2020** [comment]
![Uploading image.png…]()

**Comment by DUYANG2020** [comment]
![image](https://user-images.githubusercontent.com/69193660/94658047-e334c080-0334-11eb-9a32-922354c757fb.png)

**Comment by DUYANG2020** [comment]
![image](https://user-images.githubusercontent.com/69193660/94658094-f34ca000-0334-11eb-94d7-043bcc06b30b.png)
这是电脑里的文档

**Comment by zepinglee** [comment]
我这里的是 `L3 programming layer <2020-09-24>`，而你的是 2020-09-06，建议换个源（比如清华的）再更新一下。

如果还不行就重装一下 latex 和 latex3。
```
tlmgr install --reinstall latex l3kernel
```

**Comment by DUYANG2020** [comment]
已解决

**Comment by muzimuzhi** [comment]
@DUYANG2020 欢迎简单说说，是怎么解决的，也许能帮到其他人。

**Comment by DUYANG2020** [comment]
管理员权限下，执行 fmtutil-sys --all 这条命令，刷新 format


Get Outlook for Android<https://aka.ms/ghei36>
________________________________
