### ISSUE TITLE
\caption* 生成了编号

### ISSUE THREAD

**Issue by muyuuuu** [CTeX-org/forum#150]
## 检查

- [x] Overleaf 中的 Texlive 2019，`xelatex` 命令编译。

## 问题描述

众所周知，不想要编号时可以 `\caption*{内容}`或者`\section*{内容}`等，可为啥我这编号还是出来了。

![image](https://user-images.githubusercontent.com/43681138/94904756-63daf480-04ce-11eb-8bd2-3bc3c685ff38.png)

## MWE

```
\documentclass[12pt]{ctexart}

\usepackage{graphicx}

\begin{document}

\begin{figure}
    \centering
    \includegraphics[scale=0.2]{1.png}
    \caption*{Caption}
    \label{fig:my_label}
\end{figure}

\end{document}
```

或者，来我分享的链接这来看看（含图片）。https://www.overleaf.com/7364981229qdmmygskjcgf

结果是这样的：

![image](https://user-images.githubusercontent.com/43681138/94904738-59b8f600-04ce-11eb-8dae-3456d54cfd32.png)

## 其他

我本地暂时没有装 `texlive`，但我感觉我代码没错，是不是 overleaf 的错？但愿我没提问错地方（

**Comment by OsbertWang** [comment]
印象中，`caption*` 想达到你的想法需要引 `caption` 包。

**Comment by mybelovedlz** [comment]
加`caption`包即可，这里lshort或许可以改一下

**Comment by OsbertWang** [comment]
印象中，`caption*` 想达到你的想法需要引 caption 包。
或者，用 `\captionsetup{labelformat=empty}` 吧。

**Comment by muyuuuu** [comment]
多谢二位。

> 这里lshort或许可以改一下

`lshort` 确实要改一下了，里面没有提到。

> 用 `\captionsetup{labelformat=empty}` 吧

新知识get。
