### ISSUE TITLE
如何在 figure 环境开始后重定义西文句号「.」

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#151]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

我在尝试将西文句号「.」定义为控制序列，然后设置在文本模式为 `。`，数学模式为 `.`，现在需要在 `figure` 环境开始后中设置为 `.`，在 `figure` 环境结束后设置为 `。`，但是没成功。

## 最小工作示例（MWE）

没报错的例子：
```latex
\documentclass{ctexart}
\begin{document}
  \def\myfullstop{.}
  \catcode`\.=13
  \def.{\ifmmode\myfullstop\else。\fi}
  \begin{figure}
    \def.{\myfullstop}
    .
  \end{figure}
\end{document}
```
报错的例子：
```latex
\documentclass{ctexart}
\makeatletter
\renewenvironment{figure}
               {\@float{figure}\def.{\myfullstop}}
               {\end@float\def.{\ifmmode\myfullstop\else。\fi}}
\makeatother
\begin{document}
  \def\myfullstop{.}
  \catcode`\.=13
  \def.{\ifmmode\myfullstop\else。\fi}
  \begin{figure}
    .
  \end{figure}
\end{document}
```
（用 XeLaTeX 编译后）输出

```latex
ABD: EverySelectfont initializing macros
! Missing control sequence inserted.
<inserted text>
                \inaccessible
l.537   \begin{figure}

?
```

**Comment by muzimuzhi** [comment]
> ```tex
> \renewenvironment{figure}
>                {\@float{figure}\def.{\myfullstop}}
>                {\end@float\def.{\ifmmode\myfullstop\else。\fi}}
> ```

几个问题

1. 在重定义时，`.` 的 catcode 就确定了，所以这里的 `\def.{...}` 是失败的
1. `\@float{figure}` 会吸收一个可选参数，对应 `\begin{figure}[htp]` 里的 `[htp]`，所以不应在它后面加代码
1. 环境自带分组，只需要在环境头改一次

以下几种写法均生效
1. 从需求描述，猜测直接在 `figure` 内部恢复 `.` 的 catcode 就可以，这里用了 latex Oct 2020 加入的 hook 系统：
    ```tex
    \AddToHook{env/figure/begin}{\catcode`\.=12}
    ```
1. 先改 catcode 再 patch
    ```tex
    \begingroup
    \catcode`\.=13
    \def\temp{\endgroup\AddToHook{env/figure/begin}{\def.{\myfullstop}}}
    \temp
    ```
1. 用 eTeX primitive `\scantokens` 重新 tokenize，譬如用 `\renewenvironment`
    ```tex
    \renewenvironment{figure}
       {\scantokens{\def.{\myfullstop}\ignorespaces}\@float{figure}}
       {\end@float}
    ```

**Comment by sikouhjw** [comment]
> 
> 
> > ```
> > \renewenvironment{figure}
> >                {\@float{figure}\def.{\myfullstop}}
> >                {\end@float\def.{\ifmmode\myfullstop\else。\fi}}
> > ```
> 
> 几个问题
> 
>     1. 在重定义时，`.` 的 catcode 就确定了，所以这里的 `\def.{...}` 是失败的
> 
>     2. `\@float{figure}` 会吸收一个可选参数，对应 `\begin{figure}[htp]` 里的 `[htp]`，所以不应在它后面加代码
> 
>     3. 环境自带分组，只需要在环境头改一次
> 
> 
> 以下几种写法均生效
> 
>     1. 从需求描述，猜测直接在 `figure` 内部恢复 `.` 的 catcode 就可以，这里用了 latex Oct 2020 加入的 hook 系统：
>        ```
>        \AddToHook{env/figure/begin}{\catcode`\.=12}
>        ```
> 
>     2. 先改 catcode 再 patch
>        ```
>        \begingroup
>        \catcode`\.=13
>        \def\temp{\endgroup\AddToHook{env/figure/begin}{\def.{\myfullstop}}}
>        \temp
>        ```
> 
>     3. 用 eTeX primitive `\scantokens` 重新 tokenize，譬如用 `\renewenvironment`
>        ```
>        \renewenvironment{figure}
>           {\scantokens{\def.{\myfullstop}\ignorespaces}\@float{figure}}
>           {\end@float}
>        ```

感谢！
