### ISSUE TITLE
GPL Ghostscript 9.53.2: Unrecoverable error, exit code 1

### ISSUE THREAD

**Issue by DUYANG2020** [CTeX-org/forum#152]
## 检查

- [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 最小工作示例（MWE）

（用 XeLaTeX 编译后）输出

```latex
GPL Ghostscript 9.53.2: Unrecoverable error, exit code 1

```

## 链接

- TeX.SX:
- GitHub:

**Comment by sikouhjw** [comment]
更多的信息在[这里](https://wenda.latexstudio.net/q-2601.html)，提问的时候请给更多的信息而不是一句报错。

**Comment by DUYANG2020** [comment]
把我发的两个帖子就这一链接，好吧......

**Comment by muzimuzhi** [comment]
请提供足够的信息，以让他人能复现问题。可能需要一个完整的 latex 例子、一个图片、编译使用的命令、相关程序的版本信息。

**Comment by DUYANG2020** [comment]
\documentclass[UTF8]{ctexart}

\usepackage{pstricks-add}

\begin{document}
	\begin{psmatrix}[rowsep=0.7,colsep=0.7]
		
		&\psovalbox[fillstyle=solid, fillcolor=yellow!30,shadow=true]{准备写论文} \\
		
		&\psframebox[shadow=true]{\shortstack{找资料找资料找资料找资料找资料}} \\
		
		&\psparallelogrambox[fillstyle=solid,fillcolor=blue!20,shadow]{\shortstack{找资料找资料找资料找资料}} \\
		
		&\psdiabox[fillstyle=solid, fillcolor=magenta!20,shadow=true]{\shortstack{找资料找资料找资料\\找资料找资料找资料}} &
		
		\psparallelogrambox[fillstyle=solid,fillcolor=blue!20,shadow=true]{找资料} \\
		
		&\psframebox[shadow=true]{找资料找资料找资料}  & 
		
		\psovalbox[fillstyle=solid, fillcolor=yellow!30,shadow=true]{找资料找资料}\\
		
		&\psdiabox[fillstyle=solid, fillcolor=magenta!20,shadow=true]{找资料找资料找资料}  \\
		
		&\psframebox[shadow=true]{找资料找资料找资料} \\
		
		&\psparallelogrambox[fillstyle=solid,fillcolor=blue!20,shadow=true]{\shortstack{找资料找资料找资料找资料、找资料找资料找资料}} \\
		
		&\psframebox[shadow=true]{找资料、找资料找资料找资料}  \\
		
		\psparallelogrambox[fillstyle=solid,fillcolor=blue!20, shadow=true]{\shortstack{找资料找资料\\找资料找资料找资料、找资料}} &
		
		\psdiabox[fillstyle=solid, fillcolor=magenta!20,shadow=true]{\shortstack{找资料找资料、\\找资料找资料找资料}} \\
		
		&\psframebox[shadow=true]{\shortstack{找资料找资料\\（找资料找资料）}} \\
		
		&\psframebox[shadow=true]{找资料找资料} \\
		
		&\psovalbox[fillstyle=solid, fillcolor=yellow!30,shadow=true]{\shortstack{找资料找资料找资料} }
		
		\ncline{->}{1,2}{2,2}\ncline{->}{2,2}{3,2}
		
		\ncline{->}{3,2}{4,2}
		
		\ncline{->}{4,2}{5,2}
		\uput[-90](-3.5,14.3){\textcolor{red}{Yes}}
		\uput[-90](0.3,12.6){\textcolor{red}{找资料}}
		\uput[-90](-4,11){\textcolor{red}{找资料}}
		\uput[-90](-7.5,6){\textcolor{red}{找资料}}
		\uput[-90](-3.5,4.3){\textcolor{red}{找资料}}
		\uput[-90](-8,14){\textcolor{red}{找资料找资料}}
		\uput[-90](1.5,15.6){\textcolor{red}{No}}
		\ncline{->}{5,2}{6,2}
		
		\ncline{->}{5,3}{6,3}
		
		\ncline{->}{6,3}{7,3}
		
		\ncline{->}{6,2}{7,2}
		
		\ncline{->}{7,2}{8,2}\ncline{->}{8,2}{9,2}
		
		\ncline{->}{9,2}{10,2}\ncline{->}{10,2}{11,2}
		
		\ncangles[angleA=-180,angleB=0,armA=0cm,armB=0cm]{->}{10,2}{10,1}
		
		\ncangles[angleA=90,angleB=180,armA=2cm,armB=4.65cm]{->}{10,1}{5,2}
		
		\ncline{->}{11,2}{12,2}\ncline{->}{12,2}{13,2}
		
		\ncline{->}{13,2}{14,2}
		
		\ncline{->}{10,2}{10,0}
		
		\ncline{->}{4,2}{4,3}
		
		\ncline{->}{4,3}{5,3}
		
		\ncangles[angleA=0,angleB=0,armA=0.5cm,armB=0.5cm]{->}{6,2}{5,2}
		
		
	\end{psmatrix}
\end{document}

**Comment by DUYANG2020** [comment]
![image](https://user-images.githubusercontent.com/69193660/95641768-c3d92880-0ad6-11eb-9136-e6f5ac1803ad.png)
![image](https://user-images.githubusercontent.com/69193660/95641780-d6ebf880-0ad6-11eb-9d3a-25b67cf5b428.png)
![image](https://user-images.githubusercontent.com/69193660/95641787-e53a1480-0ad6-11eb-95a3-7ed4760e8f74.png)
所有宏包均已更新

**Comment by muzimuzhi** [comment]
* 只要有可能复制粘接纯文本，就请避免发截图。例如 texstudio 摘取的报错信息、ghostscript 的版本信息
* 只要有可能让例子更短，就请适当精简。例如 `psmatrix` 环境内容

在 macOS 10.15.7 + mactex 2020 + ghostscript 9.53.3 (执行 `rungs --version`)，我编译你的例子不报错，无法复现问题。我本地的版本信息
```
*File List*
 ctexart.cls    2020/08/23 v2.5.4 Chinese adapter for class article (CTEX)
ctexbackend.cfg    2020/08/23 v2.5.4 Backend configuration file (CTEX)
   expl3.sty    2020-10-05 L3 programming layer (loader) 
l3backend-xetex.def    2020/08/23 v2.5.4 Chinese adapter for class article (CTEX)
  xparse.sty    2020-10-05 L3 Experimental document command parser
xparse-generic.tex
l3keys2e.sty    2020-10-05 LaTeX2e option processing using LaTeX3 keys
ctexhook.sty    2020/08/23 v2.5.4 Document and package hooks (CTEX)
ctexpatch.sty    2020/08/23 v2.5.4 Patching commands (CTEX)
  fix-cm.sty    2015/01/14 v1.1t fixes to LaTeX
  ts1enc.def    2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
everysel.sty    2011/10/28 v1.2 EverySelectfont Package (MS)
ctexopts.cfg    2020/08/23 v2.5.4 Option configuration file (CTEX)
 article.cls    2020/04/10 v1.4m Standard LaTeX document class
  size10.clo    2020/04/10 v1.4m Standard LaTeX file (size option)
ctex-engine-xetex.def    2020/08/23 v2.5.4 XeLaTeX adapter (CTEX)
   xeCJK.sty    2020/08/23 v3.8.5 Typesetting CJK scripts with XeLaTeX
xtemplate.sty    2020-10-05 L3 Experimental prototype document functions
fontspec.sty    2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX
fontspec-xetex.sty    2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX
 fontenc.sty
fontspec.cfg
   xeCJK.cfg    2020/08/23 v3.8.5 Configuration file for xeCJK package
zhnumber.sty    2020/05/01 v2.8 Typesetting numbers with Chinese glyphs
zhnumber-utf8.cfg    2020/05/01 v2.8 Chinese numerals with UTF8 encoding
ctex-scheme-chinese-article.def    2020/08/23 v2.5.4 Chinese scheme for article (CTEX)
ctex-name-utf8.cfg    2020/08/23 v2.5.4 Caption with encoding UTF-8 (CTEX)
ctex-c5size.clo    2020/08/23 v2.5.4 c5size option (CTEX)
ctex-fontset-mac.def    2020/08/23 v2.5.4 macOS fonts definition (CTEX)
ctex-fontset-macnew.def    2020/08/23 v2.5.4 macOS fonts definition for El Capitan or later version (CTEX)
    ctex.cfg    2020/08/23 v2.5.4 Configuration file (CTEX)
pstricks-add.sty    2018/02/04 v. 0.16 package wrapper for pstricks-add.tex (hv)
pstricks.sty    2020/06/11 v0.70 LaTeX wrapper for `PSTricks' (RN,HV)
   iftex.sty    2020/03/06 v1.0d TeX engine tests
  xcolor.sty    2016/05/11 v2.12 LaTeX color extensions (UK)
   color.cfg    2016/01/02 v1.6 sample color configuration
   xetex.def    2020/08/26 v5.0i Graphics/color driver for xetex
pst-xkey.tex    2005/11/25 v1.6 PSTricks specialization of xkeyval (HA)
pst-xkey.tex    2005/11/25 v1.6 PSTricks specialization of xkeyval (HA)
 xkeyval.sty    2014/12/03 v2.7a package option processing (HA)
 xkeyval.tex    2014/12/03 v2.7a key=value parser (HA)
pstricks.tex    2020/09/18 v3.01 `PSTricks' (tvz,hv)
  pst-fp.tex    2020/09/18 v3.01 `PST-fp' (hv)
pstricks-xetex.def
pst-plot.sty    2011/04/13 package wrapper for pst-plot.tex (hv)
pst-xkey.sty    2005/11/25 v1.6 package wrapper for pst-xkey.tex (HA)
 multido.sty    2011/04/13 package wrapper for pst-plot.tex (hv)
 multido.tex    2010/05/14 v1.42 `multido' (tvz,hv)
pst-plot.tex    2019/05/16 1.92 `pst-plot' (tvz,hv)
pst-node.sty    2010/04/22 package wrapper for pst-node.tex
pst-node.tex    2019/05/16 1.92 `pst-node' (tvz,hv)
  pst-3d.sty    2009/07/28 package wrapper for pst-3d.tex (hv)
  pst-3d.tex    2019/05/16 v1.92 `PST-3d' (hv)
pst-math.sty    2018/12/16 v 0.65 package wrapper for PSTricks pst-math.tex
pst-calculate.sty    2019/01/24 v. 0.02(Herbert Voss) Support for caculations with floating point numbers.
 siunitx.sty    2020/02/25 v2.8b A comprehensive (SI) units package
 amstext.sty    2000/06/29 v2.01 AMS text
  amsgen.sty    1999/11/30 v2.0 generic functions
   array.sty    2020/10/01 v2.5c Tabular extension package (FMi)
translator.sty    2020-08-03 v1.12c Easy translation of strings in LaTeX
ifluatex.sty    2019/10/25 v1.5 ifluatex legacy package. Use iftex instead.
 xstring.sty    2018/02/04 v. 0.16 package wrapper for pstricks-add.tex (hv)
pstricks-add.tex    2019/05/16 v1.92 `PSTricks-add' (hv)
siunitx-abbreviations.cfg    2017/11/26 v2.7k siunitx: Abbreviated units
translator-basic-dictionary-English.dict    
```

**Comment by DUYANG2020** [comment]
已经意识到问题的所在，感谢！

**Comment by sikouhjw** [comment]
> 已经意识到问题的所在，感谢！

问题在哪？不妨简单说说

**Comment by DUYANG2020** [comment]
我把 ghostscript 9.53.1 更新为 ghostscript 9.53.3 就可以使用了
