### ISSUE TITLE
以下代码里的 red 为什么没有显示？

### ISSUE THREAD

**Issue by DUYANG2020** [CTeX-org/forum#153]
## 检查

- [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020 
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题
这个代码里的 red 没有显示

## 最小工作示例（MWE）

```latex
\documentclass[10pt,a4paper]{article}
\usepackage{xcolor}
\usepackage{tikz}
\begin{document}
	\begin{tikzpicture}
	\shadedraw [ball color=red] (13,-5) circle (1cm);
	\end{tikzpicture}
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
正常显示圆，但是 red 的阴影没有显示
```

## 链接

- TeX.SX:
- GitHub:

**Comment by DUYANG2020** [comment]
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020/W32TeX) (preloaded format=xelatex 2020.10.11)  12 OCT 2020 12:21
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**example-red.tex
(./example-red.tex
LaTeX2e <2020-10-01> patch level 1
L3 programming layer <2020-10-05> xparse <2020-03-03>
(d:/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(d:/texlive/2020/texmf-dist/tex/latex/base/size10.clo
File: size10.clo 2020/04/10 v1.4m Standard LaTeX file (size option)
)
\c@part=\count171
\c@section=\count172
\c@subsection=\count173
\c@subsubsection=\count174
\c@paragraph=\count175
\c@subparagraph=\count176
\c@figure=\count177
\c@table=\count178
\abovecaptionskip=\skip47
\belowcaptionskip=\skip48
\bibindent=\dimen138
)
(d:/texlive/2020/texmf-dist/tex/latex/xcolor/xcolor.sty
Package: xcolor 2016/05/11 v2.12 LaTeX color extensions (UK)

(d:/texlive/2020/texmf-dist/tex/latex/graphics-cfg/color.cfg
File: color.cfg 2016/01/02 v1.6 sample color configuration
)
Package xcolor Info: Driver file: xetex.def on input line 225.

(d:/texlive/2020/texmf-dist/tex/latex/graphics-def/xetex.def
File: xetex.def 2020/08/26 v5.0i Graphics/color driver for xetex
)
Package xcolor Info: Model `cmy' substituted by `cmy0' on input line 1348.
Package xcolor Info: Model `RGB' extended on input line 1364.
Package xcolor Info: Model `HTML' substituted by `rgb' on input line 1366.
Package xcolor Info: Model `Hsb' substituted by `hsb' on input line 1367.
Package xcolor Info: Model `tHsb' substituted by `hsb' on input line 1368.
Package xcolor Info: Model `HSB' substituted by `hsb' on input line 1369.
Package xcolor Info: Model `Gray' substituted by `gray' on input line 1370.
Package xcolor Info: Model `wave' substituted by `hsb' on input line 1371.
)
(d:/texlive/2020/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty
(d:/texlive/2020/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty
(d:/texlive/2020/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty
(d:/texlive/2020/texmf-dist/tex/generic/pgf/utilities/pgfutil-common.tex
\pgfutil@everybye=\toks15
\pgfutil@tempdima=\dimen139
\pgfutil@tempdimb=\dimen140

(d:/texlive/2020/texmf-dist/tex/generic/pgf/utilities/pgfutil-common-lists.tex)
) (d:/texlive/2020/texmf-dist/tex/generic/pgf/utilities/pgfutil-latex.def
\pgfutil@abb=\box47
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/utilities/pgfrcs.code.tex
(d:/texlive/2020/texmf-dist/tex/generic/pgf/pgf.revision.tex)
Package: pgfrcs 2020/10/01 v3.1.6a (3.1.6a)
))
Package: pgf 2020/10/01 v3.1.6a (3.1.6a)

(d:/texlive/2020/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty
(d:/texlive/2020/texmf-dist/tex/latex/graphics/graphicx.sty
Package: graphicx 2020/09/09 v1.2b Enhanced LaTeX Graphics (DPC,SPQR)

(d:/texlive/2020/texmf-dist/tex/latex/graphics/keyval.sty
Package: keyval 2014/10/28 v1.15 key=value parser (DPC)
\KV@toks@=\toks16
)
(d:/texlive/2020/texmf-dist/tex/latex/graphics/graphics.sty
Package: graphics 2020/08/30 v1.4c Standard LaTeX Graphics (DPC,SPQR)

(d:/texlive/2020/texmf-dist/tex/latex/graphics/trig.sty
Package: trig 2016/01/03 v1.10 sin cos tan (DPC)
)
(d:/texlive/2020/texmf-dist/tex/latex/graphics-cfg/graphics.cfg
File: graphics.cfg 2016/06/04 v1.11 sample graphics configuration
)
Package graphics Info: Driver file: xetex.def on input line 105.
)
\Gin@req@height=\dimen141
\Gin@req@width=\dimen142
)
(d:/texlive/2020/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty
(d:/texlive/2020/texmf-dist/tex/generic/pgf/systemlayer/pgfsys.code.tex
Package: pgfsys 2020/10/01 v3.1.6a (3.1.6a)

(d:/texlive/2020/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex
\pgfkeys@pathtoks=\toks17
\pgfkeys@temptoks=\toks18

(d:/texlive/2020/texmf-dist/tex/generic/pgf/utilities/pgfkeysfiltered.code.tex
\pgfkeys@tmptoks=\toks19
))
\pgf@x=\dimen143
\pgf@y=\dimen144
\pgf@xa=\dimen145
\pgf@ya=\dimen146
\pgf@xb=\dimen147
\pgf@yb=\dimen148
\pgf@xc=\dimen149
\pgf@yc=\dimen150
\pgf@xd=\dimen151
\pgf@yd=\dimen152
\w@pgf@writea=\write3
\r@pgf@reada=\read2
\c@pgf@counta=\count179
\c@pgf@countb=\count180
\c@pgf@countc=\count181
\c@pgf@countd=\count182
\t@pgf@toka=\toks20
\t@pgf@tokb=\toks21
\t@pgf@tokc=\toks22
\pgf@sys@id@count=\count183
 (d:/texlive/2020/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg
File: pgf.cfg 2020/10/01 v3.1.6a (3.1.6a)
)
Driver file for pgf: pgfsys-xetex.def

(d:/texlive/2020/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-xetex.def
File: pgfsys-xetex.def 2020/10/01 v3.1.6a (3.1.6a)

(d:/texlive/2020/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-dvipdfmx.def
File: pgfsys-dvipdfmx.def 2020/10/01 v3.1.6a (3.1.6a)

(d:/texlive/2020/texmf-dist/tex/generic/pgf/systemlayer/pgfsys-common-pdf.def
File: pgfsys-common-pdf.def 2020/10/01 v3.1.6a (3.1.6a)
)
\pgfsys@objnum=\count184
)))
(d:/texlive/2020/texmf-dist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.tex
File: pgfsyssoftpath.code.tex 2020/10/01 v3.1.6a (3.1.6a)
\pgfsyssoftpath@smallbuffer@items=\count185
\pgfsyssoftpath@bigbuffer@items=\count186
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.tex
File: pgfsysprotocol.code.tex 2020/10/01 v3.1.6a (3.1.6a)
)) (d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcore.code.tex
Package: pgfcore 2020/10/01 v3.1.6a (3.1.6a)

(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmathcalc.code.tex
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmathutil.code.tex)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmathparser.code.tex
\pgfmath@dimen=\dimen153
\pgfmath@count=\count187
\pgfmath@box=\box48
\pgfmath@toks=\toks23
\pgfmath@stack@operand=\toks24
\pgfmath@stack@operation=\toks25
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.code.tex
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.basic.code.te
x)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.trigonometric
.code.tex)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.random.code.t
ex)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.comparison.co
de.tex)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.base.code.tex
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.round.code.te
x)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.misc.code.tex
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmathfunctions.integerarithm
etics.code.tex)))
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmathfloat.code.tex
\c@pgfmathroundto@lastzeros=\count188
))
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfint.code.tex)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepoints.code.tex
File: pgfcorepoints.code.tex 2020/10/01 v3.1.6a (3.1.6a)
\pgf@picminx=\dimen154
\pgf@picmaxx=\dimen155
\pgf@picminy=\dimen156
\pgf@picmaxy=\dimen157
\pgf@pathminx=\dimen158
\pgf@pathmaxx=\dimen159
\pgf@pathminy=\dimen160
\pgf@pathmaxy=\dimen161
\pgf@xx=\dimen162
\pgf@xy=\dimen163
\pgf@yx=\dimen164
\pgf@yy=\dimen165
\pgf@zx=\dimen166
\pgf@zy=\dimen167
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.cod
e.tex
File: pgfcorepathconstruct.code.tex 2020/10/01 v3.1.6a (3.1.6a)
\pgf@path@lastx=\dimen168
\pgf@path@lasty=\dimen169
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathusage.code.te
x
File: pgfcorepathusage.code.tex 2020/10/01 v3.1.6a (3.1.6a)
\pgf@shorten@end@additional=\dimen170
\pgf@shorten@start@additional=\dimen171
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcorescopes.code.tex
File: pgfcorescopes.code.tex 2020/10/01 v3.1.6a (3.1.6a)
\pgfpic=\box49
\pgf@hbox=\box50
\pgf@layerbox@main=\box51
\pgf@picture@serial@count=\count189
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.code
.tex
File: pgfcoregraphicstate.code.tex 2020/10/01 v3.1.6a (3.1.6a)
\pgflinewidth=\dimen172
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransformations.c
ode.tex
File: pgfcoretransformations.code.tex 2020/10/01 v3.1.6a (3.1.6a)
\pgf@pt@x=\dimen173
\pgf@pt@y=\dimen174
\pgf@pt@temp=\dimen175
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex
File: pgfcorequick.code.tex 2020/10/01 v3.1.6a (3.1.6a)
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.tex
File: pgfcoreobjects.code.tex 2020/10/01 v3.1.6a (3.1.6a)
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepathprocessing.co
de.tex
File: pgfcorepathprocessing.code.tex 2020/10/01 v3.1.6a (3.1.6a)
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcorearrows.code.tex
File: pgfcorearrows.code.tex 2020/10/01 v3.1.6a (3.1.6a)
\pgfarrowsep=\dimen176
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex
File: pgfcoreshade.code.tex 2020/10/01 v3.1.6a (3.1.6a)
\pgf@max=\dimen177
\pgf@sys@shading@range@num=\count190
\pgf@shadingcount=\count191
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex
File: pgfcoreimage.code.tex 2020/10/01 v3.1.6a (3.1.6a)

(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.tex
File: pgfcoreexternal.code.tex 2020/10/01 v3.1.6a (3.1.6a)
\pgfexternal@startupbox=\box52
))
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcorelayers.code.tex
File: pgfcorelayers.code.tex 2020/10/01 v3.1.6a (3.1.6a)
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcoretransparency.code
.tex
File: pgfcoretransparency.code.tex 2020/10/01 v3.1.6a (3.1.6a)
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.tex
File: pgfcorepatterns.code.tex 2020/10/01 v3.1.6a (3.1.6a)
) (d:/texlive/2020/texmf-dist/tex/generic/pgf/basiclayer/pgfcorerdf.code.tex
File: pgfcorerdf.code.tex 2020/10/01 v3.1.6a (3.1.6a)
))) (d:/texlive/2020/texmf-dist/tex/generic/pgf/modules/pgfmoduleshapes.code.te
x
File: pgfmoduleshapes.code.tex 2020/10/01 v3.1.6a (3.1.6a)
\pgfnodeparttextbox=\box53
)
(d:/texlive/2020/texmf-dist/tex/generic/pgf/modules/pgfmoduleplot.code.tex
File: pgfmoduleplot.code.tex 2020/10/01 v3.1.6a (3.1.6a)
)
(d:/texlive/2020/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-0-65.st
y
Package: pgfcomp-version-0-65 2020/10/01 v3.1.6a (3.1.6a)
\pgf@nodesepstart=\dimen178
\pgf@nodesepend=\dimen179
)
(d:/texlive/2020/texmf-dist/tex/latex/pgf/compatibility/pgfcomp-version-1-18.st
y
Package: pgfcomp-version-1-18 2020/10/01 v3.1.6a (3.1.6a)
)) (d:/texlive/2020/texmf-dist/tex/latex/pgf/utilities/pgffor.sty
(d:/texlive/2020/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty
(d:/texlive/2020/texmf-dist/tex/generic/pgf/utilities/pgfkeys.code.tex))
(d:/texlive/2020/texmf-dist/tex/latex/pgf/math/pgfmath.sty
(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex))
(d:/texlive/2020/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex
Package: pgffor 2020/10/01 v3.1.6a (3.1.6a)

(d:/texlive/2020/texmf-dist/tex/generic/pgf/math/pgfmath.code.tex)
\pgffor@iter=\dimen180
\pgffor@skip=\dimen181
\pgffor@stack=\toks26
\pgffor@toks=\toks27
))
(d:/texlive/2020/texmf-dist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex
Package: tikz 2020/10/01 v3.1.6a (3.1.6a)

(d:/texlive/2020/texmf-dist/tex/generic/pgf/libraries/pgflibraryplothandlers.co
de.tex
File: pgflibraryplothandlers.code.tex 2020/10/01 v3.1.6a (3.1.6a)
\pgf@plot@mark@count=\count192
\pgfplotmarksize=\dimen182
)
\tikz@lastx=\dimen183
\tikz@lasty=\dimen184
\tikz@lastxsaved=\dimen185
\tikz@lastysaved=\dimen186
\tikz@lastmovetox=\dimen187
\tikz@lastmovetoy=\dimen188
\tikzleveldistance=\dimen189
\tikzsiblingdistance=\dimen190
\tikz@figbox=\box54
\tikz@figbox@bg=\box55
\tikz@tempbox=\box56
\tikz@tempbox@bg=\box57
\tikztreelevel=\count193
\tikznumberofchildren=\count194
\tikznumberofcurrentchild=\count195
\tikz@fig@count=\count196

(d:/texlive/2020/texmf-dist/tex/generic/pgf/modules/pgfmodulematrix.code.tex
File: pgfmodulematrix.code.tex 2020/10/01 v3.1.6a (3.1.6a)
\pgfmatrixcurrentrow=\count197
\pgfmatrixcurrentcolumn=\count198
\pgf@matrix@numberofcolumns=\count199
)
\tikz@expandcount=\count266

(d:/texlive/2020/texmf-dist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzli
brarytopaths.code.tex
File: tikzlibrarytopaths.code.tex 2020/10/01 v3.1.6a (3.1.6a)
)))
(d:/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-xetex.def
File: l3backend-xetex.def 2020-09-24 L3 backend support: XeTeX
\g__graphics_track_int=\count267
\l__pdf_internal_box=\box58
\g__pdf_backend_object_int=\count268
\g__pdf_backend_annotation_int=\count269
)
(./example-red.aux)
\openout1 = `example-red.aux'.

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 4.
LaTeX Font Info:    Trying to load font information for TS1+cmr on input line 4
.
 (d:/texlive/2020/texmf-dist/tex/latex/base/ts1cmr.fd
File: ts1cmr.fd 2019/12/16 v2.5j Standard LaTeX font definitions
)
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for TU/lmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 4.
LaTeX Font Info:    ... okay on input line 4.

[1

] (./example-red.aux) ) 
Here is how much of TeX's memory you used:
 11263 strings out of 477474
 237977 string characters out of 5841243
 483425 words of memory out of 5000000
 30562 multiletter control sequences out of 15000+600000
 535096 words of font info for 30 fonts, out of 8000000 for 9000
 1348 hyphenation exceptions out of 8191
 96i,5n,99p,417b,508s stack positions out of 5000i,500n,10000p,200000b,80000s

Output written on example-red.pdf (1 page).

**Comment by stone-zeng** [comment]
见 <https://github.com/pgf-tikz/pgf/issues/928>。

在导言区添加：

```tex
\makeatletter
\def\pgfutil@insertatbegincurrentpagefrombox#1{%
  \edef\pgf@temp{\the\wd\pgfutil@abb}%
  \global\setbox\pgfutil@abb\hbox{%
    \unhbox\pgfutil@abb%
    \hskip\dimexpr2in-2\hoffset-\pgf@temp\relax% changed
    #1%
    \hskip\dimexpr-2in-2\hoffset\relax% new
  }%
}
\makeatother
```

**Comment by DUYANG2020** [comment]
不行

**Comment by DUYANG2020** [comment]
![image](https://user-images.githubusercontent.com/69193660/95715229-13b51c80-0c9c-11eb-9e37-60caf603a6c8.png)

**Comment by stone-zeng** [comment]
放在 `\usepackage` 后面

**Comment by DUYANG2020** [comment]
太牛了，感谢！

**Comment by zoushucai** [comment]
```
\documentclass{article}
\usepackage{xcolor}
\usepackage{ctex}
\def\pgfsysdriver{pgfsys-dvipdfm.def}
\usepackage{tikz}

\begin{document}
\begin{tikzpicture}
\shadedraw [ball color=red] (0,0) circle (2); 
\end{tikzpicture}
你好啊！
\end{document}
```
这样就可以啦，设置驱动
![](https://wenda.latexstudio.net/data/attach/201014/bazfSk9K.png)
