### ISSUE TITLE
更新到 latex 2020-10-01 后文档 install-latex-guide-zh-cn 编译出错

### ISSUE THREAD

**Issue by OsbertWang** [CTeX-org/forum#154]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

10月12日更新 TeX Live 后，编译我的手册 [install-latex-guide-zh-cn](https://github.com/OsbertWang/install-latex-guide-zh-cn) 会提示出现了错误 `! Extra \endgroup.`，具体的报错见附件的 log 文件.
从 log 文件里我觉得它应该是和 `pgf` 有关，但是我不清楚这样的错误如何解决。

## 附件
[install-latex-guide-zh-cn.log](https://github.com/CTeX-org/forum/files/5369318/install-latex-guide-zh-cn.log)

**Comment by zepinglee** [comment]
`menukeys` 的锅，MWE：
```latex
\documentclass{article}
\usepackage{menukeys}
\begin{document}
Foo
\end{document}
```
```
./install-latex-guide-zh-cn.tex:3: Extra \endgroup.
\document ->\endgroup 
                      \let \BeforeStartOfDocument \@firstofone \cpt@beforest...
l.3 \begin{document}
                    
No pages of output.
```

**Comment by muzimuzhi** [comment]
是 `menukeys` 依赖的 `catoptions` 和 latex 2020 fall 不兼容，可以用 `\RequirePackage[2020-02-02]{latexrelease}` 回滚 latex 版本。完整例子

```tex
\RequirePackage[2020-02-02]{latexrelease}
\documentclass{article}
\usepackage{menukeys}

\begin{document}

\section{Menukeys test}
\menu{File>New File}

\end{document}
```

参考：https://tex.stackexchange.com/a/565938

**Comment by muzimuzhi** [comment]
`menukeys` 发布了 2020/10/31 v1.6，去掉了对 `catoptions` 的依赖，问题已解决。具体修改见 [texlive/r56822](http://www.tug.org/svn/texlive?view=revision&revision=56822) 。
