### ISSUE TITLE
autorightleftharpoons 效果不符合预期

### ISSUE THREAD

**Issue by DUYANG2020** [CTeX-org/forum#155]
## 检查

- [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 最小工作示例（MWE）

```latex
\documentclass[fontset=fandol]{ctexart}
\usepackage{amsmath,chemarrow}
\begin{document}
	\[(a+b)(a-b)\autorightleftharpoons{\text{多项式乘法}}{\text{因式分解}}a^2-b^2\]
\end{document}
```

（用 XeLaTeX 编译后）输出

![image](https://user-images.githubusercontent.com/69193660/96242371-fbb00680-0fd5-11eb-941c-53acb1037b2b.png)

## 链接

- TeX.SX:
- GitHub:

## 附件
[example-f.log](https://github.com/CTeX-org/forum/files/5390603/example-f.log)

**Comment by DUYANG2020** [comment]
![image](https://user-images.githubusercontent.com/69193660/96243107-de2f6c80-0fd6-11eb-9bc7-278ed00a6f8b.png)

**Comment by OsbertWang** [comment]
这是什么提问……

**Comment by Liam0205** [comment]
macOS, macTeX with latest packages, upLaTeX/XeLaTeX 均为能复现:

```tex
\documentclass{ctexart}
\usepackage{amsmath,chemarrow}
\begin{document}
  \[(a+b)(a-b)\autorightleftharpoons{\text{多项式乘法}}{\text{因式分解}}a^2-b^2\]
\end{document}
```

![image](https://user-images.githubusercontent.com/3348485/96247685-0a4dec00-0fdd-11eb-9021-a28ee2bf617c.png)

**Comment by sikouhjw** [comment]
Overleaf(TeXLive 2020) 的 XeLaTeX 和 LuaLaTeX 均未复现

**Comment by muzimuzhi** [comment]
@DUYANG2020 建议再确认一次，问题确实存在。另外，不使用 `ctexart`，只用 `\text{abcdefg}`，问题复现吗？

**Comment by OsbertWang** [comment]
在 Windows 和 WSL 上试过了同样的代码：
```LaTeX
\documentclass[fontset=none]{ctexart}
\ctexset{fontset=fandol}
\usepackage{amsmath,chemarrow}
\begin{document}
\[
(a+b)(a-b)\autorightleftharpoons{\text{多项式乘法}}{\text{因式分解}}a^2-b^2
\]
\end{document}
```
在 Windows 上会复现问题但 WSL 上不会。

**Comment by sikouhjw** [comment]
win 10 下 TeXLive  2020（未更新）复现不了

**Comment by OsbertWang** [comment]
再次实验。
在 Windows 和 WSL 上运行以下代码：
```
\documentclass{article}
\usepackage{amsmath,chemarrow}
\begin{document}
  \[
  (a+b)(a-b)\autorightleftharpoons{\text{Polynomial multiplication}}{\text{Factorization}}a^2-b^2
  \]
\end{document}
```
结果如下：
- Windwos：`pdflatex` 无法复现问题，而 `xelatex` 可以复现问题
- WSL：`pdflatex` 和 `xelatex` 无法复现问题

**Comment by DUYANG2020** [comment]
> article

![image](https://user-images.githubusercontent.com/69193660/96328825-80079580-1079-11eb-81d3-6e8959ab5380.png)

**Comment by Liam0205** [comment]
看起来是 Win 上 XeTeX 的问题？

**Comment by DUYANG2020** [comment]
这个怎么检测？

**Comment by Liam0205** [comment]
目前看就是这样了。

不论是 `ctexart` 还是 `article`，都只在 Win + XeTeX 的情况下会出问题。只能 dive into codes，细查原因了。

**Comment by DUYANG2020** [comment]
我是小白，具体如何操作？还请大神指点

**Comment by Liam0205** [comment]
@DUYANG2020 等一等就好……

**Comment by Liam0205** [comment]
托 Clerk 查了一下，应该是 Windows 版本中 DVIPDFMx 的问题。Windows 版本的 DVIPDFMx 追开发版本追得比较紧，引入了新版本带来的问题导致的。所以在 Linux 和 macOS 上都没法复现。

因为共用 DVIPDFMx 的代码，所以 Windows 版本的 LaTeX + DVIPDFMx 链路应该也能复现。有兴趣的可以试一下。

这个问题 Clerk 会修复，过段时间再更新，应该就可以了。短时间内应该没啥好办法，只能换 pdfLaTeX 或者 LuaLaTeX 暂时绕过这个问题。

**Comment by OsbertWang** [comment]
> 托 Clerk 查了一下，应该是 Windows 版本中 DVIPDFMx 的问题。Windows 版本的 DVIPDFMx 追开发版本追得比较紧，引入了新版本带来的问题导致的。所以在 Linux 和 macOS 上都没法复现。
> 
> 因为共用 DVIPDFMx 的代码，所以 Windows 版本的 LaTeX + DVIPDFMx 链路应该也能复现。有兴趣的可以试一下。
> 
> 这个问题 Clerk 会修复，过段时间再更新，应该就可以了。短时间内应该没啥好办法，只能换 pdfLaTeX 或者 LuaLaTeX 暂时绕过这个问题。

我试过了，问题复现。

**Comment by Liam0205** [comment]
Clerk 在他的微信公众号上，提供了一个临时的解决方案。

https://mp.weixin.qq.com/s/So5I8khQPrEbLsbrzPJeBQ
