### ISSUE TITLE
用 xelatex 编译，在 beamer 中输出不了 ball 符号

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#156]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

全部宏包均为最新，在这里看到[这个问题](https://wenda.latexstudio.net/q-2616.html)，我精简了一下

## 最小工作示例（MWE）

```latex
\documentclass{beamer}
\setbeamertemplate{itemize items}[ball]
\begin{document}
  \begin{frame}
    \begin{itemize}
      \item 
    \end{itemize}
  \end{frame}
\end{document}
```

用 xelatex 编译后没有输出 `ball` 符号，用 pdflatex 可以输出。

我还测试了 `default`、`triangle`、`circle`、`square` 均无问题。

我用 Overleaf 测试，正常输出。

## 附件

[beamer-test.zip](https://github.com/CTeX-org/forum/files/5395741/beamer-test.zip)

**Comment by muzimuzhi** [comment]
duplicate of #153
