### ISSUE TITLE
xelatex 编译 beamer 的 Warsaw 主题会造成无序列表的标记消失

### ISSUE THREAD

**Issue by OsbertWang** [CTeX-org/forum#158]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

今天有朋友问到这个问题，表示将 TeX Live 2020 升级到最新版后，`xelatex` 编译结果异常，无序列表的 `bullet` 标记都不显示了。

## 最小工作示例（MWE）

```latex
\documentclass{beamer}
\usetheme{Warsaw}
\begin{document}
\begin{frame}{frame}
  \begin{itemize}
    \item a
    \item b
  \end{itemize}
\end{frame}
\end{document}
```
用 `xelatex` 编译以上代码后的结果和日志文件见附件。
用 `pdflatex` 编译无问题。

## 附件

[main.log](https://github.com/CTeX-org/forum/files/5422975/main.log)
[main.pdf](https://github.com/CTeX-org/forum/files/5422976/main.pdf)

**Comment by sikouhjw** [comment]
https://github.com/CTeX-org/forum/issues/156
