### ISSUE TITLE
geometry 包会更改纸张的默认输出大小

### ISSUE THREAD

**Issue by tanukihee** [CTeX-org/forum#160]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020 
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

在安装 TeXLive 2020 时，选择「缺省的纸张给 A4」（TeX Live 默认选项），编译文档时，输出的 pdf 纸张大小为 A4 大小（210mm×297mm），
Adobe Acrobat Reader DC 文档属性：
![O2D(@0U7G9VF9PE%8KXY}H4](https://user-images.githubusercontent.com/34062491/97183957-5537e280-17d9-11eb-914d-5b08829c9c53.png)

但代码输出结果为 614.295pt×794.9699pt，即 letter 纸张的大小（8.5'×11'，215.9mm×279.4mm）。而在使用 geometry 包后，输出的 pdf 纸张大小则变成了实际的 letter 大小。
Adobe Acrobat Reader DC 文档属性：
![RNOB703I_U1PW1}ZFC_NAJM](https://user-images.githubusercontent.com/34062491/97184159-97612400-17d9-11eb-9444-e2b603af8a1d.png)

pdf、xe、lua均能复现。

## 最小工作示例（MWE）

```latex
\documentclass{article}
\usepackage{geometry}
% 不添加时，纸张显示大小为 a4，添加后变为 ltr
\begin{document}
\the\paperwidth

\the\paperheight
\end{document}
```

输出结果

![image](https://user-images.githubusercontent.com/34062491/97182900-12c1d600-17d8-11eb-82cc-0863d9522fd5.png)

## 链接

- TeX.SX:
- GitHub:

## 我还做了这些尝试

在 `\documentclass[]{article}` 中或在 `\geometry{}` 中添加 `a4paper` 选项，纸张的实际大小均会改变为 A4 大小，即 `\paperwidth` 变为 597.50787pt，210mm，`\paperheight` 变为 845.04684pt，270mm。

## 附件

[不使用geometry的文档.pdf](https://github.com/CTeX-org/forum/files/5439389/geometry.pdf)

[使用geometry的文档.pdf](https://github.com/CTeX-org/forum/files/5439393/geometry.pdf)

[添加a4paper选项的文档.pdf](https://github.com/CTeX-org/forum/files/5439399/a4paper.pdf)

**Comment by muzimuzhi** [comment]
> 编译文档时，输出的 pdf 纸张大小为 A4 大小（210mm×297mm），
> 但代码输出结果为 614.295pt×794.9699pt，即 letter 纸张的大小（8.5'×11'，215.9mm×279.4mm）。

 - `\paper(width|height)` 只是 latex 格式自己定义的 dimension，控制的是逻辑页面尺寸。而 pdf 文件的物理页面尺寸，是由引擎（或后端）控制的（xetex 和 pdftex 通过 `\pdfpage(width|height)`，luatex 通过 `\page(width|height)`，xdvipdfmx 通过配置文件或 `\special{(paper|page)size=<width>,<height>}`）。
 - 未加载 `geometry` 时，逻辑尺寸为标准文档类设置的 letterpaper，物理页面尺寸为缺省值，也就是 texlive 里设置的（可通过执行 `tlmgr paper` 查看，见文档 https://www.tug.org/texlive/doc/tlmgr.html#paper ）
 - 加载 `geometry` 后，默认情况下，它会把物理页面尺寸设为和逻辑页面尺寸相同，所以 pdf 文件的页面大小变了。相关代码见 https://github.com/davidcarlisle/geometry/blob/master/geometry.dtx#L3568-L3666 ，这段逻辑总是执行，没法跳过。

**Comment by tanukihee** [comment]
懂了，也就是说，最好还是显式地声明 `a4paper` 了。
