### ISSUE TITLE
如何解决定义环境为小字号，出现第二段行间距大于第一段行间距的情况？

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#161]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

我在重定义 `abstract` 环境的时候，将环境内的字号设置的比较小，发现第二段的行间距比第一段的行间距大，这是为什么？如何解决？

## 最小工作示例（MWE）

```latex
\documentclass{article}
\usepackage{lipsum}
\renewenvironment{abstract}{\tiny}{}
\begin{document}
  \begin{abstract}
    \lipsum[1-2]
  \end{abstract}
\end{document}
```

（用 pdfLaTeX 编译后）输出
![1](https://user-images.githubusercontent.com/49770925/97718075-7281ef00-1b00-11eb-9340-3c09ecf96ae2.png)

**Comment by muzimuzhi** [comment]
`\renewenvironment{abstract}{\tiny}{\par}`

**Comment by sikouhjw** [comment]
> 
> 
> `\renewenvironment{abstract}{\tiny}{\par}`

感谢！
