### ISSUE TITLE
newcommand 命令定制高亮单词的环境

### ISSUE THREAD

**Issue by muyuuuu** [CTeX-org/forum#162]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

`overleaf, Texlive 2020, xelatex.` （建议你们这里的选项添加 overleaf）

## 描述问题

想用 `newcommand` 命令定义一个环境，高亮一个句子中的某个单词。不想每次都 `{\color{red}\sffamily}`等，所以尝试定制环境，后面的单词也受到了环境的影响。

所以：我想问的是，如何定制这个环境，使后面的单词不受影响。举例说明，我只想高亮和更改 `database` 的字体，后面的`for reading only`应该一切正常，和正文默认的设置保持一致，不知道我描述清楚了没。
![image](https://user-images.githubusercontent.com/43681138/97774433-a574c300-1b92-11eb-8090-75d9f7c74ca0.png)

`newcommand`的使用参考的`lshort`：
![image](https://user-images.githubusercontent.com/43681138/97774458-e53baa80-1b92-11eb-9a30-7d95269e6285.png)

## 最小工作示例（MWE）

```tex
\documentclass{ctexart}
\usepackage{color}
\newcommand{\word}[1]{\color{red}\sffamily{#1}}

\begin{document}
Open existing \word{database} for reading only (default)
\end{document}
```

https://www.overleaf.com/7364981229qdmmygskjcgf 是我在overleaf上分享的MWE，可以直接来这修改并查看效果。

**Comment by stone-zeng** [comment]
漏了一组括号：`\newcommand{\word}[1]{{\color{red}\sffamily{#1}}}`

**Comment by muyuuuu** [comment]
懂了懂了，谢谢😉。我这里没其他问题了。

**Comment by muzimuzhi** [comment]
或用 `\newcommand{\word}[1]{\textcolor{red}{\sffamily#1}}`
