### ISSUE TITLE
模板 cupb-phd-thesis 编译报错，\CJKunderline 未定义

### ISSUE THREAD

**Issue by kuku1993** [CTeX-org/forum#163]
## 检查

- [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题
1. 学位论文模本无法编译
  2. 直接运行里面的Thesis.tex文件即可复现错误，错误如下图所示：
      3.试过overleaf的tex2018, tex2019和tex2020均无法编译。
![7ba23f305818d4c892d220f78294d02](https://user-images.githubusercontent.com/54982333/97779477-4e361900-1bb9-11eb-8878-c9f6e309b2ae.png)
## 最小工作示例（MWE）

该论文模本的下载链接如下。

- TeX.SX:
- GitHub: https://github.com/linyuantiaohe/cupb-phd-thesis
[cupb-phd-thesis-master.zip](https://github.com/CTeX-org/forum/files/5469076/cupb-phd-thesis-master.zip)

**Comment by kuku1993** [comment]
我把\makeenglishtitle 注释掉，发现后面的\makedeclaration和\chapter都显示无定义，这个怎么修改呢？

**Comment by sikouhjw** [comment]
两个 error
- `\CJKunderlinecolor` undefined
  ```tex
  ! LaTeX Error: Command \CJKunderlinecolor undefined.

  See the LaTeX manual or LaTeX Companion for explanation.
  Type  H <return>  for immediate help.
  ...

  l.122     \renewcommand{\CJKunderlinecolor}
                                             {\color[rgb]{0,0,0}}% set underli...

  ?
  ```
- `\uline` undefined
  ```tex
  ! LaTeX Error: Command \uline undefined.

  See the LaTeX manual or LaTeX Companion for explanation.
  Type  H <return>  for immediate help.
  ...

  l.123     \renewcommand{\uline}
                                 [1]{\CJKunderline{#1}}% unified name
  ?
  ```

解决方案：
- https://github.com/linyuantiaohe/cupb-phd-thesis/blob/c0371c3502ec3ef1a5acca171c3bb37398ef1a2b/Style/cupbthesis.cls#L122
  改为
  ```tex
  \newcommand{\CJKunderlinecolor}{\color[rgb]{0,0,0}}% set underline color
  ```
- 在
  https://github.com/linyuantiaohe/cupb-phd-thesis/blob/c0371c3502ec3ef1a5acca171c3bb37398ef1a2b/Style/cupbthesis.cls#L123
  前加载 `xeCJKfntef` 宏包

修改后编译通过，至于其它 warning，你没问，我不管

参考：
- https://github.com/mohuangrui/ucasthesis/issues/110
- https://github.com/CTeX-org/ctex-kit/issues/463

**Comment by sikouhjw** [comment]
当然，这种连「LaTeX」都拼不对的「模板」，还是不推荐用了。

~~word 大法好~~

**Comment by muzimuzhi** [comment]
分支 [muzimuzhi/cupb-phd-thesis/tree/2020-fall-xelatex](https://github.com/muzimuzhi/cupb-phd-thesis/tree/2020-fall-xelatex) 能做到在 macOS + xe(la)tex + latex2e 2020-10-10 编译不报错。

另外，在报错信息
```tex
! Undefined control sequence.
\uline #1->\CJKunderline
                         {#1}
l.29 \makeenglishtitle
                      % 生成英文封面
?
```
中，`! Undefined control sequence.` 下一行的最后一个命令是未定义的，也就是 `\CJKunderline`。题主错看成是 `\makeenglishtitle` 未定义了。

**Comment by kuku1993** [comment]
非常感谢你们的回答！只不过还是遇到了一个小问题，就是第一种方法改完后依然无法运行，就一直卡在运行界面既不报错也不出结果，貌似陷入了死循环一样。第二种方法下载后运行提示找不到cupbthesis.cls这个文件的，用的是Texlive2019和Texstudio，如下图所示：
![image](https://user-images.githubusercontent.com/54982333/97793321-6fccea00-1c25-11eb-8f00-14d9b90d93ab.png)

**Comment by sikouhjw** [comment]
> 非常感谢你们的回答！只不过还是遇到了一个小问题，就是第一种方法改完后依然无法运行，就一直卡在运行界面既不报错也不出结果，貌似陷入了死循环一样。第二种方法下载后运行提示找不到cupbthesis.cls这个文件的，用的是Texlive2019和Texstudio，如下图所示：
> ![image](https://user-images.githubusercontent.com/54982333/97793321-6fccea00-1c25-11eb-8f00-14d9b90d93ab.png)

我用的是 texlive 2020。

你用命令行编译看看结果吧，`xelatex xx.tex`，然后看卡在哪里

**Comment by kuku1993** [comment]
按照你的方法最终带有两个问题的运行生成了结果，第一个问题是提示找不到FangSong_GB2312这款字体，但实际上这款字体我按照模本作者提示已经安装在win10系统里，第二个问题就是生成的PDF文件里的参考文献引用没有正确生成。这两个问题截图如下：
![image](https://user-images.githubusercontent.com/54982333/97793780-a86fc200-1c2b-11eb-8a80-892ddefd42bf.png)
![image](https://user-images.githubusercontent.com/54982333/97793797-c3dacd00-1c2b-11eb-998c-d3eb1d2b70b2.png)

**Comment by sikouhjw** [comment]
> 按照你的方法最终带有两个问题的运行生成了结果，第一个问题是提示找不到FangSong_GB2312这款字体，但实际上这款字体我按照模本作者提示已经安装在win10系统里，第二个问题就是生成的PDF文件里的参考文献引用没有正确生成。这两个问题截图如下：
> ![image](https://user-images.githubusercontent.com/54982333/97793780-a86fc200-1c2b-11eb-8a80-892ddefd42bf.png)
> ![image](https://user-images.githubusercontent.com/54982333/97793797-c3dacd00-1c2b-11eb-998c-d3eb1d2b70b2.png)

- 是不是「为所有人安装」？
- 参考文献需要 bib 编译，去看 `texdoc lshort-zh`

**Comment by kuku1993** [comment]
字体是为所有人安装的，如下图所示：
![image](https://user-images.githubusercontent.com/54982333/97793849-7317a400-1c2c-11eb-8129-8b3a1d037505.png)

**Comment by kuku1993** [comment]
能再看看字体问题吗，现在就差字体问题不知道怎么解决了，安装很多次字体了，还是不行

**Comment by sikouhjw** [comment]
编译
```tex
\documentclass{ctexart}
\setCJKmainfont{FangSong_GB2312}
\begin{document}
  测试
\end{document}
```
看看能不能通过，如果不能，将 `仿宋_GB2312.ttf` 放到 `cupb-phd-thesis-master` 目录下，而不是 `cupb-phd-thesis-master\Fonts`

**Comment by kuku1993** [comment]
按照你的方法，第一次没有编译通过，并且依然报无法找到该字体的错误，然后我把字体复制到cupb-phd-thesis-master 目录下，发现还是不能编译通过，报相同的错误。还有其他的可能性吗？

**Comment by sikouhjw** [comment]
> 按照你的方法，第一次没有编译通过，并且依然报无法找到该字体的错误，然后我把字体复制到cupb-phd-thesis-master 目录下，发现还是不能编译通过，报相同的错误。还有其他的可能性吗？

那就不要用「字体名」查找，用「字体文件名」查找，将 `xxxx.sty` 里面的字体设置改成 `仿宋_GB2312.ttf`

**Comment by kuku1993** [comment]
在artratex.sty里将FanfSong_GB2312替换成仿宋_GB2312.ttf后，再次运行还是提示找不到仿宋_GB2312字体，如下图所示：
![image](https://user-images.githubusercontent.com/54982333/97794895-b2e58800-1c3a-11eb-98a3-f4813ed4ba9e.png)

呜呜

**Comment by sikouhjw** [comment]
我建议你用 texlive 2020 或者 Overleaf 吧

**Comment by kuku1993** [comment]
好的，我试试Texlive2020。当我安装这个字体后到C盘的Windows\fonts里找到该字体时，发现该字体和其他安装的字体有些区别，该字体后面的显示是“可安装”而不是可安装，请问这是正常的吗？
![image](https://user-images.githubusercontent.com/54982333/97795010-fa204880-1c3b-11eb-9862-c2428322e552.png)

**Comment by kuku1993** [comment]
你好，在安装2020版本的Texlive后，字体问题和引用问题都解决了。还是剩下的多余空白页的问题。就是生成的PDF的第2页，第4页，第6的莫名其妙的空白页，请问这种该怎么解决呢？

**Comment by sikouhjw** [comment]
> 你好，在安装2020版本的Texlive后，字体问题和引用问题都解决了。还是剩下的多余空白页的问题。就是生成的PDF的第2页，第4页，第6的莫名其妙的空白页，请问这种该怎么解决呢？

这是另外的问题了，去新开一个 issue 吧

还有，你自己确定一下「规范是不是如此规定」，不要「你觉得」

**Comment by kuku1993** [comment]
好的

**Comment by muyuuuu** [comment]
> 就是生成的PDF的第2页，第4页，第6的莫名其妙的空白页，

这可能是论文样式，正常。

**Comment by kuku1993** [comment]
因为这个latex模本是依据里面的Word模本制作的，我对比过两者，发现Word版本没有这样的多余页，有办法删除吗？

**Comment by muyuuuu** [comment]
> 因为这个latex模本是依据里面的Word模本制作的，我对比过两者，发现Word版本没有这样的多余页，有办法删除吗？

word当然没有，您导出『pdf』看一下，可能就有了。

**Comment by kuku1993** [comment]
我在另一个issue提了这个问题。并且这几个空白页不都属于完全的空白页，是和它上一页的重复页，除了第4页是全空白页。我把Word导出PDF没有发现这样的现象。

**Comment by tanukihee** [comment]
请检查是否是因为「双面打印文档需要在右侧（奇数页）开启新章」而导致的空白页，如果是的话，可以改成单面打印（`openany` 选项）

**Comment by kuku1993** [comment]
你说的很对，那前面的几个纯空白页是用来双面打印用的。但是后面的中文摘要和英文摘要之间多出一页包含“摘要”的页眉以及后面的创新点之间也多出一页带有页眉的页，这两页不完全属于空白页，但是呢，摘要在这里只需要一页就写完了，但还是多出了这样一页，如下图所示：
![image](https://user-images.githubusercontent.com/54982333/97796678-11693100-1c50-11eb-8e56-1568395ba1a5.png)

![image](https://user-images.githubusercontent.com/54982333/97796682-20e87a00-1c50-11eb-9050-1f92804f7416.png)
这是为什么呢？

**Comment by tanukihee** [comment]
当然是因为摘要也算新章，需要右开

**Comment by kuku1993** [comment]
那这样不是会导致：我即使一页就写完了摘要，双面打印出来后摘要的背面不是全空白，而是含有摘要二字的页眉，能不能设成全空白页来右开？

**Comment by tanukihee** [comment]
你写完后把页眉去掉呗
`\thispagestyle{empty}`

**Comment by kuku1993** [comment]
好的，非常感谢你们的帮助！

**Comment by sikouhjw** [comment]
原来这个「模板」是手动设置页眉页脚的……我还以为是写好的、自动化的……
> 3.3.1  中文摘要
> 如果是一页，单面打印；否则双面打印。

很明显，这里的意思就是从奇数页开始，所以只需要按照上面说的将页眉页脚去掉就好了

**Comment by kuku1993** [comment]
能不能为我写一个自动化的LaTex学位模本？^_^

**Comment by sikouhjw** [comment]
> 
> 
> 能不能为我写一个自动化的LaTex学位模本？^_^

你知道市场价多少吗

**Comment by kuku1993** [comment]
多少呢一份？

**Comment by kuku1993** [comment]
可以做到和Word格式几乎没差别吗？

**Comment by sikouhjw** [comment]
据说是 3000，还做不到几乎无差别 hhh

**Comment by kuku1993** [comment]
只要肉眼看不出来就行

**Comment by muzimuzhi** [comment]
标题里的问题已经解决，关闭当前 issue。
