### ISSUE TITLE
关于数学手稿排版格式的问题讨论

### ISSUE THREAD

**Issue by zsben2** [CTeX-org/forum#166]
一般的数学手稿、笔记并不会像出版书籍那样有严谨的段落，更多的是无脑换行。一个常见的例子就是中学数学题，一个 ∵ 或 ∴ 就要占用一行，因此数学考试的答题卡会设计成细长条状的答题区域，尤以A3幅面的答题卡为甚。

![](https://wenda.latexstudio.net/data/attach/201130/eDCVTX39.png)

这些频繁的换行，如果在行末使用 `\\` 实现，那么在每行都要手动换行，一门课的笔记好几十页，这每一行都手动换行不可谓不是一个大工程，并且这样会使代码都书写得很紧凑，不美观（因为不能空行分段）；如果使用空行换段并设置 `\parindent=0pt` 来设置无缩进的话，又会使代码过于松散（因为每一行自成一段）。因此在此想征求一个从代码的角度上看层次分明，从pdf的效果上看又能贴合手稿格式的优雅的解决方案。

![](https://wenda.latexstudio.net/data/ueditor/php/upload/file/20201208/1607431801191610.jpg)

在公式方面，无处不在的递等式要求在等号处对齐也是常规操作。但这些无处不在的对齐无论是使用文本的 `tabular` 环境实现还是数学的 `align` 环境实现都会产生极大的不便。（上下这两张都是我这学期的笔记，献丑了）

![](https://wenda.latexstudio.net/data/ueditor/php/upload/file/20201208/1607431538941542.jpg)

所以本文的问题就是想大伙一起讨论一下，有没有什么适用于数学手稿的优雅的排版方法。其根本是要解决：
1. 频繁的无脑换行
2. 无处不在的对齐

**Comment by zepinglee** [comment]
用 `\\` 换行更合理，因为还没形成完整的句子。如果要是在代码上想要空一行的效果，可以使用 `%` 注释，这样不会形成分段，但不宜滥用。

“无处不在的对齐”？我感觉 `align` 足够。

另外提醒下不宜滥用 `\because` 和 `\therefore`。

**Comment by muzimuzhi** [comment]
`breqn` 宏包提供了一些公式自动分行、对齐的功能。可能会遇到一些和其他数学字体包和数学功能包的兼容性问题，遇到时可以单独提问。一个使用例子：
```tex
\documentclass{article}
\usepackage{breqn}  % amsmath auto-loaded
\usepackage{lipsum}

\begin{document}
\lipsum[2]
\begin{dmath*}
  f(x) 
    = (x+1)^3
    = (x^2 + 2x + 1)(x+1)
    = x^3 + 3x^2 + 3x + 1
\end{dmath*}
\lipsum[3]
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/101980902-cf49fb00-3ca3-11eb-9d32-2f0adafc5ee4.png)


PS:
 - 建议把问题拆小，这样容易得到回应，也容易抵达「讨论结束」的状态
 - 手写笔记的图片可能上传失败，我这里总是加载不完整

**Comment by lhy7889678** [comment]
（高中党表示没有排过手稿，以下内容为个人观点，仅供参考）

首先，强烈不建议使用空行来分段，这样极其“不优雅”，因为在逻辑上并不构成独立的段落。还是用 `\\` 更恰当。

其次，如果你觉得使用 `\\` 麻烦，一劳永逸的办法是配置一下你的编辑器。比如用 `Alt+Enter`（Emacs 党喜闻乐见的 `M-RET`，使用方法：用左手大拇指按住 `Alt`，右手小拇指按 `Enter`）来完成一系列操作，先把光标移到行尾，再加上 `\\` 换行，接着在代码中新开一行自动缩进，还可以再来一对 `$` 并把光标移到中间……手头没有电脑，恕不提供具体方法。

最后，考虑到优雅性，提醒一下要勤换 `$`，不要为了图方便什么东西都往数学模式里塞。

**Comment by zsben2** [comment]
感谢 @zepinglee @lhy7889678 的意见，我也觉得用 `\\` 在逻辑上才更为恰当。由此联想到如果能毋须手动 `\\` ，也能像抄录环境一样，只需单个回车就能直接换行，那就能省很多功夫了，而且从代码风格上来看，每一行也不会有过于泛滥的 `\\` 后缀。因此直接改写 `^^M` 的作用效果是我想到的第一个方法。

```tex
\documentclass{article}
% \catcode`\^^M=\active %放这里会报错
% \def^^M{\ifhmode\ifinner\else\newline\fi\fi}
\begin{document}
\catcode`\^^M=\active
\def^^M{\ifhmode\ifinner\else\newline\fi\fi}

first line
second line
third line
\end{document}
```

![1](https://wenda.latexstudio.net/data/attach/201212/HSnyIsN7.png)

但是这个方式太不鲁棒了。这直接抹杀掉换段的效果，就跟抄录环境一样，爱换多少行换多少行，需要补充更多的逻辑和判断。在参考了 [How can I include external macros for every line of the source code?](https://tex.stackexchange.com/questions/251853/how-can-i-include-external-macros-for-every-line-of-the-source-code) 上的代码后，第二个方法改写成如下的 `mathlines` 环境

```tex
\documentclass{article}
\def\breakline{\ifhmode\ifinner\else\newline\fi\fi}
\makeatletter
{\obeylines\gdef\linepar{\@ifnextchar{^^M}{\endgraf}{\breakline}}}
\makeatother
\newenvironment{mathlines}
{\endgraf\let\par\linepar\obeylines}{\endgraf}
\begin{document}
\begin{mathlines}
first paragraph
bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb 
ccc ccc ccc ccc ccc ccc ccc

second paragraph
bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb 
ccc ccc ccc ccc ccc ccc ccc
\end{mathlines}
\end{document}
```

![2](https://wenda.latexstudio.net/data/attach/201212/2Lbym8yb.png)

在环境内用 `obeylines` 为每一行自动添加 `\par`，然后改写 `\par` 的动作，而非改写 `^^M` 的动作。并使用原始的 `\endgraf` 命令恢复分段功能。那么只要将这部分需要频繁换行的文字放在这个环境里，即可在不影响上下文段落结构的基础上实现随意换行了。

但在一些测试后发现这段代码仍不够鲁棒，例如我虽然指定了 `\breakline` 在在水平模式中才展开为 `\newline` ，但是这仍会在一些意想不到的地方产生多余的换行，例如在列表数学模式的前后

```tex
\documentclass{article}
\def\breakline{\ifhmode\ifinner\else\newline\fi\fi}
\makeatletter
{\obeylines\gdef\linepar{\@ifnextchar{^^M}{\endgraf}{\breakline}}}
\makeatother
\newenvironment{mathlines}
{\endgraf\let\par\linepar\obeylines}{\endgraf}
\begin{document}
\begin{mathlines}
first paragraph
bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb mmm
\[a^2+b^b=c^2\]
ccc ccc ccc ccc ccc ccc ccc

second paragraph
bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb bbb
ccc ccc ccc ccc ccc ccc ccc
\end{mathlines}
\end{document}
```

![3](https://wenda.latexstudio.net/data/attach/201212/vgewCGvr.png)

这里的公式上下会正确地产生多余的换行，而解决方式就是在 `mmm` 和 `\]` 之后添加一个额外的 `%` 以注释掉这个多余的换行。但如果这样的 `%` 输多了，那么就与创作这个环境的目的——省功夫相悖了，还不如直接用 `\\` 换行还省心~

其实我觉得当前这段代码其实是一个很好的思路，但就是不知道应如何使它更鲁棒而已。或者说能不能另辟蹊径，模仿抄录环境的随意换行。

**Comment by muzimuzhi** [comment]
> * 建议把问题拆小，这样容易得到回应，也容易抵达「讨论结束」的状态

每一个问题，建议发成单独的 issue。

**Comment by zsben2** [comment]
本 issue 拆分为两个子问题，请大家移步 #169 和 #170 继续讨论。
