### ISSUE TITLE
sectsty 宏包设置章节字体时，文字重叠

### ISSUE THREAD

**Issue by muyuuuu** [CTeX-org/forum#167]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境
  - [x] TeX Live 2020, Overleaf

## 描述问题

我想设置章节标题的颜色，查到了`sectsty`包，但发现文字出现了重叠：

![image](https://user-images.githubusercontent.com/43681138/101771373-cb439f00-3b24-11eb-9090-51c5ce788385.png)

或者退一步，不使用这个包，只要能设置章节标题颜色就可以。

## 最小工作示例（MWE）

```tex
\documentclass{ctexart}
\usepackage[dvipsnames]{xcolor}
\definecolor{sec}{RGB}{102, 144, 207}
\usepackage{sectsty}
\sectionfont{\color{sec}}
\subsectionfont{\color{sec}}
\subsubsectionfont{\color{sec}}
\begin{document}
\section{测试}
没想好写些什么。
\subsection{测试}
阿斯顿
\subsubsection{测试}
阿斯顿
\end{document}
```

## 链接

- TeX.SX: https://tex.stackexchange.com/questions/75667/change-colour-on-chapter-section-headings-lyx

原文链接，我看他那里没有重叠。

**Comment by sikouhjw** [comment]
为什么不用 CTeX 宏集提供的章节设置功能……`texdoc ctex`

**Comment by tanukihee** [comment]
```LaTeX
\documentclass{ctexart}

\usepackage[dvipsnames]{xcolor}
\definecolor{sec}{RGB}{102, 144, 207}
\ctexset{
    section={
        format+=\color{sec}
    },
    subsection={
        format+=\color{sec}
    },
    subsubsection={
        format+=\color{sec}
    }
}

\begin{document}
\section{测试}
没想好写些什么。
\subsection{测试}
阿斯顿
\subsubsection{测试}
阿斯顿

\end{document}
```

![image](https://user-images.githubusercontent.com/34062491/101772861-eb745d80-3b26-11eb-80c4-66f4fab16ee9.png)

**Comment by muyuuuu** [comment]
> 为什么不用 CTeX 宏集提供的章节设置功能……`texdoc ctex`

老忘了有这个东西的存在......查了一下解决了，多谢。

```tex
\ctexset{
    section/format += {\color{red}},
}
```

**Comment by muyuuuu** [comment]
也谢谢您的回复 @tanukihee  。
