### ISSUE TITLE
对插入整页pdf文件设置对称页边距

### ISSUE THREAD

**Issue by krisfans** [CTeX-org/forum#168]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] macOS
  - [ ] 更早版本的 Windows
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live  2020 
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题
将一个完整的pdf文件重新设置页边距。
我删除了一个pdf文档原来的页边距，希望设置对称页边距业适用与打印装订。能不能在`latex`中利用`pdfpages`和`geometry`这两个包实现如下效果。
![页边距](https://user-images.githubusercontent.com/57793534/101983698-b21f2780-3cb7-11eb-9cea-4b5e07912607.png)
我的尝试结果
![捕获](https://user-images.githubusercontent.com/57793534/101983818-4ab5a780-3cb8-11eb-8d62-49f6f083e22f.PNG)

测试的pdf文件见附件

## 最小工作示例（MWE）

```latex
%!TEX program = xelatex
\documentclass[a4paper,zihao=-4,UTF8]{ctexbook}
\usepackage[inner=4cm,outer=2cm,top=2cm,bottom=2cm]{geometry}
\usepackage{pdfpages}
\begin{document}
\includepdf[pages={-},noautoscale]{test.pdf}
\end{document}
```

## 附件

[test.pdf](https://github.com/CTeX-org/forum/files/5683055/test.pdf)

**Comment by tanukihee** [comment]
似乎 pdfpages 默认会将 PDF 页面居中，所以只能使用 `offset` 选项，而且这个值需要自己算。在宽度为 `\textwidth` 下，`offset` 值为内外边距之差的一半。

```LaTeX
\documentclass[a4paper,zihao=-4,UTF8]{ctexbook}
\usepackage[inner=4cm,outer=2cm,top=2cm,bottom=2cm]{geometry}
\usepackage{pdfpages}
\usepackage{graphicx}

\begin{document}
\includepdf[pages={-} , width=\textwidth , offset = 1cm 0]{test.pdf}

\end{document}
```LaTeX

**Comment by tanukihee** [comment]
似乎 pdfpages 默认会将 PDF 页面居中，所以只能使用 `offset` 选项，而且这个值需要自己算。在宽度为 `\textwidth` 下，`offset` 值为内外边距之差的一半。

```LaTeX
\documentclass[a4paper,zihao=-4,UTF8]{ctexbook}
\usepackage[inner=4cm,outer=2cm,top=2cm,bottom=2cm]{geometry}
\usepackage{pdfpages}
\usepackage{graphicx}

\begin{document}
\includepdf[pages={-} , width=\textwidth , offset = 1cm 0 ]{test.pdf}

\end{document}
```LaTeX

**Comment by krisfans** [comment]
> 
> 
> 似乎 pdfpages 默认会将 PDF 页面居中，所以只能使用 `offset` 选项，而且这个值需要自己算。在宽度为 `\textwidth` 下，`offset` 值为内外边距之差的一半。
> 
> ```
> \documentclass[a4paper,zihao=-4,UTF8]{ctexbook}
> \usepackage[inner=4cm,outer=2cm,top=2cm,bottom=2cm]{geometry}
> \usepackage{pdfpages}
> 
> \begin{document}
> \includepdf[pages={-} , width=\textwidth , offset=1cm 0]{test.pdf}
> 
> \end{document}
> ```

谢谢。原来只需要调整`offset`就行，我还以为要对每一页分奇偶数设置页边距。

**Comment by muzimuzhi** [comment]
> 似乎 pdfpages 默认会将 PDF 页面居中

参考 `texdoc pdfpages`, sec. 2.3 _The Layout_
> The inserted logical pages are being centered on the sheet of paper by default.
To displace them use the offset option, which argument should be two dimen-
sions. E.g. `offset=10mm 14mm` means that the logical pages are displaced by
`10mm` in horizontal direction and by `14mm` in vertical direction. In '_oneside_'
documents positive values shift the pages to the _right_ and to the _top_ margin, re-
spectively, whereas in '_twoside_' documents positive values shift the pages to the
_outer_ and to the _top_ margin, respectively.
