### ISSUE TITLE
国防科技大学博士学位论文Letax模板NUDTPaper编译执行失败

### ISSUE THREAD

**Issue by TaihuLight** [CTeX-org/forum#17]
## 检查

- [X] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
    - [X] Windows 10

- TeX 发行版
    - [X] MiKTeX <2.9.6972>

## 描述问题
   《国防科技大学学位论文模板》编译时无任务错误提示，但是编译了1个小时，仍然在执行编译。

## 最小工作示例（MWE）
  - GitHub:  https://github.com/liubenyuan/nudtpaper

**Comment by stone-zeng** [comment]
1. 你完全没有描述清楚出现的问题
2. 你给的 MWE 是无效的
3. 在模版有 GitHub 仓库的时候，请去相关地方提问

**Comment by muzimuzhi** [comment]
我尝试了那个模板，把遇到的导致编译失败的可能原因列在下面，以帮助后来人
* 缺字体。模板基于 `xecjk` 提供了四套配置，默认配置用到了 Adobe 的商业字体。字体配置在用户文档里说明了，但用户文档需要用户从 `dtx` 自己编译，导致出现「没有字体 - 编译出错 - 得不到用户文档 - 无法从文档里读到如何配置配置」的循环
* 未加载示例文档依赖的 `enumitem` 宏包，见 https://github.com/liubenyuan/nudtpaper/issues/16

**Comment by TaihuLight** [comment]
那这个问题如何解决呢？
（1）Windows上编译生成cls感觉比较麻烦
（2）这个商业字体我找了很久都没找到地方可以下载

**Comment by muzimuzhi** [comment]
建议去模板对应的项目里问。（而且项目文档里提供了下载链接的）

此处不讨论「如何免费获取付费商业字体」。

也别在已关闭的 issue 下反复回复。
