### ISSUE TITLE
Linux 没发现可安装 ctexbook 的包管理器

### ISSUE THREAD

**Issue by micfan** [CTeX-org/forum#171]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [x] Linux（ArchLinux）

- TeX 发行版
  - [x] TeX Live, https://www.archlinux.org/packages/extra/any/texlive-core/
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题
* 使用 pacman 安装了 TexLive
* MiKTeX 与 TexLive冲突无法共存
* TexLive 的原生包管理器 tlmgr 已经损坏: https://wiki.archlinux.org/index.php/TeX_Live#tlmgr
* 如下列 shell 操作 报错, 请问是否有人遇到相似情况?

## 最小工作示例（MWE）

下面是 shell 操作：

```shell
~/ » which tllocalmgr
/bin/tllocalmgr
--------------------------------------------
~/ » tllocalmgr install ctexbook
Initializing ...
Error: command install is not defined
```

## 链接

- http://www.latexstudio.net/archives/4014.html

**Comment by stone-zeng** [comment]
`ctexbook` 对应的包的名字就叫 `ctex`

**Comment by micfan** [comment]
哦, 发现这个包下面的文件里确有这个 ctexbook.cls: https://www.archlinux.org/packages/extra/any/texlive-langchinese/

`usr/share/texmf-dist/tex/latex/ctex/ctexbook.cls`

安装了这个包, 和后续一系列字体 AUR (如 ttf-adobe-*) 后, 终于编译成功了.

多谢指导!
