### ISSUE TITLE
elegantbook模板和包enotez冲突

### ISSUE THREAD

**Issue by InitialXKO** [CTeX-org/forum#172]
```
("C:\Program Files\MiKTeX 2.9\tex/latex/enotez\enotez.sty"

! LaTeX3 Error: Control sequence \endnote already defined.

For immediate help type H <return>.
 ...                                              
                                                  
l.357 \cs_new_protected:Npn \endnote
                                    
? 
```

**Comment by sikouhjw** [comment]
- ElegantBook 的问题请去 https://github.com/ElegantLaTeX/ElegantBook/issues 提问
- 为什么不按照模板提问？为什么不给 MWE？

**Comment by InitialXKO** [comment]
不是说论坛挂了这里暂时当论坛使用么？

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: sikouhjw<mailto:notifications@github.com>
发送时间: 2020年12月16日 16:20
收件人: CTeX-org/forum<mailto:forum@noreply.github.com>
抄送: InitialXKO<mailto:perfectko@msn.com>; Author<mailto:author@noreply.github.com>
主题: Re: [CTeX-org/forum] elegantbook模板和包enotez冲突 (#172)


  *   ElegantBook 的问题请去 https://github.com/ElegantLaTeX/ElegantBook/issues 提问
  *   为什么不按照模板提问？为什么不给 MWE？

―

**Comment by sikouhjw** [comment]
> 不是说论坛挂了这里暂时当论坛使用么？

模板有专门的提问地方，去那里提问可以让维护者回答你的问题，更权威、更快捷，还可以顺便修复可能的 bug。

所以 MWE 呢？

**Comment by InitialXKO** [comment]
MWE正在整理

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by InitialXKO** [comment]
MWE来了
`\documentclass{elegantbook}
 \usepackage{enotez}
 \begin{document}
 \end{document}`

**Comment by InitialXKO** [comment]
有意思的是，endnotes这个包不受影响。

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sikouhjw** [comment]
```tex
\documentclass{elegantbook}
\let\endnote\relax
\usepackage{enotez}
```
这么做可以不报错（其它的就不知道了）

**Comment by muzimuzhi** [comment]
`elegantbook` 定义了环境 `note`，占用了命名 `\note` 和 `\endnote`。

见 https://github.com/ElegantLaTeX/ElegantBook/blob/78fe2c7dafcede6641e3ef06e45803afc0110eeb/elegantbook.cls#L668-L671
```tex
\newenvironment{note}{
  \par\noindent\makebox[-3pt][r]{
    \scriptsize\color{red!90}\textdbend\quad}
    \textbf{\color{second}\notename} \citshape}{\par}
```

**Comment by muzimuzhi** [comment]
以下修改，让 `elegantbook` 的 `note` 环境保持不变，通过 `\endnoteZ` 使用原 `enotez` 的 `\endnote`。
```tex
\documentclass{elegantbook}

% make "note" env and "enotez" pkg compatible
\makeatletter
\let\endnote@backup\endnote
\let\endnote\@undefined

\AtBeginDocument{
  \let\endnoteZ\endnote
  \let\endnote\endnote@backup
}
\makeatother

\usepackage{enotez}

\begin{document}
\begin{note}
  content
\end{note}

text\endnoteZ{first end note} text\endnoteZ{second end note}

\printendnotes
\end{document}
```

**Comment by muzimuzhi** [comment]
相关 issue，https://github.com/ElegantLaTeX/ElegantBook/issues/138
