### ISSUE TITLE
background 宏包在 xelatex 下出现「首页水印加深」的情况，有没有更优雅的方式解决？

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#173]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

`background` 宏包在 xelatex 下出现「首页水印加深」的情况，经过测试（查看警告），是 `everypage` 宏包的问题，将 `background` 宏包的第 42 行
```tex
\@ifpackageloaded{everypage}{}{\RequirePackage{everypage}}
```
改为
```tex
\@ifpackageloaded{everypage}{}{\RequirePackage{everypage-1x}}
```
就好了，但有没有更优雅的方式呢？（指在导言区修改好）

## 最小工作示例（MWE）

```latex
\documentclass{article}
\usepackage[contents = test]{background}
\begin{document}
  test
  \newpage
  test
\end{document}
```

（用 XeLaTeX 编译后）输出

![1](https://user-images.githubusercontent.com/49770925/102369751-43afd180-3ff7-11eb-9493-afa9bc90056e.png)

**Comment by stone-zeng** [comment]
可以用 `ver@xxx` 的技巧避免调用某宏包：

```tex
\documentclass{article}
\makeatletter
\@namedef{ver@everypage.sty}{9999/99/99}
\makeatother
\usepackage{everypage-1x}
\usepackage[contents=DRAFT, color=red, opacity=0.2]{background}
\begin{document}
test
\newpage
test
\end{document}
```

**Comment by muzimuzhi** [comment]
是 bug，报给 pgf 了
