### ISSUE TITLE
在 \section 后面接 tcblisting 环境会报环境匹配错误的错

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#176]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

用 `pdflatex` 编译 MWE 会报错，报错为：
```tex
! LaTeX Error: \begin{tcolorbox} on input line 237 ended by \end{center}.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.237   \end{tcblisting}

? 
```
看起来是 `\begin{tcolorbox}` 与 `\end{center}` 匹配了。

复现条件应该是（选项中带 `\end` 的）`tcblisting` 环境前面接着 `\section` 之类的命令。在中间插入文字，不会复现问题。

## 最小工作示例（MWE）

```latex
\documentclass{article}
\usepackage{tcolorbox}
\tcbuselibrary{listings}
\begin{document}
  \section{test}
  % test
  \begin{tcblisting}{before=\begin{center},after=\end{center}}
test
  \end{tcblisting}
\end{document}
```

**Comment by muzimuzhi** [comment]
> 复现条件应该是（选项中带 `\end` 的）`tcblisting` 环境前面接着 `\section` 之类的命令。在中间插入文字，不会复现问题。

是文档化了的特性，参考 `tcolorbox` 宏包文档中 `/tcb/before` 和 `/tcb/ignore nobreak` 的部分。

根据文档，`ignore nobreak=true` 在所有情况下都有效，`before nobreak=\begin{center}` 对不可断页的 `tcolorbox` 有效。
