### ISSUE TITLE
authblk 包提供的 authorcr 命令会影响字体设置

### ISSUE THREAD

**Issue by OsbertWang** [CTeX-org/forum#177]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

使用 `authblk` 包时设置了 `\affil` 的字体 `\Affilfont`，
```latex
\renewcommand{\Affilfont}{\itshape\small}
```
同时我还设置了 `\author` 的字体 `\Authfont`,
```latex
\renewcommand{\Authfont}{\scshape\small}
```
接下来在 `\affil` 中使用 `\authorcr` 对内容换行, 换行后的内容没有保持 `\itshape` 而变成了 `\scshape`,
删除 `\authorcr` 后, `\itshape` 可以保持.

## 最小工作示例（MWE）

```latex
\documentclass{article}
\usepackage{authblk}
\renewcommand{\Authfont}{\scshape\small}
\renewcommand{\Affilfont}{\itshape\small}

\title{The Deathly Hallows and Its usage}
\author{Albus Dumbledore}
\author{Harry Potter}
\affil{Gryffindor,\authorcr
  Hogwarts School of Witchcraft and Wizardry}

\begin{document}
\maketitle
\end{document}
```

用 PDFLaTeX 编译后，会产生结果
![例子](https://user-images.githubusercontent.com/37971080/103861261-1aff9100-50f8-11eb-960f-86660c075459.png)

**Comment by muzimuzhi** [comment]
LaTeX2e 2020-02-02 拓展了支持的字族，`scit` (Caps and small caps italic) 是其中的一个 [1]。于是 `\scshape\itshape` 调用的不是 `it`，而是 `scit`，而 computer modern 不支持这个字族，回退了。tex 里的字体回退，是整个字体回退，而不是逐字符。

warnings in log:
```tex
% compiled with pdflatex
LaTeX Font Warning: Font shape `OT1/cmr/m/scit' undefined
(Font)              using `OT1/cmr/m/it' instead on input line 25.

LaTeX Font Warning: Font shape `OT1/cmr/m/scit' undefined
(Font)              using `OT1/cmr/m/sc' instead on input line 25.
```

```tex
% compiled with xelatex
LaTeX Font Warning: Font shape `TU/lmr/m/scit' undefined
(Font)              using `TU/lmr/m/scsl' instead on input line 25.
```

解决办法：在指定新 shape 之前，用 `\upshape` 切回去，甚至可以用 `\normalfont` 重制回默认字族。
```tex
\renewcommand{\Authfont}{\upshape\scshape\small}
\renewcommand{\Affilfont}{\upshape\itshape\small}
```

PS：记得要看 log 里的 warning。

[1] `texdoc ltnews`, LaTeX News Issue 31, February 2020

**Comment by muzimuzhi** [comment]
> 使用 `authblk` 包时设置了 `\affil` 的字体 `\Affilfont`，
> 
> ```
> \renewcommand{\Affilfont}{\itshape\small}
> ```
> 
> 同时我还设置了 `\author` 的字体 `\Authfont`,
> 
> ```
> \renewcommand{\Authfont}{\scshape\small}
> ```
> 
> 接下来在 `\affil` 中使用 `\authorcr` 对内容换行, 换行后的内容没有保持 `\itshape` 而变成了 `\scshape`,
> 删除 `\authorcr` 后, `\itshape` 可以保持.

根据 `authblk` 的文档（和实现），`\authorcr` 会把字体切换为 `\Authfont`，于是那里应该用 `\\`.

```tex
% authblk.sty v1.3, line 147
\newcommand\authorcr{\protect\\ \protect\Authfont \protect\AB@setsep}%
```

**Comment by OsbertWang** [comment]
我错误使用了 `\authorcr`, 它应该被用于 `\author` 中, 如
```latex
\documentclass{article}
\usepackage{authblk}
\renewcommand{\Authfont}{\scshape\small}
\renewcommand{\Affilfont}{\itshape\small}

\title{The Deathly Hallows and Its Usage}
\author{Albus Percival Wulfric Brian \authorcr Dumbledore}
\author{Harry Potter}
\affil{Gryffindor,
  Hogwarts School of Witchcraft and Wizardry}

\begin{document}
\maketitle
\end{document}
```
这样使用就不会有什么问题了.
