### ISSUE TITLE
一些关于\tikz@scan@one@point的疑问

### ISSUE THREAD

**Issue by CHEN-z-y** [CTeX-org/forum#178]
## 编译环境
操作系统
* [X] Windows 7/8/10
* [ ] macOS
* [ ] Linux
`若需勾选，请把[ ]改成[x]`

Tex发行版
* [X] TexLive `年份`
* [ ] MikTeX `版本号`
* [ ]  CTeX
`若需勾选，请把[ ]改成[x]`

## 一些关于`\tikz@scan@one@point`的疑问

我正在阅读`\tikz@scan@one@point`，
但是我遇到了一系列问题：

1. 如何分辨一个宏的parameter对应的参数？比如：

   ```tex
   \def\tikz@scan@one@point#1{%
     \let\tikz@to@use@whom=\tikz@to@use@last@coordinate%
     \tikz@shapeborderfalse%
     \pgfutil@ifnextchar+{\tikz@scan@relative#1}{\tikz@scan@absolute#1}}%
   ```

   如果输入 `\tikz@scan@one@point\pgfutil@firstofone(A)`，
   （A是一个node）
   那么与定义中“`#1`”对应的  是 `\pgfutil@firstofone`，还是
   `\pgfutil@firstofone(A)`呢？

2. `\tikz@scanexpand`只有一个参数（`\def\tikz@scanexpand#1{...`）
   但是在`\tikz@scan@absolute`的定义中，`\tikz@scanexpand`的调用
   却不带任何参数：

   ```tex
   \def\tikz@scan@absolute#1{%
     \pgfutil@ifnextchar({\tikz@scan@@absolute#1}%)
     {%
       \advance\tikz@expandcount by -1%
       \ifnum\tikz@expandcount<0\relax%
         \let\pgfutil@next=\tikz@@scangiveup%
       \else%
         \let\pgfutil@next=\tikz@@scanexpand%
       \fi%
       \pgfutil@next{#1}%
     }%
   }%
   ```

   这种现象在TikZ的源码中多次出现，
   有大牛可以解释一下这是为什么吗^_^

另外，有没有通读过`tikz.code.tex`的大佬
可以大概解释一下`\tikz@scan@one@point`是如何工作的？
可不可以展示一些例子？

**Comment by muzimuzhi** [comment]
先回答具体的问题

> 1. 如果输入 `\tikz@scan@one@point\pgfutil@firstofone(A)`，
>    （A是一个node）
>    那么与定义中“`#1`”对应的  是 `\pgfutil@firstofone`，还是
>    `\pgfutil@firstofone(A)`呢？

`#1` 是 `\pgfutil@firstofone`。

> 2. `\tikz@scanexpand`只有一个参数（`\def\tikz@scanexpand#1{...`）
>     但是在`\tikz@scan@absolute`的定义中，`\tikz@scanexpand`的调用
>     却不带任何参数：

你可能看错了。
 - pgf-tikz 的代码库中没有 `\tikz@scanexpand`，只有 `\tikz@@scanexpand`，后者是一个宏，有一个参数。
 - 你引用的代码里用到的是 `\tikz@expandcount`，它是一个 tex count，由 `\newcount\tikz@expandcount` 定义。count 在使用时自然不需要带参数。

------
然后一些抽象的

> 1. 如何分辨一个宏的parameter对应的参数？

分辨不了。主要靠文档，没有文档的靠看源码。一个命令，用户看到的是 `\cmd{}{}{}`，内部的实现可能是 `\def\cmd#1{\cmd@i} \def\cmd@i#1{\cmd@ii} \def\cmd@ii#1{...}`。所以 `\cmd` 的 parameter text `#1` 不能代表它完整的用法。

> 可以大概解释一下`\tikz@scan@one@point`是如何工作的？
> 可不可以展示一些例子？

`\tikz@scan@one@point#1<point>` 会 parse 一个 `<point>`，然后调用 `#1{<pgf coordinate>}`。一般 `#1` 是一个有一个参数的宏。

**对于最简单的坐标**，`\tikz@scan@one@point\cmd (1,2)` 会最终展开到 `\cmd{\pgfpointxy{1}{2}}`。几个主要步骤是
```tex
\tikz@scan@one@point\cmd (1,2)
  \tikz@scan@absolute\cmd (1,2)
    \tikz@scan@@absolute\cmd (1,2)
      \tikz@@@scan@@absolute\cmd (1,2)
        \tikz@scan@no@calculator\cmd (1,2)
          \tikz@@scan@@no@calculator\cmd (1,2)
            \tikz@parse@regular\cmd (1,2)
              \tikz@@@parse@regular\cmd (1,2)
                \cmd{\pgfpointxy{1}{2}}
```
parse 的主要过程是不断用 `\pgfutil@ifnextchar<char>{<true>}{<false>}` 来进入不同的分支，偶尔用到 `\pgfutil@in@`。[1] 在整个过程中，`\cmd` 会被一直传递下去，直到 tikz 知道了使用哪个 pgf 命令来组成一个 pgf coordinate。

典型的 `\cmd#1{...}` 会包含 `\pgf@process{#1} <codes using \pgf@x and \pgf@y>`。`\pgf@process` 展开 pgf coordinate，把 x, y 坐标存在 `\pgf@x`, `\pgf@y` 里（三维坐标用到 `\pgf@z`）。

**一个具体 `\cmd` 的例子**，`\draw (0,0) -- (1,1);`，
 - 先进入 `\tikz@scan@next@command (0,0) -- (1,1);`
 - 在 `\tikz@handle` 里因为 `\ifx\pgf@let@token( == true`，进入 `\tikz@movetoabs (0,0) -- (1,1);` 的分支
 - 然后展开到 `\tikz@scan@one@point{\tikz@@moveto}(0,0) -- (1,1);`
 - 到 `\tikz@@moveto{\pgfpointxy{0}{0}} -- (1,1);`，`\tikz@@moveto` 获取 pgf coordinate `\pgfpointxy{0}{0}` 的值，存入 tikz 的内部 dimension，把 tikz 的当前位置挪到 `(0pt, 0pt)`，最后调用 `\tikz@scan@next@command` 继续 parse `-- (1, 1);` 的部分。


[1] 这两个都在 `pgfutil-commen.tex` 里定义，功能和 latex2e 里的 `\@ifnextchar` 和 `\in@` 相同（可以直接看 `texdoc source2e` 也可以看 `texdoc macros2e` 的总结），pgf 因为要跨格式（plaintex, latex, ConTeXt）所以必须自己定义一套工具宏。

**Comment by muzimuzhi** [comment]
理解源码和调试例子时，除了 tex 自带的 tracing [1] 和 `\showXXX` 的功能、通过 warning/error 输出，还可以通过 `unravel` 包逐步展开

```tex
\documentclass{article}
\usepackage{tikz}
\usepackage{unravel}

\begin{document}
\begin{tikzpicture}
  \unravel{\draw (0,0) -- (1,1);}
\end{tikzpicture}
\end{document}
```
在命令行编译上面的例子，按回车可以看到每一步展开的过程和结果。输入 `s10` 表示快进 10 步，输入 `u\tikz@handle` 表示快进到 `\tikz@handle`。不是所有 `\primitive` 都支持，但够用了。

[1] https://tex.stackexchange.com/a/60494

**Comment by muzimuzhi** [comment]
> > 1. 如何分辨一个宏的parameter对应的参数？
> 
> 分辨不了。主要靠文档，没有文档的靠看源码。一个命令，用户看到的是 `\cmd{}{}{}`，内部的实现可能是 `\def\cmd#1{\cmd@i} \def\cmd@i#1{\cmd@ii} \def\cmd@ii#1{...}`。所以 `\cmd` 的 parameter text `#1` 不能代表它完整的用法。
> 
> > 可以大概解释一下`\tikz@scan@one@point`是如何工作的？
> > 可不可以展示一些例子？
> 
> `\tikz@scan@one@point#1<point>` 会 parse 一个 `<point>`，然后调用 `#1{<pgf coordinate>}`。一般 `#1` 是一个有一个参数的宏。

前者有一点点像 functional programming 里的 currying/partial application，后者也许可以看作 handler 或 continuation。只是像，其实都不是，因为 tex 里没有函数。

**Comment by CHEN-z-y** [comment]
非常感谢你的回答！对整体情况有个大概印象了
不过我有一些疑惑：

关于第二个问题：
> 2. `\tikz@@scanexpand` 有一个参数，
            但是在 `\tikz@scan@absolute`的定义中，`\tikz@@scanexpand`却不带参数

这样理解对吗：比如说  进入`\tikz@scan@absolute`定义中的  分支`\else`，
那么“`\let\pgfutil@next=\tikz@@scandexpand`”, 
这时代码运行到`\fi`，紧接着就是“`\pgfutil@next`{#1}”，
这一系列操作是不是相当于利用\pgfutil@next变相实现 `\tikz@@scanexpand{#1}`，
等于说不用把 `{#1}` 写2遍？

**Comment by CHEN-z-y** [comment]
另外，
具有2个参数的`\tikz@scan@options`  
在 `\tikz@scan@@absolute`的定义中  同样也没有跟任何实参。
这又是为什么呢？

`\tikz@scan@@absolute`定义如下：

```tex
\def\tikz@scan@@absolute#1({%
    \pgfutil@ifnextchar[% uhoh... options!
    {\def\tikz@scan@point@recall{#1}\tikz@scan@options}%
    {\tikz@@@scan@@absolute#1(}%
}%

**Comment by muzimuzhi** [comment]
你没理解 `\let` 的语法，可参考 _TeX by Topic_, sec 11.7 Token assignments by `\let` and `\futurelet` [1]. 

从你使用「实参」这个词来看，你可能在用大部分编程语言里的 [applicative-order evaluation](https://sarabander.github.io/sicp/html/1_002e1.xhtml#Applicative-order-versus-normal-order) 模型来理解 tex，这不一定准确。tex 里没有函数，没有处处可见的表达式求值。`\let\a=<token>` 只执行一个操作，让 `\a` 的定义和 `<token>` 相同。在这个过程中 `<token>` 不会展开。

根据 [`\tikz@scan@absolute`](https://github.com/pgf-tikz/pgf/blob/1b7e3ddef23414ff660e269adb0c12d26c152bb6/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex#L5167-L5178) 的定义，
```tex
\def\tikz@scan@absolute#1{%
  \pgfutil@ifnextchar({\tikz@scan@@absolute#1}%)
  {%
    \advance\tikz@expandcount by -1
    \ifnum\tikz@expandcount<0\relax%
      \let\pgfutil@next=\tikz@@scangiveup%
    \else%
      \let\pgfutil@next=\tikz@@scanexpand%
    \fi%
    \pgfutil@next{#1}%
  }%
}%
```

 - 如果是 `\tikz@scan@absolute\cmd(`，next token == `(`, 所以展开到 `\tikz@scan@@absolute\cmd`
 - 如果是 `\tikz@scan@absolute\cmd!` 且 `\tikz@expandcount>0`，则先执行 `\let\pgfutil@next=\tikz@@scanexpand`（这里就是简单地让 `\pgfutil@next` 和 `\tikz@@scanexpand` 的定义相等），再执行 `\pgfutil@next{\cmd}`，综合起来「相当于」执行了 `\tikz@@scanexpand{\cmd}`。

[1] pdf file: https://ctan.org/pkg/texbytopic ，通过发行版安装后可执行 `texdoc topic` 打开。

**Comment by CHEN-z-y** [comment]
OK是这样子！感谢前辈的回答！
让我少走了许多弯路
 
我想彻底弄懂关于宏的一系列问题，
我可以抓住这个机会再问一些问题吗 😄  

有没有一些用到  `\scan@@expand` 的例子呢？

另外，关于参数的问题，
`\tikz@scan@@absolute`定义中对于`\tikz@scan@options`的调用
我还是有点不太明白

> 
> 另外，
> 具有2个参数的`\tikz@scan@options`
> 在 `\tikz@scan@@absolute`的定义中 同样也没有跟任何实参。
> 这又是为什么呢？
> 
> `\tikz@scan@@absolute`定义如下：
> 
> ```
> \def\tikz@scan@@absolute#1({%
>     \pgfutil@ifnextchar[% uhoh... options!
>     {\def\tikz@scan@point@recall{#1}\tikz@scan@options}%
>     {\tikz@@@scan@@absolute#1(}%
> }%
> ```

**Comment by muzimuzhi** [comment]
> 我可以抓住这个机会再问一些问题吗 😄

保持 on-topic 即可。离题时，就可以考虑开新 issue。
> 有没有一些用到 `\scan@@expand` 的例子呢？

如果没找到当前 token 的 handler，通过 `\tikz@@scanexpand` 展开一次这个 token，然后重新 parse，以此循环。最大循环次数为 100，通过 `\tikz@expandcount` 控制（每成功 parse 一个 token，重制它为 100；每展开一次，递减 1）。如果展开 100 次后都找不到对应的 handler，报错 `\tikzerror{Giving up on this path. Did you forget a semicolon?}`.

例子：`\def\x{(0,0)} \draw \x -- (1,0);`，用 `unravel` 查看展开过程，可以用 `u\tikz@scan@next@command` 跳到感兴趣的部分。

> 另外，关于参数的问题，
> `\tikz@scan@@absolute`定义中对于`\tikz@scan@options`的调用
> 我还是有点不太明白

如果下一个 token 是 `[`（这个 token 会被 `\pgfutil@ifnextchar` 吃掉），说明遇到了 `([<options>]<point>)`，暂存那个 recall 的 macro，用 `\tikz@scan@options` parse `[<options>]` 的部分。

例子：`\draw ([yshift=10pt]0,0) -- (1,1);`，用 `unravel` 查看展开过程。

PS：
 - 在本地找到一个之前记录的展开步骤，上传到 [tikz-tikzpicture-expansion.tex](https://github.com/muzimuzhi/latex-expansion/blob/master/tikz-tikzpicture-expansion.tex) 了
 - PR https://github.com/pgf-tikz/pgf/pull/970 修复了一个 `\tikz@expandcount` 未及时重置的 bug  ，感兴趣可以看看。
 - 问答交流无法代替自己动手实践。有工具时可以借助工具，不用执着于「干看代码来完全理解」。

**Comment by CHEN-z-y** [comment]
非常感谢你的回答🙂
我看了你的 `tikz-tikzpicture-expansion.tex`
我把大致流程做成了PDF
不知道这样画可不可以？
（阅读顺序：从左往右）
说实话我对TeX内部的4个主要步骤还是不太清楚😓
我看了TeXbytopic和TeXbook，但还是有很多疑惑。
TeX是先展开再执行，还是说这两者是交替发生的？
[tikz-tikzpicture-expansion 试.pdf](https://github.com/CTeX-org/forum/files/5815891/tikz-tikzpicture-expansion.pdf)

**Comment by muzimuzhi** [comment]
> TeX是先展开再执行，还是说这两者是交替发生的？

 - 正常情况下，是接连发生的。tokenize 一个 token 后，能展开就（tokenize 所需 tokens 后）展开，不能就（tokenize 所需 tokens 后）执行，过程中有问题就报错。这和 C 语言里的「宏」是不同的。于是下面截图里的第二步应该是执行 `\def\@currenvir{tikzpicture}`。强烈建议用 `unravel` 自己试一试，逐步看一看过程。
![image](https://user-images.githubusercontent.com/6376638/104630920-6c021d00-56d6-11eb-87cd-40da66ca26a5.png)
 - 特殊情况下只展开不执行，例如在 `\edef` 的 replacement text 和 `\write` 的参数中。也叫 expansion-only。

一组例子：
 - 如果有 `\def\a{\def\b{bb}}\a`，
   - 先遇到 `\def`，于是执行 `\def\a{\def\b{bb}}`
   - 然后遇到 `\a`，它是宏，于是展开为 `\def\b{bb}`
   - 接着遇到 `\def`，于是执行 `\def\b{bb}`
 - 如果有 `\edef\a{\def\b{bb}}\a`，
   - 先遇到 `\edef`，于是先完全展开 `\def\b{bb}`，再执行 `\edef\a{<展开结果>}`
   - 在完全展开时，先遇到 `\def`，它是不可展开的，跳过；然后是 `\b`，如果它没定义，就报错 "Undefined control sequence"；如果有定义而且是宏，就展开，如果有定义而且不是宏，就按照对应的语法展开或执行。

感觉可以单开问题。看起来是问 tikz 的内部实现，其实是对 tex 的语法等尚有疑问。tex.stackexchange.com 有不少积累的问答，可以用英文关键词搜索并阅读。还可以从通讯 TUGBoat 的[历史文章](https://www.tug.org/TUGboat/Contents/listkeyword.html)里，凭主题找合适的阅读内容。

**Comment by CHEN-z-y** [comment]
OK是这样子😄作为一个编程新手，
很感谢你能抽空回答这些问题！
我有试过unravel，可能没有看仔细，其实
有些时候我也不是很清楚应该跳到哪一步：
我反应比较慢，所以会自己亲手把过程写一遍
我正在读TeXbook和TeXbytopic关于macro的部分，
也有在看stackexchange.com和overleaf上的相关文章。
如果有问题的话我会再开一个issue的。
