### ISSUE TITLE
重新定义 `unicode-math` 中的 `\mathcal` 后无法添加部分重音

### ISSUE THREAD

**Issue by syvshc** [CTeX-org/forum#179]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

先提出我的产生问题的需求. 在使用 `unicode-math` 的过程中, 发现默认的 5 个字体中都不包含默认的 `\mathcal` 的样式, 文中指的默认样式如下
```latex
\documentclass{article}
\begin{document}
    $ \mathcal{DBFT} $
\end{document}
```
![defaultcal.jpg](https://i.loli.net/2021/01/10/eRV4xO3NESXBogu.jpg)

但是默认的 `unicode-math` 宏包的 `\mathcal` 的输出样式与 `\mathscr` 相同
```latex
\documentclass{article}
\usepackage{unicode-math}
\begin{document}
    $ \mathcal{DBFT}, \mathscr{DBFT} $
\end{document}
```
![unimathcal.jpg](https://i.loli.net/2021/01/10/KmflFduQWw9Zyi6.jpg)
于是我在 StackExchange 上搜索到了一个[解决方法](https://tex.stackexchange.com/a/305501/180617), 如下
```latex
\documentclass{article}
\usepackage{unicode-math}
\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}
\begin{document}
$ \mathcal{DBFT}, \mathscr{DBFT} $
\end{document}
```
![unimathsolution.jpg](https://i.loli.net/2021/01/10/GWZpPu91S6Mq5HV.jpg)
但是这样做会产生一个新的问题, 即无法在 `\mathcal{}` 的字上无法添加部分重音(这里的部分是因为我只测试了会用到的 `\tilde` 与 `\hat`)
```latex
\documentclass{article}
\usepackage{unicode-math}
\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}
\begin{document}
$ \tilde{\mathcal{B}} $

% $ \hat{\mathcal{B}} $
\end{document}
```
会产生一个错误提示
```
! Internal error: bad native font flag in `map_char_to_glyph'
```
目前可以使用 `\tilde{\text{$ \mathcal{B} $}}` 这样的方式来处理, 但是这未免看起来有一些蠢.

我的问题是: 有没有方法可以直接使用 `\tilde{\mathcal{B}}` 来在 `\mathcal` 上加重音. 

## 最小工作示例（MWE）

```latex
\documentclass{article}
\usepackage{unicode-math}
\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}
\begin{document}
$ \tilde{\mathcal{B}} $

% $ \hat{\mathcal{B}} $
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
! Internal error: bad native font flag in `map_char_to_glyph'
```

**Comment by tanukihee** [comment]
lua 不会报错，先用 lua 代替吧

**Comment by zepinglee** [comment]
在 unicode 的编码中不区分 `\mathcal` 和 `\mathscr`，这两种的语义也是一样的，具体做成哪种样式取决于字体。不过 SITX 和 XITS 做成了 StylisticSet。下面的例子中四种字体配置都可以编译通过。
```latex
\documentclass{article}
\usepackage{unicode-math}

\setmathfont{XITSMath-Regular.otf}
% \setmathfont{XITSMath-Regular.otf}[StylisticSet=1]
% \setmathfont{STIX2Math.otf}
% \setmathfont{STIX2Math.otf}[StylisticSet=1]

\begin{document}
  $ \mathcal{DBFT}, \mathscr{DBFT} $
  $ \tilde{\mathcal{B}} $
\end{document}
```

**Comment by syvshc** [comment]
> 在 unicode 的编码中不区分 `\mathcal` 和 `\mathscr`，这两种的语义也是一样的，具体做成哪种样式取决于字体。不过 SITX 和 XITS 做成了 StylisticSet。下面的例子中四种字体配置都可以编译通过。
> 
> ```
> \documentclass{article}
> \usepackage{unicode-math}
> 
> \setmathfont{XITSMath-Regular.otf}
> % \setmathfont{XITSMath-Regular.otf}[StylisticSet=1]
> % \setmathfont{STIX2Math.otf}
> % \setmathfont{STIX2Math.otf}[StylisticSet=1]
> 
> \begin{document}
>   $ \mathcal{DBFT}, \mathscr{DBFT} $
>   $ \tilde{\mathcal{B}} \hat{\mathcal{B}} $
> \end{document}
> ```

也就是说我无法通过设置字体的方法在使用 `unicode-math` 时同时得到"默认样式"的 `\mathcal` 与"默认样式"的 `\mathscr` 与 `\tilde{\mathcal{B}`, 是这样吗,

**Comment by stone-zeng** [comment]
LaTeX 默认（的字体 Computer Modern）只有 `\mathcal` 而没有 `\mathscr`，至于 Latin Modern 没有完全按照 Computer Modern 画这几个 glyphs，那只能算做他们的设计选择。

**Comment by stone-zeng** [comment]
> lua 不会报错，先用 lua 代替吧

但是因为 Type1 里面不存在 `MathTopAccentAttachment` 这些信息所以重音符号位置是有偏差的（大概又要处理一下 tfm？）

**Comment by syvshc** [comment]
> LaTeX 默认（的字体 Computer Modern）只有 `\mathcal` 而没有 `\mathscr`，至于 Latin Modern 没有完全按照 Computer Modern 画这几个 glyphs，那只能算做他们的设计选择。

刚去试了一下, 发现把 `mathrsfs` 宏包当成默认设置的了2333, Computer Modern 里确实没有 `\mathscr`, 谢谢了

**Comment by muzimuzhi** [comment]
> 在使用 `unicode-math` 的过程中, 发现默认的 5 个字体中都不包含默认的 `\mathcal` 的样式
> https://github.com/CTeX-org/forum/issues/179#issue-782828852

默认的 5 个字体，具体指哪些？

> 也就是说我无法通过设置字体的方法在使用 `unicode-math` 时同时得到"默认样式"的 `\mathcal` 与"默认样式"的 `\mathscr` 与 `\tilde{\mathcal{B}`, 是这样吗,
> https://github.com/CTeX-org/forum/issues/179#issuecomment-757491635

可以为 `\mathcal` 和 `\mathscr` 指定不同的数学字体。
```tex
\documentclass{article}
\usepackage{unicode-math}
\setmathfont{Latin Modern Math}
\setmathfont[range=\symscr]{XITSMath-Regular.otf}

\begin{document}
\def\test#1{$#1{DBFT, \hat{B}, \tilde{B}}$\par}

\test\mathcal
\test\mathscr
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/104127879-86b75780-539f-11eb-8ded-b3b467af40ae.png)

**Comment by syvshc** [comment]
> > 在使用 `unicode-math` 的过程中, 发现默认的 5 个字体中都不包含默认的 `\mathcal` 的样式
> > [#179 (comment)](https://github.com/CTeX-org/forum/issues/179#issue-782828852)
> 
> 默认的 5 个字体，具体指哪些？
> 
> > 也就是说我无法通过设置字体的方法在使用 `unicode-math` 时同时得到"默认样式"的 `\mathcal` 与"默认样式"的 `\mathscr` 与 `\tilde{\mathcal{B}`, 是这样吗,
> > [#179 (comment)](https://github.com/CTeX-org/forum/issues/179#issuecomment-757491635)
> 
> 可以为 `\mathcal` 和 `\mathscr` 指定不同的数学字体。
> 
> ```
> \documentclass{article}
> \usepackage{unicode-math}
> \setmathfont{Latin Modern Math}
> \setmathfont[range=\symscr]{XITSMath-Regular.otf}
> 
> \begin{document}
> \def\test#1{$#1{DBFT, \hat{B}, \tilde{B}}$\par}
> 
> \test\mathcal
> \test\mathscr
> \end{document}
> ```
> 
> ![image](https://user-images.githubusercontent.com/6376638/104127879-86b75780-539f-11eb-8ded-b3b467af40ae.png)

抱歉, 我想指的是` texdoc unimath-symbols` 中给出的 6 个字体, 写 issue 时误记成5个, 另外, 如果我想指定 Computer Modern 样式 (即 issue 第一张图片中的样式) 的 `\mathcal` 字体并可以直接使用 `\tilde{\mathcal{B}` 添加重音, 是否有解决方法呢

**Comment by muzimuzhi** [comment]
> 至于 Latin Modern 没有完全按照 Computer Modern 画这几个 glyphs，那只能算做他们的设计选择。
> https://github.com/CTeX-org/forum/issues/179#issuecomment-757492180

可以去 TeX-SX 提问，作为 https://tex.stackexchange.com/a/305501 的 follow-up

**Comment by muzimuzhi** [comment]
一些搜索得到的信息
 - 2012 年 7 月，TeX-SX 提问 [1] 报告了 `` ! Internal error: bad native font flag in `map_char_to_glyph' `` 这个问题，当时 xetex 维护者确认是 bug
 - 2014 年 2 月，这个 bug 被提交到 xetex [2]
 - 2019 年 7 月，bug 报告里的例子已经无法复现报错，issue 被关闭。

[1] https://tex.stackexchange.com/q/63244
[2] https://sourceforge.net/p/xetex/bugs/89/

**Comment by syvshc** [comment]
> > 至于 Latin Modern 没有完全按照 Computer Modern 画这几个 glyphs，那只能算做他们的设计选择。
> > [#179 (comment)](https://github.com/CTeX-org/forum/issues/179#issuecomment-757492180)
> 
> > 另外, 如果我想指定 Computer Modern 样式 (即 issue 第一张图片中的样式) 的 `\mathcal` 字体并可以直接使用 `\tilde{\mathcal{B}` 添加重音, 是否有解决方法呢
> 
> 我觉得有，但是我不会。可以去 TeX-SX 提问，作为 https://tex.stackexchange.com/a/305501 的 follow-up

已经在 TeX SX 提问 (https://tex.stackexchange.com/q/578372/180617)

**Comment by SainoNamkho** [comment]
修改了一下xetex，用这个dll替换发行版里的xetex.dll（64位）即可
[xetex-amd64.dll.zip](https://github.com/CTeX-org/forum/files/10178959/xetex-amd64.dll.zip)

**Comment by FvNCCR228** [comment]
参照了 [tex.stackexchange.com/questions/166327](https://tex.stackexchange.com/questions/166327)
注意如果使用 [tex.stackexchange.com/questions/666889](https://tex.stackexchange.com/questions/666889) 中最后一个回答会导致cal字符本体偏移

用了 `mathrlap` (mathtools) 和 `skew` 凑合着用用吧

可以在导言区提前定义部分命令

```
\newcommand{\tildeCalA}[1][]{\adaptcal[8]\tilde{\mathcal{A}}[#1]} % 这里定义可选参数是为了支持数学原子的上下标
```

```
\documentclass{article}
% https://tex.stackexchange.com/questions/166327

\usepackage{mathtools}
\usepackage{unicode-math}

\usepackage{pgffor}% 写test循环用的，不用调用

\setmathfont{Latin Modern Math}
\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}

\NewDocumentCommand\adaptcal{O{3} m m O{}}{%
  \mathrlap{\skew{#1}#2{\phantom{\kern0pt #3}}}{#3}#4%
}

\def\test#1{%
  \foreach \x in {A,...,Z} {%
    $#1{\mathcal{\x}}$,%
  }\par%
}

\newcommand{\tildeCalA}[1][]{\adaptcal[8]\tilde{\mathcal{A}}[#1]}

\begin{document}

% $\hat{\mathcal{A}}$

$\adaptcal\hat{\mathcal{A}}$

\test{\adaptcal\hat}

\test{\adaptcal\bar}

\test{\adaptcal\dot}

\test{\adaptcal\tilde}

$\adaptcal\hat{\mathcal{A}}[_y^t]$

$\adaptcal\hat{\mathcal{A}}[_{\adaptcal[8]\hat{\mathcal{A}}}^{\adaptcal[8]\tilde{\mathcal{A}}}]$

$\tildeCalA[^{\sum_{min}^{max}}_t]$

\end{document}
```

用法 `\adaptcal[<skew>]<accents macro>{\mathcal{<letter>}}[<script>]` `\adaptcal[8]\hat{\mathcal{A}}[_y^t]` A、J的skew建议设置为8

![image](https://github.com/CTeX-org/forum/assets/94803387/a406526d-bf0d-45fc-a3c4-ab9ff9846100)

latex宏包展开这些不太熟练，搞不来，理论上应该可以提前在代码里面设置好不同字母的倾斜度(依照上面图可以看到部分字母还是有错位)，完整代码丢下面，会的朋友没事儿可以看看

```
\documentclass{article}

% https://tex.stackexchange.com/questions/166327

\usepackage{mathtools}
\usepackage{unicode-math}

\usepackage{pgffor}% 写test循环用的，不用调用

% \newtoks\legacymathcodes\legacymathcodes={
% \mathcode`A="7141 \mathcode`B="7142 \mathcode`C="7143
% \mathcode`D="7144 \mathcode`E="7145 \mathcode`F="7146
% \mathcode`G="7147 \mathcode`H="7148 \mathcode`I="7149
% \mathcode`J="714A \mathcode`K="714B \mathcode`L="714C
% \mathcode`M="714D \mathcode`N="714E \mathcode`O="714F
% \mathcode`P="7150 \mathcode`Q="7151 \mathcode`R="7152
% \mathcode`S="7153 \mathcode`T="7154 \mathcode`U="7155
% \mathcode`V="7156 \mathcode`W="7157 \mathcode`X="7158
% \mathcode`Y="7159 \mathcode`Z="715A
% }
% \def\nmathcal#1{\mathcal{\the\legacymathcodes #1}}

\setmathfont{Latin Modern Math}
\DeclareMathAlphabet{\mathcal}{OMS}{cmsy}{m}{n}

\ExplSyntaxOn
\makeatletter
\def\extractparam#1#2{%
  \def\tempmacro{#1}%
  \def\checkmacro{\mathcal}%
  \ifx\tempmacro\checkmacro
    #2%
  \else
    % do nothing
  \fi
}
\makeatother

\newcommand\cmsyCalSkew[1]{%
  \str_case:nnF{#1}{%
      {A}{8}%
      {B}{0.1}%
      {W}{0.02}%
      {J}{0.18}%
  }{0}% Default
}
\ExplSyntaxOff

\NewDocumentCommand\adaptcal{O{3} m m O{}}{%
  % \def\calcode{\extractparam#3}
  % \calcode
  % \cmsyCalSkew{\calcode}
  % \mathrlap{\skew{\calcode}#2{\phantom{\kern0pt #3}}}{#3}#4%
  \mathrlap{\skew{#1}#2{\phantom{\kern0pt #3}}}{#3}#4%
}

\def\test#1{%
  \foreach \x in {A,...,Z} {%
    $#1{\mathcal{\x}}$,%
  }\par%
}

\newcommand{\tildeCalA}[1][]{\adaptcal[8]\tilde{\mathcal{A}}[#1]}

\begin{document}

% $\hat{\mathcal{A}}$

$\adaptcal\hat{\mathcal{A}}$

\test{\adaptcal\hat}

\test{\adaptcal\bar}

\test{\adaptcal\dot}

\test{\adaptcal\tilde}

$\adaptcal\hat{\mathcal{A}}[_y^t]$

$\adaptcal\hat{\mathcal{A}}[_{\adaptcal[8]\hat{\mathcal{A}}}^{\adaptcal[8]\tilde{\mathcal{A}}}]$

$\tildeCalA[^{\sum_{min}^{max}}_t]$


% $\nmathcal{F}$

\end{document
```
