### ISSUE TITLE
CTEX 发行版，中文编译结果不符

### ISSUE THREAD

**Issue by JackQuu** [CTeX-org/forum#181]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [x] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

中文转译的结果不符，字符不对应

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\begin{document}
你好！
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
侼姙！
```
有以下警告

```latex
LaTeX Warning: You have requested package ‘savesym’,
                but the package provides ‘savesymbol’.
```

## 我还做了这些尝试

 调用 xeCJK 宏包并设置 CJK 主字体为 SimSun后结果依然不符 

[test.zip](https://github.com/CTeX-org/forum/files/5859671/test.zip)

**Comment by stone-zeng** [comment]
请确保你的文件是用 UTF-8 编码的。

**Comment by JackQuu** [comment]
保存文件时是设置为UTF-8的。

**Comment by OsbertWang** [comment]
发行版是 ctex 套装，那么你用的编辑器是 winedt 吗？如果是，考虑拿其他的编辑器再查验下文件编码，之后在命令行编译一下。

**Comment by muzimuzhi** [comment]
> 保存文件时是设置为UTF-8的。

上传那个 tex 文件。

**Comment by JackQuu** [comment]
已上传，文件名为 test 。

**Comment by muzimuzhi** [comment]
试试写成 `\documentclass[UTF8]{ctexart}` 呢

**Comment by JackQuu** [comment]
结果还是之前不符的中文字符

**Comment by muzimuzhi** [comment]
> 已上传，文件名为 test 。

从附件里的 `test.log` 看，应该是 CTEX 发行版。不熟悉也用不了这个发行版，帮不上忙。

**Comment by sikouhjw** [comment]
我用 CTeX 2.9.2.164 编译了一下，结果正确
