### ISSUE TITLE
ctexbook 下使用 fancyhdr 宏包的 \leftmark 命令输出与预期不符

### ISSUE THREAD

**Issue by syvshc** [CTeX-org/forum#183]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

在 `57327` 版本的 `fancyhdr` 宏包下配合 `56705` 版本的 `ctex` 下的 `ctexbook` 时, `\leftmark` 命令输出与预期不符.  

## 最小工作示例（MWE）

```latex
\documentclass{ctexbook}
\usepackage{zhlipsum}
\usepackage{fancyhdr}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[OL]{\leftmark}
\fancyhead[ER]{\rightmark}
\begin{document}
    \chapter{第一章}
    \section{第一节}
    \zhlipsum[1-5]
\end{document}
```

（用 XeLaTeX 编译后）输出

![Screenshot 2021-01-27_10-37-51.png](https://i.loli.net/2021/01/27/BodNW69G8x1qEHa.png)

并且给出了一个 warning
```latex
Package ctex Warning: Oops! Command `\ps@fancy' is NOT patchable.
(ctex) 
```

## 附件
这是完整的 `log` 文件
https://paste.ubuntu.com/p/m9rjBmmrgq/

**Comment by zepinglee** [comment]
同 <https://github.com/CTeX-org/ctex-kit/issues/554>，`ctex` 对新版 `fancyhdr` patch 失败造成的。

**Comment by syvshc** [comment]
> 同 [CTeX-org/ctex-kit#554](https://github.com/CTeX-org/ctex-kit/issues/554)，`ctex` 对新版 `fancyhdr` patch 失败造成的。

本地已经回滚 fancyhdr 版本, 等待 ctex 更新, 谢谢
