### ISSUE TITLE
在 `unicode-math` 宏包下如何为希腊字母设置中等宽度的衬线和无衬线字体

### ISSUE THREAD

**Issue by syvshc** [CTeX-org/forum#185]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

**由于对字体知识的不了解, 该问题内可能混淆了很多关于字体的名词.**

首先, 在 `texdoc unicode-math` 的 5.3.1 小节有一处告知:

![image.png](https://i.loli.net/2021/02/09/AFgLR86iE4nfjo9.png)

也就是我无法在默认的字体设置 (latinmodern math) 下使用 medium-weight 的无衬线希腊字母, 同时通过查阅 `texdoc unimath-symbols` 也发现并没有 "sans serif, greek, lowercase/uppercase" 与 "italic sans serif, greek, lowercase/uppercase" 的分类, 那么如果我仍然想使用 medium-weight 的无衬线希腊字母, 并且仍然保留衬线体的希腊字母的选项, 我只能为 `sfup, sfit, bfsfit, bfsfup` 分别设置为无衬线的数学字体, 比如 `FiraMath-Regular.otf`. 

但是, 我需要的 "无衬线中等宽度正体/斜体" 应该被分类到 `sfup, sfit`, 因为我同样还需要 "衬线中等宽度正体/斜体", 即 `up, it` (这里我不知道我有没有说明白), 但是现在的问题是, "无衬线中等宽度正体/斜体" 在 `FiraMath` 中被设置为 `up, it`, 即 `FiraMath` 本身没有提供 "sans serif" 的一系列字体, 那么我想设置 `FiraMath` 的时候就只能使用

```latex
\documentclass{article}
\usepackage{amsmath}
\usepackage[sans-style=italic]{unicode-math}
\setmathfont{latinmodern-math.otf}
\setmathfont[range={up/{greek, Greek}, it/{greek, Greek}}]{FiraMath-Regular.otf}

\begin{document}
    $ \symup{ABCabc\mu}, \symit{ABCabc\mu} $
\end{document}
```
输出了
![image.png](https://i.loli.net/2021/02/09/bvW7VABNY9kH6eo.png)
一旦这样设置我就无法使用 "衬线中等宽度" 的希腊字母. 请问有什么方法可以让我分别设置中等宽度的衬线与无衬线希腊字母吗?

**Comment by muzimuzhi** [comment]
需要反复提及一个长名词时，可以定义新名词（或代称）来简化描述

名词约定
   - a) 衬线……
   - b) 非衬线……
   - c) ...
 
问题描述：我想通过命令 xxx 得到效果 a，命令 xxx 得到效果 b，但是……

**Comment by stone-zeng** [comment]
Unicode 没有定义中等粗细的无衬线希腊字母，但有些字体提供了 Stylistic Set 以供替换，比如 XITS。可以用 Math version 来切换不同字体，但需要注意 `\mathversion` 命令不能用在数学模式里面，所以写起来比较啰嗦：

```tex
\documentclass{article}
\usepackage{amsmath}
\usepackage{unicode-math}
\setmathfont{latinmodern-math.otf}
\setmathfont{XITSMath-Regular.otf}[version=ss, StylisticSet=2]
\newcommand\greeksymsf[1]{\mbox{\mathversion{ss}$#1$}}
\begin{document}
\[ \symup{ABCabc\mu}, \symit{ABCabc\mu} \]
\[ \symup{ABCabc}\greeksymsf{\symup{\mu}}, \symit{ABCabc}\greeksymsf{\symit{\mu}} \]
\end{document}
```

参考：<https://tex.stackexchange.com/questions/321418/greek-sans-serif-math>

**Comment by syvshc** [comment]
> Unicode 没有定义中等粗细的无衬线希腊字母，但有些字体提供了 Stylistic Set 以供替换，比如 XITS。可以用 Math version 来切换不同字体，但需要注意 `\mathversion` 命令不能用在数学模式里面，所以写起来比较啰嗦：
> 
> ```
> \documentclass{article}
> \usepackage{amsmath}
> \usepackage{unicode-math}
> \setmathfont{latinmodern-math.otf}
> \setmathfont{XITSMath-Regular.otf}[version=ss, StylisticSet=2]
> \newcommand\greeksymsf[1]{\mbox{\mathversion{ss}$#1$}}
> \begin{document}
> \[ \symup{ABCabc\mu}, \symit{ABCabc\mu} \]
> \[ \symup{ABCabc}\greeksymsf{\symup{\mu}}, \symit{ABCabc}\greeksymsf{\symit{\mu}} \]
> \end{document}
> ```
> 
> 参考：https://tex.stackexchange.com/questions/321418/greek-sans-serif-math

谢谢曾老师, 顺便有个疑问, 如何去找一个字体的不同 version 和 StylisticSet 的介绍呢? 我在 [STIX 的 github](https://github.com/stipub/stixfonts) 上找到了关于 STIX 的 StylisticSet.  但是, 我没有找到关于 XITS 的这些信息.

**Comment by syvshc** [comment]
@stone-zeng 我用 `\setmathfontface` 简单实现了我的需求, 

```latex
\documentclass{article}
\usepackage{amsmath}
\usepackage[sans-style=italic]{unicode-math}
\setmathfont{latinmodern-math.otf}
\setmathfontface\fira{FiraMath-Regular.otf}

\begin{document}
    $ \fira{\mupmu, \mupGamma, \mitmu, \mitGamma} $
\end{document}
```
![image](https://user-images.githubusercontent.com/38098591/107341822-6e4f6f80-6afa-11eb-8b72-eeb39f667207.png)

使用起来暂时没有发现其他问题

**Comment by stone-zeng** [comment]
> 如何去找一个字体的不同 version 和 StylisticSet 的介绍呢? 

如果文档没写，就要看字体本身的信息了，比如用 [fonttools](https://github.com/fonttools/fonttools)、[FontGoggles](https://fontgoggles.org/) 或者 Glyphs、FontForge 之类的字体编辑软件。

**Comment by syvshc** [comment]
> > 如何去找一个字体的不同 version 和 StylisticSet 的介绍呢?
> 
> 如果文档没写，就要看字体本身的信息了，比如用 [fonttools](https://github.com/fonttools/fonttools)、[FontGoggles](https://fontgoggles.org/) 或者 Glyphs、FontForge 之类的字体编辑软件。

了解了, 谢谢曾老师
