### ISSUE TITLE
今天发布的最新版的texstudio似乎无法设置成中文界面

### ISSUE THREAD

**Issue by workhardyzh** [CTeX-org/forum#187]
进入options把语言设置成zh-cn后关闭设置界面，界面不会变成中文，再回去看，语言又变成了default

**Comment by muzimuzhi** [comment]
（补充一些后续信息）

问题出现在 texstudio 3.0.5，题主后来直接报告给了 https://github.com/texstudio-org/texstudio/issues/1473 。问题已经在 [texstudio 3.1.0](https://github.com/texstudio-org/texstudio/releases/tag/3.1.0) 中修复。
