### ISSUE TITLE
表格形状的长文档如何实现比较好？

### ISSUE THREAD

**Issue by DangeRS2** [CTeX-org/forum#188]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

类似如图所示的表格形状的长文档如何实现比较好？

我能想到的是
\usepackage[showframe]{geometry}
然后在章节前面画横线

各位还有更好的思路吗？

## 最小工作示例（MWE）

![image](https://user-images.githubusercontent.com/49086184/110070223-724a7680-7db4-11eb-9e3b-be14d6702734.png)

## 链接

- TeX.SX:
- GitHub:

**Comment by stone-zeng** [comment]
这种工作并不适合用 LaTeX 做，硬要弄的话就是用 `longtable`，但要注意单元格并不能跨页，所以需要额外处理。

**Comment by sikouhjw** [comment]
用 tikz 去画呢？

**Comment by DangeRS2** [comment]
> 用 tikz 去画呢？

结合showframe和tikz，我想了一个思路。因为这个需求其实很简单，其实就是在main body text上加个框。

```latex
\documentclass[UTF8, a4paper, zihao = -4, fontset = fandol]{ctexart}

\usepackage{zhlipsum}

\usepackage{fancyhdr}
\fancypagestyle{testhdr}{%
	\fancyhf{}
	\fancyfoot[C]{\zihao{5}\thepage}}
\renewcommand{\headrulewidth}{0pt}

\usepackage{tikzpagenodes}
\usepackage{everypage}
\def\drawcode{%
	\tikz [remember picture, overlay] \draw
	(current page text area.south west)
	rectangle
	(current page text area.north east);}
\AddEverypageHook{\drawcode}

\begin{document}

\pagestyle{testhdr}

\section{A}

\zhlipsum[1]

\end{document}
```

结果：
![image](https://user-images.githubusercontent.com/49086184/110192203-91eea700-7e67-11eb-96f7-588b970cdf8e.png)

**Comment by muzimuzhi** [comment]
> 我能想到的是
> \usepackage[showframe]{geometry}
> 然后在章节前面画横线

这个思路就不错
