### ISSUE TITLE
\par在nameformat域不起作用

### ISSUE THREAD

**Issue by DangeRS2** [CTeX-org/forum#189]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 最小工作示例（MWE）

`\par`在如下MWE中的nameformat域不起作用

```latex
\documentclass[UTF8, a4paper, zihao = -4, fontset = fandol]{ctexart}

\usepackage{zhlipsum}

\ctexset{%
	section = {%
		format = \zihao{4}\bfseries\raggedright,
		aftertitle += \rule{\textwidth}{1bp},
		nameformat += \rule{\textwidth}{1bp}\par}
}

\begin{document}

\section{A}

\zhlipsum[1]

\end{document}
```

（用 XeLaTeX 编译后）输出

![image](https://user-images.githubusercontent.com/49086184/110192485-67055280-7e69-11eb-8f60-8bdda95447a5.png)

## 链接

- TeX.SX:
- GitHub:

**Comment by sikouhjw** [comment]
不是在 `nameformat` 里写 `\rule`，是在 `format` 里写。

我还调整了一下间距
```tex
\documentclass[UTF8, a4paper, zihao = -4, fontset = fandol]{ctexart}

\usepackage{zhlipsum}

\ctexset{
	section       = {
		format      = \zihao{4}\bfseries\raggedright\rule{\textwidth}{1bp}\\[-10pt],
		aftertitle  = \\[-15pt]\rule{\textwidth}{1bp},
    number      = \chinese{section},
    name        = {,、},
    aftername   = {},
    afterskip   = 0pt,
    fixskip     = true,
  }
}


\usepackage{fancyhdr}
\fancypagestyle{testhdr}{%
	\fancyhf{}
	\fancyfoot[C]{\zihao{5}\thepage}}
\renewcommand{\headrulewidth}{0pt}

\usepackage{tikzpagenodes}
\usepackage{everypage}
\def\drawcode{%
	\tikz [remember picture, overlay] \draw
	(current page text area.south west)
	rectangle
	(current page text area.north east);}
\AddEverypageHook{\drawcode}

\pagestyle{testhdr}


\begin{document}

\section{立项的背景及意义}

\zhlipsum[1]

\end{document}
```

**Comment by muzimuzhi** [comment]
印象里之前有相关 issue，很可能是在一则 qinglee 或 ruixi 指出我错误的评论里。暂时没搜到。

默认情况，`nameformat` 在 `\hbox{...}` 里使用，即 restricted horizontal mode。在这个模式下 `\par` 自动忽略。

复现例子：
```tex
\documentclass{article}
\begin{document}
  \hbox{a\par b}
\end{document}
```

**Comment by DangeRS2** [comment]
> 印象里之前有相关 issue，很可能是在一则 qinglee 或 ruixizhang 指出我错误的评论里。暂时没搜到。
> 
> 默认情况，`nameformat` 在 `\hbox{...}` 里使用，即 restricted horizontal mode。在这个模式下 `\par` 被忽略，参考 `texdoc texbytopic`, sec. 6.3.1 "Restricted horizontal mode".
> 
> 复现例子：
> 
> ```
> \documentclass{article}
> \begin{document}
>   \hbox{a\par b}
> \end{document}
> ```

那有没有优雅一点方式解决这个问题？我其实就是想在标题前面画一条横线

**Comment by stone-zeng** [comment]
现在 `ctex` 手册的 7.6 节就有个这种东西吧：

![image](https://user-images.githubusercontent.com/18233088/110217421-f1dc6080-7eee-11eb-90fc-c3effc4a7821.png)

**Comment by DangeRS2** [comment]
> 现在 `ctex` 手册的 7.6 节就有个这种东西吧：
> 
> ![image](https://user-images.githubusercontent.com/18233088/110217421-f1dc6080-7eee-11eb-90fc-c3effc4a7821.png)

对，我就是看了这个例子，想这么干来着，发现了\par的问题
