### ISSUE TITLE
siunitx 宏包无法自动在两侧插入空白

### ISSUE THREAD

**Issue by gzxu** [CTeX-org/forum#19]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2018
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

讲道理啊，CTeX会在中英文之间插入空白的，打比方说`第1页`渲染出来应该是`第␣1␣页`的效果，但是`加上\SI{20}{\volt}电压`渲染出来是`加上20␣V␣电压`的效果而不是`加上␣20␣V␣电压`的效果，看上去贼丑了。我记得在哪篇文档讲过这应该是一个Known issue，但我忘了具体是啥。

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\usepackage{siunitx}
\begin{document}
加上\SI{20}{\volt}电压
\end{document}
```

**Comment by stone-zeng** [comment]
相关讨论 <https://github.com/CTeX-org/ctex-kit/issues/392>，总之始终建议在这些地方加上空格（虽然可能在一定程度上违背「内容、样式分离」的原则）。

**Comment by RuixiZhang42** [comment]
我直接引用 Liam0205 啦：

> 结论大致是：技术上实现一个 case 不难。但是有很多的 edge case，所以很难保证完备性。因此，暂时不去实现；同时在 `xeCJK` 层面，中文与西文之间建议手工加上空格。
