### ISSUE TITLE
biblatex 不能在 \AtEndPreamble 中调用

### ISSUE THREAD

**Issue by tanukihee** [CTeX-org/forum#190]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [x] WSL 2 Debian

- TeX 发行版
  - [x] TeX Live 2020
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

biblatex 不能在 `\AtEndPreamble` 中调用

## 最小工作示例（MWE）

```latex
\documentclass{article}
\usepackage{etoolbox}
\AtEndPreamble{\usepackage{biblatex}}
\begin{document}
foo

\end{document}
```
报错一堆，直接提供 log

## 我还做了这些尝试

用 `\ctex_at_end_preamble:n` 就可以了

## 附件

[test.log](https://github.com/CTeX-org/forum/files/6095467/test.log)

**Comment by muzimuzhi** [comment]
1. `\AtEndPreamble` 用的是 hook `begindocument/before`，是在 `\document` 里被使用
2.  `\ctex_at_end_preamble:n` 用的是 hook `env/document/before`，是在 `\begin{document}` 的 `\begin` 被使用

 - 猜测 1 报错是因为 hook `begindocument/before` 被使用得太晚了，具体原因还没看。
 - 根据 2 的信息，手动加入到 hook `env/document/before` 就可以，相关功能是 latex2e 2020/10 加入的，参考文档 `texdoc lthooks`
    ```tex
    \documentclass{article}
    \AddToHook{env/document/begin}{\usepackage{biblatex}}
    
    \begin{document}
      foo	
    \end{document}
    ```

**Comment by muzimuzhi** [comment]
> 报错一堆，直接提供 log

建议在提供 log 文件的同时，总是贴出第一处报错的信息。在你的例子中，它是
```tex
/usr/local/texlive/2020/texmf-dist/tex/latex/biblatex/biblatex.sty:503: Undefined control sequence.
<argument> ...atibility@endpreambleonly \ifnum \blx@hyperref 
                                                  =\thr@@ \else \ifnum \blx@...
l.503   \let\do\noexpand}
```

**Comment by tanukihee** [comment]
https://github.com/plk/biblatex/issues/1107#issuecomment-792232951 https://tex.stackexchange.com/questions/305095/loading-biblatex-from-within-the-atendpreamble-hook

看起来是一个很老的问题了……

**Comment by muzimuzhi** [comment]
放进 `\AtBeginDocument` 不够吗

**Comment by muzimuzhi** [comment]
> 如果要想像 fduthesis 那样让用户决定使用 bibtex 还是 biblatex 的话，可能把 `bib-backend` 放进文档类选项里更好……

也可以试试用配置文件 ，例如通过 `\InputIfFileExists{xxx.cfg}`。配置文件里可以写一些默认注释掉的代码，用户通过解注释来使用它们。载入配置文件后，可以在文档类里写一些条件判断的代码。

**Comment by tanukihee** [comment]
2.5.6 之后，`\ctex_at_end_preamble:n` 也不行了

**Comment by tanukihee** [comment]
https://github.com/CTeX-org/ctex-kit/commit/a12c13380406a4cabef970d9d9aeac08bbcef45b 中，把钩子给改了……

**Comment by muzimuzhi** [comment]
https://github.com/CTeX-org/forum/issues/190#issuecomment-792113492 提到的 `\AddToHook{env/document/begin}{\usepackage{biblatex}}` 仍然有效？

**Comment by tanukihee** [comment]
> https://github.com/CTeX-org/forum/issues/190#issuecomment-792113492 提到的 `\AddToHook{env/document/begin}{\usepackage{biblatex}}` 仍然有效？

嗯，仍然有效的
