### ISSUE TITLE
如何实现类似未被ctex封装前的appendix功能？

### ISSUE THREAD

**Issue by wxyinucas** [CTeX-org/forum#192]
比如现在有一个tex文件如下，中间我需要section计数器重新计数
```
\documentclass[hyperref]{ctexart}

\begin{document}
    \makeatletter
    \tableofcontents

    \section{一}
    \appendix
    \section{二}
\end{document}
```
这样的到的toc文件是
```
\contentsline {section}{\numberline {1}一}{1}{section.1}%
\contentsline {section}{\numberline {A}二}{1}{appendix.A}%
```

请问如何不用\appendix命令实现类似的功能？
我自己仿写的结果是
```
\documentclass[hyperref]{ctexart}

\begin{document}
    \makeatletter
    \tableofcontents

    \section{一}
    \setcounter{section}{0}
    \gdef\thesection{\@Alph\c@section}
    % \appendix
    \section{二}
\end{document}
```
但这这样生成的toc文件是错误的
```
\contentsline {section}{\numberline {1}一}{1}{section.1}%
\contentsline {section}{\numberline {A}二}{1}{section.1}%
```
最后会指向相同的超链接。

谢谢！

**Comment by muzimuzhi** [comment]
> 请问如何不用\appendix命令实现类似的功能？

为什么需要避免使用 `\appendix` 呢？似乎还有一部分问题的背景没有交代。最简单的绕过办法，是给它取个别名：
```tex
\documentclass{ctexart}
\usepackage{hyperref}

\AtBeginDocument{%
  \let\MyAppendix\appendix
}

\begin{document}
\tableofcontents

\section{一}
\newpage % 为了便于判别超链接跳转目标的正确与否

\MyAppendix
\section{二}
\end{document}
```

> 我自己仿写的结果是 [...] 但这这样生成的toc文件是错误的 [...] 最后会指向相同的超链接。

 - `ctex` 层面，参考 `texdoc ctex`, sec. 11, "对旧版本的兼容性"，具体在 sec. 11.2
    > `hyperref` 选项过时，因兼容性保留，功能是在导言区末尾载入 `hyperref` 宏包。
- `hyperref` 层面，它重定义了 `\appendix`，见[源码](https://github.com/latex3/hyperref/blob/0a07a1063ac083ae66dc985804c23432692fdcc9/hyperref.dtx#L10608-L10631)，和带注释的文档 `texdoc hyperref.pdf`, sec. 29,  "Automated LaTeX hypertext cross-references"。

**Comment by wxyinucas** [comment]
@muzimuzhi 参考了hyperref的源码，问题解决了～谢谢！
