### ISSUE TITLE
公式编号使用中文括号

### ISSUE THREAD

**Issue by zepinglee** [CTeX-org/forum#193]
某校要求数学公式的编号使用中文括号，所以我尝试了修改 `amsmath` 的 `\tagform@`，但是使用 `\eqref` 会导致与前方中文的间距过窄。

有什么办法修改为像「公式（2）」的样式？

<img width="527" alt="Screen Shot 2021-04-09 at 01 53 53" src="https://user-images.githubusercontent.com/12290822/114073969-75b2af80-98d6-11eb-8ca4-88367b546b6a.png">

```latex
\documentclass{ctexart}
\usepackage{amsmath}
\makeatletter
% \def\maketag@@@#1{\hbox{\m@th\normalfont#1}}
% \def\tagform@#1{\maketag@@@{(\ignorespaces#1\unskip\@@italiccorr)}}
\def\tagform@#1{\maketag@@@{（\ignorespaces#1\unskip\@@italiccorr ）}}
\begin{document}
公式\eqref{eq1}示例公式（2）示例
\begin{equation}
  a = b \label{eq1}
\end{equation}
\end{document}
```

**Comment by gxkkkkkk** [comment]
\renewcommand{\eqref}[1]{公式（\ref{#1}）}
