### ISSUE TITLE
用 tocloft 宏包设置目录间距的一点疑惑

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#194]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

用 tocloft 宏包设置目录间距，发现编号与标题中的间距看不懂，不是「一个西文空格」宽，不知道从哪来的间距

## 最小工作示例（MWE）

```latex
\documentclass{ctexbook}
\usepackage[titles]{tocloft}
\setlength\cftchapnumwidth{3\ccwd}
\newlength{\secjuli}
\settowidth{\secjuli}{\cftsecfont 1.1}
\setlength\cftsecnumwidth{\secjuli}
\newlength{\subsecjuli}
\settowidth{\subsecjuli}{\cftsubsecfont 1.1.1}
\setlength\cftsubsecnumwidth{\subsecjuli}
\begin{document}
  \tableofcontents
  \chapter{测试 english}
  \section{测试 english}
  \subsection{测试 english}
\end{document}
```

（用 XeLaTeX 编译后）输出

![222](https://user-images.githubusercontent.com/49770925/116768394-d9a93d80-aa68-11eb-8115-534ca61bb3b0.png)

**Comment by muzimuzhi** [comment]
根据 [ctex 的实现](https://github.com/CTeX-org/ctex-kit/blob/5bdb9cbaca6467e92ec9bd7726e2b3bdd1943303/ctex/ctex.dtx#L8706-L8720)，插入的间距宽度为当前字号的一半。这个间距，确实比空格要宽。

**Comment by sikouhjw** [comment]
> 
> 
> 根据 [ctex 的实现](https://github.com/CTeX-org/ctex-kit/blob/5bdb9cbaca6467e92ec9bd7726e2b3bdd1943303/ctex/ctex.dtx#L8706-L8720)，插入的间距宽度为当前字号的一半。这个间距，确实比空格要宽。

那要怎么改这个距离变成一个空格的距离？

**Comment by muzimuzhi** [comment]
```tex
\documentclass{ctexbook}
\usepackage{tocloft}

\settowidth{\cftsecnumwidth}{\cftsecfont 1.1}

\makeatletter
\ExplSyntaxOn
% renew \CTEX@toc@width@n, add width of a space to \@tempdima
\cs_set_protected:Npn \CTEX@toc@width@n #1
  {
    \hbox_set:Nn \l__ctex_tmp_box {#1\space}
    \dim_set:Nn \@tempdima
      {
        \box_wd:N \l__ctex_tmp_box
      }
  }
\ExplSyntaxOff
\makeatother

\begin{document}
  \tableofcontents
  \chapter{测试 english}
  \section{测试 english}
  \subsection{测试 english}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/116773825-b0010e00-aa8a-11eb-8da1-c120fe389c27.png)

**Comment by sikouhjw** [comment]
问题解决，感谢

**Comment by tanukihee** [comment]
为什么要设置成半个汉字宽，全宽或者一个空格宽都能理解（
