### ISSUE TITLE
在 `ctexbeamer` 文档类下使用 `$ f' $` 会出现字符重叠

### ISSUE THREAD

**Issue by syvshc** [CTeX-org/forum#196]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

在 `ctexbeamer` 文档类下使用 `$ f' $` 会出现字符重叠, 下面是 MWE

## 最小工作示例（MWE）
均使用 **`xelatex`** 编译
使用衬线体
```latex
\documentclass{ctexbeamer}
\usefonttheme{serif}
% \usepackage{unicode-math}
% \setmathfont{Latin Modern Math}
% \setmathfont{Fira Math}
\begin{document}
    $ f'(\xi_{f'}) $ 
\end{document}
```
![image](https://user-images.githubusercontent.com/38098591/118347288-a8eefb00-b574-11eb-8534-fe6f66dea3b6.png)

使用无衬线体
```latex
\documentclass{ctexbeamer}
% \usefonttheme{serif}
% \usepackage{unicode-math}
% \setmathfont{Latin Modern Math}
% \setmathfont{Fira Math}
\begin{document}
    $ f'(\xi_{f'}) $ 
\end{document}
```
![image](https://user-images.githubusercontent.com/38098591/118347302-c8862380-b574-11eb-8242-67c961ede50f.png)

而如果加上 `unicode-math`, 那么衬线体和无衬线体都不会有问题

`Latin Modern Math` 
![image](https://user-images.githubusercontent.com/38098591/118347513-88c03b80-b576-11eb-8793-e518f2602c37.png)
`Fira Math`
![image](https://user-images.githubusercontent.com/38098591/118347539-bb6a3400-b576-11eb-8280-c4487cf6840f.png)

## 链接

- TeX.SX:
- GitHub:

**Comment by syvshc** [comment]
在另外的测试中, 发现可能是 `xelatex` 编译方式引起的, 仅以无衬线体为例
```latex
\documentclass{beamer}
% \usefonttheme{serif}
\begin{document}
    $ f'(\xi_{f'}) $ 
\end{document}
```
使用 `pdflatex` 编译:
![image](https://user-images.githubusercontent.com/38098591/118347652-7561a000-b577-11eb-8b69-523bda5af8e2.png)

使用 `xelatex` 编译:
![image](https://user-images.githubusercontent.com/38098591/118347646-6d096500-b577-11eb-9d53-bfaa09cc1801.png)

**Comment by muzimuzhi** [comment]
已知问题，见 https://github.com/josephwright/beamer/issues/375
