### ISSUE TITLE
设置了 `\defaultCJKfontfeatures` 后，思源宋体中的省略号没有垂直居中

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#198]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

设置了 `\defaultCJKfontfeatures` 后，思源宋体中的省略号没有垂直居中

## 最小工作示例（MWE）

```latex
\documentclass{article}
\usepackage{xeCJK}
\defaultCJKfontfeatures{Mapping=fullwidth-stop}
\setCJKmainfont{Source Han Serif SC SemiBold}
\begin{document}
  测试……测试
\end{document}
```

**Comment by sikouhjw** [comment]
（自问自答）
@zepinglee 在 tg 群里回答了：
> 我想起来了，思源的省略号默认是居下的，xeCJK 默认有个 `\defaultCJKfontfeatures{Script=CJK}`，这个 feature 会将省略号居中。而你设置 `\defaultCJKfontfeatures{Mapping=fullwidth-stop}` 相当于把 `Script=CJK` 去掉了

**Comment by sikouhjw** [comment]
完整代码：
```latex
\documentclass{article}
\usepackage{xeCJK}
\defaultCJKfontfeatures{Mapping=fullwidth-stop,Script=CJK}
\setCJKmainfont{Source Han Serif SC SemiBold}
\begin{document}
  测试……测试
\end{document}
```

**Comment by muzimuzhi** [comment]
参考 `\defaultCJKfontfeatures` 的[定义方式](https://github.com/CTeX-org/ctex-kit/blob/5bdb9cbaca6467e92ec9bd7726e2b3bdd1943303/xeCJK/xeCJK.dtx#L7246-L7249)，可以自定义一个 `\addDefaultCjkFontFeatures` 命令，只增加字体设置。

```tex
\documentclass{article}
\usepackage{xeCJK}

\ExplSyntaxOn
\makeatletter

\NewDocumentCommand \addDefaultCjkFontFeatures { m }
  { \clist_gput_right:Nn \g__xeCJK_default_features_clist {#1} }
\@onlypreamble \addDefaultCjkFontFeatures

\makeatother
\ExplSyntaxOff


% \defaultCJKfontfeatures{Mapping=fullwidth-stop} % 对照组
\addDefaultCjkFontFeatures{Mapping=fullwidth-stop}
\setCJKmainfont{Source Han Serif SC SemiBold}

\begin{document}
  测试……测试
\end{document}
```
