### ISSUE TITLE
从 visio 复制到 word 里的图片，在打印的时候图片字体发生了变化

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#199]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- word 2019
- visio 2016

## 描述问题

（虽然我知道这不是 latex 问题，但感觉这个跟 pdf、字体有关，就来这问了）
在 visio 中画好图，设置好文字，然后全选复制粘贴到 word 中，再输出 pdf，然后去打印店打印的时候发现图片里的字体变了（从 tnr 变成了无衬线的一个字体），用 Acrobat Reader DC 检查 pdf 中是否嵌入了字体，发现也嵌入了，不知道该怎么办了
![1](https://user-images.githubusercontent.com/49770925/120262922-42384400-c2cd-11eb-9b3b-8e8abcb14180.jpg)

## 最小工作示例（MWE）

[mwe.zip](https://github.com/CTeX-org/forum/files/6573159/mwe.zip)

**Comment by sikouhjw** [comment]
目前解决方法：
- 将 pdf 再用虚拟打印机打印成位图，不过这样会让文件非常大
- visio 输出 svg 再插入 word，再剪裁到合适大小

都好麻烦……

**Comment by muzimuzhi** [comment]
> 用 Acrobat Reader DC 检查 pdf 中是否嵌入了字体，发现也嵌入了

Times New Roman 没嵌入，Adobe Reader 显示的结果也是这样

```
$ pdffonts main.pdf
Fontconfig warning: ignoring UTF-8: not a valid region tag
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
BCDEEE+DengXian                      TrueType          WinAnsi          yes yes no      12  0
TimesNewRomanPS-ItalicMT             TrueType          WinAnsi          no  no  no       7  0
TimesNewRomanPSMT                    TrueType          WinAnsi          no  no  no      10  0
```

**Comment by sikouhjw** [comment]
> 
> 
> > 用 Acrobat Reader DC 检查 pdf 中是否嵌入了字体，发现也嵌入了
> 
> Times New Roman 没嵌入，Adobe Reader 显示的结果也是这样
> 
> ```
> $ pdffonts main.pdf
> Fontconfig warning: ignoring UTF-8: not a valid region tag
> name                                 type              encoding         emb sub uni object ID
> ------------------------------------ ----------------- ---------------- --- --- --- ---------
> BCDEEE+DengXian                      TrueType          WinAnsi          yes yes no      12  0
> TimesNewRomanPS-ItalicMT             TrueType          WinAnsi          no  no  no       7  0
> TimesNewRomanPSMT                    TrueType          WinAnsi          no  no  no      10  0
> ```

啊……我可能没分清嵌没嵌入

图片
![图片](https://user-images.githubusercontent.com/49770925/120284747-29408a80-c2ef-11eb-9bfc-db331c63a152.png)

自己写的测试文件
![图片](https://user-images.githubusercontent.com/49770925/120284837-4412ff00-c2ef-11eb-8b69-0fb3827f6ad3.png)

确实不一样，是我看的不仔细。

**Comment by sikouhjw** [comment]
后续的测试：将 word 选项改成「将字体嵌入文件」，输出的 pdf 依旧没有嵌入字体，看来是 visio 或者是 visio 在复制进 word 的时候出的问题。
