### ISSUE TITLE
如何在 XeTeX 中使用 CID 调用字符

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/forum#20]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 描述

在 LuaTeX 中，利用 `luatexja` 附带的 `luatexja-otf` 宏包可以使用 `\CID` 和 `\UTF` 命令：

```latex
% lualatex 编译
\documentclass{ctexart}
\usepackage{luatexja-otf}
\setCJKmainfont{KozMinPr6N-Regular.otf}

\begin{document}
森\UTF{9DD7}外と内田百\UTF{9592}とが\UTF{9AD9}島屋に行く。

\CID{7652}飾区の\CID{13706}野家，\CID{1481}城市，葛西駅，高崎と\CID{8705}\UTF{FA11}
\end{document}
```

这几个命令继承自 upTeX。那么，在 XeTeX 中是否有方法直接根据 CID 调用某个 glyph 呢？

## 链接

- [Insert characters via CID in XeTeX](https://tex.stackexchange.com/q/482446)

**Comment by clerkma** [comment]
可以使用下面的代码：
```latex
\documentclass{article}
\usepackage{iftex}
\ifXeTeX
\usepackage{fontspec}
\setmainfont{KozMinPr6N-Regular.otf}
\def\UTF#1{\char"#1}
\def\CID#1{\XeTeXglyph#1}
\fi
\ifLuaTeX
\usepackage{luatexja-fontspec}
\usepackage{luatexja-otf}
\setmainjfont{KozMinPr6N-Regular.otf}
\fi
\begin{document}
\ifXeTeX\texttt{XeTeX}\fi\ifLuaTeX\texttt{LuaTeX}\fi


森\UTF{9DD7}外と内田百\UTF{9592}とが\UTF{9AD9}島屋に行く。

\CID{7652}飾区の\CID{13706}野家，\CID{1481}城市，葛西駅，高崎と\CID{8705}\UTF{FA11}
\end{document}

```
效果如下：
![0](https://user-images.githubusercontent.com/8791213/55586908-b5c97f80-575c-11e9-84fc-7a8905c7c033.png)
![1](https://user-images.githubusercontent.com/8791213/55586917-bb26ca00-575c-11e9-8922-42362551ded3.png)

**Comment by hushidong** [comment]
awesome！！

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png&name=hzzmail&uid=hzzmail%40sjtu.org&ftlId=3&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Ahzzmail%40sjtu.org%22%5D>
[https://mail-online.nosdn.127.net/qiyelogo/defaultAvatar.png]
hzzmail
邮箱：hzzmail@sjtu.org


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制

在2019年04月05日 04:40，Clerk Ma<mailto:notifications@github.com> 写道：

可以使用下面的代码：

\documentclass{article}

\usepackage{iftex}

\ifXeTeX

\usepackage{fontspec}

\setmainfont{KozMinPr6N-Regular.otf}

\def\UTF#1{\char"#1}

\def\CID#1{\XeTeXglyph#1}

\fi

\ifLuaTeX

\usepackage{luatexja-fontspec}

\usepackage{luatexja-otf}

\setmainjfont{KozMinPr6N-Regular.otf}

\fi

\begin{document}

\ifXeTeX\texttt{XeTeX}\fi\ifLuaTeX\texttt{LuaTeX}\fi





森\UTF{9DD7}外と内田百\UTF{9592}とが\UTF{9AD9}島屋に行く。



\CID{7652}飾区の\CID{13706}野家，\CID{1481}城市，葛西駅，高崎と\CID{8705}\UTF{FA11}

\end{document}



效果如下：
[0]<https://user-images.githubusercontent.com/8791213/55586908-b5c97f80-575c-11e9-84fc-7a8905c7c033.png>
[1]<https://user-images.githubusercontent.com/8791213/55586917-bb26ca00-575c-11e9-8922-42362551ded3.png>

**Comment by stone-zeng** [comment]
问题在于 `\XeTeXglyph` 用的是 GID，但有很多字体的 GID 跟 CID 并不一样：

![image](https://user-images.githubusercontent.com/18233088/55609780-22bc3400-57b4-11e9-8839-781f523e03b5.png)

甚至于同样是游明朝，mac 下面的和 office 自带的还有区别。

TeX.SX 上面 [egreg 给出的方法](https://tex.stackexchange.com/a/482461/) 是靠 cidmap 转到 unicode 码位，但显然变体就被废掉了。而且有些 CID 似乎没有对应的 unicode 码位。

所以有没有什么办法可以搞到 CID 到 GID 的映照呢？

**Comment by clerkma** [comment]
其实，你对CID的认识可能不是特别完整。

- CID，也就是Character Identifier font，规定了字符顺序和glyph顺序
- 针对字体曲线格式为CFF的，如CFF内的标识符是Adobe-Japan1-6/7的，那么所谓cid和gid是相同的
- 针对字体曲线格式为TrueType活CFF内部标识符非Adobe-Japan1-6/7的，那么基本不存在CID的概念
- 之所以说基本不存在，是因为有一个例外，TrueType也可以做到有CID支持，见TrueType Reference的[gcid](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6gcid.html)表
- 不过，macOS下面的带gcid表的字体基本都被移除了，一个例外是PingFang.ttc。不过里面的表的tag是cidg（而且CID只有Adobe-GB1-2和Adobe-CNS1-0）。macOS下的日文字体并不带gcid或cidg表，而是带IVS支持的cmap表。

所以，结论就是：只有Adobe-Japan1-6/7才能正确跟CID index配合使用。
对于其他的字体可以使用GSUB的一些feature或相关IVS获取相关glyph。
 
还有就是，需要强调的一点，就是CID是PostScript时代的产物。
有时候看起来很直观很好用。但是会出现一些移植性的问题。
甚至OpenType内其实也不强调CID概念。

所以我不是特别推荐使用CID概念。日本社区这么做有历史惯性的原因在。
现在还是推荐使用OpenType的featur来实现所要的glyph。
