### ISSUE TITLE
便携版 TeXLive2021 修改盘符后无法使用 TeXLive 自带字体

### ISSUE THREAD

**Issue by syvshc** [CTeX-org/forum#200]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live  2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

我在u盘里安装了texlive2021，当时的盘符是`E`，现在由于某些原因盘符变成了`F`, TeX 相关的功能(xelatex, latexmk)等都可以正常使用，但是 fc-cache 中的路径还保留着E盘的信息，无法写入F盘的缓存
![image](https://user-images.githubusercontent.com/38098591/122003857-35940f80-cde6-11eb-9998-018f45014737.png)
这导致我无法使用部分 TeXLive 自带字体，如 `Fira Math`，`Fira Sans` 等，但是默认的 `computer modern` 可以正常使用，其他的字体未做测试。
我检查了 `TEXMFROOT` 中的值，为 `F:/texlive/2021`，请问应该修改什么内容才可以将 TeXLive 中的字体加入字体缓存呢
## 最小工作示例（MWE）
```latex
\documentclass{article}
\usepackage{unicode-math}
\setmathfont{Fira Math}
\begin{document}
    $ a^2 $ 
\end{document}
```
报错为
```
! Package fontspec Error: The font "Fira Math" cannot be found.

For immediate help type H <return>.
 ...

l.4 \begin
          {document}
?
```
```latex
\documentclass{article}
\usepackage{fontspec}
\setsansfont{Fira Sans}
\begin{document}
    \sffamily Hi
\end{document}
```
报错为
```
! Package fontspec Error: The font "Fira Sans" cannot be found.
For immediate help type H <return>.
 ...

l.4 \begin
          {document}
?
```

**Comment by CamuseCao** [comment]
请检查 `texlive/texmf-var/fonts/conf/texlive-fontconfig.conf` 里的内容，如果发现不对做相应的修改，再刷新字体缓存试试。

**Comment by syvshc** [comment]
> 请检查 `texlive/texmf-var/fonts/conf/texlive-fontconfig.conf` 里的内容，如果发现不对做相应的修改，再刷新字体缓存试试。

我这里并没有该文件，我的 `texlive` 文件夹中有 `2021` 与 `texmf-local` 两个文件夹，而 `2021/texmf-var/fonts/conf` 中并没有该文件，
![image](https://user-images.githubusercontent.com/38098591/122007347-6d04bb00-cdea-11eb-9a9f-688241d67224.png)

**Comment by syvshc** [comment]
> 请检查 `texlive/texmf-var/fonts/conf/texlive-fontconfig.conf` 里的内容，如果发现不对做相应的修改，再刷新字体缓存试试。

我修改了 `texlive/2021/texmf-var/fonts/conf/fonts.conf` 中的值，问题解决了
