### ISSUE TITLE
编译失败：Undefined control sequence. \sys_if_output_pdf:TF

### ISSUE THREAD

**Issue by ShivangSong** [CTeX-org/forum#201]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\begin{document}
    你好 \LaTeX
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
d:/TeXLive/texlive/2021/texmf-dist/tex/latex/ctex/ctexart.cls:136: Undefined control sequence.
l.136 \sys_if_output_pdf:TF
```

## 链接

- TeX.SX:
- GitHub:https://github.com/CTeX-org/forum/issues/149

## 我还做了这些尝试

我升级完了所有宏包，使用的是bjtu的源，并且命令行运行了fmtutil-sys --all --force。

**Comment by stone-zeng** [comment]
不能复现，请上传一下 log 文件。

另外也可以再试一下 #149 提到的 `tlmgr install --reinstall latex l3kernel` 之类的办法。

**Comment by ShivangSong** [comment]
命令行执行`tlmgr install --reinstall latex l3kernel`失败了，downloading did not succeed。
[test.log](https://github.com/CTeX-org/forum/files/6684269/test.log)

**Comment by Liam0205** [comment]
@ShivangSong try it again.

**Comment by stone-zeng** [comment]
现在最新的版本号是

```
LaTeX2e <2021-06-01> patch level 1
L3 programming layer <2021-06-18>
```

但你给的 log 里面显示

```
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-05-11>
```

所以还是没更新好。

换个源再试试？

**Comment by ShivangSong** [comment]
![image](https://user-images.githubusercontent.com/63501298/122712137-02de9100-d296-11eb-9470-6d59b590f958.png)
可是我用`texdoc expl3`打开的日期是6.18最新的。

**Comment by ShivangSong** [comment]
这个问题我上次更新宏包时也出现了，当时清华源太差了，所以换到了北交源，并且上次运行了`fmtutil-sys --all --force`之后就能正常编译了，请问这是我装的TeXLive出现问题了吗？

**Comment by stone-zeng** [comment]
`expl3` 代码实际上已经被 dump 进了 LaTeX 内核，你的 log 里面还有另一个报错：

```tex
(d:/TeXLive/texlive/2021/texmf-dist/tex/latex/l3kernel/expl3.sty
Package: expl3 2021-06-18 L3 programming layer (loader) 


! LaTeX3 Error: Mismatched LaTeX support files detected.
(LaTeX3)        Loading 'expl3.sty' aborted!
(LaTeX3)        
(LaTeX3)        The L3 programming layer in the LaTeX format
(LaTeX3)        is dated 2021-05-11, but in your TeX tree the files require
(LaTeX3)        at least 2021-06-18.

For immediate help type H <return>.
 ...                                              
                                                  
l.77      \ExplLoaderFileDate{expl3.sty}}
                                         %

The cause seems to be an old format file in the user tree.
LaTeX found these files:
 - c:/Users/Administrator/.texlive2021/texmf-var/web2c/xetex/xelatex-dev.fmt 
 - d:/TeXLive/texlive/2021/texmf-var/web2c/xetex/xelatex-dev.fmt 
Try deleting the file in the user tree then run LaTeX again.
LaTeX will abort loading the incompatible support files but this may lead to
later errors. Please ensure that your LaTeX format is correctly regenerated.


)
```

尽管这个包是新的，但你的 format 文件还是旧的。

> 当时清华源太差了，所以换到了北交源

每个源不保证都同步，建议再更新一下。安装出错的话，每次 `tlmgr install` 会有提示，然后加上 `--reinstall` 把提示有问题的包再装一遍，直到装成功为止。

**Comment by ShivangSong** [comment]
[tlmgr-commands.log](https://github.com/CTeX-org/forum/files/6684464/tlmgr-commands.log)
我又换了清华源，`tlmgr update --self --all`和`tlmgr install --reinstall latex l3kernel`都成功了，但是`fmtutil-sys --all --force`还是失败，输出disabled formats: 5。

**Comment by muzimuzhi** [comment]
> 但是`fmtutil-sys --all --force`还是失败，输出disabled formats: 5。

有更完整的输出内容（`stdout`）吗？

**Comment by ShivangSong** [comment]
上面上传了tlmgr-commands.log，是这个吗？

**Comment by muzimuzhi** [comment]
可以算。第 95749 行开始，可以看到
```
fmtutil [INFO]: log file copied to: d:/texlive/texlive/2021/texmf-var/web2c/pdftex/csplain.log
fmtutil [INFO]: d:/texlive/texlive/2021/texmf-var/web2c/pdftex/csplain.fmt installed.
fmtutil [WARNING]: you have a shadowing format dump in TEXMFVAR for pdftex/pdftex!!!
```

没怎么搜到和这个 warning 相关的信息，`tinyTeX` 下有一个[类似的 issue](https://githubmemory.com/repo/yihui/tinytex/issues/309)，看起来和你遇到的问题不同。

（可能会坏事）把整个 `d:/texlive/texlive/2021/texmf-var/web2c` 目录先备份，然后再删了试试？

**Comment by ShivangSong** [comment]
首先谢谢各位的答复。我这边……还是不行，我想我还是有时间重装一下TeXLive吧。

**Comment by OsbertWang** [comment]
重装的话，记得也清理下用户文件夹下的 `.texlive`

**Comment by ShivangSong** [comment]
感谢各位，今天晚上有时间重装了`TeXLive`，已成功编译。
![image](https://user-images.githubusercontent.com/63501298/124938930-4c233480-e03b-11eb-9d0b-48d28506f4e5.png)
