### ISSUE TITLE
如何旋转并改变页面纸张大小？

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#202]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

我校的封面要求为 A3+横置页面，所以要临时更改页面的尺寸，我在 `geometry` 上找到 `\newgeometry`，然而 `\newgeometry` 不能改变与 `papersize` 有关的参数，该怎么做才能实现呢？

或者换一种思路，仅让页面横置，纸张大小不变，改变内容的字体大小为原来的一半？

**Comment by muzimuzhi** [comment]
相似问题：[https://tex.stackexchange.com/q/6834](Change paper size in mid-document)

**Comment by sikouhjw** [comment]
> 
> 
> 相似问题： [Change paper size in mid-document](https://tex.stackexchange.com/q/6834)

感谢，解决了
