### ISSUE TITLE
怎样调整英文字体大小？

### ISSUE THREAD

**Issue by nuuuuuuuuut** [CTeX-org/forum#203]
使用elegantnote模板，使用fontsize只能调整中文字体大小，英文字体无法调整

**Comment by sikouhjw** [comment]
这不是 MWE

**Comment by nuuuuuuuuut** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    不好意思，我不太明白MWE的意思……
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                201911130216
                            
                            
                                
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年7月1日 ***@***.***> 写道： 




这不是 MWE



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by sikouhjw** [comment]
能够编译的最小代码

**Comment by nuuuuuuuuut** [comment]
`\documentclass[cn,blue,screen]{elegantnote}

\begin{document}
	\section{\fontsize{16pt}{20pt}问题}
	\subsection{\fontsize{16pt}{20pt}问题}
	\fontsize{16pt}{24pt}alpha内容%中英文字体大小不同
\end{document}`

**Comment by sikouhjw** [comment]
`texdoc lshort-zh-cn`, sec 5.1.2
> 如果不是在导言区，`\fontsize` 的设定需要 `\selectfont` 命令才能立即生效，而表 5.2 的字号设定都是立即生效的。

**Comment by nuuuuuuuuut** [comment]
那如果在导言区应该怎样设置标题与正文的字体呢

**Comment by nuuuuuuuuut** [comment]
而且章节序号的大小似乎没有办法通过\selectfont解决
`	\subsection{\fontsize{16pt}{20pt}\selectfont 问题}`

**Comment by sikouhjw** [comment]
> 
> 
> 那如果在导言区应该怎样设置标题与正文的字体呢

请你去读 `texdoc lshort-zh-cn`

**Comment by sikouhjw** [comment]
> 
> 
> 而且章节序号的大小似乎没有办法通过\selectfont解决
> ` \subsection{\fontsize{16pt}{20pt}\selectfont 问题}`

这样做是不对的，去看 `texdoc ctex` 中的 `\ctexset`
