### ISSUE TITLE
在align环境下使用scalebox缩小字体后，如何使行距也跟着缩小呢？

### ISSUE THREAD

**Issue by CHEN-z-y** [CTeX-org/forum#204]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [ ] TeX Live 
  - [x] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

我希望将等式的证明过程藏在等式内部，
并且将等号放在每一行的中间，
这样放大 PDF 即可查看答案。
但是我发现：使用`\scalebox`后，
行距并不会跟着变化。
想问下：不知道有没有什么命令可以自动调整行距

附件内部也含有问题描述。

## 最小工作示例（MWE）

最小工作示例位于附件内，

用 XeLaTeX 编译后，输出无错误。

## 链接

- zhihu: [在align环境下使用scalebox缩小字体后，如何使行距也跟着缩小呢？](https://www.zhihu.com/question/469765958)

## 我还做了这些尝试

我查阅了mathtools宏包手册，不知道是否有遗漏

## 附件

[附件.zip](https://github.com/CTeX-org/forum/files/6757969/default.zip)

**Comment by muzimuzhi** [comment]
应用的是 `0x` 的行距。能不能给一个示意图，展示想要的最终效果？现在正常字号的公式只有 `0x`，不是一个完整的等式。

建议把 tex 文件内容贴到 issue 里，这样方便一些。

**Comment by CHEN-z-y** [comment]
Okay 好的
![QQ图片20210630204736](https://user-images.githubusercontent.com/53009740/124347248-b8ff8e80-dc37-11eb-9835-87fe5c3d72a8.png)

不好意思我源文件用了eso-pic...

**Comment by CHEN-z-y** [comment]
好像无法上传tex文件。。。
![image](https://user-images.githubusercontent.com/53009740/124347969-5f00c800-dc3b-11eb-83ec-1b071277ad73.png)

**Comment by sikouhjw** [comment]
> 
> 
> 好像无法上传tex文件。。。
> ![image](https://user-images.githubusercontent.com/53009740/124347969-5f00c800-dc3b-11eb-83ec-1b071277ad73.png)

贴内容，不是上传文件

**Comment by CHEN-z-y** [comment]
https://drive.google.com/file/d/1rxetKJxCMvOVmCvj0BZM6F6VOSmcThse/view?usp=sharing, https://drive.google.com/file/d/1ufuQcukblW_WDxsKgWzIwBwA6ym26_mR/view?usp=sharing

我把附件的文件放在google drive里了

**Comment by sikouhjw** [comment]
是这个意思……
```tex
% 编译引擎: XeLaTeX
\documentclass[10pt,a4paper]{article}
\usepackage{% 数学工具
	amsmath,
	mathtools,
	amsfonts,
	amssymb,
	ctex,
%	tabularray
}

\def\scalequater#1{\scalebox{0.25}{\ensuremath{#1}}}

% 调高underset/stackrel 
\newcommand{\upperset}[2]{\:%
	\underset{% 下标内容
		\text{% 文本
			\raisebox{1.2ex}{%
				\smash{% 拍扁盒子 下标*0.8
					\scalebox{0.8}{$#1$}%
				}%
			}%
		}%
	}{% 被标记的对象
		\text{\raisebox{0.2ex}{\smash{$#2$}}}% 拍扁盒子 正文
	}%
\:}

\newcommand\symbolwithin[2]{% 仿mathtools宏包的 \vdotswithin
	{%
		\mathmakebox[%
			\widthof{\ensuremath{{}#2{}}}%
		][c]{{#1}}%
	}%
}

\def\FLUSH{% 缩短行距（人肉计算的行距）
	\noalign{\vskip-0.875\baselineskip}
}
\def\EQUAL{% 原尺寸1/4大小的等号
	\symbolwithin{%
		\scalequater{%
			$=$%
		}%
	}{%
		\scalequater{{}={}}%
	}%
}
\def\EQUALph{% \phantom{\EQUAL}
	\phantom{%
		\scalequater{{}={}}%
	}%
}

\begin{document}


我希望将等式的证明过程藏在等式内部，

并且将等号放在每一行的中间，

这样放大PDF即可查看答案。

但是我发现：使用\verb|\scalebox|后，

行距并不会跟着变化。

\vskip3cm

\noindent
未添加 \verb|\FLUSH| 的代码:
$\begin{aligned}% 未添加\FLUSH 的代码, 注意到行距不会随字体大小变化
0x 	&\EQUAL							\\
	&\EQUALph\scalequater{0x + 0_V} \\
	&\EQUAL 						\\
	&\EQUALph\scalequater{0x+(1x-x)}
\end{aligned}$

\vskip2cm

\noindent
添加 \verb|\FLUSH| 后的代码：
$\begin{aligned}% 添加\FLUSH后的代码
0x 	&\EQUAL	\\\FLUSH
	&\EQUALph\scalequater{\phantom{(}0x + 0_V}\\\FLUSH
	&\EQUAL \\\FLUSH
	&\EQUALph\scalequater{\phantom{(}0x+(1x-x)}
\end{aligned}$

\vskip2cm

\noindent
但是：
$\begin{aligned}% 添加\FLUSH后的代码
0x 	&\EQUAL	\\\FLUSH
	&\EQUALph\scalequater{\phantom{(}0x + 0_V }\\\FLUSH
	&\EQUAL \\\FLUSH
	&\EQUALph\scalequater{\phantom{(}0x+(1x-x) +\dfrac{ \dfrac{ \dfrac{2}{3} }{3} }{3} }
\end{aligned}$

\noindent
注意到：第二行的分数会顶到上一行


\end{document}
```

**Comment by CHEN-z-y** [comment]
> 
> 
> 是这个意思……
> 
> ```
> % 编译引擎: XeLaTeX
> \documentclass[10pt,a4paper]{article}
> \usepackage{% 数学工具
> 	amsmath,
> 	mathtools,
> 	amsfonts,
> 	amssymb,
> 	ctex,
> %	tabularray
> }
> 
> \def\scalequater#1{\scalebox{0.25}{\ensuremath{#1}}}
> 
> % 调高underset/stackrel 
> \newcommand{\upperset}[2]{\:%
> 	\underset{% 下标内容
> 		\text{% 文本
> 			\raisebox{1.2ex}{%
> 				\smash{% 拍扁盒子 下标*0.8
> 					\scalebox{0.8}{$#1$}%
> 				}%
> 			}%
> 		}%
> 	}{% 被标记的对象
> 		\text{\raisebox{0.2ex}{\smash{$#2$}}}% 拍扁盒子 正文
> 	}%
> \:}
> 
> \newcommand\symbolwithin[2]{% 仿mathtools宏包的 \vdotswithin
> 	{%
> 		\mathmakebox[%
> 			\widthof{\ensuremath{{}#2{}}}%
> 		][c]{{#1}}%
> 	}%
> }
> 
> \def\FLUSH{% 缩短行距（人肉计算的行距）
> 	\noalign{\vskip-0.875\baselineskip}
> }
> \def\EQUAL{% 原尺寸1/4大小的等号
> 	\symbolwithin{%
> 		\scalequater{%
> 			$=$%
> 		}%
> 	}{%
> 		\scalequater{{}={}}%
> 	}%
> }
> \def\EQUALph{% \phantom{\EQUAL}
> 	\phantom{%
> 		\scalequater{{}={}}%
> 	}%
> }
> 
> \begin{document}
> 
> 
> 我希望将等式的证明过程藏在等式内部，
> 
> 并且将等号放在每一行的中间，
> 
> 这样放大PDF即可查看答案。
> 
> 但是我发现：使用\verb|\scalebox|后，
> 
> 行距并不会跟着变化。
> 
> \vskip3cm
> 
> \noindent
> 未添加 \verb|\FLUSH| 的代码:
> $\begin{aligned}% 未添加\FLUSH 的代码, 注意到行距不会随字体大小变化
> 0x 	&\EQUAL							\\
> 	&\EQUALph\scalequater{0x + 0_V} \\
> 	&\EQUAL 						\\
> 	&\EQUALph\scalequater{0x+(1x-x)}
> \end{aligned}$
> 
> \vskip2cm
> 
> \noindent
> 添加 \verb|\FLUSH| 后的代码：
> $\begin{aligned}% 添加\FLUSH后的代码
> 0x 	&\EQUAL	\\\FLUSH
> 	&\EQUALph\scalequater{\phantom{(}0x + 0_V}\\\FLUSH
> 	&\EQUAL \\\FLUSH
> 	&\EQUALph\scalequater{\phantom{(}0x+(1x-x)}
> \end{aligned}$
> 
> \vskip2cm
> 
> \noindent
> 但是：
> $\begin{aligned}% 添加\FLUSH后的代码
> 0x 	&\EQUAL	\\\FLUSH
> 	&\EQUALph\scalequater{\phantom{(}0x + 0_V }\\\FLUSH
> 	&\EQUAL \\\FLUSH
> 	&\EQUALph\scalequater{\phantom{(}0x+(1x-x) +\dfrac{ \dfrac{ \dfrac{2}{3} }{3} }{3} }
> \end{aligned}$
> 
> \noindent
> 注意到：第二行的分数会顶到上一行
> 
> 
> \end{document}
> ```

**Comment by CHEN-z-y** [comment]
Gosh 我按错了。。

**Comment by muzimuzhi** [comment]
> ![QQ图片20210630204736](https://user-images.githubusercontent.com/53009740/124347248-b8ff8e80-dc37-11eb-9835-87fe5c3d72a8.png)

缩小的部分，等号需要和公示内容不平齐吗？右下侧的 `0_v` 的高度是怎么确定的？

**Comment by CHEN-z-y** [comment]
最上面的那个 "$0x=$"
其实是在同一行，只不过等号缩小为原来的1/4而已

右下角的 "$1x-x=0_V$"
也是位于同一行，等号缩小为原来的1/4

**Comment by CHEN-z-y** [comment]
![image](https://user-images.githubusercontent.com/53009740/124359792-980c5d00-dc7a-11eb-9d9a-378d3d99d7d0.png)
这幅图对应的代码如下：

```tex
% 编译引擎: XeLaTeX
\documentclass[10pt,a4paper]{article}
\usepackage{% 数学工具
	amsmath,
	mathtools,
	amsfonts,
	amssymb,
	ctex,
	adjustbox
}

\def\scalequater#1{\scalebox{0.25}{\ensuremath{#1}}}

% 调高underset/stackrel 
\newcommand{\upperset}[2]{\:%
	\underset{% 下标内容
		\text{% 文本
			\raisebox{1.2ex}{%
				\smash{% 拍扁盒子 下标*0.8
					\scalebox{0.8}{$#1$}%
				}%
			}%
		}%
	}{% 被标记的对象
		\text{\raisebox{0.2ex}{\smash{$#2$}}}% 拍扁盒子 正文
	}%
\:}

\newcommand\symbolwithin[2]{% 仿mathtools宏包的 \vdotswithin
	{%
		\mathmakebox[%
			\widthof{\ensuremath{{}#2{}}}%
		][c]{{#1}}%
	}%
}

\def\FLUSH{%
	\noalign{\vskip-0.875\baselineskip}%
}
\def\EQUALph{%
	\phantom{%
		\scalequater{{}={}}%
	}%
}
\def\EQUAL#1#2{
	\symbolwithin{%
		\scalequater{%
			\upperset{% 
				\adjustbox{scale = 0.25, raise=2.5pt}{%
					$#1$ #2%
				}%
			}{=}%
		}%
	}{%
		\scalequater{{}={}}%
	}
}

\begin{document}

$
\begin{aligned}%{3}
0x 	&\EQUAL{\oplus}{单位元}\\\FLUSH
	&\EQUALph\scalequater{\phantom{(}0x + \phantom{(}0_V}\\\FLUSH
	&\EQUAL{*}{单位元}\\\FLUSH
	&\EQUALph\scalequater{\phantom{(}0x + (1x\phantom{)} - x)}\\\FLUSH
	&\EQUAL{\oplus}{结合律}\\\FLUSH
	&\EQUALph\scalequater{(0x + \phantom{(}1x) - x}\\\FLUSH
	&\EQUAL{\phantom{\oplus}}{分配律}\\\FLUSH
	&\EQUALph\scalequater{\phantom{(0x+{}\phantom{(}} 1x\phantom{)} - x\phantom{)}}
	 \EQUAL{*}{单位元}0_V\\
\end{aligned}
$

\end{document}
```

**Comment by muzimuzhi** [comment]
仍然没明白你想达到的排版效果。

**Comment by CHEN-z-y** [comment]
我的表述可能过于含糊。。。抱歉
我做了一张示意图

[示意圖.pdf](https://github.com/CTeX-org/forum/files/6759368/default.pdf)

**Comment by muzimuzhi** [comment]
没想到什么简答的思路，抱歉

**Comment by CHEN-z-y** [comment]
啊没关系，你能帮我看这个问题我已经很感激了😁
其实我就是想知道
使用scalebox缩小文本内容后
如何让行距也等比例缩小呢？
剩下的就让我自己手动操作吧。
![image](https://user-images.githubusercontent.com/53009740/124386362-1fff6f00-dd2e-11eb-8c3f-a0872cb2cb72.png)


[1_simp.pdf](https://github.com/CTeX-org/forum/files/6759906/1_simp.pdf)

**Comment by muzimuzhi** [comment]
主要的困难是
 - 如果靠指定字号来实现小字号文本，因为公式字号需要在文本模式下修改，也就是 `{\tiny $...$}` 有效而 `$\tiny ...$` 无效，所以需要多次进出数学模式。
 - 如果靠缩放来实现小字号文本，就需要缩放整个公式，否则（像题主的例子里那样，仅做逐行缩放）行距不会改变。（局部修改行距至很小的值？我不喜欢）更严重的是，缩放后就失去了基于公式内容的基线高度信息。（可以用缩放前的高/深 * 缩放比例来获得）
 - 还可以用表格里的单元格来拼，`nicematrix`, `tabularray` 和 `tikz` 应该都可以，但这需要准确模拟出 `a &= b` 里等号前后的空距。

下面是一个「靠指定字号来实现小字号文本」的例子，空距并未准确模拟。

```tex
\documentclass{article}
\usepackage{amsmath}

\NewDocumentEnvironment{myaligned}{ O{t} m m +b }{%
  \setbox0=\hbox{$#2$}%
  \tiny
  $\begin{aligned}[#1]
    \smash{\text{\usebox0}}
    #4
    \smash{\text{\normalsize $#3$}}
  \end{aligned}$%
}{}

\begin{document}
XXX
\begin{myaligned}{A}{B}
  &= a \\
  &= b \\
  &= c = 
\end{myaligned}
XXX
\begin{myaligned}[b]{A}{B}
  &= a \\
  &= b \\
  &= c = 
\end{myaligned}
XXX
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/142560820-4d55e875-b436-4f82-b418-cad93a13951a.png)
