### ISSUE TITLE
xeCJK不能fallback到plane 15（PUA-A）的字体

### ISSUE THREAD

**Issue by ostaith** [CTeX-org/forum#205]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [x] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [ ] TeX Live 
  - [x] MiKTeX 21.2 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## xeCJK不能fallback到plane 15（PUA-A）的字体

如下代码，

```tex
\documentclass{ctexart}

\xeCJKsetup{AutoFallBack=true}

\setCJKfamilyfont{mysong}{SimSun}
\setCJKfallbackfamilyfont{mysong}{SimSun-ExtB}
% \setCJKfallbackfamilyfont{mysong}{ZhongHuaSongPlane15}

\newcommand*{\mysongti}{\CJKfamily+{mysong}}

\begin{document}

\mysongti{一\char"20000\char"F0000二}

\end{document}
```

可以正确排出ExtB字符`𠀀`
![image](https://user-images.githubusercontent.com/34862369/126814967-50d45376-e823-4ffc-8773-643a0857b97f.png)

但是换一下，如果fallback到15平面，

```tex
\documentclass{ctexart}

\xeCJKsetup{AutoFallBack=true}

\setCJKfamilyfont{mysong}{SimSun}
% \setCJKfallbackfamilyfont{mysong}{SimSun-ExtB}
\setCJKfallbackfamilyfont{mysong}{ZhongHuaSongPlane15}

\newcommand*{\mysongti}{\CJKfamily+{mysong}}

\begin{document}

\mysongti{一\char"20000\char"F0000二}

\end{document}
```

却排不出第三个字符（PUA-A字符\char"F0000）:
![image](https://user-images.githubusercontent.com/34862369/126815705-f8eaea0f-2717-43f1-bb50-28d8c378e887.png)

15平面的字符可以从[这里](https://pan.baidu.com/s/1VfX8sooCZEoTn9RZCMvCIQ)下载。

**Comment by ostaith** [comment]
@qinglee 我找到原因了，是因为`xeCJK.sty`中的`\clist_const:Nn \c__xeCJK_CJK_chars_clist`未定义15平面范围。在`\c__xeCJK_CJK_chars_clist`定义中最后一行增加15平面的范围`"F0000 -> "FFFFF`就可以fallback了，并且可以多层fallback。

**Comment by muzimuzhi** [comment]
`\xeCJKDeclareCharClass{CJK}{"F0000 -> "FFFFF}` 可以作为临时方案

**Comment by stone-zeng** [comment]
> @qinglee 我找到原因了，是因为`xeCJK.sty`中的`\clist_const:Nn \c__xeCJK_CJK_chars_clist`未定义15平面范围。在`\c__xeCJK_CJK_chars_clist`定义中最后一行增加15平面的范围`"F0000 -> "FFFFF`就可以fallback了，并且可以多层fallback。

Plane 15 被 Unicode 标准定义为私有区，因此不应该在 `xeCJK` 的默认实现中提供定义。

> `\xeCJKDeclareCharClass{CJK}{"F0000 -> "FFFFF}` 可以作为临时方案

结束位置设为 `"FFFFD` 吧，后面两个 U+FFFFE 和 U+FFFFF 是 noncharacters。

**Comment by ostaith** [comment]
> `\xeCJKDeclareCharClass{CJK}{"F0000 -> "FFFFF}` 可以作为临时方案
这个方案是最好的，不用修改xeCJK宏包。

附上MWE供其他人参考：
```
\documentclass{ctexart}

\xeCJKsetup{AutoFallBack=true}

\xeCJKDeclareCharClass{CJK}{"F0000 -> "FFFFD}

\setCJKfamilyfont{mysong}{SimSun}
\setCJKfallbackfamilyfont{mysong}{SimSun-ExtB, ZhongHuaSongPlane15}

\newcommand*{\mysongti}{\CJKfamily+{mysong}}

\begin{document}

\mysongti{一\char"20000\char"F0000丁}

\end{document}
```

**Comment by sikouhjw** [comment]
> ```
> \mysongti{一\char"20000\char"F0000丁}
> ```

花括号是不必要的，又不是带参数的命令……为什么都这么写……
