### ISSUE TITLE
macOS 插入 eps 图片时出现错误

### ISSUE THREAD

**Issue by syvshc** [CTeX-org/forum#207]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [x] macOS Big Sur
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 最小工作示例（MWE）

我想使用如下代码插入 `eps` 格式图片
```latex
\documentclass{ctexart}
\usepackage{graphicx}
\begin{document}
    \includegraphics{example-image.eps}
\end{document}
```
使用 xelatex 编译后报错
```
xdvipdfmx:fatal: Image inclusion failed for "example-image.eps".
```
请问该如何解决? 

我想将 `eps` 文件转为 `pdf` 文件再尝试, 在另一 `eps` 文件上运行 `epstopdf golfer.eps` 返回
![image](https://user-images.githubusercontent.com/38098591/127516070-6dccbcf9-96ea-44af-90f4-9caeb94afad6.png)

**Comment by zepinglee** [comment]
mac 的 TeX Live 没有带 ghostscript，所以不能处理 eps。可以用 Homebrew 装一个。
```
brew install ghostscript
```

**Comment by muzimuzhi** [comment]
根据 mactex 的说明 
 - https://www.tug.org/mactex/mactex-download.html
 - https://www.tug.org/mactex/morepackages.html

mactex（的安装包）自带了 ghostscript，用户可选安装；basictex 不自带

**Comment by syvshc** [comment]
> mac 的 TeX Live 没有带 ghostscript，所以不能处理 eps。可以用 Homebrew 装一个。
> 
> ```
> brew install ghostscript
> ```

安装后可以使用 `epstopdf` 了, 但是在直接编译含 `eps` 图片的 `tex` 文件时依然报错
![image](https://user-images.githubusercontent.com/38098591/127590091-571a6e6c-7dd9-41f1-bc69-a693069e3448.png)
同样回复 @muzimuzhi 无论是否使用后缀, 错误都相同

**Comment by syvshc** [comment]
问题解决了, 上一个问题是由于我没有把 `brew` 相关的内容放到 `~/.zshrc` 中导致的, 谢谢二位

**Comment by ddai2024** [comment]
> 问题解决了, 上一个问题是由于我没有把 `brew` 相关的内容放到 `~/.zshrc` 中导致的, 谢谢二位

我也碰到了相同的问题。请问如何把 `brew` 相关的内容放到 `~/.zshrc` 中？
