### ISSUE TITLE
在不定长的文本下添加下划线

### ISSUE THREAD

**Issue by syvshc** [CTeX-org/forum#208]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 11
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live  2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

我有一段不定长的文本, 要将它们放到定宽 (`13\ccwd`) 的 `parbox` 中并添加下划线, 要求最后一行文字的下划线的长度也为 `13\ccwd`

## 最小工作示例（MWE）
```latex
\documentclass{ctexart}
\usepackage{xeCJKfntef}
\begin{document}
\parbox{13\ccwd}{\centering\CJKunderline{这是一个很长的学位论文题目中华人民共和国刑法这是一个很长的学位论文}}
\end{document}
```
![image](https://user-images.githubusercontent.com/38098591/127985859-670afc22-0c77-4ea5-927f-ba4905eb0b00.png)
希望达到下面的效果
![image](https://user-images.githubusercontent.com/38098591/127986223-6594405f-1135-493e-b795-aba441e4a548.png)

**Comment by muzimuzhi** [comment]
知乎文章《[双语标题：LaTeX 实现](https://zhuanlan.zhihu.com/p/51494365)》 里有一个实现

**Comment by syvshc** [comment]
> 知乎文章《[双语标题：LaTeX 实现](https://zhuanlan.zhihu.com/p/51494365)》 里有一个实现

谢谢, 我对该源码有一些疑惑, 请问可以在这里继续提问吗

**Comment by muzimuzhi** [comment]
行，不过我自己都懒得看那个实现。

**Comment by syvshc** [comment]
> 行，不过我自己都懒得看那个实现。它应该只能在特定情况下生效

我又看了一遍, 差不多看懂了, 我试着把它应用到我的实例中看看有没有问题

**Comment by syvshc** [comment]
已经可以实现, 实现方法发在了
https://syvshc.github.io/2021-08-04-thesis-title/
https://syvshc.gitee.io/2021-08-04-thesis-title/

**Comment by muzimuzhi** [comment]
用 `lineno` 包或许更好，总之我对自己之前的实现没什么信心。

```tex
\documentclass{ctexart}
\usepackage{lineno}
\usepackage{zhlipsum}

\makeatletter
\newlength\underlineMinSep
\setlength\underlineMinSep{1em}

\newcommand\underlineX[1]{%
  \hskip\underlineMinSep
  \begin{minipage}[t]{8cm}
    \centering
    % see `texdoc lineno`, sec. 7.4
    \internallinenumbers
    \renewcommand\makeLineNumber{\hss
      \rlap{\hskip-\underlineMinSep
        \rule[.5\dimexpr\f@size pt-\baselineskip]{\dimexpr\textwidth+2\underlineMinSep}{.4pt}}}%
    #1
  \end{minipage}%
}
\makeatother

\begin{document}
标题：\underlineX{\zhlipsum[19][name=zhufu]}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/128434606-ed0eb683-9032-417e-84ed-dc685c1d5e9c.png)
