### ISSUE TITLE
通过 \newCJKfontfamily 加载在某一文件夹下的 FallBack 字体 无法移植

### ISSUE THREAD

**Issue by scirem** [CTeX-org/forum#210]
## 问题描述

为了项目清晰，将所有的字体文件都放到了fonts文件夹下，包括来自 [http://fonts.jp/hanazono/](http://fonts.jp/hanazono/) 的HanaMinA.ttf和HanaMinB.ttf文件。
单独通过`\newCJKfontfamily{\mingtiA}[Path=fonts/]{HanaMinA.ttf}`和`\newCJKfontfamily{\mingtiB}[Path=fonts/]{HanaMinB.ttf}`都可以加载字体文件。

但是，`\newCJKfontfamily{\mingti}[Path=fonts/,FallBack=HanaMinB.ttf]{HanaMinA.ttf}`却提示无法找到`HanaMinB`。
* 修改为`\newCJKfontfamily{\mingti}[Path=fonts/,Extension=.ttf,FallBack=HanaMinB]{HanaMinA}`，可以在Overleaf正常编译；但是在Windows Texlive 2021上无法找到HanaMinB字体。
* 修改为`\newCJKfontfamily{\mingti}[Path=fonts/,Extension=.ttf,FallBack=HanaMinB.ttf]{HanaMinA}`，在Overleaf提示找不到字体；在Windows Texlive 2021上可以编译。

其他的一些字体，如果放在项目的根目录下，加载这些字体都没有问题，但是放到fonts文件夹后，很多又找不到FallBack。

由于涉及到字体文件，我在Overleaf建立了一个Project：
Overleaf链接： [https://www.overleaf.com/read/rrbykyszdrnh](https://www.overleaf.com/read/rrbykyszdrnh)

## 编译环境

- 操作系统
  - [x] Windows 10
  - [x] Overleaf

- TeX 发行版
  - [x] TeX Live <2021>

**Comment by muzimuzhi** [comment]
`FallBack={[Path=<path>]<fontname>}` 有用吗？

**Comment by scirem** [comment]
> `FallBack={[Path=<path>]<fontname>}` 有用吗？

`\newCJKfontfamily{\FZkaiti}[Path=fonts/,FallBack={[Path=fonts/]FZKaiS(SIP).ttf}]{FZKaiS.ttf}`可用。
