### ISSUE TITLE
能否正文右侧增加留白区域而不影响 header/footer 宽度？

### ISSUE THREAD

**Issue by neruthes** [CTeX-org/forum#211]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [x] Linux（Gentoo）

- TeX 发行版
  - [x] TeX Live  `XeTeX 3.141592653-2.6-0.999993 (TeX Live 2021 Gentoo Linux)`
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

场景是在 A4 纸（宽度 210mm）上排版信件。信件包含 letterhead 模板和正文内容。

目前，letterhead 使用 fancyhdr 的 header/footer 实现。

我希望使用如下宽度配置：

区域 | Header/Footer | 正文
--- | --- | ---
左侧留白 | 20mm | 20mm
自身宽度 | 170mm | 130mm
右侧留白 | 20mm | 60mm

另外，信件正文长度可能超出 1 页。

## 我还做了这些尝试

在通用搜索引擎和各类社区搜索相关关键词未见可用方案。

特别地，`\adjustbox{minipage=130mm}` 对于单页场景可用，但我仍希望找到优雅的方案来应对多页场景。

## 备注

在早前版本，曾经分离为 2 个文件，在同一张纸上先后打印 letterhead 和信件本体。但是，我希望优化成单独 PDF 文件，以优化工作流。

**Comment by muzimuzhi** [comment]
可以先增加右侧页边距，再让页眉超出正文区域。`fancyhdr` 提供了 `\fancyheadoffset / \fancyfootoffset / \fancyhfoffset` 来设置页眉页脚超出正文的距离，参考 https://tex.stackexchange.com/questions/200914/how-to-extend-header-over-the-page-margins 的例子。

```tex
\documentclass{article}
\usepackage{fancyhdr}
\usepackage[outer=60mm]{geometry}
\usepackage{lipsum}

\pagestyle{fancy}
\fancyheadoffset[r]{40mm}

\begin{document}
\section{title}
\lipsum
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/129474612-c75fcc80-6054-4618-995b-defdb2958741.png)

**Comment by neruthes** [comment]
> 可以先增加右侧页边距，再让页眉超出正文区域……

感谢，方案成功，效果优雅。
