### ISSUE TITLE
如何使用 `runin` 选项来让 sub(sub)section 的内容与标题同行

### ISSUE THREAD

**Issue by syvshc** [CTeX-org/forum#212]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live  2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

使用 `\ctexset{}` 设置 `sub(sub)section/runin = true` 无法使 sub(sub)section 的标题与内容同行, 但是 `paragraph/runin = false` 可以使 paragraph 的标题和内容不同行.

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\listfiles
\ctexset{
    subsection/runin    =   true,
    subsubsection/runin =   true,
    paragraph/runin     =   false,
}
\begin{document}
    \section{section} some words
    \subsection{subsection} some words
    \subsubsection{subsubsection} some words
    \paragraph{test} some words
\end{document}
```

使用 xelatex 编译后得到

![image](https://user-images.githubusercontent.com/38098591/129469748-9587a142-2cbd-4f92-9f41-789067f6943f.png)

其中引入的宏包版本为
```
 *File List*
 ctexart.cls    2021/06/20 v2.5.7 Chinese adapter for class article (CTEX)
ctexbackend.cfg    2021/06/20 v2.5.7 Backend configuration file (CTEX)
   expl3.sty    2021-07-12 L3 programming layer (loader) 
l3backend-xetex.def    2021-08-04 L3 backend support: XeTeX
  xparse.sty    2021-08-04 L3 Experimental document command parser
l3keys2e.sty    2021-08-04 LaTeX2e option processing using LaTeX3 keys
ctexhook.sty    2021/06/20 v2.5.7 Document and package hooks (CTEX)
ctexpatch.sty    2021/06/20 v2.5.7 Patching commands (CTEX)
  fix-cm.sty    2020/11/24 v1.1t fixes to LaTeX
  ts1enc.def    2001/06/05 v3.0e (jk/car/fm) Standard LaTeX file
ctexopts.cfg    2021/06/20 v2.5.7 Option configuration file (CTEX)
 article.cls    2021/02/12 v1.4n Standard LaTeX document class
  size10.clo    2021/02/12 v1.4n Standard LaTeX file (size option)
ctex-engine-xetex.def    2021/06/20 v2.5.7 XeLaTeX adapter (CTEX)
   xeCJK.sty    2021/06/20 v3.8.7 Typesetting CJK scripts with XeLaTeX
xtemplate.sty    2021-08-04 L3 Experimental prototype document functions
fontspec.sty    2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX
fontspec-xetex.sty    2020/02/21 v2.7i Font selection for XeLaTeX and LuaLaTeX
 fontenc.sty
fontspec.cfg
   xeCJK.cfg    2021/06/20 v3.8.7 Configuration file for xeCJK package
zhnumber.sty    2020/05/01 v2.8 Typesetting numbers with Chinese glyphs
zhnumber-utf8.cfg    2020/05/01 v2.8 Chinese numerals with UTF8 encoding
ctex-scheme-chinese-article.def    2021/06/20 v2.5.7 Chinese scheme for article
 (CTEX)
ctex-name-utf8.cfg    2021/06/20 v2.5.7 Caption with encoding UTF-8 (CTEX)
ctex-c5size.clo    2021/06/20 v2.5.7 c5size option (CTEX)
ctex-fontset-windows.def    2021/06/20 v2.5.7 Windows fonts definition (CTEX)
    ctex.cfg    2021/06/20 v2.5.7 Configuration file (CTEX)
 ***********
```

**Comment by muzimuzhi** [comment]
换段是由 `aftertitle` 导致的，对 `section/subsection/subsubsection` 而言默认值是 `\@@par` (primitive `\par` 的备份)。

```tex
\documentclass{ctexart}
\ctexset{
  subsection = {
    runin = true,
    aftertitle = {}
  },
  subsubsection = {
    runin = true,
    aftertitle = {}
  },
  paragraph/runin = false
}

\begin{document}
  \section{section} some words
  \subsection{subsection} some words
  \subsubsection{subsubsection} some words
  \paragraph{paragraph} some words
\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/129474050-0fcb8308-fb84-41f4-8e90-2cfe88a104f6.png)

**Comment by muzimuzhi** [comment]
与 https://github.com/CTeX-org/ctex-kit/issues/574 相同

**Comment by syvshc** [comment]
> 与 [CTeX-org/ctex-kit#574](https://github.com/CTeX-org/ctex-kit/issues/574) 相同

好的, 谢谢

**Comment by djunhao** [comment]
如果想让section也能够runin，要如何设置？我用了与subsection一样的设置，但是对section不起作用。

**Comment by muzimuzhi** [comment]
> 我用了与subsection一样的设置，但是对section不起作用。

@djunhao 建议提供例子，开新 issue。

在我本地和 overleaf texlive 2022 测试，https://github.com/CTeX-org/forum/issues/212#issuecomment-899022905 里对 subsection 的设置，对 section 同样起作用。
<details><summary>完整例子</summary>
<p>

```tex
\documentclass{ctexart}
\ctexset{
  section       = {runin=true, aftertitle={}},
  subsection    = {runin=true, aftertitle={}},
  subsubsection = {runin=true, aftertitle={}},
  paragraph/runin = false
}

\begin{document}
  \section{section} some words
  \subsection{subsection} some words
  \subsubsection{subsubsection} some words
  \paragraph{paragraph} some words
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/231698678-a551e0ff-8d25-41e9-a29c-b095682ab007.png)

</p>
</details>

**Comment by djunhao** [comment]
> > 我用了与subsection一样的设置，但是对section不起作用。
> 
> @djunhao 建议提供例子，开新 issue。
> 
> 在我本地和 overleaf texlive 2022 测试，[#212 (comment)](https://github.com/CTeX-org/forum/issues/212#issuecomment-899022905) 里对 subsection 的设置，对 section 同样起作用。
> 
> 完整例子

非常感谢慕子老师的回复。我找到问题所在了。我的代码的最小示例如下：
`\documentclass{ctexart}
\ctexset{
  subsection = {
    runin = true,
    aftertitle = {}
  },
  subsubsection = {
    runin = true,
    aftertitle = {}
  },
  paragraph/runin = false
}

\begin{document}
  \section{一级标题} 
  \subsection{二级标题} 二级标题下的内容。
  \subsubsection{三级标题} 三级标题下的内容。
\end{document}`

由于我的“一级标题”下直接就是“二级标题”，所以会形成断行。虽然在公文写作中，一级标题直接接二级标题偶尔还是会选择不断行，但是ctex的这种设定我觉得是合理的。由于当时我没有查看上下文，所以才提出了以上的问题。
