### ISSUE TITLE
如何分别控制目录级别（显示深度）和pdf的书签级别

### ISSUE THREAD

**Issue by goodluck1982** [CTeX-org/forum#214]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [ ] TeX Live 
  - [x] MiKTeX  4.8 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题
我的文档里有很多subsubsection，我希望它们出现在 pdf 的标签里，这样点击跳转很方便，但我不希望它们出现在目录里，因为会占好多页使得目录太长没必要。可是网上能找到的都是说设置 tocdepth，比如`\setcounter{tocdepth}{2} `但奇怪的是正好相反，得到的结果是pdf书签里没有了 subsubsection 而目录里依然有 subsubsection。这可能是和我用的 revtex4-2 文档类有关，我试了如果用普通的 article 文档类 或者 仍用 revtex4-2 但加上 `\usepackage{tocloft}` 的话，则不论pdf书签还是目录同时都不显示 subsubsection 了，这也不是我想要的。不论是 revtex4-2 的bug或副作用也好，至少说明 pdf书签和目录的深度是可以不一样的，但不知如何满足我的需求，最好仍然使用 revtex4-2 文档类。

## 最小工作示例（MWE）

```
\documentclass[onecolumn]{revtex4-2}
\usepackage{hyperref}
\hypersetup{colorlinks=true, linkcolor=blue}
\begin{document}

\title{test title}
\maketitle

\setcounter{tocdepth}{2}  %目录深度设为2
\tableofcontents          %插入目录

\section{sec1}
\subsection{subsec1.1}
\subsubsection{subsubsec1.1.1}
\subsection{subsec1.2}
\section{sec2}
\subsection{subsec2.1}
\subsection{subsec2.2}

\end{document}
```

**Comment by zepinglee** [comment]
可以设置 `hyperref` 的 `bookmarksdepth`，甚至还有 `bookmarksopen` 和 `bookmarksopenlevel`。

另外如果是投稿的话，建议不要用 `tocloft` 或者设置 `tocdepth` 修改期刊/会议规定好的样式。

**Comment by goodluck1982** [comment]
> 可以设置 `hyperref` 的 `bookmarksdepth`，甚至还有 `bookmarksopen` 和 `bookmarksopenlevel`。
加了 `bookmarksdepth` 后确实 pdf 书签的级别可以控制了。但是目录的级别仍然无法控制，总是停留在 subsubsection 级别（revtex4-2下），如何能调整呢？
> 
> 另外如果是投稿的话，建议不要用 `tocloft` 或者设置 `tocdepth` 修改期刊/会议规定好的样式。
是投稿的补充材料，很长，有很多的表格，所以希望在pdf书签里显示但不在目录里显示。而且为了和正文一致，使用 revtex4-2 文档类。

**Comment by goodluck1982** [comment]
完美解决！果然是 revtex4-2 的问题，tocdepth 对其不管用。
[https://tex.stackexchange.com/questions/155454/tocdepth-for-the-table-of-contents-in-revtex4](url)
要如下修改
```
% disable and subsubsections in the TOC
\makeatletter
\def\l@subsubsection#1#2{}
\makeatother
```
