### ISSUE TITLE
strikeout（ulem宏包的sout命令） 删除线无法让中文的句子换行

### ISSUE THREAD

**Issue by asmwarrior** [CTeX-org/forum#217]
## 检查
- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7

- TeX 发行版
  - [x] TeX Live 2021

## 描述问题
发现在xelatex编译器下，无法用`\sout`命令来对删除线的文字进行换行。
下面的例子中，`中文中文中文中文中文中文中文中文中文中文，英文，英文` 正常应该进行换行
我试了texlive2020，而且下午刚装了texlive2021，都是同样的问题。结果截图在后面。
我也试了把`\usepackage{ulem}` 改成 `\usepackage{ulem}`，同样的不能换行。
示例代码改造自：[text decorations - Strikeout - when which package ? ( ulem vs soul vs ...) - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/74893/strikeout-when-which-package-ulem-vs-soul-vs)

## 最小工作示例（MWE）

```latex
\documentclass[11pt]{ctexart}

\usepackage{ulem}

\textwidth=2cm % just to force hyphenation to happen

\usepackage{cancel,soul}

\begin{document}
\[
\frac{\cancel{5}*17}{\cancel{5}*23}
\]

X \sout{supercalifragilisticexpialidocious 中文中文中文中文中文中文中文中文中文中文，英文，英文}

X \st{supercalifragilisticexpialidocious}

X \emph{supercalifragilisticexpialidocious}

X \ul{supercalifragilisticexpialidocious}

\end{document}
```

（用 XeLaTeX 编译后）输出
![image](https://user-images.githubusercontent.com/561818/138587340-6fd7930a-1305-4c1a-b394-5cdc3f875d12.png)

**Comment by Mikachu2333** [comment]
关联一下便于搜索

`\uline{}`
