### ISSUE TITLE
中文右括号与西文点号之间的混排所产生的额外间距问题

### ISSUE THREAD

**Issue by peng-zehua** [CTeX-org/forum#219]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题
在使用 ctexbook 文档类对一本数学书籍进行排版的过程中发现：当中文右括号”）“和西文点号“.”混排时，会在两者之间产生比较大的间距，比如，使用以下工作示例：
``` latex
\documentclass{ctexbook}
\begin{document}
验，具有下的试验，称为随机试验（random experiment）.
\end{document}
```
排版效果为：
![image](https://user-images.githubusercontent.com/70280543/143996640-30e766ed-52dd-43c3-a70f-a9a82a4cc5ef.png)
而原书在中文右括号”）“和西文点号”.“之间的间距则要更加合理一些：
![image](https://user-images.githubusercontent.com/70280543/143999891-18d51a5e-0027-4516-afdb-7f84319da2c0.png)
当在中文右括号“）”和西文点号“.”之间可能会产生断行时，西文点号甚至有可能被排在下一行的句首处：
``` latex
\documentclass{ctexbook}
\begin{document}
占位验，具有下述三个特征的试验，称为随机试验（random experiment）.
\end{document}
```
排版效果为：
![image](https://user-images.githubusercontent.com/70280543/143997049-0bc65c3e-d51a-469d-ae64-2b30f5b3d1c0.png)
虽然使用 `\nolinebreak` 可以防止西文点号出现在下一行的句首处，但如果将上面示例代码中的西文点号“.”替换成中文句号“。”，则在中文右括号“）”和中文句号“。”之间，即使不使用 `nolinebreak`，也不会使得中文句号“。”被排到下一行行首。比如：
``` latex
\documentclass{ctexbook}
\begin{document}
占位验，具有下述三个特征的试验，称为随机试验（random experiment）。
\end{document}
```
排版效果为：
![image](https://user-images.githubusercontent.com/70280543/143999825-dd8d4faf-fc32-4ff0-9040-e497411c8a6c.png)
我所想想到的是，是否在文本模式中也用一个类似在数学环境中的负间距命令 `\!` 来消除这一似乎有些多余的间距？
## 我还做了这些尝试
为了描述问题的方便，我的尝试已在问题描述中给出。

**Comment by tanukihee** [comment]
用U+FF0E「．」，不要用「.」

**Comment by sikouhjw** [comment]
你要不考虑用 `Mapping = fullwidth-stop`

**Comment by peng-zehua** [comment]
> 用 U+FF0E「．」，不要用「.」
确实有用，谢谢
> 你要不考虑用 `Mapping = fullwidth-stop`
这个貌似是 xeCJK 宏包中的选项，我使用的是进一步封装好的 ctex 宏包，我在 ctex 宏包的帮助文档中没有检索到这个选项

**Comment by sikouhjw** [comment]
> > 你要不考虑用 `Mapping = fullwidth-stop`
> 
> 这个貌似是 xeCJK 宏包中的选项，我使用的是进一步封装好的 ctex 宏包，我在 ctex 宏包的帮助文档中没有检索到这个选项

`ctex` 宏集包括 `xeCJK` 宏包，那么 `xeCJK` 的语法也是可以用的。

**Comment by syvshc** [comment]
> 这个貌似是 xeCJK 宏包中的选项，我使用的是进一步封装好的 ctex 宏包，我在 ctex 宏包的帮助文档中没有检索到这个选项

直接用 `\xeCJKsetup` 即可

**Comment by peng-zehua** [comment]
> `ctex` 宏集包括 `xeCJK` 宏包，那么 `xeCJK` 的语法也是可以用的。

``` latex
\documentclass{ctexbook}
\ctexset {
    Mapping = fullwidth-stop,
}
\begin{document}
占位验，具有下述三个特征的试验，称为随机试验（random experiment）．
占位验，具有下述三个特征的试验，称为随机试验（random experiment）。
\end{document}
```

谢谢，但我使用如上工作示例进行尝试，然后得到了如下 `Error`：
`Error: The key 'ctex/Mapping' is unknown and is being ignored.`
如果 CTeX 宏包提供了这个选项，那么为什么我这里还是报 `unknown` 相关的 `Error` 了呢？

**Comment by syvshc** [comment]
> > `ctex` 宏集包括 `xeCJK` 宏包，那么 `xeCJK` 的语法也是可以用的。
> 
> ```
> \documentclass{ctexbook}
> \ctexset {
>     Mapping = fullwidth-stop,
> }
> \begin{document}
> 占位验，具有下述三个特征的试验，称为随机试验（random experiment）．
> 占位验，具有下述三个特征的试验，称为随机试验（random experiment）。
> \end{document}
> ```
> 
> 谢谢，但我使用如上工作示例进行尝试，然后得到了如下 `Error`： `Error: The key 'ctex/Mapping' is unknown and is being ignored.` 如果 CTeX 宏包提供了这个选项，那么为什么我这里还是报 `unknown` 相关的 `Error` 了呢？

因为这个选项不是在 `\ctexset` 或者 `\xeCJKsetup` 中使用的, 是在字体设置过程中使用的:

![image](https://user-images.githubusercontent.com/38098591/144015472-100138d9-92da-4cb4-bb09-f87d48345251.png)

**Comment by syvshc** [comment]
```
\documentclass{ctexbook}
\setCJKmainfont{simsun.ttc}[ BoldFont = simhei.ttf, ItalicFont = simkai.ttf, Mapping = fullwidth-stop]
% \xeCJKsetup{Mapping = fullwidth-stop}
\begin{document}
占位验，具有下述三个特征的试验，称为随机试验（random experiment）．

占位验，具有下述三个特征的试验，称为随机试验（random experiment）。
\end{document}
```
![image](https://user-images.githubusercontent.com/38098591/144016283-fcf2d471-6115-438f-83dd-da71ef690aff.png)

**Comment by peng-zehua** [comment]
@syvshc 
刚刚我也一直在尝试并阅读 xeCJK 的帮助文档，以下代码得到了成功编译：
``` latex
\documentclass{ctexbook}

\setCJKmainfont[Mapping = fullwidth-stop]{STSong}

\begin{document}
占位验，具有下述三个特征的试验，称为随机试验（random experiment）．
占位验，具有下述三个特征的试验，称为随机试验（random experiment）。
\end{document}
```
