### ISSUE TITLE
日经问题：LaTeX 如何转为 Word？

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/forum#22]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 描述

怎样把 LaTeX（或者由 LaTeX 生成的 PDF）转换为 Word？

欢迎大家补充。

## 链接

- TeX.SX: [How to convert a scientific manuscript from LaTeX to Word using Pandoc?](https://tex.stackexchange.com/q/111886)
- 知乎: [LaTeX（XeLaTeX）写的文档如何一键转为word？](https://www.zhihu.com/question/31850346)

**Comment by stone-zeng** [comment]
我所尝试过的办法：

- 保存为 PDF 之后用 Adobe Acrobat 转换为 Word 文档
- 直接用 MS Word 打开 PDF 并转换

貌似前者效果比较好，可以保持大体的文档结构；但公式之类依旧会比较凌乱。亲测可以进行查重（知网）。

**Comment by gzxu** [comment]
转不了，散了吧（逃

**Comment by sd44** [comment]
https://github.com/michal-h21/

mical-h21做的格式转换简易包不少。可以看看他的这些仓库，我印象中有make4ht,lua4ht，helper4ht。基本都支持openoffice的odt格式，个别支持docx。

基于tex4ht的make4ht可能用ctex套装较好。
lua4ht看着挺好，我好像没有弄成功。
helper4ht好像成功了，但效果不是很满意。

反正配置调试挺麻烦。。。。

**Comment by TianyiShi2001** [comment]
用pandoc
支持几十种文件格式的转换，而且可以自定义
https://pandoc.org
