### ISSUE TITLE
enumitem 宏包与列表缩进问题

### ISSUE THREAD

**Issue by peng-zehua** [CTeX-org/forum#220]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

为了方便问题的描述，在这里先放一张 `enumitem` 宏包对列表各个参数长度解释的图：

![image-20211201194635814](https://gitee.com/zehua-peng/img/raw/master/CPrograming/introduction/20211201194642.png)

我想使用 `enumitem` 宏包将列表的缩进设置成如下形式：

![image-20211201194859940](https://gitee.com/zehua-peng/img/raw/master/CPrograming/introduction/20211201194859.png)

为此，我设置了 `enumitem` 宏包中的的 `leftmargin` 参数，企图将 `leftmargin` 设置成 `\labelwidth + \labelsep - \itemindent` 以将开篇给出的图中的红色方框部分的间距设为 `0`：

``` latex
\documentclass[fontset = windows]{ctexart}
\usepackage{enumitem}
\setlist{nosep, leftmargin = \labelwidth + \labelsep - \itemindent}
\begin{document}
占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位
\begin{enumerate}
    \item 占位
    \item 占位
\end{enumerate}
\end{document}
```

然而，我得到了如下结果：

![image-20211201195823596](https://gitee.com/zehua-peng/img/raw/master/CPrograming/introduction/20211201195823.png)

不仅没有得到我想要的结果，而出现了一个令人沮丧的 `+`。

## 我还做了这些尝试

在阅读 `enumitem` 宏包的过程中，我发现了一个 `\labelindent` 的选项，因此，我又做了如下尝试：

``` latex
\documentclass[fontset = windows]{ctexart}
\usepackage{enumitem}
% \setlist{nosep, leftmargin = \labelwidth + \labelsep - \itemindent}
\setlist[1]{nosep, labelindent = \parindent}
\begin{document}
占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位
\begin{enumerate}
    \item 占位
    \item 占位
\end{enumerate}
\end{document}
```

得到了如下结果：

![image-20211201200233679](https://gitee.com/zehua-peng/img/raw/master/CPrograming/introduction/20211201200233.png)

幸运的是，那个 `+` 消失了，但其实就算没有 `labelindent = \parindent`，其结果也不会有什么变化。

``` latex
\documentclass[fontset = windows]{ctexart}
\usepackage{enumitem}
% \setlist{nosep, leftmargin = \labelwidth + \labelsep - \itemindent}
\setlist[1]{nosep, } % labelindent = \parindent
\begin{document}
占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位占位
\begin{enumerate}
    \item 占位
    \item 占位
\end{enumerate}
\end{document}
```

运行结果如下：

![image-20211201200408145](https://gitee.com/zehua-peng/img/raw/master/CPrograming/introduction/20211201200408.png)

同时，我注意到 `enumitem` 宏包中有一段这样的说明：

> This parameter is added in enumitem for the blank space from the margin of the enclosing
>
> list/text to the left edge of the label box. This means there is a redundancy because one of the
>
> parameters depends on the others, i.e., it has to be computed from the other values, as described
>
> below. By default, the computed value is labelindent, even if explicitly set with some value (it
>
> defaults to 0 pt). So, if you are setting it to some value, very likely you want to set some other
>
> parameter to ! or *, because otherwise it is ignored.

我不明白此处的 `!` 或 `*` 是什么用法，`\labelindent` 到底应该怎样被设置才会更加合理一些呢？

同时，我还发现了一篇类似尝试的博客：https://sikouhjw.github.io/2020/06/04/2020-06-04-Chinese-style-list/

但其中各种参数的设置让我有些疑惑，似乎存在着更优雅的某种方式可以实现类似下面这样的效果呢？

![image-20211201194859940](https://gitee.com/zehua-peng/img/raw/master/CPrograming/introduction/20211201201532.png)

**Comment by syvshc** [comment]
![image](https://user-images.githubusercontent.com/38098591/144233640-4df16418-5615-4ee3-8614-29c9c9db60e6.png)

enumitem 宏包文档的后面的 Samples 中是否有你需要的样式呢

**Comment by peng-zehua** [comment]
> 

是可以实现，但我依然无法理解那个令人意外的 `+`

**Comment by muzimuzhi** [comment]
> 是可以实现，但我依然无法理解那个令人意外的 `+`

那个 `+` 是 `leftmargin = \labelwidth + \labelsep - \itemindent` 里的加号。

大多数接受 length/dimension 的地方（参数、选项的值），都不支持（带加减和括号的）dimension expression [^1]。手动加上 `\dimexpr` (文档见 `texdoc etex`, sec. 3.5 "Expressions") 即可。
```tex
\setlist{nosep, leftmargin = \labelwidth + \labelsep - \itemindent}
```

[^1]: 只支持 `<multiplier>?<dimension>` 的形式，例如 `key=\parindent`, `key=.5\textwidth`。`tikz` 及其衍生包是例外，因为它自建了一个数学表达式计算器 `pgfmath`。

---
查看 `enumitem.sty` 知，
```tex
\setlist{leftmargin = \labelwidth + \labelsep - \itemindent}
->
\enit@calcset\leftmargin\thr@@{\labelwidth + \labelsep - \itemindent}
->
\enit@setlength\leftmargin{\labelwidth + \labelsep - \itemindent}
->
\setlength\leftmargin{\labelwidth + \labelsep - \itemindent}
```
又因为有 `\def\setlength#1#2{#1 #2\relax}`，
```tex
\setlength\leftmargin{\labelwidth + \labelsep - \itemindent}
->
\leftmargin \labelwidth + \labelsep - \itemindent\relax
-> % 等价于
\leftmargin=\labelwidth
+
\labelsep= -\itemindent\relax
```
所以会不报错地输出一个 `+`.

知道了最终会展开到 `\setlength`，那么加载（允许 `\setlength` 处理 dimension expression 的）`calc` 包，也是一个解决办法。

**Comment by peng-zehua** [comment]
问题已解决，现对问题做一个简短的补充说明如下：

1. `LaTeX` 在接受 `length/dimension` 的大多数地方不像其他编程语言一样支持带 `+` 或 `-` 的表达式赋值。如果你这样做了，也许你会像我一样在没有任何 `error` 和 `warning` 的情况下得到一个意外的符号。（更详细的解释参见 muzimuzhi 的回答）

2. 如果想将列表缩进到与段落对齐，且让原列表的上下缩进变得与段落行距一致，你可以尝试在导言区添加如下命令：

   ``` latex
   \usepackage{enumitem}
   \setlist{nosep, labelindent=\parindent,leftmargin=*}
   ```

感谢 muzimuzhi 和 syvshc 的指点。

**Comment by syvshc** [comment]
我整理了一下这些命令的关系, 可以看一下, 
https://syvshc.github.io/2021-12-05-length-in-enumitem/ 
如果有内容上的错误或者补充也欢迎评论

**Comment by peng-zehua** [comment]
> 我整理了一下这些命令的关系, 可以看一下, https://syvshc.github.io/2021-12-05-length-in-enumitem/ 如果有内容上的错误或者补充也欢迎评论

好的，谢谢
