### ISSUE TITLE
\trivlist 中的 \triv 代表着什么？

### ISSUE THREAD

**Issue by peng-zehua** [CTeX-org/forum#221]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

`\trivlist` 命令的语义是什么呢？比如 `\titlepage` 命令的语义明显就是**题名页**。我在 [LaTeX2e unofficial reference manual](http://latexref.xyz/trivlist.html) 中查到：`\trivlist` 代表着 A restricted form of `list`。但这与 `\trivlist` 命令的前一段 `triv` 有什么关系呢？

## 最小工作oo示例（MWE）

无

## 链接

无

## 我还做了这些尝试

无

## 附件

无

**Comment by stone-zeng** [comment]
trivial，平凡的

**Comment by peng-zehua** [comment]
@stone-zeng 谢谢

**Comment by zepinglee** [comment]
数学书中很常见的词。
