### ISSUE TITLE
定义tcolorbox样式，并进行整合时报错

### ISSUE THREAD

**Issue by FvNCCR228** [CTeX-org/forum#223]
## 检查

- [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

定义tcolorbox样式，并进行整合时报错

## 最小工作示例（MWE）

```latex
\documentclass{article}

\usepackage{xcolor}
\usepackage{tcolorbox}
\tcbuselibrary{most}

\definecolor{JXred}{cmyk}{0.12,0.92,0.95,0.20}
\definecolor{YYgrey}{cmyk}{0.47,0.37,0.37,0.00}
\definecolor{BSblue}{cmyk}{1.00,0.60,0.00,0.15}
\definecolor{HYgreen}{cmyk}{1.00,0.00,0.90,0.15}
\definecolor{YXyellow}{cmyk}{0.00,0.40,1.00,0.15}

\def\tcbtheocolortheo{JXred}
\def\tcbtheocolorexa{YYgrey}
\def\tcbtheocolordef{BSblue}
\def\tcbtheocolorlem{HYgreen}
\def\tcbtheocolorcond{YXyellow}

\def\tcbtheoin#1{%
	tcb#1style/.style={enhanced,%
		drop fuzzy shadow southeast,%
		colback=\csname tcbtheocolor#1\endcsname!2!white,%
		colframe=\csname tcbtheocolor#1\endcsname,%
		fonttitle=\normalsize\bfseries,%
		coltitle=black}
}

\newcounter{SCUtheoremCount}
\newcounter{SCUexampleCount}
\newcounter{SCUdefinitionCount}
\newcounter{SCUlemmaCount}
\newcounter{SCUconditionCount}

\newtcolorbox[use counter=SCUtheoremCount,%
number within=section]{SCUtheorem}[3][]%
{title={定理~\thetcbcounter: #2},label={theo:#3},%
	opacityback=0.95,tcbtheostyle,#1}
\newtcolorbox[use counter=SCUexampleCount,%
number within=section]{SCUexample}[3][]%
{title={例~\thetcbcounter: #2},label={exam:#3},%
	opacityback=0.95,tcbexastyle,#1}
\newtcolorbox[use counter=SCUdefinitionCount,%
number within=section]{SCUdefinition}[3][]%
{title={定义~\thetcbcounter: #2},label={def:#3},%
	opacityback=0.95,tcbdefstyle,#1}
\newtcolorbox[use counter=SCUlemmaCount,%
number within=section]{SCUlemma}[3][]%
{title={引理~\thetcbcounter: #2},label={lemm:#3},%
	opacityback=0.95,tcblemstyle,#1}
\newtcolorbox[use counter=SCUconditionCount,%
number within=section]{SCUcondition}[3][]%
{title={条件~\thetcbcounter: #2},label={cond:#3},%
	opacityback=0.95,tcbcondstyle,#1}

\begin{document}

\tcbset{%
	\tcbtheoin{theo},
	\tcbtheoin{exa},
	\tcbtheoin{def},
	\tcbtheoin{lem},
	\tcbtheoin{cond},
}

\begin{SCUtheorem}{做}{aa}
	aa
\end{SCUtheorem}
\begin{SCUexample}{一}{bb}
	bb
\end{SCUexample}
\begin{SCUdefinition}{个}{cc}
	cc
\end{SCUdefinition}
\begin{SCUlemma}{测}{dd}
	dd
\end{SCUlemma}
\begin{SCUcondition}{试}{ee}
	ee
\end{SCUcondition}

\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
TeX capacity exceeded, sorry [input stack size=5000]. }
```

## 链接

- TeX.SX:
- GitHub:

**Comment by muzimuzhi** [comment]
```tex
\tcbset{%
	\tcbtheoin{theo},
	\tcbtheoin{exa},
	\tcbtheoin{def},
	\tcbtheoin{lem},
	\tcbtheoin{cond},
}
```
错误发生在这里，因为 `\tcbset` 会把每一个 `\tcbtheoin{xxx}` 解析成 (parse 成) 一个没有值 (value) 的键 (key），而不是先分别对每一个 `\tcbtheoin` 展开一次，再解析整个 key-value 列表。

可以改成让 `\tcbtheoin` 调用 `\tcbset`，
```tex
% 定义
\def\tcbtheoin#1{%
  \tcbset{
    tcb#1style/.style={...}
  }%
}

% 使用
\tcbtheoin{theo}
\tcbtheoin{exa}
\tcbtheoin{def}
\tcbtheoin{lem}
\tcbtheoin{cond}
```

**Comment by muzimuzhi** [comment]
一个建议，应该力所能及地让例子简短。短的例子，阅读负担小，也有更大的可能，容易看出/暴露出问题。比如，在你的例子里，
 - 只保留任意两组定义（比如 `theo` 和 `exa`）就能复现问题；
 - 尝试缩减 `tcb#1style/.style` 里的选项列表时，能发现只要去掉 `fonttitle=\normalsize\bfseries`，就会变成另一个报错[^1]。
 - 继续缩减，报错种类不变。例如减少到只包含一个 key （比如 `enhanced`）时，能得到报错 `! Package pgfkeys Error: I do not know the key '/tcb/tcbtheostyle/.style={enhanced} ' and I am going to ignore it. Perhaps you misspelled it.` 有经验的话，从这里能知道，`\tcbtheoin{theo}` 的展开结果，被整体当成 key 来解析了。
 - 这样，可以一步步靠近知道怎么解决。（只是介绍一种可能的过程，我没有用到这个过程）

[^1]: 这是因为 `tcolorbox` 用的 key-value 功能是从 `pgfkeys` 来的，后者会对解析得到的 key 做 `\edef` 的操作，而这里 `\normalsize\bfseries` 不能被完全展开。使用 `\edef\x{\normalsize\bfseries}` 就能复现 `TeX capacity exceeded` 的报错。

**Comment by FvNCCR228** [comment]
> 一个建议，应该力所能及地让例子简短。短的例子，阅读负担小，也有更大的可能，容易看出/暴露出问题。比如，在你的例子里，
>  - 只使用 `\tcbset{\tcbtheoin{theo}}` 就能复现问题，这样既可以去掉其他四组定义，又可以知道至少在没有进行整合时，就已经出现了问题。
>  - 尝试缩减 `tcb#1style/.style` 里的选项列表时，能发现只要去掉 `fonttitle=\normalsize\bfseries`，就会变成另一个报错[^1]。
>  - 继续缩减，报错种类不变。例如减少到只包含一个 key （比如 `enhanced`）时，能得到报错 `! Package pgfkeys Error: I do not know the key '/tcb/tcbtheostyle/.style={enhanced} ' and I am going to ignore it. Perhaps you misspelled it.` 有经验的话，从这里能知道，`\tcbtheoin{theo}` 的展开结果，被整体当成 key 来解析了。
>  - 这样，可以一步步靠近知道怎么解决。（只是介绍一种可能的过程，我没有用到这个过程）
> 
> [^1]: 这是因为 `tcolorbox` 用的 key-value 功能是从 `pgfkeys` 来的，后者会对解析得到的 key 做 `\edef` 的操作，而这里 `\normalsize\bfseries` 不能被完全展开。使用 `\edef\x{\normalsize\bfseries}` 就能复现 `TeX capacity exceeded` 的报错。

好的，是我思维限制死了。
问问像后面这种有连续多个类死的环境定义应该用什么来简化代码呢

**Comment by sikouhjw** [comment]
> 好的，是我思维限制死了。 问问像后面这种有连续多个类死的环境定义应该用什么来简化代码呢

一个问题一个 issue

**Comment by muzimuzhi** [comment]
> 问问像后面这种有连续多个 <s>类死</s> 类似 的环境定义应该用什么来简化代码呢

可以试试以关键词 latex + 循环、latex + loop 、latex + iterate 搜索。

**Comment by muzimuzhi** [comment]
我重新看了一遍例子，感觉只在最后一步 `\tcbtheoin` 用循环，只是能少打几个字，收益不大。在定义部分，已经有太多的数据绑定。于是我重写了一份，把数据的绑定，集中在了 `\mytcbtheorem` 的使用阶段：
```tex
\documentclass{article}
\usepackage{xeCJK}
\usepackage{tcolorbox}
\tcbuselibrary{skins, theorems}

\definecolor{JXred}{cmyk}{0.12,0.92,0.95,0.20}
\definecolor{YYgrey}{cmyk}{0.47,0.37,0.37,0.00}
\definecolor{BSblue}{cmyk}{1.00,0.60,0.00,0.15}
\definecolor{HYgreen}{cmyk}{1.00,0.00,0.90,0.15}
\definecolor{YXyellow}{cmyk}{0.00,0.40,1.00,0.15}

\tcbset{
  % #1 = color name
  my tcb theorem/.style={
    enhanced,
    drop fuzzy shadow southeast,
    colback=#1!2!white,
    colframe=#1,
    fonttitle=\normalsize\bfseries,
    coltitle=black,
    opacityback=0.95
  }
}

% #1: short name - label prefix, color name, etc
% #2: long name - envname
% #3: cn name in title
% #4: color name
\newcommand\mytcbtheorem[4]{%
  \newtcolorbox[
    auto counter, number within=section
  ]{SCU#2}[3][]{
    title={#3~\thetcbcounter: ##2},
    label={#1:##3},
    my tcb theorem=#4,
    ##1
  }%
}

\mytcbtheorem{theo}{theorem}   {定理} {JXred}
\mytcbtheorem{exa} {example}   {例}   {YYgrey}
\mytcbtheorem{def} {definition}{定义} {BSblue}
\mytcbtheorem{lem} {lemma}     {引理} {HYgreen}
\mytcbtheorem{cond}{condition} {条件} {YXyellow}

\begin{document}

\section{title}
\begin{SCUtheorem}{定理名}{aa}
	aa
\end{SCUtheorem}
\begin{SCUexample}{示例名}{bb}
	bb
\end{SCUexample}

\end{document}
```
注意，在 `title={#3~\thetcbcounter: ##2}` 里，你可能需要判断 `##2` 是否为空，为空时不输出冒号
 - 可以用 `title={#3~\thetcbcounter\ifstrempty{##2}{}{: ##2}}`，其中 `\ifstrempty` 由 `etoolbox` 提供，后者已经由 `tcolorbox` 加载
 - 也可以用 `tcolorbox` 的 `\NewTColorBox` + 选项 `IfNoValueTF`，需要使用 `\tcbuselibrary{xparse}`

**Comment by FvNCCR228** [comment]
> 我重新看了一遍例子，感觉只在最后一步 `\tcbtheoin` 用循环，只是能少打几个字，收益不大。在定义部分，已经有太多的数据绑定。于是我重写了一份，把数据的绑定，集中在了 `\mytcbtheorem` 的使用阶段：
> 
> ```
> \documentclass{article}
> \usepackage{xeCJK}
> \usepackage{tcolorbox}
> \tcbuselibrary{skins, theorems}
> 
> \definecolor{JXred}{cmyk}{0.12,0.92,0.95,0.20}
> \definecolor{YYgrey}{cmyk}{0.47,0.37,0.37,0.00}
> \definecolor{BSblue}{cmyk}{1.00,0.60,0.00,0.15}
> \definecolor{HYgreen}{cmyk}{1.00,0.00,0.90,0.15}
> \definecolor{YXyellow}{cmyk}{0.00,0.40,1.00,0.15}
> 
> \tcbset{
>   % #1 = color name
>   my tcb theorem/.style={
>     enhanced,
>     drop fuzzy shadow southeast,
>     colback=#1!2!white,
>     colframe=#1,
>     fonttitle=\normalsize\bfseries,
>     coltitle=black,
>     opacityback=0.95
>   }
> }
> 
> % #1: short name - label prefix, color name, etc
> % #2: long name - envname
> % #3: cn name in title
> % #4: color name
> \newcommand\mytcbtheorem[4]{%
>   \newtcolorbox[
>     auto counter, number within=section
>   ]{SCU#2}[3][]{
>     title={#3~\thetcbcounter: ##2},
>     label={#1:##3},
>     my tcb theorem=#4,
>     ##1
>   }%
> }
> 
> \mytcbtheorem{theo}{theorem}   {定理} {JXred}
> \mytcbtheorem{exa} {example}   {例}   {YYgrey}
> \mytcbtheorem{def} {definition}{定义} {BSblue}
> \mytcbtheorem{lem} {lemma}     {引理} {HYgreen}
> \mytcbtheorem{cond}{condition} {条件} {YXyellow}
> 
> \begin{document}
> 
> \section{title}
> \begin{SCUtheorem}{定理名}{aa}
> 	aa
> \end{SCUtheorem}
> \begin{SCUexample}{示例名}{bb}
> 	bb
> \end{SCUexample}
> 
> \end{document}
> ```
> 
> 注意，在 `title={#3~\thetcbcounter: ##2}` 里，你可能需要判断 `##2` 是否为空，为空时不输出冒号
> 
> * 可以用 `title={#3~\thetcbcounter\ifstrempty{##2}{}{: ##2}}`，其中 `\ifstrempty` 由 `etoolbox` 提供，后者已经由 `tcolorbox` 加载
> * 也可以用 `tcolorbox` 的 `\NewTColorBox` + 选项 `IfNoValueTF`，需要使用 `\tcbuselibrary{xparse}`

好的, 谢谢了, 判断条件我已经加上去了

下面链接是修改之后全部相关代码的示例(不能完全算MWE, 但编译是通过了的), 整体思路有问题吗

https://github.com/FvNCCR228/SCU_Beamer_Slide-demo/issues/1
