### ISSUE TITLE
有没有哪种输入法或者编辑器，可以中文输入模式下，自动修改输入的字符，尤其可以避免中英文切换

### ISSUE THREAD

**Issue by asmwarrior** [CTeX-org/forum#224]
比如我现在输入`\`，输入的时候。我希望在中文模式下就直接能输入，默认中文模式下输入的时候，就变成中文的顿号了。

再例如大括号`{中文}`，因为括号必须使用英文的括号，所以输入的时候，总是需要中英文反复切换，有时候感觉挺麻烦。

如果有哪个编辑器，能自动识别输入的错误，比如我输入了`｛中文｝`，能自动帮我修正成：`{中文}`，那就再好不过了。

不知道我描述的这些功能，有没有哪个输入法能实现，或者哪个编辑器自带或者可以配置？

谢谢！

**Comment by stone-zeng** [comment]
小狼毫 / 中州韵 / 鼠须管

**Comment by asmwarrior** [comment]
> 小狼毫 / 中州韵 / 鼠须管

我们这里有人这么在配置么？有没有人介绍一下经验？
小狼毫输入法我用过，感觉配置什么的还挺麻烦。

**Comment by syvshc** [comment]
可以看看你的输入法软件中有没有“在中文下输入英文标点”的功能,

**Comment by FvNCCR228** [comment]
我记得微软默认输入法可以设置快捷键切换中英文标点，就是有时候打顿号比较麻烦
