### ISSUE TITLE
如何抑制 `zhlineskip` 的 warning？

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#225]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

我在用 `zhlineskip` 宏包时，加载了 `UseMSWordMultipleLineSpacing` 选项，会产生警告，是由这段代码产生的
https://github.com/CTeX-org/ctex-kit/blob/fcbe2c0e10c494a4813cb54c5f9286e182fd3f24/zhlineskip/zhlineskip.sty#L62-L67
如何抑制？

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\usepackage[UseMSWordMultipleLineSpacing, MSWordLineSpacingMultiple = 1.568]{zhlineskip}
\begin{document}
  测试
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
Use Microsoft Word multiple line spacing
(zhlineskip)	Singlespace to fontsize ratio = `1.296875'
(zhlineskip)	Multiple = `1.568'.
```

**Comment by muzimuzhi** [comment]
其实是个 info (`\PackageInfo`)。忍一下吧

**Comment by sikouhjw** [comment]
> 其实是个 info (`\PackageInfo`)。忍一下吧

我把模板几乎全部 warning 都去掉了，就差这一个了（有点强迫症

**Comment by muzimuzhi** [comment]
```tex
\usepackage{silence}
\WarningFilter{zhlineskip}{Use Microsoft Word multiple line spacing}
\usepackage[UseMSWordMultipleLineSpacing, MSWordLineSpacingMultiple = 1.568]{zhlineskip}
```
这样不好

**Comment by sikouhjw** [comment]
感谢

**Comment by stone-zeng** [comment]
所以这边是不是最好改成 info？
