### ISSUE TITLE
提议将默认的fandol字库更换为founder字库

### ISSUE THREAD

**Issue by Firestar-Reimu** [CTeX-org/forum#229]
https://github.com/CTeX-org/forum/issues/34 的后续

为了解决 Fandol 字体出现的 `Font "FandolSong-Regular" does not contain requested Script "CJK".` 问题和 [字库欠缺](https://stone-zeng.github.io/2019-07-06-use-opentype-fonts-ii/#ctex-%E5%AE%8F%E9%9B%86%E6%8F%90%E9%AB%98%E7%AF%87) 问题，这里提议将默认的fandol字库更换为founder字库，也就是说：

TeXLive中收录的字体从fandol改为方正黑体、方正书宋、方正仿宋、方正楷体，在未识别操作系统（linux操作系统等）使用founder字库，不再支持fandol字库

方正的[授权](https://www.foundertype.com/index.php/About/powerbus.html)见下：

> 方正公司针对“商业发布”行为将方正字体分为“免费字体”、“基础字体”和“精选字体”三类：免费字体：包括五种字体：方正黑体、方正书宋、方正仿宋、方正楷体、 方正甲骨文。针对“商业发布”这种使用方式免费。

还有就是李阿玲在知乎上的一个[回答](https://www.zhihu.com/question/50862287/answer/123206761)：

> 在TeX中可不可以用方正的字体呢？可以，在保证不侵权不修改这两个字体的情况下是可以的。需要做三个事，第一是重新写一个metrics，可能需要重新量一下这两个字体之中的一些符号的高度宽度深度等，而且可能需要写入到几个TFM文件之中。第二是写VF做映射，这几个TFM要分散地映射到这两个TrueType字体之中，对于dvipdfmx，可能还需要在map文件之中写一下配置。第三是写上层的一些宏，plain格式下最为简单，LaTeX中略微繁复一些。这三个都准备好了之后就可以念一句诗然后写文档了。

希望有人能够支持并推进这一提议，也欢迎大家在下面发表自己的意见，谢谢！

**Comment by sikouhjw** [comment]
# 上传到 ctan 需要什么条件？
在提交界面[^1]可以看到，对于提交的文件有 `License type` 的要求。

# 方正免费字体到底是什么？
> 免费字体：包括五种字体：方正黑体、方正书宋、方正仿宋、方正楷体、 方正甲骨文。针对“商业发布”这种使用方式免费。

## 商业发布是什么？
根据方正的《商业授权》[^2]
> 3.商业发布：指以直接营利或者间接营利为目的，将字体作为视觉设计要素，进行复制、发行、展览、放映、信息网络传播、广播等使用字体的行为。

很明显，上传到 ctan 并不是『商业发布』行为，更像是『内置使用』。
> 2.内置使用：指将字库文件整体或部分、直接或格式转换后，以嵌入的方式应用到网站、计算机程序或带有可视化显示功能的电子产品中的行为。

方正免费字体并不对『内置使用』免费。从《方正字库知识产权用户许可协议》[^3]可以看到
> 4.4未经方正电子公司的书面许可，您不得将本字库软件的字型嵌入到可携式文件中（包括但不限于pdf、WORD等文件格式），亦不得将本软件使用于网络上及多用户环境。

综上，如果你想让方正免费字体被 texlive 收录，请去跟方正公司联系。

~~（最好的方式应该是给李阿玲打钱，让他改改 fandol）~~

[^1]: https://ctan.org/upload
[^2]: https://www.foundertype.com/index.php/About/powerbus.html
[^3]: https://www.foundertype.com/index.php/About/powerAllowPro.html

**Comment by zepinglee** [comment]
换成方正字体只为了解决这么一个小小的 warning 有点不合适吧？

1. 这五个字体（尤其是宋体和黑体）没有对应的粗体。
2. 这里说的“免费字体”，不代表可以上传到 CTAN 上（分发）。

解决这个 warning 有几下即中思路：

**Comment by Firestar-Reimu** [comment]
不只是解决warning，默认的字库缺字很多，在overleaf这种在线编辑（它默认fandol）网站上后果更严重，主要还是解决缺字问题

**Comment by muzimuzhi** [comment]
> 方正的[授权](https://www.foundertype.com/index.php/About/powerbus.html)见下：
> 
> > 方正公司针对“商业发布”行为将方正字体分为“免费字体”、“基础字体”和“精选字体”三类：免费字体：包括五种字体：方正黑体、方正书宋、方正仿宋、方正楷体、 方正甲骨文。针对“商业发布”这种使用方式免费。

免的字库大小是什么？如果只是 gb2312，则不能解决缺字问题。

**Comment by Firestar-Reimu** [comment]
编码：GB2312-80(完整) 
字数：7156

**Comment by chenxiao445566** [comment]
严重支持同意用方正作为默认字体

**Comment by Liam0205** [comment]
作为 *nix 下的默认字体，我们需要保证在所有的 OS 发行版下都能工作。在这个考虑之下，缺字不是主要矛盾，「能跑起来」才是主要矛盾。

如 @muzimuzhi 所说，符合授权的方正字体依然缺字，现在用的方正字体又没有授权（需要自行购买、下载）。所以，即使将缺字作为主要矛盾，换用方正字体也不解决问题。

所以不适宜将方正字体作为默认字体。

此帖终结，顺祝新春快乐。

**Comment by Firestar-Reimu** [comment]
楷体找到了一款 https://github.com/lxgw/LxgwWenKai ，但可能和一般的楷体（方正/中易）不是那么像

宋体和黑体可以用Noto/Source Han

仿宋还不知道

**Comment by Sinofine** [comment]
@Firestar-Reimu 霞鹜文楷还是太comic sans了，我个人觉得

**Comment by Sinofine** [comment]
不过可以参考参考这个
https://wiki.ubuntu.com.cn/%E5%85%8D%E8%B4%B9%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93
