### ISSUE TITLE
如何在宏两侧自动插入CJKecglue

### ISSUE THREAD

**Issue by gzxu** [CTeX-org/forum#23]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 描述问题

在中文段落中插入宏展开之后，若展开为英文，则此英文片段和两侧的中文文本之间将没有空白，需要手动插入空格。

* #19
* https://github.com/CTeX-org/ctex-kit/issues/392#issuecomment-481989964 
* https://github.com/CTeX-org/ctex-kit/blob/xeCJK-v3.7.2/xeCJK/xeCJK.dtx#L443

现在已知在某文档内特定的宏展开一定是英文，有没有什么办法可以在这些宏展开时自带空格呢？

一种刀耕火种的思路是

```latex
\let\origeqref\eqref
\renewcommand{\eqref}[1]{ \origeqref{#1} }
\let\origref\ref
\renewcommand{\ref}[1]{~\origref{#1} } % \ref 前面一定是“图”或者“表”
\let\origSI\SI
\renewcommand{\SI}[2]{ \origSI{#1}{#2} }
```

但有个问题，即在宏展开之后跟一个逗号或者句号时，依然会有空格（没试过，我猜的）。请问下大家对于这个场景有没有更好的解决方案呢？多谢！

**Comment by anamewing** [comment]
类似于`图 5 说明了`这样的描述中，`图`和`5`之间总需要有空格，这由你重定义宏来完成。但是5之后有没有空格取决于后面跟的是字符还是标点。
解决方案是文章写好之后手动用正则表达式替换一次，只在需要的情况下加入空格。

我之前在用 cleveref 时遇到了类似的问题，所以下面开头是 `[cC]ref`。式子最后加入那些特定的标点符号，表示紧跟这些符号时不要匹配正则。
把
`(\\[cC]ref\{((fig:|tab:|algo:|thm:|cha:appendix:|sub:|ssub:)[\w\d:-]+,)*((fig:|tab:|algo:|thm:|cha:appendix:|sub:|ssub:)[\w\d:-]+)\})(?!。|：|？|，| |\n|）|（|；|\\|([a-z]\)))`
替换为
`\1 `   （即后面加个空格）

**Comment by zepinglee** [comment]
不建议用带空格的宏，最好手动写到代码里，因为中西文之间的空格使易读性更好

**Comment by gzxu** [comment]
谢谢各位的建议，我还是比较好奇如何在不重构文档的情况下实现这个效果呢  :thinking:

**Comment by muzimuzhi** [comment]
一个尝试。具体原理和可能的风险，我也不清楚。

```latex
\documentclass{ctexart}
\usepackage{siunitx}

\makeatletter
\def\ref#1{${}$\expandafter\@setref\csname r@#1\endcsname
  \@firstoftwo{#1}${}$}
\def\pageref#1{${}$\expandafter\@setref\csname r@#1\endcsname
  \@secondoftwo{#1}${}$}
% caution: complete syntax of \SI is \SI[#1]{#2}[#3]{#4}
\def\SInew#1#2{${}$\SI{#1}{#2}${}$}
\makeatother

\def\test#1{#1\ref{eqn}#1\pageref{eqn}#1\SInew{3.14}{m/s}#1\par}

\begin{document}
\begin{equation}\label{eqn}
	a = 10
\end{equation}

\subsection{与英文字母和标点连缀时}
\test{a} \test{,} \test{.} 

\subsection{与中文汉字和标点连缀时}
\test{字} \test{。} \test{，} \test{“} \test{”}
\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/56090201-973c5480-5ed1-11e9-82c9-4c3f8bc76b3a.png)

**Comment by anamewing** [comment]
@muzimuzhi 看起来在使用了 hyperref 包之后，这个方法在中文汉字与引用之间加的空格依然会失效。
那么为什么 hyperref 会改变空格呢？

**Comment by muzimuzhi** [comment]
以上只是瞎试的结果，不具有普遍性。如果你需要解决具体文档里的问题，提供 MWE。
