### ISSUE TITLE
是否可能在保持全局恒定 CJK 字距的前提下，每行动态空格宽度，以实现 justify 

### ISSUE THREAD

**Issue by neruthes** [CTeX-org/forum#230]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [x] Linux（Gentoo）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

这是一段示例文本。我需要这段文本两端对齐；这在 LaTeX 中是经典的实践。但这会导致一个问题：每行的汉字间距有差异。我希望汉字和其他一切全角字符（包括但不限于标点符号、假名、谚文）之间具有恒定的宽度。由 justify 带来的间距调整负担，由行内所有空格承受。

进一步地，是否可能保障每个 CJK 字符都在矩阵网格内？即，每个 CJK 字符到行左端的距离必然是字宽的整数倍。

另注：以上叙述认为 CJK 字符与西文间存在一种名为空格的字符，这未必符合 TeX 家族排版引擎对空格问题的理解。本人确实在源代码内保障空格存在。

![image](https://user-images.githubusercontent.com/2139261/153807996-f26091b5-2625-4ec9-b4e2-20c074d6ae59.png)

## 最小工作示例（MWE）

```latex
\documentclass[12pt,a4paper]{article}
\usepackage[textwidth=19em,vmargin=30mm]{geometry}
\usepackage{xeCJK}

\begin{document}
\parindent=0pt

这是一段示例文本。
我需要这段文本两端对齐；这在 LaTeX 中是经典的实践。
但这会导致一个问题：每行的汉字间距有差异。
我希望汉字和其他一切全角字符（包括但不限于标点符号、假名、谚文）之间具有恒定的宽度。
由 justify 带来的间距调整负担，由行内所有空格承受。

另注：以上叙述认为 CJK 字符与西文间存在一种名为空格的字符，这未必符合 TeX 家族排版引擎对空格问题的理解。本人确实在源代码内保障空格存在。

\end{document}
```

## 我还做了这些尝试

搜索引擎和本论坛未见相关讨论。

**Comment by muzimuzhi** [comment]
`\xeCJKsetup{CJKglue=\hskip 0pt, PunctStyle=hangmobanjiao}` 很接近你想要的效果。100% 实现可能需要定义新的标点处理格式，见 `\xeCJKDeclarePunctStyle` 相关文档和 [`xeCJK.dtx`](https://github.com/CTeX-org/ctex-kit/blob/master/xeCJK/xeCJK.dtx) 里的相关应用

**Comment by neruthes** [comment]
> `\xeCJKsetup{CJKglue=\hskip 0pt, PunctStyle=hangmobanjiao}` 很接近你想要的效果。100% 实现可能需要定义新的标点处理格式，见 `\xeCJKDeclarePunctStyle` 相关文档和 [`xeCJK.dtx`](https://github.com/CTeX-org/ctex-kit/blob/master/xeCJK/xeCJK.dtx) 里的相关应用

![image](https://user-images.githubusercontent.com/2139261/162127641-db55a2e0-c858-4b70-bb8a-53c2345036cf.png)

实践成果比较理想，感谢。

**Comment by neruthes** [comment]
阅读 xeCJK 文档后继续尝试 `\usepackage[PunctStyle=plain,CJKglue=\hskip 0pt,xCJKecglue=true,CJKecglue=\hfill]{xeCJK}` 得到了更好的结果，但 CJK/nonCJK 与 nonCJK/CJK 的空白不等宽，有些遗憾。

![image](https://user-images.githubusercontent.com/2139261/162232534-e22eeb42-804b-4069-b069-323982e7fad0.png)

**Comment by neruthes** [comment]
最新进展：

鉴于语言切换次数比较少，我现在手动添加 `\nSpecialGlue` 来拉开距离。

```
\newcommand{\nSpecialGlue}[0]{\hskip 2pt\hfill}
```

![image](https://user-images.githubusercontent.com/2139261/162372611-e077c8d2-0762-4355-80ec-d88c214daa70.png)

![image](https://user-images.githubusercontent.com/2139261/162372646-8b574cb1-a2ba-4fd0-8c2b-da14d23b44e0.png)

**Comment by neruthes** [comment]
后续：


使用 `CJKglue=,CJKecglue=\hskip 5pt plus 20pt` 能够满足我的需求
