### ISSUE TITLE
如何在 latex3 语法中让 patch 浮动体间距的代码起作用？

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#232]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

我想在模板中添加一段 patch 浮动体间距的代码，可是这段代码放在 latex3 语法中不起作用，我尝试用 `~` 替代空格也没用。

## 最小工作示例（MWE）

```latex
\begin{filecontents*}{test.cls}
\NeedsTeXFormat{LaTeX2e}[2020/10/01]
\RequirePackage{expl3}
\ProvidesExplClass{test}
  {2022/02/28}{v0.1d}{Thesis Template for Guangdong University of Technology}
\LoadClass { ctexbook }
\RequirePackage{xpatch}
\patchcmd{\@addtocurcol}%
  {\vskip \intextsep}%
  {\edef\save@first@penalty{\the\lastpenalty}\unpenalty
   \ifnum \lastpenalty = \@M  % hopefully the OR penalty
     \unpenalty
   \else
     \penalty \save@first@penalty \relax % put it back
   \fi
   \ifnum\outputpenalty <-\@Mii
     \addvspace\intextsep
     \vskip\parskip
   \else
     \addvspace\intextsep
   \fi}%
  {\typeout{*** SUCCESS ***}}{\typeout{*** FAIL ***}}
\patchcmd{\@addtocurcol}%
  {\vskip\intextsep \ifnum\outputpenalty <-\@Mii \vskip -\parskip\fi}%
  {\ifnum\outputpenalty <-\@Mii
     \aftergroup\vskip\aftergroup\intextsep
     \aftergroup\nointerlineskip
   \else
     \vskip\intextsep
   \fi}%
  {\typeout{*** SUCCESS ***}}{\typeout{*** FAIL ***}}
\patchcmd{\@getpen}{\@M}{\@Mi}
  {\typeout{*** SUCCESS ***}}{\typeout{*** FAIL ***}}
\endinput
\end{filecontents*}

\documentclass{test}
\usepackage{mwe,zhlipsum}
\begin{document}
\zhlipsum[1]

\begin{figure}[h]
  \includegraphics[width=0.4\textwidth]{example-image.pdf}
\end{figure}

\zhlipsum[1]
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
***FAIL***
***FAIL***
***FAIL***
```

## 链接

- TeX.SX: https://tex.stackexchange.com/questions/39867/intextsep-gives-doubled-space/40363#40363
- zhihu: https://www.zhihu.com/question/46618031

**Comment by zepinglee** [comment]
似乎可以用 `ctex` 的 `\ctex_patch_cmd:Nnn`？

https://github.com/CTeX-org/ctex-kit/blob/a8907eefdd8b69a609f94c016d017fa96dd5f146/ctex/ctex.dtx#L11771-L11784

**Comment by muzimuzhi** [comment]
你需要临时恢复 space char 的 catcode，
```tex
\char_set_catcode_space:n {32}
\xpatchcmd ...
\char_set_catcode_letter:n {32}
```
也可以用 `l3cctab`.

`\(x)patchcmd` 使用 `\scantokens` 重建命令（的 replacement text）时，依赖当前的 catcode table。命令定义里有 space char 时，patch 前要将 space 的 catcode 恢复。
```tex
\def\a{a a} % patch \a 时，要保证 \the\catcode`\ 是 10 (space)

\ExplSyntaxOn
\cs_new:Npn \b {b ~ b} % 这里的 ~ 会变成 catcode 10，char code 32 的正常 space char
                       % 可以用 \tl_analysis_show:N \b 查看
                       % 所以，patch \b 时，同样要保证 \the\catcode`\ 是 10 (space)
\ExplSyntaxOff
```

其他
 - 有 `\tracingpatches` 可以增加 debug 输出，看看在哪一步 patch 失败
 - 加载了 `xpatch`，何不用 `\xpatchcmd`
 - 例子不够精简，只要 `\ExplSyntaxOn \(x)patchcmd ... \ExplySyntaxOff` 就能复现问题

相似回答
 - https://tex.stackexchange.com/a/623487

**Comment by sikouhjw** [comment]
> 似乎可以用 `ctex` 的 `\ctex_patch_cmd:Nnn`？

是的，经测试没有问题。感谢。

> 你需要临时恢复 space char 的 catcode，
> 
> ```
> \char_set_catcode_space:n {32}
> \xpatchcmd ...
> \char_set_catcode_letter:n {32}
> ```

这里应该不是用 `\char_set_catcode_letter:n`，测试时会报错，应该是 `\char_set_catcode_ignore:n`。

>     * 加载了 `xpatch`，何不用 `\xpatchcmd`
>     * 例子不够精简，只要 `\ExplSyntaxOn \(x)patchcmd ... \ExplySyntaxOff` 就能复现问题

犯傻了，MWE 没做好。


最省事的办法应该还是用 `\ctex_patch_cmd:Nnn`。
