### ISSUE TITLE
VS code（latex workshop）+texlive的x-b-x-x编译链无法自动完成

### ISSUE THREAD

**Issue by Hodorzh** [CTeX-org/forum#233]
## 编译环境

- 操作系统
  - [x] Windows 11
 

- TeX 发行版
  - [x] TeX Live <-- 2021-->

## 描述问题

<--
    VS code（latex workshop）+texlive的x-b-x-x编译链无法自动完成。我用的是nst给的模板，里面的交叉引用在完成一次xelatex后显示问号，采用x-b-x-x在第二步处编译链停止，手动完成四个步骤是可以的。
-->

## 附件
这是问题的LaTex文件
[Template for Nuclear Science and Techniques Journal.zip](https://github.com/CTeX-org/forum/files/8349544/Template.for.Nuclear.Science.and.Techniques.Journal.zip)
这个文件时我在vs code里的设置json文件
[settings.zip](https://github.com/CTeX-org/forum/files/8349548/settings.zip)

**Comment by Hodorzh** [comment]
我在目标模板的编译中，一次XeLaTex编译后交叉引用显示问号，采用x-b-x-x编译链在第二步处编译链中断，不继续编译。手动点击x，b，x，x能完成编译。

**Comment by muzimuzhi** [comment]
> VS code（latex workshop）+texlive的x-b-x-x编译链无法自动完成。我用的是nst给的模板，里面的交叉引用在完成一次xelatex后显示问号，采用x-b-x-x在第二步处编译链停止，手动完成四个步骤是可以的。

不能复现问题，点击你配置文件里的 "Recipe: xe->bib->xe->xe" 能正常编译。可以提供编译链停止时的 log 吗，xelatex 的 log 是 `nst_template.log` 文件，bibtex 的 log 是 `nst_template.blg`。

**Comment by Hodorzh** [comment]
> > VS code（latex workshop）+texlive的x-b-x-x编译链无法自动完成。我用的是nst给的模板，里面的交叉引用在完成一次xelatex后显示问号，采用x-b-x-x在第二步处编译链停止，手动完成四个步骤是可以的。
> 
> 不能复现问题，点击你配置文件里的 "Recipe: xe->bib->xe->xe" 能正常编译。可以提供编译链停止时的 log 吗，xelatex 的 log 是 `nst_template.log` 文件，bibtex 的 log 是 `nst_template.blg`。

我也复现不出来了0.0，下次遇到了我先把日志保存下来。谢谢。
