### ISSUE TITLE
在overleaf上无法正常运行，请求帮助😜

### ISSUE THREAD

**Issue by redhat123456** [CTeX-org/forum#237]
## 检查

- [ ] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

overleaf无法正常使用
![image](https://user-images.githubusercontent.com/57751257/163679922-953bcf5a-4d9f-4982-9a90-aed7e16cf31a.png)

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\begin{document}
Hello, \LaTex!
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
! Undefined control sequence.
l.3 Hello, \LaTex
                 !
?
```

## 链接

- TeX.SX:
- GitHub:

**Comment by Sinofine** [comment]
@redhat123456 打错字了

**Comment by redhat123456** [comment]
@Sinofine 能具体指出来吗？不怎么会用Latex以及对overleaf编辑器不熟悉

**Comment by Sinofine** [comment]
@redhat123456 没, 你没删干净模板内容; 请给出你的代码的最小示例(删去没有用的东西)

**Comment by redhat123456** [comment]
@Sinofine 还是不知道要删那一部分的内容，要不大佬给一份可行的LaTex模板关于mathorcup杯，也许（

**Comment by sikouhjw** [comment]
当时写的时候就没想过在 Overleaf 上用，Overleaf 上没有 windows 下的字体，所以编译不了。

把字体设置全注释应该就可以了。

**Comment by muzimuzhi** [comment]
> Please never ever post images of code.
> --- [daleif](https://tex.stackexchange.com/questions/640002/the-function-and-meaning-of-variable-afterindenttrue#comment1595225_640002)

提问时，请总是考虑到，要提供足够的信息，让他人能在各自的电脑上复现问题。只有一张截图，是信息不足的。具体到你的提问
 - 可以提供一个例子（把 tex 文件全文复制、粘贴过来，放进 markdown 的 [fenced code block](https://github.github.com/gfm/#fenced-code-blocks)），并文字说明「这个例子，在 overleaf 上编译出错，错误信息是xxx」。
 - 可以在删去敏感信息后，打包下载那个项目，然后发到这里
 - overleaf 有项目分享功能，可以直接提供项目的权限尾只读或可编辑的分享链接（最好不要这么做，因为这让这个 issue 不是独立的，一旦关闭 overleaf 分享，这个 issue 对未来的读者就意义很小）

**Comment by sikouhjw** [comment]
把这两行注释
https://github.com/sikouhjw/MathorCupmodeling/blob/40c89e7d33878cc58ecc69b0e20ce8894e9426c3/MathorCupmodeling.cls#L36-L37
然后将编译方式改为 `xelatex`，就可以编译了。

PS：题问模板在 [https://github.com/sikouhjw/MathorCupmodeling](https://github.com/sikouhjw/MathorCupmodeling)，历史遗留产物，我懒得改了。
