### ISSUE TITLE
使用 `chapter/break={}` 设置 `\chapter` 不分页时会出现预期之外的排版

### ISSUE THREAD

**Issue by syvshc** [CTeX-org/forum#238]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 11

- TeX 发行版
  - [x] TeX Live 2022

## 描述问题

我想设置 `ctexbook` 文档类中 `\chapter` 不换页, 为此我使用了

```tex
\ctexset{chapter/break={}}
```

来将 `break` 置空, 但是当一页的内容的数量特殊时, 会有本来可以被排版下的内容被挤到新的一页, 详见 MWE

## 最小工作示例（MWE）

```latex
\documentclass[openany]{ctexbook}
\usepackage{showframe}
\usepackage{zhlipsum}
\newcommand{\test}
  {
    劳仑衣普桑，认至将指点效则机，最你更枝。想极整月正进好志次回总
    般，段然取向使张规军证回，世市总李率英茄持伴。用阶千样响领交出，器
    程办管据家元写，名其直金团。化达书据始价算每百青，金低给天济办作照
    明，取路豆学丽适市确。如提单各样备再成农各政，设头律走克美技说没，
    体交才路此在杠。响育油命转处他住有，一须通给对非交矿今该，花象更面
    据压来。与花断第然调，很处己队音，程承明邮。常系单要外史按机速引也
    书，个此少管品务美直管战，子大标蠢主盯写族般本。农现离门亲事以响规，
    局观先示从开示，动和导便命复机李，办队呆等需杯。见何细线名必子适取
    米制近，内信时型系节新候节好当我，队农否志杏空适花。又我具料划每地，
    对算由那基高放，育天孝。派则指细流金义月无采列，走压看计和眼提问接，
    作半极水红素支花。果都济素各半走，意红接器长标，等杏近乱共。层题提
    万任号，信来查段格，农张雨。省着素科程建持色被什，所界走置派农难取
    眼，并细杆至志本。
    她己道按收面学上全始，形万然许压己金史好，力住记赤则引秧。处高
    方据近学级素专，者往构支明系状委起查，增子束孤不般前。相斗真它增备
    听片思三，听花连次志平品书消情，清市五积群面县开价现准此省持给，争
    式身在南决就集般，地力秧众团计。日车治政技便角想持中，厂期平及半干
    速区白土，观合村究研称始这少。验商眼件容果经风中，质江革再的采心年
    专，光制单万手斗光就，报却蹦杯材。内同数速果报做，属马市参至，入极
    将管医。但强质交上能只拉，据特光农无五计据，来步孤平葡院。江养水图
  }
\ctexset{chapter/break={}}
\begin{document}
  \chapter{测试1}
  \test
  \clearpage
  \chapter{测试2}
  \test

  \chapter{测试2}
  \zhlipsum
\end{document}
```

（用 XeLaTeX 编译后）输出

第一页:

![image](https://user-images.githubusercontent.com/38098591/164196927-368b2274-31af-4ec8-9eee-81da252f48a0.png)

可以看到文字的底部下面还有很大的空白. 

第二页

![image](https://user-images.githubusercontent.com/38098591/164197078-fd210a7f-5b45-45a2-b00e-4d2625d40194.png)

可以看到章标题的上面和下面有着比第一页更大的空白, 并且将文字挤到了页面底部, 

第三页

![image](https://user-images.githubusercontent.com/38098591/164197252-83dbfd1a-7834-40b6-8e33-ab7dcab7bfb1.png)

这一页的顶部仍有第二页的剩余文字, 第二, 三页的表现与预期不符. 我猜测原因是如果按第一页的方法去排, 剩余的空间不足以放下一个 `\chapter` 标题, 或者一页不能以 `\chapter` 结尾. 但是看起来也不能以 `\chapter` 开头, 否则就不会留下一行. 

而同样的事情在 `\section` 标题之间就不会出现. 如下

```latex
\documentclass{ctexart}
\usepackage{showframe}
\usepackage{zhlipsum}
\ctexset{section/break={}}
\begin{document}
  \section{测试1}
\zhlipsum[1-2]
  \clearpage
  \section{测试2}
\zhlipsum[1-2]
  \section{测试2}
  \subsection{测试2}
  \subsubsection{测试2}
  \zhlipsum
\end{document}
```

![image](https://user-images.githubusercontent.com/38098591/164198151-79b5bf01-4cc4-4234-b23f-25f555cc018b.png)

![image](https://user-images.githubusercontent.com/38098591/164198190-1e0fab8e-9eca-46f1-b9bb-d98aa8a9b4ec.png)

请问是我设置不换页的方法错误吗, 还是另有原因呢?

**Comment by sikouhjw** [comment]
设置成
```tex
\ctexset{chapter/break={\par\mbox{}\par}}
```
就可以正确分页并且段前间距正确，为什么需要两个 `\par` 就不清楚了。

**Comment by syvshc** [comment]
设置成这样的话可以不让文字被放到第三页, 但是间距仍然不正确

![image](https://user-images.githubusercontent.com/38098591/164212708-99652eb5-a9be-4471-ad2d-aaab59d7d1ae.png)

**Comment by muzimuzhi** [comment]
参考 `texdoc ctex`, 表20 "break 选项的默认设置"，用
```tex
\makeatletter
\ctexset{chapter/break=\addpenalty{\@secpenalty}}
\makeatother
```

> ```tex
> \ctexset{chapter/break={\par\mbox{}\par}}
> ```

相当于插入了一个空行。

**Comment by syvshc** [comment]
> `\ctexset{chapter/break=\addpenalty{\@secpenalty}}`

我尝试使用这个方法, 得到的效果和 `\ctexset{chapter/break={\par\mbox{}\par}}` 几乎相同, 是不是与 `\chapter` 和 `\section` 的定义方式不同有关呢?

![image](https://user-images.githubusercontent.com/38098591/164358800-ac7976eb-3b33-411e-b58e-d0420926277a.png)

**Comment by syvshc** [comment]
可以使用 `\ctexset{chapter/break=\addpenalty{\@secpenalty}, chapter/fixskip=true}` 来解决:

```latex
\documentclass[openany]{ctexbook}
\usepackage{showframe}
\usepackage{zhlipsum}
\newcommand{\test}
  {
    劳仑衣普桑，认至将指点效则机，最你更枝。想极整月正进好志次回总
    般，段然取向使张规军证回，世市总李率英茄持伴。用阶千样响领交出，器
    程办管据家元写，名其直金团。化达书据始价算每百青，金低给天济办作照
    明，取路豆学丽适市确。如提单各样备再成农各政，设头律走克美技说没，
    体交才路此在杠。响育油命转处他住有，一须通给对非交矿今该，花象更面
    据压来。与花断第然调，很处己队音，程承明邮。常系单要外史按机速引也
    书，个此少管品务美直管战，子大标蠢主盯写族般本。农现离门亲事以响规，
    局观先示从开示，动和导便命复机李，办队呆等需杯。见何细线名必子适取
    米制近，内信时型系节新候节好当我，队农否志杏空适花。又我具料划每地，
    对算由那基高放，育天孝。派则指细流金义月无采列，走压看计和眼提问接，
    作半极水红素支花。果都济素各半走，意红接器长标，等杏近乱共。层题提
    万任号，信来查段格，农张雨。省着素科程建持色被什，所界走置派农难取
    眼，并细杆至志本。
    她己道按收面学上全始，形万然许压己金史好，力住记赤则引秧。处高
    方据近学级素专，者往构支明系状委起查，增子束孤不般前。相斗真它增备
    听片思三，听花连次志平品书消情，清市五积群面县开价现准此省持给，争
    式身在南决就集般，地力秧众团计。日车治政技便角想持中，厂期平及半干
    速区白土，观合村究研称始这少。验商眼件容果经风中，质江革再的采心年
    专，光制单万手斗光就，报却蹦杯材。内同数速果报做，属马市参至，入极
    将管医。但强质交上能只拉，据特光农无五计据，来步孤平葡院。江养水图
  }
\makeatletter
\ctexset{chapter/break=\addpenalty{\@secpenalty}, chapter/fixskip=true}
\makeatletter
\begin{document}
  \chapter{测试1}
  \test
  \clearpage
  \chapter{测试2}
  \test

  \chapter{测试2}
  \zhlipsum
\end{document}
```

![image](https://user-images.githubusercontent.com/38098591/166092035-42b8989a-25e3-4ec2-a040-48826aca2cfe.png)

![image](https://user-images.githubusercontent.com/38098591/166092036-a4b11a45-f795-4c85-bf17-37adb3da2fbd.png)

**Comment by KingCrimsonWWW** [comment]
你好我想请问一下，在这个模板里面怎么添加该命令
`\ctexset{chapter={format={\centering \heiti \zihao{-2}}, number={   % 各章标题 黑体小2号 // 修改：标题和数字字号一致 
    \arabic{chapter}},name={,},afterskip={0.5ex},beforeskip={0.8ex}}}`
