### ISSUE TITLE
[灌水]大家有没有「知道各种排版技巧但不知道到底用哪种排版风格」的问题

### ISSUE THREAD

**Issue by gzxu** [CTeX-org/forum#24]
类似的问题很多，比如

* 知道Photoshop的各种用法但是不知道该把照片P成什么样
* 知道DIV+CSS的各种操作但是不知道该做成什么风格的网页
* 知道各种女生的风格、喜好，但是不知道该和谁终此一生

简言之，就是想讨chuī论shuǐ下大家的审美偏好都是怎么培养起来的？

对于LaTeX而言大多数地方都是模板所限定的，但不少地方是模板所没有覆盖到的，比如TikZ图形中文本和边框的间距、复杂公式的具体处理方式等等，这些问题不仅有不少不同的处理风格和流派，而且更为关键的是，有时候我觉得这些主流的方案都不能让我满意，但却不能提出一种让自己满意的，这

> 才是坠痛苦的

闲来吹水，如有打扰，烦请谅解🤣

**Comment by Liam0205** [comment]
额，我就是极简风。

**Comment by stone-zeng** [comment]
当然是看别人怎么做了。[我的 blog](https://stone-zeng.github.io/) 就是「借鉴了」[楼上这位的](https://liam.page/)，以及 type is beautiful（现在叫 [the type](https://thetype.com/)）的样式。
