### ISSUE TITLE
关于首字下沉的一个问题

### ISSUE THREAD

**Issue by chenxiao445566** [CTeX-org/forum#244]
```
\documentclass{ctexart}
\usepackage{lettrine}

\begin{document}
\lettrine[lines=2]{段}文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文

\lettrine[lines=3]{段}文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文

\end{document}
```
![首字下沉](https://user-images.githubusercontent.com/98209931/170388267-f1817a40-5132-46fe-94ac-2d994c7ab649.PNG)
两个问题：（1）首字之后的第一行左边与第二行左边的第一个字没有对齐，（2）当首字占三行时，首字与下方的文字太靠近。
请大佬帮忙看看如何解决？

**Comment by muzimuzhi** [comment]
```tex
\documentclass{ctexart}
\usepackage{lettrine}

\setlength{\DefaultNindent}{0pt} % initially 0.5em

\begin{document}

\lettrine[lines=2]{段}文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文

\lettrine[lines=3, loversize=-.15, lraise=.1]{段}文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字文字

\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/170395325-7f3c3f80-f04a-472c-b84c-e6cd27690eca.png)



> 两个问题：（1）首字之后的第一行左边与第二行左边的第一个字没有对齐，

这是宏包的默认设置，`\setlength{\DefaultNindent}{0pt}` 做了全局修改。

>（2）当首字占三行时，首字与下方的文字太靠近。

大多中文字体下，汉字是有深度（depth，基线以下的部分）的，而 `lines=<integer>` 的空行是只为高度（height）留的。这在在字号较小时不明显，较大时（`lines=3`）就看出来了。做的调整是，先缩小 15% 的尺寸 `loversize=-.15`，然后向上移动 10% 的高度 `lraise=.1`。

建议
 - 插入代码时，开始处的标记，可以用 ` ```tex ` 代替 ` ``` `，来指定按 tex 进行高亮。有高亮的代码更易读。
 - 逐渐养成读文档的习惯，这些选项的文档都在 `texdoc lettrine` 的第一页，`\DefaultNindent` 在第三页。
 - 减少 大佬、大神 等词的使用

**Comment by chenxiao445566** [comment]
谢谢周老师解答！我虚心接受！
