### ISSUE TITLE
ctex导致公式解析错误 ～bug

### ISSUE THREAD

**Issue by ARC-MX** [CTeX-org/forum#245]
使用ctex库以后，发现公式中的-变成* {}等符号都解析错误，
具体错误信息，我提交在<https://tex.stackexchange.com/questions/645470/>论坛上，希望尽快解决bug

**Comment by AlphaZTX** [comment]
长时间无人回复，并且问题已解决（See [TeX.SE](https://tex.stackexchange.com/questions/645470/getting-wrong-math-formula-with-ctex)），因此关闭issue。
