### ISSUE TITLE
xelatex 编译出来的 PDF 在打印机和 ghostscript 上乱码

### ISSUE THREAD

**Issue by neruthes** [CTeX-org/forum#246]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [x] Linux (Gentoo)

- TeX 发行版
  - [x] TeX Live 2021
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

使用 xelatex 编译 LaTeX 文档得到 PDF 产物，在部分阅读器上乱码。

乱码阅读器：

- ESPON L3151 打印机 (使用 CUPS 提供的 `lp` 命令打印)
- ghostscript (`9.56.1 (2022-04-04)`)

无乱码阅读器：

- Firefox (Gentoo)
- masterpdfeditor5 (Gentoo)
- mupdf (Gentoo)
- Firefox (iOS)
- Safari (iOS)
- 微信 (iOS)
- Telegram (iOS)

## 最小工作示例（MWE）

```latex
\documentclass[a4paper,12pt]{article}
\usepackage[a4paper,textwidth=36em,tmargin=28mm,bmargin=28mm]{geometry}
\usepackage{xeCJK}
\begin{document}
\LARGE
苟利国家生死以，岂因祸福避趋之。\par
苟利国家生死以，岂因祸福避趋之。\par
苟利国家生死以，岂因祸福避趋之。\par
苟利国家生死以，岂因祸福避趋之。\par
苟利国家生死以，岂因祸福避趋之。\par
苟利国家生死以，岂因祸福避趋之。\par
苟利国家生死以，岂因祸福避趋之。\par
苟利国家生死以，岂因祸福避趋之。\par
苟利国家生死以，岂因祸福避趋之。\par
苟利国家生死以，岂因祸福避趋之。\par
苟利国家生死以，岂因祸福避趋之。\par
苟利国家生死以，岂因祸福避趋之。\par
苟利国家生死以，岂因祸福避趋之。\par
苟利国家生死以，岂因祸福避趋之。\par
\end{document}
```

（用 XeLaTeX 编译后）输出

```
This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021 Gentoo Linux) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-02-18>
(/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size12.clo))
(/usr/share/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texmf-dist/tex/generic/iftex/ifvtex.sty
(/usr/share/texmf-dist/tex/generic/iftex/iftex.sty)))
(/usr/share/texmf-dist/tex/xelatex/xecjk/xeCJK.sty
(/usr/share/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texmf-dist/tex/latex/l3backend/l3backend-xetex.def
(|extractbb --version)))
(/usr/share/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
(/usr/share/texmf-dist/tex/latex/l3packages/xtemplate/xtemplate.sty)
(/usr/share/texmf-dist/tex/latex/l3packages/xparse/xparse.sty
(/usr/share/texmf-dist/tex/latex/l3packages/xparse/xparse-2020-10-01.sty
(/usr/share/texmf-dist/tex/latex/l3packages/xparse/xparse-generic.tex)))
(/usr/share/texmf-dist/tex/latex/ctex/ctexhook.sty)
(/usr/share/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/share/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(/usr/share/texmf-dist/tex/latex/base/fontenc.sty)
(/usr/share/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(/usr/share/texmf-dist/tex/xelatex/xecjk/xeCJK.cfg))

Package xeCJK Warning: Fandol is being set as the default font for CJK text.
(xeCJK)                Please make sure it has been properly installed.


Package fontspec Warning: Font "FandolSong-Regular" does not contain requested
(fontspec)                Script "CJK".

(./test.aux) (/usr/share/texmf-dist/tex/latex/base/ts1cmr.fd)
*geometry* driver: auto-detecting
*geometry* detected driver: xetex
[1] (./test.aux) )
Output written on test.pdf (1 page).
Transcript written on test.log.
```

###

ghostscript 转换命令：

```
gs \
    -dNOPAUSE \
    -dBATCH \
    -sDEVICE="jpeg" \
    -r300 \
    -dGraphicsAlphaBits=4 \
    -dTextAlphaBits=4 \
    -sOutputFile="test.jpg" \
    "test.pdf"
```

### 打印机乱码

![image](https://user-images.githubusercontent.com/2139261/171380862-08d792a0-237f-4b37-a1e8-66f7fb1fd668.png)

### ghostscript 乱码

![test](https://user-images.githubusercontent.com/2139261/171381473-534a861a-32a8-45c4-9d87-49f2d76a9940.jpg)

### PDF 产物

[test.pdf](https://github.com/CTeX-org/forum/files/8813164/test.pdf)

**Comment by neruthes** [comment]
## 其他引擎测试非 CJK 文档

测试流程相同，编译 PDF 后交给 ghostscript 转换成 JPEG，查看 JPEG 内文本是否符合预期。

- lualatex 乱码
- pdflatex 正常

源代码：

```
\documentclass[a4paper,12pt]{article}
\usepackage[a4paper,textwidth=36em,tmargin=28mm,bmargin=28mm]{geometry}
\begin{document}
\LARGE
Hello world.

Lorem ipsum dolor sit amet.

I jump over the lazy dog; it doesn't hurt me.
\end{document}
```

![test](https://user-images.githubusercontent.com/2139261/171545044-fc8a64d5-01bf-4089-8b42-0be7bff225d2.jpg)


## 测试别人的 PDF

测试了 xeCJK 的首页

PDF：[xeCJK_page1-1.pdf](https://github.com/CTeX-org/forum/files/8820417/xeCJK_page1-1.pdf)

ghostscript：

![xeCJK_page1-1 pdf 1](https://user-images.githubusercontent.com/2139261/171545363-7f25517e-2b78-4832-a377-0bfd0d1ef00d.jpg)

打印机：

![image](https://user-images.githubusercontent.com/2139261/171545618-1e162cea-7f64-4d08-ba28-171a477193cf.png)


----------------------


所以可以猜测问题并非出在 TeX 本身，但 ghostscript 与 EPSON 打印机同时乱码成相同的样子实在诡异，，，

**Comment by Sinofine** [comment]
[t.pdf](https://github.com/CTeX-org/forum/files/8820632/t.pdf)
windows下的lualatex编译你的文档

**Comment by Sinofine** [comment]
<img width="994" alt="image" src="https://user-images.githubusercontent.com/47494321/171551817-fb2d03ed-7ff1-46c8-9680-fbd33b046117.png">
![t](https://user-images.githubusercontent.com/47494321/171551931-7dcff0db-9183-48ec-80a8-b4527c9ac6cf.png)
在windows上的gs使用上面编译的文件显示正常
你要不要在你电脑上看一下

**Comment by Sinofine** [comment]
在archlinux下的

GPL Ghostscript 9.56.1

This is LuaHBTeX, Version 1.15.0 (TeX Live 2022/Arch Linux) 

This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022/Arch Linux) (preloaded format=xelatex)

下也有正常输出,下附导出jpg. 采用文中给的转换命令

![test](https://user-images.githubusercontent.com/47494321/171553895-a9841086-f567-4a17-97c8-1d2357894a7e.jpg)

![test2](https://user-images.githubusercontent.com/47494321/171553902-5f3ddf6a-294b-4760-aa92-7b447c566895.jpg)

**Comment by neruthes** [comment]
感谢大家的协助。现在看来，此现象更多是 CUPS 的问题而非 TeX 的问题。我会关闭此 issue 以免过多占用列表版面资源，但问题本身尚未解决，我仍然欢迎调查思路方面的讨论。
