### ISSUE TITLE
如何使 figure 的 caption 置顶的同时使 subfigure 的 caption 置底？

### ISSUE THREAD

**Issue by rosekc** [CTeX-org/forum#25]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2018
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

用 `floatrow` 包可以使两者同时置顶。

```tex
\usepackage{floatrow}
\floatsetup[figure]{capposition=top}

\begin{figure}[htbp]
    \centering
    \subfloat[subfig caption a]{
        \includegraphics[width=100px]{...}
    }
    \subfloat[subfig caption b]{
        \includegraphics[width=100px]{...}
    }
    \caption{main caption}\label{fig:padding_demo}
\end{figure}
```
但是不能分别设置 subfig 的 caption 位置。

```tex
\usepackage{floatrow}
\floatsetup[figure]{capposition=top}
\floatsetup[subfigure]{capposition=bottom}
```

以上设置无效。

请问如何使 figure 的 caption 置顶的同时使 subfigure 的 caption 置底？

**Comment by muzimuzhi** [comment]
0. 你的例子不完整，提问应提供从 `\documentclass` 开始，到 `\end{document}` 结束的完整例子
0.1. 你的例子里，`width=100px` 里使用了非法单位 `px`
0.2. 例子里如需插图，可考虑使用 `mwe` 宏包提供的示例图片

1. 试试这个例子，仅依赖 `subfig` 宏包

```latex
\documentclass{article}
\usepackage{mwe}
\usepackage{subfig}
\captionsetup[figure]{position=top}
\captionsetup[subfigure]{position=bottom}

\begin{document}
\begin{figure}
    \centering
    \caption{main caption}
    \subfloat[subfig caption a]{
        \includegraphics[width=100pt]{example-image-a}
    }
    \subfloat[subfig caption b]{
        \includegraphics[width=100pt]{example-image-b}
    }
\end{figure}
\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/56762752-2e0ee800-67d3-11e9-8664-00aa3f8acc23.png)

2. 一些说明
2.1. 对 `<type> = figure | table` 而言，`\captionsetup[<type>]{position=top}` 影响的是 `\caption` 上下的纵向间距，`\caption` 输出时具体是置顶还是置底，由输入顺序指定。见 `caption` 宏包文档，Sec. 2.6，选项 `caption` 相关段落。
2.2. 对 `<type> = subfigure | subtable` 而言，`\captionsetup[<type>]{position=top}` 既影响上下间距，又影响子图标题输出时的置顶/置底位置。

**Comment by rosekc** [comment]
好的感谢指导。
