### ISSUE TITLE
Beamer中的footnote被footline遮盖住，如何解决？

### ISSUE THREAD

**Issue by inexcel** [CTeX-org/forum#250]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

    1. 出现的情况：Beamer中的footnote显示不全，被footline给遮挡住了，请问这个问题如何解决？
    2. 理想结果是：footenote整体往上移动一点点距离，不被footline遮盖即可】
    3. 已尝试的方法：我尝试了设置页边距（结果是把\footline直接挤没了）  或者\vspace{1cm}  （结果是footnote每个条目之间都显示有1cm空格）

## 最小工作示例（MWE）

```latex
%%%%% Xelatex

\documentclass{beamer}
\usepackage{color}
\usepackage{ctex} 

\usetheme[]{Pittsburgh}

\definecolor{green}{RGB}{77,124,44}
\setbeamercolor{footline color}{fg=black,bg=green!20}
\setbeamercolor{symbol color}{fg=green}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%设置footline为带底色  显示页码、作者简短姓名、标题简短姓名
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\setbeamertemplate{footline}{
	\vspace{-1cm}
	
	\begin{beamercolorbox}[wd=\paperwidth, ht=2.25ex, dp=1ex, leftskip=0pt, rightskip=10pt]{footline color}{
			\insertshortauthor  \hfill \insertshorttitle \hfill \insertframenumber/\inserttotalframenumber}
	\end{beamercolorbox}%
}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%设置标题、作者、机构等信息
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\title[beamer short title]{\vspace{2cm}\newline \textbf{Beamer template for presentations}} 
\author[Trump]{Donald J. Trump}
\institute{University}
\date{2016}

\begin{document}
{
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%设置footline为带底色  显示页码、作者简短姓名、标题简短姓名
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 \begin{frame}
	Bla bla bla \footnote{footnote1} Ble ble ble\footnote{footnote2} 
\end{frame}

 \end{document}


```

（用 XeLaTeX 编译后）输出

```latex
开始 : xelatex.exe -synctex=1 -interaction=nonstopmode "MWE".tex

完成
```

## 链接

- TeX.SX:
- GitHub:

## 附件
与上面粘贴的代码一致，将txt改为tex即可。

[MWE.txt](https://github.com/CTeX-org/forum/files/8935158/MWE.txt)

**Comment by muzimuzhi** [comment]
把 `\setbeamertemplate{footline}{...}` 开头的 `\vspace{-1cm} <空行>` 去掉即可。提问时就可以附上截图，展示输出问题。

PS：`\begin{document}` 下一行的 `{` 是多余的，可能是简化例子时误留下的。

![image](https://user-images.githubusercontent.com/6376638/174479796-c4d60378-6a7d-4caa-9cf6-68937bf4187b.png)

**Comment by inexcel** [comment]
> 把 `\setbeamertemplate{footline}{...}` 开头的 `\vspace{-1cm} <空行>` 去掉即可。提问时就可以附上截图，展示输出问题。
> 
> PS：`\begin{document}` 下一行的 `{` 是多余的，可能是简化例子时误留下的。
> 
> ![image](https://user-images.githubusercontent.com/6376638/174479796-c4d60378-6a7d-4caa-9cf6-68937bf4187b.png)

非常非常感谢！！！

**Comment by inexcel** [comment]
![image](https://user-images.githubusercontent.com/57343270/175228834-9b7aad39-d82b-4e09-a391-b1b6de50afb5.png)
感谢您的回复！

**Comment by inexcel** [comment]
感谢您的指导！    
有几个小问题再请教一下： "logo 和 head 两张图片"在上一个帖子的zip压缩包里
用 mwe 包提供的示例图片代替了

![image](https://user-images.githubusercontent.com/57343270/175228960-7add17e5-8f94-4669-9a65-c8169246c86c.png)

**Comment by inexcel** [comment]
感谢您的指导！有几个小问题再请教一下：1. "logo 和 head 两张图片"在上一个帖子的zip压缩包里
用 mwe 包提供的示例图片代替了
![image](https://user-images.githubusercontent.com/57343270/175228960-7add17e5-8f94-4669-9a65-c8169246c86c.png)

**Comment by inexcel** [comment]
感谢您的指导！通过自己的尝试，先是遇到一个小问题：
1. ```logo 和 head 两张图片```在上一个帖子的**zip压缩包**里，利用您提供的代码，显示是下图这个效果，浅绿色head图片上方有一段空白。
    且  如您所用的```mwe 包提供的示例图片```, 图A上方明显有10pt的空格。
造成上述问题的原因，应该是
`     \setbeamertemplate{headline}{}
       \setbeamertemplate{footline}{}
   `
只让headline不显示，而所占空间并没有被调整

![image](https://user-images.githubusercontent.com/57343270/175230639-6ac5a7d9-1a61-4917-bff9-62dceda1d160.png)
2. 后来我进行了一下调整，把封面页healine设置部分进行了修改

**Comment by muzimuzhi** [comment]
```diff
 {
   \setbeamertemplate{headline}{}
   \setbeamertemplate{footline}{}
-  \logo{\includegraphics[scale=0.25]{example-image-b}}
-  \setbeamertemplate{background canvas}{%
-    \includegraphics[width=\paperwidth,height=\paperheight,keepaspectratio=false]{example-image-a}%
-    \llap{\hbox to \paperwidth{\insertlogo\hss}}%
-  }
-
-  \frame[plain]{\titlepage}
+  \logo{\includegraphics[scale=0.25]{example-image-b}\hspace{\dimexpr\paperwidth-1.8cm}\vspace{-0cm}}
+  
+  \usebackgroundtemplate{\includegraphics[width=\paperwidth,height=\textheight,keepaspectratio=true]{example-image-a}}
+  
+  \frame{\titlepage}
 }
 
 \begin{frame}[plain]{Outline}
```
![image](https://user-images.githubusercontent.com/6376638/175283997-93dbb16b-b31c-442e-b6bf-ed730a8ba9bb.png)

说明
 - 用 `\setbeamertemplate{background canvas}{...}`，不用仅作兼容性支持的旧命令 `\usebackgroundtemplate{...}`
 - `\logo{..}` 里只放图片，不插空距
 - 封面页也用 `plain` 选项，用 `\insertlogo` 把 logo 插在 `background canvas`
 - （可能只对 `example-image-a` 有用）使用 `height=\paperheight` 而非 `height=\textheight`。建议把图片 `head` 修改为宽高比和 beamer 页面一致（16:9）。
