### ISSUE TITLE
在文章内部使用 `\ctexset{chapter/pagestyle=...}` 会改变之前的章标题样式

### ISSUE THREAD

**Issue by syvshc** [CTeX-org/forum#251]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Arch linux

- TeX 发行版
  - [x] TeX Live 2022

## 描述问题

在文章内部使用 `\ctexset{chapter/pagestyle=...}` 会改变之前的章标题样式。
## 最小工作示例（MWE）

```latex
\documentclass[oneside]{ctexbook}
\usepackage{etoolbox}
\begin{document}
  \chapter{test}
  \makeatletter
% wrong 
  % \ctexset{
  %   chapter/pagestyle=empty
  % }
% wrong
  % \renewcommand{\CTEX@chapter@pagestyle}{empty}
% right
  % \patchcmd{\chapter}{\thispagestyle{\CTEX@chapter@pagestyle}}{\thispagestyle{empty}}{}{\fail}
  \makeatother
  \chapter*{test}
\end{document}
```

（用 XeLaTeX 编译后）输出

标记为 `wrong` 的部分会导致所有 `\chapter` 的样式也会变成 `empty`

标记为 `right` 的部分第一个 `\chapter` 的样式会保持 `plain`, 第二个 `\chapter` 的样式会变为 `empty`，是我对这个设置的预期行为

**Comment by muzimuzhi** [comment]
要换页

**Comment by muzimuzhi** [comment]
pagestyle 设置的页眉页脚，直到一页内容真正 shipout 时才会使用。如果在一页中间，pagestyle 改了，那么这一页 shipout 时用的是最后一次更改的 pagestyle。

这和 `\thispagestyle{...}` 是类似的，只是改了一个状态，但状态对应的代码，要到一页 shipout 时才使用。所有页眉页脚里的内容，都有这个特性。你可以试试在一页结束前修改 `\thepage`。类似的，在段落结束前修改行距，修改也会应用到当前段落。

在你的例子里，在 `\chapter*{test}` 内部执行 `\clearpage` 之前的内容，都在第一页。所以对 `chapter/pagestyle` 的修改，对第一章就生效了。如果修改 chapter/pagestyle 之前，第一章已经换过页了（更准确地，需要 `\ctexset` 所在的段落开始前，已经换页），就能观察到 pagestyle 的修改只应用到（未编号的）第二章

我第一条回复说「要换页」，是指为了确保 pagestyle 的修改不对当前页生效，应该先换页、再设置 pagestyle、最后使用 `\chapter` 开始下一章。它们的差别，就是是否保证了 pagestyle 在新的一页里执行。(la)tex 的实现保证了，`\clearpage <不产生输出的内容> \clearpage` 不会换两次页。

**Comment by syvshc** [comment]
> pagestyle 设置的页眉页脚，直到一页内容真正 shipout 时才会使用。如果在一页中间，pagestyle 改了，那么这一页 shipout 时用的是最后一次更改的 pagestyle。

那么如果用 `patchcmd` 的时候它会先 shipout 这一页, 然后再处理 patch 吗

**Comment by muzimuzhi** [comment]
> 那么如果用 `patchcmd` 的时候它会先 shipout 这一页, 然后再处理 patch 吗

1. patch 是立即生效的，`\patchcmd` 立即就重定义了 `\chapter`
2. `ctex` 把 `\chapter` 重定义为了
  ```tex
  \renewcommand\chapter{%
  % \if@openright\cleardoublepage\else\clearpage\fi
  % \thispagestyle{plain}%
    \CTEX@chapter@break
    \thispagestyle{\CTEX@chapter@pagestyle}%
    \global\@topnum\z@
  % \@afterindentfalse
    \ifodd \CTEX@chapter@afterindent
      \@afterindenttrue
    \else
      \@afterindentfalse
    \fi
    \secdef\@chapter\@schapter}
  ```
   其中 `\CTEX@chapter@break` 会执行 `\clear(double)page`，shipout 一页。所以 patch 后，在你的例子里，相当于 `\clearpage \thispagestyle{empty} <\chapter 的剩余部分>`，可以看到，是先 shipout、后修改 pagestyle。

**Comment by muzimuzhi** [comment]
尝试重新表述。

1. 直接用 `\thispagestyle` 的例子
   - 如果某一页是 `\thispagestyle{plain}\thispagestyle{empty} text \newpage`，可以理解生效的是 pagestyle `empty`
   - 如果顺序调整为 `\thispagestyle{plain} text\thispagestyle{empty}\newpage`，根据我第二条回复里的说明，生效的依然是 `empty`
1. ctex 的封装
   - `\ctexset{chapter/pagestyle=empty}` 相当于 `\def\CTEX@chapter@pagestyle{empty}`
   - `\chapter{...}` 相当于 `\clear(double)page \thispagestyle{\CTEX@chapter@pagestyle}`
   - 所以你的问题，相当于在下面的例子里，为什么 `\def\myheading{empty}` 会影响第一页的 pagestyle。
      ```tex
      \documentclass{article}
      \def\myheading{plain}
      \begin{document}
      \clearpage
      \thispagestyle{\myheading}
      first page
      \def\myheading{empty}
      
      \clearpage
      \thispagestyle{\myheading}
      second page 
      \end{document}
      ```
1. latex2e 对 pagestyle 的处理：`\thispagestyle` 把它的参数存到 `\@specialstyle` 里，后者的值在 shipout 时才被使用（见 `\@outputpage` 的定义，定义很长就不贴了）。
      ```tex
      % > latexdef -s \thispagestyle
      % latex.ltx, line 13849:
      \def\thispagestyle#1{%
        \@ifundefined{ps@#1}%
          \undefinedpagestyle
          {\global\@specialpagetrue\gdef\@specialstyle{#1}}}
      ```
   - 所以每个 `\chapter` 里的 `\thispagestyle` 只是做了 `\gdef\@specialstyle{\CTEX@chapter@pagestyle}`。如果在当前页 shipout 之前重定义 `\CTEX@chapter@pagestyle`，当前页的 pagestyle 会受影响。 
1. 你的需求，可以通过把 `\chapter` 内部修改为 `\expanded{\noexpand\thispagestyle{\CTEX@chapter@pagestyle}}` 来实现（只展开一次也许不够）。ctex 现在的实现和你的需求，都有合理性。出于向后兼容考虑，可能 ctex 不会改变现在的行为了。
    - 使用 latex2e 2022-06 的新命令，可以写成 `\ExpandArgs{e}\thispagestyle{\CTEX@chapter@pagestyle}`。（实际使用的是 `\exp_args:Ne`）

**Comment by syvshc** [comment]
我明白了, 谢谢您

**Comment by qinglee** [comment]
将 `\CTEX@(part|chapter)@pagestyle` 及时展开再传给 `\thispagestyle` 看起来比较合理一些。
