### ISSUE TITLE
tikz里这段展开的意义是什么？

### ISSUE THREAD

**Issue by SainoNamkho** [CTeX-org/forum#259]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

`pgfkeys.code.tex` 中
```tex
\long\def\pgfkeyssetvalue#1#2{%
  \pgfkeys@temptoks{#2}\expandafter\edef\csname pgfk@#1\endcsname{\the\pgfkeys@temptoks}%
}

\long\def\pgfkeyssetevalue#1#2{%
  \expandafter\edef\csname pgfk@#1\endcsname
  {\pgfkeys@unexpanded\expandafter{\pgfkeys@expanded{#2}}}%
}
```
我感觉这个跟
```tex
\long\def\pgfkeyssetvalue#1#2{%
  \expandafter\def\csname pgfk@#1\endcsname{#2}%
}

\long\def\pgfkeyssetevalue#1#2{%
  \edef\csname pgfk@#1\endcsname{#2}%
}
```
是一样的。
他们之间有什么区别吗？

**Comment by SainoNamkho** [comment]
想了一下，第一个大概是为了让`#`变成`##`，第二个则是为了避免`#`变成`##`。

**Comment by muzimuzhi** [comment]
> 想了一下，第一个大概是为了让`#`变成`##`，第二个则是为了避免`##`变成`#`。

不，两个都是为了让 `#` 变成 `##`：
 - `\pgfkeys-set-value` 里，传统技巧 `\toks0{<code>}\edef\cmd{\the\toks0}` 就够用了。
 - `\pgfkeys-set-e-value` 里，要先完全展开 value（再让 `#` 变成 `##`），传统技巧不够用了[^1]，不得不使用 eTeX 加入的 primitive `\unexpanded` 和各引擎在 texlive 2019 才加齐的 `\expanded`[^2]。
 - 注意，`\toks0{<code>}\edef\cmd{\the\toks0}` 和 `\edef\cmd{\unexpanded{<code>}}` 的功能是一样的，只不过前者在 tex 里就支持，而后者需要 eTeX 的 `\unexpanded`。

```tex
% both are equivalent to \@namedef{pgfk@<key>}{\def\xxa##1{xx##1}}
\pgfkeyssetvalue{/abc}{\def\xxa#1{xx#1}}
\pgfkeyssetevalue{/abc2}{\def\noexpand\xxa#1{xx#1}}
```

当时可能为了只作必要改动，没有在 `pgfkeys.code.tex` 里全面应用 `\pgfkeys@expanded` 和 `\pgfkeys@unexpanded`。写成下面这样，会更一致和对称一些。
```tex
\long\def\pgfkeyssetvalue#1#2{%
  \expandafter\edef\csname pgfk@#1\endcsname{\pgfkeys@unexpanded{#2}}%
}

\long\def\pgfkeyssetevalue#1#2{%
  \expandafter\edef\csname pgfk@#1\endcsname
    {\pgfkeys@unexpanded\expandafter{\pgfkeys@expanded{#2}}}%
}
```

[^1]: 见 `https://github.com/pgf-tikz/pgf/issues/305` 和 `https://github.com/pgf-tikz/pgf/pull/1002` （为避免产生 backref，我故意把链接标记成了代码）
[^2]: https://tug.org/texlive/doc/texlive-en/texlive-en.html#x1-870009.1.16

**Comment by muzimuzhi** [comment]
以及，issue 标题不够好。

**Comment by SainoNamkho** [comment]
谢谢慕子的耐心解答！

> 不，两个都是为了让 # 变成 ##：

这里是我的表述问题，其实我们是一个意思。“让 # 变成 ##”是从`\edef`的含义而言，“避免##变成#”是从tex输入栈的状态而言。
在《TeX: The program》模块 477 中定义了 `\edef` 的读入过程
![image](https://user-images.githubusercontent.com/23036788/177946240-ddd2b011-f941-42f7-b5f1-03e5aaf0943c.png)
`\edef` 是一边展开一边把 ## 变成 #。
而 `\unexpanded` 直接调用 `store_new_token` 把记号列放进链表了，跳过了转换过程。
![image](https://user-images.githubusercontent.com/23036788/177946522-6e7058b4-dc11-4eaf-a31f-bc238bc0ad9b.png)

我一开始说“第一个大概是为了让#变成##”的时候，尝试了`\toks0={#}\message{\the\toks0}`，误以为 `\the\toks` 本身就会重复`#`，其实这是 `\message` 的原因。如慕子所说， `\the\toks` 跟 `\unexpanded`  一样，并不修改记号列。

> 以及，issue 标题不够好

确实没有想好怎么给他起一个合适的标题，提得有点仓促，发完之后我想出了答案，试图删掉issue，结果发现只能关闭。或许叫 “`\pgfkeyssetvalue` 定义中为什么会用到toks寄存器”会好一点？

**Comment by muzimuzhi** [comment]
> 或许叫 “`\pgfkeyssetvalue` 定义中为什么会用到toks寄存器”会好一点？

请修改。哪怕只是说「`pgfkeys` 中 `\pgfkeyssetvalue` 为何这样定义」也是很大的改善。（`pgfkeys` 是一个可单独调用的宏包，虽然大部分用户第一次接触它是通过 tikz）

请总是避免，能容纳100种不同问题描述的、过于一般性的标题。之前也遇到过「借口问题标题足够一般，于是可以追问、不会 off-topic」的提问者。
