### ISSUE TITLE
分享一个 CTeX 论坛存档

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [CTeX-org/forum#26]
CTeX 论坛虽然已经关闭，幸运的是，有一家网站积累了大量的原论坛的帖子，将当年网友们的智慧都珍藏起来，如遇疑难，欢迎浏览。
地址：https://web.archive.org/web/2018*/http://bbs.ctex.org/

**Comment by stone-zeng** [comment]
Internet Archive 似乎只保留了顶层页面，实际的论坛内容并没有存档……

**Comment by muzimuzhi** [comment]
> Internet Archive 似乎只保留了顶层页面，实际的论坛内容并没有存档……

从 sitemap（https://web.archive.org/web/sitemap/http://bbs.ctex.org/ ）看，有部分帖子得到了存档，例如[这则](https://web.archive.org/web/20180718013649/http://bbs.ctex.org/forum.php?mod=viewthread&tid=48330&page=1)。

遗憾的是，存档的帖子不够全。（它倒是存档了好多论坛用户的个人主页）

**Comment by Liam0205** [comment]
@muzimuzhi sad news
