### ISSUE TITLE
在 `\LoadClass` 后使用 `\RequirePackage{linegoal}` 出现 `etex` 警告

### ISSUE THREAD

**Issue by xkwxdyy** [CTeX-org/forum#264]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [x] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2022 
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

在给 `exam-zh` 的 `exam-zh-question` 模块开发可换行的空白内容但有下划线时，想使用 `linegoal` 宏包的 `\linegoal` 命令进行相关操作，但是突然发现有 `etex` 的警告。然后我经过测试调整，整理了下面的 MWE：

## 最小工作示例（MWE）

```latex
\documentclass{TEST}

\begin{document}

test \underline{\hspace*{\linegoal}}

\end{document}
```

其中 `TEST.cls` 内容如下：
```latex
\NeedsTeXFormat{LaTeX2e}
\RequirePackage{expl3}

\ProvidesExplClass {TEST} {2022-07-29} {v0.1.14} {TEST}

% \RequirePackage { linegoal }

\LoadClass { ctexbook }

\RequirePackage { linegoal }
```

（用 XeLaTeX 编译后）输出

```latex
Extended allocation already in use.
(etex)	etex.sty code will not be used.
(etex)	To force etex package to load, add
(etex)	\RequirePackage{etex}
(etex)	at the start of the document.
```

但是我测试发现，如果把 `\RequirePackage{linegoal}` 放在 `\LoadClass` 前面就不会出现这个警告。但是从模版的最小化来看，我应该避免在 `exam-zh.cls` 中加入这个宏包。所以希望能够有办法解决这个问题。

## 链接

TeX.SX:
- https://tex.stackexchange.com/questions/285950/package-autonum-needs-the-obsolete-etex-package
- https://tex.stackexchange.com/questions/605616/how-to-remove-the-etex-warning-when-using-cryptocode-with-the-llncs-document-cla
里面提供了 
```latex
\expandafter\def\csname ver@etex.sty\endcsname{3000/12/31}
```
的方法我放在了 `\RequirePackage { linegoal }` 前 `xelatex` 编译失效，后则不起作用

**Comment by muzimuzhi** [comment]
也许和在通用编程语言里不同，LaTeX 里不必刻意追求 0 warning(s)。

```tex
\LoadClass { ctexbook }

\RequirePackage { silence }
\WarningFilter {etex} {Extended~ allocation~ already~ in~ use.}
\ActivateWarningFilters

\RequirePackage { linegoal }
```
或
```tex
\LoadClass { ctexbook }

% 阻止载入 etex.sty，并模拟 linegoal 用到的两个命令
\cs_new:cpn {ver@etex.sty}{3000/12/31}
\cs_set_eq:NN \globcount \newcount
\cs_set_eq:NN \globdimen \newdimen

\RequirePackage { linegoal }
```
都能让你看不见 `etex.sty` 的那个 warning。

LaTeX 会记录六种寄存器（count, dimen, ...）已经分配的数量，分别储存在 `\count10` 到 `\count15` 里。在 knuth tex 里，这六种寄存器分别最多只能分配 255 个。etex 把这个上限增加到了 32768（见 `texdoc etex`）。于是 `etex.sty` 里有一个逻辑，如果这六个计数器有任何一个已经分配了大于 255 个，就认为当前已经运行在与 etex 兼容的引擎里，于是抛出警告 `Extended allocation already in use. ...`

刚好，已分配的 count 的数量，在 `\LoadClass{ctexbook}` 之前小于 255，在这之后大于 255，所以有了你观察到的情况。换成轻一点的文档类，比如 `\LoadClass{article}`，就没有这个差异。

------

> * https://tex.stackexchange.com/questions/605616/how-to-remove-the-etex-warning-when-using-cryptocode-with-the-llncs-document-cla
>   里面提供了
> 
> ```
> \expandafter\def\csname ver@etex.sty\endcsname{3000/12/31}
> ```
> 
> 的方法我放在了 `\RequirePackage { linegoal }` 前 `xelatex` 编译失效，后则不起作用

下次建议提供报错信息。

**Comment by muzimuzhi** [comment]
一些我做的化简例子、找问题出处的事

是不是自定义文档类才能复现？不是。`ctexbook` + `linegoal` 就能复现
```tex
% !TeX TS-program = xelatex
\documentclass{ctexbook}
\usepackage{linegoal}
\begin{document}
\end{document}
```
而且 `linegoal` + `ctexbook` 不能复现。
```tex
% !TeX TS-program = xelatex
\RequirePackage{linegoal}
\documentclass{ctexbook}
\begin{document}
\end{document}
```

- `article` + `ctex` + `linegoal` 能复现吗？能
- `article` + `xeCJK` + `linegoal` 能复现吗？能

另一个方向
- 警告是 `linegoal` 调用的 `etex` 抛的，于是可以把 `linegoal` 替换成 `etex`
  - 例子变成，`article` + `xeCJK` + `etex` 能复现
- 查看 `etex.sty` 里触发这个警告的条件，看到 `\count10` 到 `\count15` 和 `\@cclv` 做比较。
  - 谷歌搜 `latex, "\count10"`，结果第一条 https://tex.stackexchange.com/questions/173901/why-is-newcount-declared-outer 里说，它储存的是已分配的 count 数量。
  - 命令行运行 `latexdef -s \@cclv`，知道它是常数 255。
- 在 `article` + `xeCJK` + `etex` 的例子里，在 `\usepackage{xeCJK}` 前后分别通过报错，输出 `\count10` 到 `\count15` 的值。
- 可以做一些其他试验，来验证推断/猜想。

再换一个方向，
```tex
% !TeX TS-program = xelatex
\documentclass{article}
\usepackage{xeCJK}
\expandafter\def\csname ver@etex.sty\endcsname{3000/12/31}
\usepackage{linegoal}
\begin{document}
\end{document}
```
报错，`! Undefined control sequence. l.51 \globcount` 和 `! Undefined control sequence. l.52 \globdimen`。在 `etex.sty` 里能找到
```tex
\expandafter\let\csname globcount\expandafter\endcsname
                \csname newcount\endcsname
\expandafter\let\csname globdimen\expandafter\endcsname
                \csname newdimen\endcsname
```

**Comment by qinglee** [comment]
现在禁用宏包可以用 LaTeX 2020-10-01 开始提供的 `\disable@package@load`。例如本问题可以在调用 `linegoal` 包之前设置
```LaTeX
\disable@package@load { etex }
  {
    \cs_set_eq:NN \globcount \newcount
    \cs_set_eq:NN \globdimen \newdimen
  }
```
这种方式比传统的定义一个虚假的 `\ver@etex.sty` 标识好看一点。

**Comment by Sophanatprime** [comment]
另一种可行的（但并不一定很安全）方法是，使用 `\declare@file@substitution{file1}{file2}` 将 `etex` 宏包或 `linegoal` 宏包替换为自己的一个实现。或者使用 `\disable@package@load{...}{\RequirePackage{...-my}}`，目前 LaTeX 对某些宏包的替换就是使用这种机制。

**Comment by xkwxdyy** [comment]
非常感谢各位的解答～

**Comment by xkwxdyy** [comment]
> 一些我做的化简例子、找问题出处的事
> 
> 是不是自定义文档类才能复现？不是。`ctexbook` + `linegoal` 就能复现
> 
> ```
> % !TeX TS-program = xelatex
> \documentclass{ctexbook}
> \usepackage{linegoal}
> \begin{document}
> \end{document}
> ```
> 
> 而且 `linegoal` + `ctexbook` 不能复现。
> 
> ```
> % !TeX TS-program = xelatex
> \RequirePackage{linegoal}
> \documentclass{ctexbook}
> \begin{document}
> \end{document}
> ```
> 
> * `article` + `ctex` + `linegoal` 能复现吗？能
> * `article` + `xeCJK` + `linegoal` 能复现吗？能
> 
> 另一个方向
> 
> * 警告是 `linegoal` 调用的 `etex` 抛的，于是可以把 `linegoal` 替换成 `etex`
>   
>   * 例子变成，`article` + `xeCJK` + `etex` 能复现
> * 查看 `etex.sty` 里触发这个警告的条件，看到 `\count10` 到 `\count15` 和 `\@cclv` 做比较。
>   
>   * 谷歌搜 `latex, "\count10"`，结果第一条 https://tex.stackexchange.com/questions/173901/why-is-newcount-declared-outer 里说，它储存的是已分配的 count 数量。
>   * 命令行运行 `latexdef -s \@cclv`，知道它是常数 255。
> * 在 `article` + `xeCJK` + `etex` 的例子里，在 `\usepackage{xeCJK}` 前后分别通过报错，输出 `\count10` 到 `\count15` 的值。
> * 可以做一些其他试验，来验证推断/猜想。
> 
> 再换一个方向，
> 
> ```
> % !TeX TS-program = xelatex
> \documentclass{article}
> \usepackage{xeCJK}
> \expandafter\def\csname ver@etex.sty\endcsname{3000/12/31}
> \usepackage{linegoal}
> \begin{document}
> \end{document}
> ```
> 
> 报错，`! Undefined control sequence. l.51 \globcount` 和 `! Undefined control sequence. l.52 \globdimen`。在 `etex.sty` 里能找到
> 
> ```
> \expandafter\let\csname globcount\expandafter\endcsname
>                 \csname newcount\endcsname
> \expandafter\let\csname globdimen\expandafter\endcsname
>                 \csname newdimen\endcsname
> ```
> 
> 只提供 `\globcount` 和 `\globdimen` 会不会不稳妥，会不会少了点什么？注意到附近代码的结构是
> 
> ```
> \@tempswafalse
> \ifnum\count10>\@cclv\@tempswatrue\else
>   ...
> \fi
> 
> \if@tempswa
>   \PackageWarningNoLine{etex}{%
>   Extended allocation already in use.\MessageBreak ...}
>   \expandafter\let\csname globcount\expandafter\endcsname
>                   \csname newcount\endcsname
>   \expandafter\let\csname globdimen\expandafter\endcsname
>                   \csname newdimen\endcsname
>   \expandafter\let\csname globskip\expandafter\endcsname
>                   \csname newskip\endcsname
>   \expandafter\let\csname globmuskip\expandafter\endcsname
>                   \csname newmuskip\endcsname
>   \expandafter\let\csname globtoks\expandafter\endcsname
>                   \csname newtoks\endcsname
>   \expandafter\let\csname globmarks\expandafter\endcsname
>                   \csname newmarks\endcsname
>   ...
> \expandafter\endinput\fi
> ```
> 
> 因为 `\expandafter\endinput\fi`，包的载入会在这个 `\if@tempswa ...\fi` 之后提前结束，`etex.sty` 在此后面的内容都不用看了。`etex.sty` 在此之前没有影响当前状态（所有primitive、宏、寄存器以及它们的状态）的内容，所以只需要模拟那六个 `\globXXX` 就行了。

非常感谢，您这才是自主探索问题的解决的优秀示例，学习了。
