### ISSUE TITLE
natbib下，multibib 与 backref 的不兼容问题

### ISSUE THREAD

**Issue by bcegkmqs23** [CTeX-org/forum#265]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Linux（Gentoo）

- TeX 发行版
  - [x] TeX Live 2021 

## 描述问题

1. 情况与复现：在memoir文档类使用multibib和hyperref的backref，backref只对原始的（非multibib所定义的宏所创建的）参考文献列表有效。
2. 已有尝试：见下文的「尝试」一节

## 最小工作示例（MWE）

见附件。使用latexmk(latexmkrc)编译，实际为xelatex和bibtexall（差不多就是`for f in *.aux; do bibtex "$f"; done`）。

## 链接

- TeX.SX: 没有找到完全一致的，但确实有一些：
  - https://tex.stackexchange.com/questions/119635/multibib-with-backref-in-classicthesis

## 我还做了这些尝试

首先，我发现multibib的调用须在backref之前。两者都会给 `\thebibliography` 打补丁，若multibib在backref之后调用，则backref的补丁失效（通过在backref中插入typeout可以发现，backref的代码不会执行），除非手动到multibib代码中插入backref的 `\BR@starttoc` 。

然后，我阅读源码了解到：

- 当 `\thebibliography` 被展开，则 `\BR@starttoc` 会 `\input` brf文件，并打开一个到 `\jobname.brf` 文件的流为`tf@brf`。而对于multibib，我们可能需要多个brf文件才行。
- 当hyperref的 `\hyper@natlinkstart` 被调用，则会展开出经过backref修改的 `\Hy@backout` ，它会向 `@auxout` 写入 `\@writefile{brf}{\string\backsite{...}}` 。等到载入aux文件的时候就会向 `tf@brf` 写入 `\backsite{...}` 。

我修改了backref和multibib，以使以上行为对多个参考文献列表适用：

- multibib：对于各 `\@suffix` （即 `\newcites` 创建的参考文献命令的后缀），打开名为 `\csname mb@brf@write@\@suffix\endcsname` 的到 `\@suffix.brf` 的 `\write` `\openout` 。
- multibib：在 `\@citename` （会在循环中被展开为 `\citep` `\citet` 等）的定义中，插入 `\let\noexpand\currentbrf\csname mb@brf@write@\@suffix\endcsname` ，也就是说展开 `\citep` 时把 `\currentbrf` 设为该 `\@suffix` 对应的流。
- multibib：在 `\csname bibliography\@suffix\endcsname` （即multibib版本的 `\bibliography` ）的定义中，插入 `\let\noexpand\currentbibbrf\@suffix` ，也就是说展开 `\csname bibliography\@suffix\endcsname` 时把 `\currentbibbrf` 设为 `\@suffix` 。
- backref：移除打开 `tf@brf` 流的代码。并将 `\input{\jobname.brf}` 换为 `\input{\currentbibbrf.brf}`
- backref：在写入到aux文件的代码中：在即将执行 `\write{brf}{...}` 前，插入 `\string\let\string\tf@brf\currentbrf` ，试图将 `tf@brf` 设为 `\currentbrf`。但我不清楚这个代码具体是什么时候执行的、那时的`\currentbrf`的定义是怎样的，我怀疑这是我代码的一个主要问题所在。

作以上修改后，能生成brf文件，也能看到我在aux插入的 `\typeout` 信息，但brf文件并未写入内容。

## 附件

[tex文件](https://github.com/CTeX-org/forum/files/9276113/multibib.zip)
[修改后的sty文件](https://github.com/CTeX-org/forum/files/9276177/multibib_modify_UTC202208070420.zip)

**Comment by qinglee** [comment]
粗看了一下，问题的根源应该是 `multibib` 包在内部重定义了 `\jobname` 和 `\@auxout` ，造成了混淆。我们在 `backref` 内部恢复这些定义应该就可以解决，可能不需要开多个 `.brf` 文件流。
```latex
\makeatletter
\ExplSyntaxOn
%% 恢复 \jobname 的定义
\cs_set_eq:NN \TEXJOBNAME \c_sys_jobname_str
\ctex_patch_cmd:Nnn \BR@starttoc
  { \makeatletter }
  {
    \makeatletter
    \let\jobname\TEXJOBNAME
  }
%% multibib 将 \@auxout 的原始定义保持在 \@save@auxout 中
\ctex_patch_cmd_all:NnnnTF \Hy@backout
  {
    \ExplSyntaxOff
    \makeatletter
  }
  { \@auxout }
  { \@save@auxout }
  { }
  { \ctex_patch_failure:N \Hy@backout }
\ExplSyntaxOff
\makeatother
```

**Comment by bcegkmqs23** [comment]
问题已解决。只需确保 backref 的位置在backref之前，然后使用楼上给的补丁，就一切正常了。

多谢这位热心高手。
