### ISSUE TITLE
左全角括号在 `\textcolor` 参数中，编辑结果出现额外间距

### ISSUE THREAD

**Issue by xkwxdyy** [CTeX-org/forum#268]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [x] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2022
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

我把全角括号放在了 `\textcolor` 的参数中，发现编译结果是左括号左边产生了额外的间距。

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\usepackage{color}

\begin{document}

\begin{enumerate}
	\item \begingroup \color{blue}（中文）\endgroup 测试文本
	\item \textcolor{blue}{(中文)} 测试文本
	\item \textcolor{blue}{（中文）}测试文本
	\item (中文) 测试文本
	\item（中文）测试文本
\end{enumerate}

\end{document}
```

（用 XeLaTeX 编译后）输出

![image](https://user-images.githubusercontent.com/87134063/188252589-d00f0018-6c67-4aa0-aa80-b306e066b4b9.png)

## 我还做了这些尝试

我觉得圆括号只是个个例，于是尝试了方括号：
```latex
\documentclass{ctexart}
\usepackage{color}

\begin{document}

\begin{enumerate}
	\item \begingroup \color{blue} 【中文】\endgroup 测试文本
	\item \textcolor{blue}{[中文]} 测试文本
	\item \textcolor{blue}{【中文】}测试文本
	\item \relax [中文] 测试文本
	\item【中文】测试文本
\end{enumerate}

\end{document}
```
![image](https://user-images.githubusercontent.com/87134063/188252779-cc0e4334-e513-4f8a-9356-4b00552ab829.png)

发现确实是这样。

然后我去查了 `\textcolor` 的源码：

```latex
% color.sty
\protected\def\textcolor#1#{\@textcolor{#1}}
\def\@textcolor#1#2#3{\protect\leavevmode{\color#1{#2}#3}}
```
发现他和 `\color` 的区别应该是在于一个 `\leavevmode`？具体为什么会造成这个，我个人觉得和标点的 glue 有关，于是我尝试了下面的例子：
```latex
\documentclass{ctexart}
\usepackage{color}
\xeCJKsetwidth{（}{0.4em}

\begin{document}

\begin{enumerate}
	\item \begingroup \color{blue}（中文）\endgroup 测试文本
	\item \textcolor{blue}{（中文）}测试文本
	\item（中文）测试文本
\end{enumerate}

\end{document}
```

![image](https://user-images.githubusercontent.com/87134063/188252963-fbdb9067-2b87-4a4f-847f-dbf1c07d5d7b.png)

我猜测具体原因是因为中文标点所占宽度是弹性的，所以我把他固定之后就没有额外的间距了。

所以问题应该变成了 `\textcolor` 造成了左全角括号的弹性宽度被“拉长”，但我不知道具体原因。

**Comment by Sophanatprime** [comment]
最简单的方法应该是在”（“之前插入 1sp 的 hskip：
```tex
\begin{enumerate}
\item \textcolor{blue}{（中文）}测试文本
\item \textcolor{blue}{\hskip1sp（中文）}测试文本
\item （中文）测试文本
\end{enumerate}
```

<img width="269" alt="image" src="https://user-images.githubusercontent.com/55335597/188258425-aa59b791-d921-4005-b6c9-676f4d9a599e.png">

`\textcolor{blue}{（` 展开变为 `\relax \leavevmode \special{...}（`，由于 `\special` 执行时，已经是水平模式（由于 `\leavevmode`），立即在 `\special` 与 `（` 之间插入 `\xeCJK_Boundary_and_FullLeft:N`，这个命令处理时，`\special` 为 whatsit node，`\lastnodetype` 为 9，随即，插入正常情况下 FullLeft 的间距（一般这间距与标点符号共约占 1\ccwd）。

插入 1sp 的 hskip，导致 `\lastnodetype` 为 11（glue node），此时，xeCJK 插入 0pt 的间距。


见 `xeCJK.pdf` 第 47、48 页。

**Comment by xkwxdyy** [comment]
@Sophanatprime 非常感谢～
