### ISSUE TITLE
为什么公式前后的空白不对称？（非中文环境独有）

### ISSUE THREAD

**Issue by gzxu** [CTeX-org/forum#27]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x] Linux

- TeX 发行版
  - [x] TeX Live 2018
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

当`\begin{equation}`、`\end{equation}`和两侧文本没有空行时，公式和上下文本间的间距是一样的，但为了代码可读性一般会留上空行，这样公式上方的空白会比下方空白更大。在`article`+`xeCJK`、`ctexart`、`article`下测试均是如此，XeLaTeX和pdfLaTeX没有区别。显示`\the\abovedisplayskip`和`\the\belowdisplayskip`是一样的。

## 最小工作示例（MWE）

```latex
% \documentclass{ctexart}
\documentclass{article}
% \usepackage{xeCJK}

\begin{document}
[1] The quick brown fox jumps over a lazy dog.
% 这个软件包提供了一个中文虚拟文本的接口。

\begin{equation}
    a+b=c
\end{equation}

[2] The quick brown fox jumps over a lazy dog.
% 这个软件包提供了一个中文虚拟文本的接口。（注意这里没有空行）
\begin{equation}
    a+b=c
\end{equation}

[3] The quick brown fox jumps over a lazy dog.
% 这个软件包提供了一个中文虚拟文本的接口。

\the\abovedisplayskip

\the\belowdisplayskip

\the\abovedisplayshortskip

\the\belowdisplayshortskip

\end{document}
```

公式(1)和段落[1]、公式(2)和段落[2]、公式(2)和段落[3]的间距都是一样的，但公式(1)和段落[2]的间距更小。

## 链接

抱歉，没有搜索到相关内容（捂脸

**Comment by gzxu** [comment]
这个回答 https://tex.stackexchange.com/a/89518 直接说公式两侧留空行的做法是错的 :woman_facepalming: 真是rlgl

**Comment by RuixiZhang42** [comment]
对于 LaTeX 来说，空行 = 换段，当你明白这个道理之后就能意识到公式前后留空行是多么错误的写法了。从写作的角度来说，公式不应当作为自然段的开头，所以公式前面留空行是**大错特错**的。当然，公式是可以结束一个段落的，比如说推导证明最后一步是个公式。

如果目的是为了让源代码更有可读性，那么应该巧用注释符号 `%`，像这样：

```tex
\documentclass{article}
\begin{document}
Some text followed by unnumbered display equation:
% <- 加在这里
\[
...
\]
% <- 加在这里，段落没结束
and another numbered equation:
% <- 加在这里
\begin{equation}
...
\end{equation}

% 如果段落结束，上面可以留空行
New paragraph starts...
\end{document}
```
