### ISSUE TITLE
想问一下现在CTEX的founder字库用的是什么

### ISSUE THREAD

**Issue by Firestar-Reimu** [CTeX-org/forum#271]
https://github.com/CTeX-org/ctex-kit I have find it here for hours but I cannot find the founder fontset file. Which fonts do CTEX use?

**Comment by Firestar-Reimu** [comment]
这就带来了一个问题，方正小标宋GBK被下架了

**Comment by Liam0205** [comment]
see: https://github.com/CTeX-org/ctex-kit/issues/643
