### ISSUE TITLE
请问哪里可以找到CTeX宏集手册的 tex file? 

### ISSUE THREAD

**Issue by rjiang9** [CTeX-org/forum#272]
想用它作为学习模板。

[http://mirrors.ibiblio.org/CTAN/language/chinese/ctex/ctex.pdf](http://mirrors.ibiblio.org/CTAN/language/chinese/ctex/ctex.pdf)
谢谢各位开发大佬。

**Comment by note286** [comment]
`C:\texlive\2022\texmf-dist\source\latex\ctex\ctex.dtx`

**Comment by Liam0205** [comment]
FYI：

CTeX 宏集使用「文学编程」范式开发。将其作为普通文档的开发反例大概是不合适的。

——你甚至可能不知道如何正确编译它得到文档。

**Comment by AlphaZTX** [comment]
@rjiang9 或许你可以去看看clsguide

**Comment by syvshc** [comment]
> FYI：
> 
> CTeX 宏集使用「文学编程」范式开发。将其作为普通文档的开发反例大概是不合适的。
> 
> ——你甚至可能不知道如何正确编译它得到文档。

反例 -> 范例

**Comment by rjiang9** [comment]
> C:\texlive\2022\texmf-dist\source\latex\ctex\ctex.dtx

多谢🙏

**Comment by rjiang9** [comment]
> FYI：
> 
> CTeX 宏集使用「文学编程」范式开发。将其作为普通文档的开发范例大概是不合适的。
> 
> ——你甚至可能不知道如何正确编译它得到文档。

感谢大佬指教。我是看它的排版挺好的。 我还真不知道啥叫文学编程。

**Comment by rjiang9** [comment]
> @rjiang9 或许你可以去看看clsguide

象这个吗？ [https://ctan.mirror.rafal.ca/macros/latex/base/clsguide.pdf](https://ctan.mirror.rafal.ca/macros/latex/base/clsguide.pdf)

谢谢

**Comment by AlphaZTX** [comment]
@rjiang9 就是这个

**Comment by stone-zeng** [comment]
另一些参考：

- https://liam.page/2015/01/23/literate-programming-in-latex/
- https://www.texdev.net/2009/10/05/the-dtx-format/
- https://www.texdev.net/2009/10/06/a-model-dtx-file/

**Comment by AlphaZTX** [comment]
@rjiang9 dtxtut 也可以看一下

**Comment by rjiang9** [comment]
> 另一些参考：
> 
> * https://liam.page/2015/01/23/literate-programming-in-latex/
> * https://www.texdev.net/2009/10/05/the-dtx-format/
> * https://www.texdev.net/2009/10/06/a-model-dtx-file/

非常感谢指导！

**Comment by rjiang9** [comment]
> @rjiang9 dtxtut 也可以看一下

好的，非常感谢🙏
