### ISSUE TITLE
讨论范围：CTeX套装问题or中文TeX问题？

### ISSUE THREAD

**Issue by gingerkitti** [CTeX-org/forum#274]
本人大概搜索了一下“CTeX论坛”是讨论什么问题的，但是还没找到。故在此冒昧提问

请问讨论问题的范围是“只要是中文TeX问题就可以”，还是“仅限于CTeX套装的问题”

**Comment by note286** [comment]
不仅限于CTeX套装的问题。

**Comment by stone-zeng** [comment]
本论坛以中文 TeX 问题为主，一般性的问题也可以讨论。CTeX 套装（不是 `ctex` 宏集 / 宏包）由于年久失修不建议使用，有关问题也未必能得到解答。

**Comment by gingerkitti** [comment]
感谢二位解答

**Comment by lvjr** [comment]
CTeX 套装最近已经有 3.0 测试版了。

**Comment by muzimuzhi** [comment]
> CTeX 套装最近已经有 3.0 测试版了。

补充一些信息，来源见 https://ctex.org/CTeX/release-notes/

> - v3.0.208.0 — 2023.01.23
>   - 升级 MiKTeX 20230120
>   - 升级 GSview 6.0 (32/64)
>   - 升级 Ghostscript 10.00.0 (32/64)
>   - 升级 WinEdt 11.0 (64-bit) / 10.3 (32-bit)
>  
> - v3.0.202.0 — 2022.10.24
>   - 修改版本号格式为 major.minor.build.stage，最后一个数字： 0-alpha, 1-beta, 2-release
>   - 升级 MiKTeX-x86 21.6-20221024
>   - 增加 MiKTeX-x64 22.7-20221024
>   - 更新 SumatraPDF 3.4.6 (32/64)
>   - 增加 MiKTeX 预装常用宏包
>   - 删除宏包 CJKpunct/hypernat，使用 MiKTeX 内含的版本
>   - 删除过时的宏包 CASthesis/PostDocRep

**Comment by sikouhjw** [comment]
> 补充一些信息，来源见 https://ctex.org/CTeX/release-notes/
> 
> > * v3.0.208.0 — 2023.01.23
> >   
> >   * 升级 MiKTeX 20230120
> >   * 升级 GSview 6.0 (32/64)
> >   * 升级 Ghostscript 10.00.0 (32/64)
> >   * 升级 WinEdt 11.0 (64-bit) / 10.3 (32-bit)
> > * v3.0.202.0 — 2022.10.24
> >   
> >   * 修改版本号格式为 major.minor.build.stage，最后一个数字： 0-alpha, 1-beta, 2-release
> >   * 升级 MiKTeX-x86 21.6-20221024
> >   * 增加 MiKTeX-x64 22.7-20221024
> >   * 更新 SumatraPDF 3.4.6 (32/64)
> >   * 增加 MiKTeX 预装常用宏包
> >   * 删除宏包 CJKpunct/hypernat，使用 MiKTeX 内含的版本
> >   * 删除过时的宏包 CASthesis/PostDocRep

看起来像是封装了一下 miktex、预装了 pdf 阅读器和 winedt，相当于是 miktex 的开封即用的替代品
