### ISSUE TITLE
xeCJK宏包文档中3.2.1节需要增补

### ISSUE THREAD

**Issue by zhangxm2312** [CTeX-org/forum#277]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 11
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2022
  - [ ] MiKTeX 
  - [x] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

```
fc-list > fontlist.txt
```
只能搜索到给所有用户安装的字体，而给当前用户安装的字体无法显示在fontlist.txt中，因此需要提醒用户这一点。
另一方面，需要告诉用户如何使得所输出的文档中的非拉丁字母不显示为乱码，至少在本人所输出的文档中有这样的问题。

**Comment by OsbertWang** [comment]
`\LaTex` ？写错了。是`\LaTeX`

**Comment by zhangxm2312** [comment]
> `\LaTex` ？写错了。是`\LaTeX`

抱歉，刚刚点错了，现在更改了issue正文。

**Comment by note286** [comment]
在`install-latex-guide-zh-cn`中有如下描述：

> xelatex 可以使用系统内安装的字体, 用户在安装字体时需右键字体文件选择为所有用户安装。

---

至于乱码的问题，是Windows默认编码的问题，这个我觉得没必要写在xeCJK手册中。

你可以执行`chcp 65001`。

**Comment by zhangxm2312** [comment]
> 你可以执行`chcp 65001`。

我试过了，在控制台中的输出是可以这么做的，但是导出到一个txt文件中（如我之前所说）仍会产生乱码。

**Comment by AlphaZTX** [comment]
Windows 下输出文本乱码可以简单地使用 cmd 执行 `fc-list > FILE` 来解决，不要使用 PowerShell。这一点在 xeCJK 文档的 3.2.1 小节第 1 段已经写得很明确了：

> 在命令行（Windows 的“命令提示符”，Linux 的 Console）下运行以下命令（后面内容省略）
