### ISSUE TITLE
使用XeLatex构建中文文档源码时报错: xdvipdfmx:fatal: Unknown coverage format

### ISSUE THREAD

**Issue by Redish101** [CTeX-org/forum#279]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [x] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2023
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

我在使用XeLaTex构建中文文档时报错：`xdvipdfmx:fatal: Unknown coverage format`

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}

\begin{document}
你好，LaTex
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
(/usr/local/texlive/2023/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-macnew.
def))) (/usr/local/texlive/2023/texmf-dist/tex/latex/ctex/config/ctex.cfg)
(./Latex.aux) [1] (./Latex.aux)
xdvipdfmx:fatal: Unknown coverage format

No output PDF file written.
 )
Error 256 (driver return code) generating output;
file Latex.pdf may not be valid.
SyncTeX written on Latex.synctex.gz.
Transcript written on Latex.log.
```

## 链接

- TeX.SX:
- GitHub:

## 我还做了这些尝试

我尝试了使用搜索引擎寻找解决方案，但是并未找到结果

## 附件

[完整的构建日志](https://pan.redish101.top/zh-CN/%E5%85%B6%E5%AE%83/Latex.log)

**Comment by muzimuzhi** [comment]
github issue 支持直接上传附件，我重传了一份 [Latex.log](https://github.com/CTeX-org/forum/files/11132247/Latex.log)

> ```
> Package fontspec Info: Font family 'SongtiSCLight(0)' created for font 'Songti	
> (fontspec)             SC Light' with options	
> (fontspec)             [Script={CJK},BoldItalicFont={Kaiti SC	
> (fontspec)             Bold},BoldFont={Songti SC Bold},ItalicFont={Kaiti SC}].	
> (fontspec)              	
> (fontspec)              This font family consists of the following NFSS	
> (fontspec)             series/shapes:	
> (fontspec)              	
> (fontspec)             - 'normal' (m/n) with NFSS spec.: <->"Songti SC	
> (fontspec)             Light/OT:script=hani;language=dflt;"
> ```

最后一行里的 `script=hani` 不是默认会带的，xecjk 初始设置的是 `\defaultCJKfontfeatures{Script=CJK}`，然后会报如下 warning，
```
Package fontspec Warning: Font "Songti SC Light" does not contain requested
(fontspec)                Script "CJK".
```
相关 log 里不会出现 `script=hani`
```tex
(fontspec)             - 'normal' (m/n) with NFSS spec.: <->"Songti SC
(fontspec)             Light/OT:language=dflt;"
```

安装 macTeX 后，有没有改过什么？

**Comment by Redish101** [comment]
> github issue 支持直接上传附件，我重传了一份 [Latex.log](https://github.com/CTeX-org/forum/files/11132247/Latex.log)
> 
> > ```
> > Package fontspec Info: Font family 'SongtiSCLight(0)' created for font 'Songti	
> > (fontspec)             SC Light' with options	
> > (fontspec)             [Script={CJK},BoldItalicFont={Kaiti SC	
> > (fontspec)             Bold},BoldFont={Songti SC Bold},ItalicFont={Kaiti SC}].	
> > (fontspec)              	
> > (fontspec)              This font family consists of the following NFSS	
> > (fontspec)             series/shapes:	
> > (fontspec)              	
> > (fontspec)             - 'normal' (m/n) with NFSS spec.: <->"Songti SC	
> > (fontspec)             Light/OT:script=hani;language=dflt;"
> > ```
> 
> 最后一行里的 `script=hani` 不是默认会带的，xecjk 初始设置的是 `\defaultCJKfontfeatures{Script=CJK}`，然后会报如下 warning，
> ```
> Package fontspec Warning: Font "Songti SC Light" does not contain requested
> (fontspec)                Script "CJK".
> ```
> 相关 log 里不会出现 `script=hani`
> ```tex
> (fontspec)             - 'normal' (m/n) with NFSS spec.: <->"Songti SC
> (fontspec)             Light/OT:language=dflt;"
> ```
> 
> 安装 macTeX 后，有没有改过什么？

并没有，但是我的设备上也安装过MikTex，但因为无法正确读取字体而又安装了MacTex，会不会是这两者冲突导致的？

**Comment by muzimuzhi** [comment]
有可能。用 "miktex, script=hani` 确实能搜到一些问答/讨论。我没有在 macOS 上使用 miktex 的经验，帮不上

**Comment by Redish101** [comment]
> 有可能。用 "miktex, script=hani" 确实能搜到一些问答/讨论。我没有在 macOS 上使用 MiKTeX 的经验，帮不上
> 
> MiKTeX 关于「在 macOS 卸载」的官方文档 https://miktex.org/howto/install-miktex-mac （见网页末尾）

我使用miktexsetup删除了miktex，但是此问题依然存在

**Comment by Redish101** [comment]
我将系统字体目录内的宋体删除，成功解决了问题

**Comment by muzimuzhi** [comment]
你是什么版本的 macOS？

**Comment by Redish101** [comment]
13.0
