### ISSUE TITLE
linux和windows下伪粗效果不统一

### ISSUE THREAD

**Issue by ytskuh** [CTeX-org/forum#281]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [x] Linux (Arch Linux)

- TeX 发行版
  - [x] TeX Live 2023
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题
学校提供了latex论文模板。该模板应该是为windows系统下设计的，未指定fontset参数。在linux下会默认使用Fandol字库而导致使用字体不符合要求。添加fontset=windows后，虽然能够得到相同的字体（SimSun, SimHei)，但无法显示粗体。windows下似乎自动使用了伪粗，但linux下不行。添加AutoFakeBold=2参数后，能得到大体上相同的结果，但细节依然有差异。

虽然从效果上来看，linux下显式地使用伪粗似乎更好（无锯齿形），但是这毕竟是一个问题——不同平台无法实现相同的效果。并且，我无法得知windows下自动的伪粗究竟使用的是什么参数。

## 最小工作示例（MWE）
windows版（原本）：
```
\documentclass[UTF8,a4paper,12pt]{ctexart}
\begin{document}
\songti\zihao{1} \textbf{模板}
\end{document}
```
![image](https://raw.githubusercontent.com/ytskuh/image/main/Screenshot_20230411_205347.png)

为实现相同字体，Linux下的修改版：
```
\documentclass[UTF8,a4paper,12pt, fontset=windows, AutoFakeBold=2]{ctexart}
\begin{document}
\songti\zihao{1} \textbf{模板}
\end{document}
```
![image](https://raw.githubusercontent.com/ytskuh/image/main/Screenshot_20230411_210604.png)

**Comment by muzimuzhi** [comment]
> windows版（原本）：
> 
> ```
> \documentclass[UTF8,a4paper,12pt]{ctexart}
> \begin{document}
> \songti\zihao{1} \textbf{模板}
> \end{document}
> ```

- 用的什么引擎？
- 请再次确认，用这个简单例子就能得到伪粗吗？如果答案是「是」，建议检查 log，看是不是加载了什么本地修改过的配置。也可以上传 log

**Comment by ytskuh** [comment]
用的xelatex
确认是。我是请求他人帮我尝试的。短时间内不能上传log。但学校提供的模板里pdf的效果一模一样（锯齿状伪粗）。并且他应该没有修改过什么配置。

**Comment by muzimuzhi** [comment]
> 但学校提供的模板里pdf的效果一模一样（锯齿状伪粗）。并且他应该没有修改过什么配置。

不，这种稍微错开多次排印的伪粗，不是 `ctexart` 默认会使用的。我在 GitHub Actions 里做了测试，见 https://github.com/muzimuzhi/hello-github-actions/pull/10 。Windows Server 2022 + TeX Live 2023 下，xelatex 编译你的例子得到的是正常的无加粗的 宋体/SimSun（可以从[这里](https://github.com/muzimuzhi/hello-github-actions/actions/runs/4675333453)下载 artifacts 查看 PDF），并伴随 warning
```
LaTeX Font Warning: Font shape `TU/SimSun(1)/b/n' undefined
(Font)              using `TU/SimSun(1)/m/n' instead on input line 3.
```

请务必检查哪里改了，比如有没有加载一个自定义的 `ctex.cfg` 或 `xeCJK.cfg`。如果安装 TeX Live 2023 后没有手动改过发行版安装目录下的文件，可以在 log 里找找有没有特别的路径。上传完整 log 文件可能会有帮助，只是可能。

**Comment by sikouhjw** [comment]
我认为你提供的信息是错的，以下是复现条件、代码和效果：
- TeX Live 2022
- win 11


```tex
\documentclass{article}
\usepackage[scheme=plain]{ctex}
\begin{document}
\songti\zihao{1}\bfseries 模板
\end{document}
```
- `pdflatex`
   ![图片](https://user-images.githubusercontent.com/49770925/231447058-32b08137-f76f-4526-8b34-05a2089b29fc.png)

- `xelatex`
   ![图片](https://user-images.githubusercontent.com/49770925/231447198-63bd2b11-fce1-4948-8094-06efc77df8d0.png)
   并报警告
   ```
   Font shape `TU/SimSun(1)/b/n' undefined
   (Font)	using `TU/SimSun(1)/m/n' instead.
   ```

```tex
\documentclass[AutoFakeBold=2]{ctexart}
\begin{document}
\songti\zihao{1} \textbf{模板}
\end{document}
```
- `xelatex`
   ![图片](https://user-images.githubusercontent.com/49770925/231448724-b5b0d846-9317-4280-b749-47588b568847.png)
- `pdflatex`
   ![图片](https://user-images.githubusercontent.com/49770925/231450027-5133ac2d-548e-4705-ab37-ca0bb1d61aa0.png)
   并报警告
   ```
   Unused global option(s):
       [AutoFakeBold].
   ```

可以发现，只跟引擎有关，请你确保你所说的『用的xelatex』是你亲眼看见、用命令行编译、能提供 log 文件的结果，否则不能作为证明。

**Comment by ytskuh** [comment]
理解。看来应该是用pdflatex编译才产生了这种效果。为给出了错误的信息而抱歉。最后请教一下，如何用pdflatex编译？我用`latexmk -pdflatex`与`pdflatex`均会报错，显示
```
!pdfTeX error: pdflatex (file simsun.ttc): cannot open TrueType font file for r
eading
```

**Comment by sikouhjw** [comment]
> 理解。看来应该是用pdflatex编译才产生了这种效果。为给出了错误的信息而抱歉。最后请教一下，如何用pdflatex编译？我用`latexmk -pdflatex`与`pdflatex`均会报错，显示
> 
> ```
> !pdfTeX error: pdflatex (file simsun.ttc): cannot open TrueType font file for r
> eading
> ```

你大概率是用 Linux 环境编译的，请你提供『完整』的信息，并尝试自行检索。
