### ISSUE TITLE
中英文之间空格不习惯，如何去掉？

### ISSUE THREAD

**Issue by eikalida** [CTeX-org/forum#282]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2017
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

中英文带空格太丑了，比如：
中英文English
不应该是
中英文 English

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\begin{document}
中英文带空格太丑了，比如：
中英文English
不应该是
中英文 English
\end{document}
```

（用 XeLaTeX 编译后）输出

## 链接

- TeX.SX:
- GitHub:

**Comment by OsbertWang** [comment]
> @OsbertWang 他喜欢啥就给啥吧，不劝。

不劝，只摆事实

**Comment by eikalida** [comment]
> > @OsbertWang 他喜欢啥就给啥吧，不劝。
> 
> 不劝，只摆事实

我刚刚用上，还太不习惯，平常的时候一半都是连着的，感觉看着断开的有点难受。

**Comment by OsbertWang** [comment]
> > > @OsbertWang 他喜欢啥就给啥吧，不劝。
> > 
> > 
> > 不劝，只摆事实
> 
> 我刚刚用上，还太不习惯，平常的时候一半都是连着的，感觉看着断开的有点难受。

我只是把我测试的结果摆出来，你怎么决定是你的事

**Comment by muzimuzhi** [comment]
> ![in-word](https://user-images.githubusercontent.com/37971080/231756257-3c2c68f3-50e7-4f5a-826a-f01055d22906.png) 专门在 word 365 中做了测试。

解释一下，ta 是想说，在 MS Office Word 里，中英文之间也有自动添加的间距。假设接受 Word 里的效果，那么 `xecjk` 里的效果就也可以接受。

**Comment by eikalida** [comment]
> 估计 @eikalida 就是接受不了。

是的，我感觉确实非常难受。在word里面不会很明显，但是到了pdf里面比较明显。刚刚试了一下你的方法，终于把问题解决了，谢谢啦，以为要很久很久才会有人回复的，没想到速度那么快。
