### ISSUE TITLE
CTeX 3.0.212.1 xelatex编译通过，但无法生成pdf。dvipdfmx:fatal: typecheck: Invalid object type: -1 7 (line 2378)]

### ISSUE THREAD

**Issue by MissyDad** [CTeX-org/forum#284]
win11系统，CTeX 3.0.212.1，对1年前已经编译过的自己的毕业论文进行xelate编译，存在下面问题：
Command Line:   xelatex.exe --interaction=errorstopmode --synctex=-1 "scutthesis.tex"
Startup Folder: D:\zjq\scutthesis-master

xelatex: security risk: running with elevated privileges
This is XeTeX, Version 3.141592653-2.6-0.999994 (MiKTeX 23.1) (preloaded format=xelatex.fmt)
 restricted \write18 enabled.
entering extended mode
(scutthesis.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-03-30> (scutthesis.cls
Document Class: scutthesis 2011/03/31 2.0.1 The LaTeX class for the thesis of S
outh China University of Technology
(d:\CTEX\MiKTeX\tex/latex/base\book.cls
Document Class: book 2022/07/02 v1.4n Standard LaTeX document class
(d:\CTEX\MiKTeX\tex/latex/base\bk12.clo))
(d:\CTEX\MiKTeX\tex/generic/iftex\ifpdf.sty
(d:\CTEX\MiKTeX\tex/generic/iftex\iftex.sty))
(d:\CTEX\MiKTeX\tex/latex/base\ifthen.sty)
(d:\CTEX\MiKTeX\tex/latex/base\doc.sty
(d:\CTEX\MiKTeX\tex/latex/tools\multicol.sty))
(d:\CTEX\MiKTeX\tex/latex/graphics\keyval.sty)
(d:\CTEX\MiKTeX\tex/latex/xcolor\xcolor.sty
(d:\CTEX\MiKTeX\tex/latex/graphics-cfg\color.cfg)
(d:\CTEX\MiKTeX\tex/latex/graphics-def\xetex.def)
(d:\CTEX\MiKTeX\tex/latex/graphics\mathcolor.ltx)
(d:\CTEX\MiKTeX\tex/latex/graphics\dvipsnam.def))
(d:\CTEX\MiKTeX\tex/latex/tools\indentfirst.sty)
(d:\CTEX\MiKTeX\tex/latex/base\makeidx.sty)
(d:\CTEX\MiKTeX\tex/latex/amsfonts\amssymb.sty
(d:\CTEX\MiKTeX\tex/latex/amsfonts\amsfonts.sty))
(d:\CTEX\MiKTeX\tex/latex/pdfpages\pdfpages.sty
(d:\CTEX\MiKTeX\tex/latex/tools\calc.sty)
(d:\CTEX\MiKTeX\tex/latex/eso-pic\eso-pic.sty)
(d:\CTEX\MiKTeX\tex/latex/graphics\graphicx.sty
(d:\CTEX\MiKTeX\tex/latex/graphics\graphics.sty
(d:\CTEX\MiKTeX\tex/latex/graphics\trig.sty)
(d:\CTEX\MiKTeX\tex/latex/graphics-cfg\graphics.cfg)))
(d:\CTEX\MiKTeX\tex/latex/pdfpages\ppxetex.def))
(d:\CTEX\MiKTeX\tex/latex/geometry\geometry.sty
(d:\CTEX\MiKTeX\tex/generic/iftex\ifvtex.sty)
(d:\CTEX\MiKTeX\tex/latex/geometry\geometry.cfg))
(d:\CTEX\MiKTeX\tex/xelatex/xecjk\xeCJK.sty
(d:\CTEX\MiKTeX\tex/latex/l3kernel\expl3.sty
(d:\CTEX\MiKTeX\tex/latex/l3backend\l3backend-xetex.def))
(d:\CTEX\MiKTeX\tex/latex/ctex\ctexhook.sty)
(d:\CTEX\MiKTeX\tex/latex/l3packages/xtemplate\xtemplate.sty)

Package xeCJK Warning: The `CJKnumber' option is deprecated.
(xeCJK)                You may load the package `CJKnumb' after xeCJK to use
(xeCJK)                its function.
(xeCJK)                

(d:\CTEX\MiKTeX\tex/latex/fontspec\fontspec.sty
(d:\CTEX\MiKTeX\tex/latex/l3packages/xparse\xparse.sty)
(d:\CTEX\MiKTeX\tex/latex/fontspec\fontspec-xetex.sty
(d:\CTEX\MiKTeX\tex/latex/base\fontenc.sty)
(d:\CTEX\MiKTeX\tex/latex/fontspec\fontspec.cfg)))
(d:\CTEX\MiKTeX\tex/xelatex/xecjk\xeCJK.cfg))
(d:\CTEX\MiKTeX\tex/latex/cjk\CJKnumb.sty)
(d:\CTEX\MiKTeX\tex/latex/subfig\subfig.sty
(d:\CTEX\MiKTeX\tex/latex/caption\caption.sty
(d:\CTEX\MiKTeX\tex/latex/caption\caption3.sty)))
(d:\CTEX\MiKTeX\tex/latex/float\float.sty)
(d:\CTEX\MiKTeX\tex/latex/newfloat\newfloat.sty)
(d:\CTEX\MiKTeX\tex/latex/tools\array.sty)
(d:\CTEX\MiKTeX\tex/latex/booktabs\booktabs.sty)
(d:\CTEX\MiKTeX\tex/latex/tools\longtable.sty)
(d:\CTEX\MiKTeX\tex/latex/ctable\ctable.sty
(d:\CTEX\MiKTeX\tex/latex/etoolbox\etoolbox.sty)
(d:\CTEX\MiKTeX\tex/latex/xkeyval\xkeyval.sty
(d:\CTEX\MiKTeX\tex/generic/xkeyval\xkeyval.tex
(d:\CTEX\MiKTeX\tex/generic/xkeyval\xkvutils.tex)))
(d:\CTEX\MiKTeX\tex/latex/tools\tabularx.sty)
(d:\CTEX\MiKTeX\tex/latex/graphics\rotating.sty)

Package ctable Warning: 
(ctable)                Transparency disabled: pdfTeX is not running in PDF mod
e .

) (d:\CTEX\MiKTeX\tex/latex/threeparttable\threeparttable.sty)
(d:\CTEX\MiKTeX\tex/latex/paralist\paralist.sty)
(d:\CTEX\MiKTeX\tex/latex/natbib\natbib.sty)
(d:\CTEX\MiKTeX\tex/latex/algorithm2e\algorithm2e.sty
(d:\CTEX\MiKTeX\tex/latex/ifoddpage\ifoddpage.sty)
(d:\CTEX\MiKTeX\tex/latex/tools\xspace.sty)
(d:\CTEX\MiKTeX\tex/latex/relsize\relsize.sty))
(d:\CTEX\MiKTeX\tex/latex/listings\listings.sty
(d:\CTEX\MiKTeX\tex/latex/listings\lstmisc.sty)
(d:\CTEX\MiKTeX\tex/latex/listings\listings.cfg))
(d:\CTEX\MiKTeX\tex/xelatex/xecjk\xeCJK-listings.sty)
(d:\CTEX\MiKTeX\tex/latex/tocbibind\tocbibind.sty

Package tocbibind Note: Using chapter style headings, unless overridden.

) (d:\CTEX\MiKTeX\tex/latex/titlesec\titletoc.sty)
(d:\CTEX\MiKTeX\tex/latex/titlesec\titlesec.sty
(d:\CTEX\MiKTeX\tex/latex/titlesec\titleps.sty))
(d:\CTEX\MiKTeX\tex/latex/tools\bm.sty)
(d:\CTEX\MiKTeX\tex/latex/amsmath\amsmath.sty
For additional information on amsmath, use the `?' option.
(d:\CTEX\MiKTeX\tex/latex/amsmath\amstext.sty
(d:\CTEX\MiKTeX\tex/latex/amsmath\amsgen.sty))
(d:\CTEX\MiKTeX\tex/latex/amsmath\amsbsy.sty)
(d:\CTEX\MiKTeX\tex/latex/amsmath\amsopn.sty))
(d:\CTEX\MiKTeX\tex/latex/amscls\amsthm.sty)
(d:\CTEX\MiKTeX\tex/latex/jknappen\mathrsfs.sty))
(d:\CTEX\MiKTeX\tex/latex/hyperref\hyperref.sty
(d:\CTEX\MiKTeX\tex/generic/ltxcmds\ltxcmds.sty)
(d:\CTEX\MiKTeX\tex/generic/pdftexcmds\pdftexcmds.sty
(d:\CTEX\MiKTeX\tex/generic/infwarerr\infwarerr.sty))
(d:\CTEX\MiKTeX\tex/latex/kvsetkeys\kvsetkeys.sty)
(d:\CTEX\MiKTeX\tex/generic/kvdefinekeys\kvdefinekeys.sty)
(d:\CTEX\MiKTeX\tex/generic/pdfescape\pdfescape.sty)
(d:\CTEX\MiKTeX\tex/latex/hycolor\hycolor.sty)
(d:\CTEX\MiKTeX\tex/latex/letltxmacro\letltxmacro.sty)
(d:\CTEX\MiKTeX\tex/latex/auxhook\auxhook.sty)
(d:\CTEX\MiKTeX\tex/latex/hyperref\nameref.sty
(d:\CTEX\MiKTeX\tex/latex/refcount\refcount.sty)
(d:\CTEX\MiKTeX\tex/generic/gettitlestring\gettitlestring.sty
(d:\CTEX\MiKTeX\tex/latex/kvoptions\kvoptions.sty)))
(d:\CTEX\MiKTeX\tex/latex/hyperref\pd1enc.def)
(d:\CTEX\MiKTeX\tex/generic/intcalc\intcalc.sty)
(d:\CTEX\MiKTeX\tex/generic/etexcmds\etexcmds.sty)
(d:\CTEX\MiKTeX\tex/latex/hyperref\puenc.def)
(d:\CTEX\MiKTeX\tex/latex/url\url.sty)
(d:\CTEX\MiKTeX\tex/generic/bitset\bitset.sty
(d:\CTEX\MiKTeX\tex/generic/bigintcalc\bigintcalc.sty))
(d:\CTEX\MiKTeX\tex/latex/base\atbegshi-ltx.sty))
(d:\CTEX\MiKTeX\tex/latex/hyperref\hxetex.def
(d:\CTEX\MiKTeX\tex/generic/stringenc\stringenc.sty)
(d:\CTEX\MiKTeX\tex/latex/rerunfilecheck\rerunfilecheck.sty
(d:\CTEX\MiKTeX\tex/latex/base\atveryend-ltx.sty)
(d:\CTEX\MiKTeX\tex/generic/uniquecounter\uniquecounter.sty)))

Package hyperref Warning: XeTeX driver only supports `unicode=true'. Ignoring
(hyperref)                option setting `unicode=false' on input line 17.

(d:\CTEX\MiKTeX\tex/xelatex/xunicode\xunicode.sty
(d:\CTEX\MiKTeX\tex/latex/tipa\t3enc.def

Package xeCJK Warning: Unknown CJK family `\CJKsfdefault' is being ignored.
(xeCJK)                
(xeCJK)                Try to use `\setCJKsansfont[<...>]{<...>}' to define
(xeCJK)                it.

)) (d:\CTEX\MiKTeX\tex/latex/hypdoc\hypdoc.sty

Package hypdoc Warning: hyperref has been loaded before. Check the options! on 
input line 56.

) (d:\CTEX\MiKTeX\tex/xelatex/xecjk\xunicode-addon.sty)
(d:\CTEX\MiKTeX\tex/xelatex/xunicode\xunicode.sty
*** Reloading Xunicode for encoding 'TU' ***
) (d:\CTEX\MiKTeX\tex/xelatex/xecjk\xunicode-extra.def) (scutthesis.aux)
(d:\CTEX\MiKTeX\tex/latex/base\ts1cmr.fd)
(d:\CTEX\MiKTeX\tex/latex/tipa\t3cmr.fd)
(d:\CTEX\MiKTeX\tex/latex/pdflscape\pdflscape.sty
(d:\CTEX\MiKTeX\tex/latex/pdflscape\pdflscape-nometadata.sty
(d:\CTEX\MiKTeX\tex/latex/graphics\lscape.sty)))
*geometry* driver: auto-detecting
*geometry* detected driver: xetex
(d:\CTEX\MiKTeX\tex/latex/caption\ltcaption.sty)
Writing index file scutthesis.idx
(scutthesis.out) (scutthesis.out) (scutthesis.hd) [1] [2]miktex-dvipdfmx: security risk: running with elevated privileges
 [3] [4] [5] [6]
[7] [8] (d:\CTEX\MiKTeX\tex/latex/amsfonts\umsa.fd)
(d:\CTEX\MiKTeX\tex/latex/amsfonts\umsb.fd)
(d:\CTEX\MiKTeX\tex/latex/jknappen\ursfs.fd) [1]

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\hbox' on input line 73.

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\hsize' on input line 73.

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\hss' on input line 73.

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                \hskip 12.0pt
(hyperref)                replaced by space on input line 73.

Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\hss' on input line 73.

[2
dvipdfmx:fatal: typecheck: Invalid object type: -1 7 (line 2378)]

No output PDF file written.
 (scutthesis.toc [3
Sorry, but xelatex.exe did not succeed.

The log file hopefully contains the information to get MiKTeX going again:

  d:\CTEX\UserData\miktex\log\xelatex.log

_____________________________________________________________________

 XeLaTeX Compilation Report (Pages: 0)

 Errors: 0   Warnings: 10   Bad Boxes: 0
_____________________________________________________________________

**Comment by MissyDad** [comment]
主要是给老婆搞毕业华南理工大学的论文格式排版
https://github.com/alwintsui/scutthesis

**Comment by MissyDad** [comment]
这个问题和https://github.com/alwintsui/scutthesis/issues/10
提到的一样

**Comment by note286** [comment]
TeX Live 2017实测可以。

**Comment by MissyDad** [comment]
> TeX Live 2017实测可以。

我想就是最新的ctex有问题。

**Comment by Sophanatprime** [comment]
与 CTeX 无关。
我使用 Overleaf 测试发现从 TeXLive 2019 开始就不能编译了。

原因是使用的 thesis_cover.pdf 这个 pdf 第 6 页的问题，不导入这一页就能正常编译。
反正这一页是空的，把 `.cls` 里的 `\includepdf[pages=-]{thesis_cover.pdf}` 改为 `\includepdf[pages={1-5,{},7,8}]{thesis_cover.pdf}` 就可以了。

PS：使用 Adobe Acrobat 导出 `thesis_cover.doc` 为 pdf，不必改动源文件，就可以正常编译。我用 LTSC Word 重新生成的 pdf 都不能正常编译。我不懂 PDF，不知道原因。

**Comment by muzimuzhi** [comment]
@MissyDad 下次建议上传 log 文件，log 里有更多信息，如各个包的版本信息。提供更多信息不一定每次都用得上，不过也没有特别的坏处。现在你贴的是 stdout。
