### ISSUE TITLE
当minipage环境和enumerate配合使用时，引入hyperref宏包会导致minipage顶部对齐失效

### ISSUE THREAD

**Issue by djunhao** [CTeX-org/forum#286]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10/11
  - [ ] Windows 8/8.1
  - [ ] Windows 7
  - [ ] 更早版本的 Windows
  - [ ] macOS
  - [ ] Linux（请附发行版）

- TeX 发行版
  - [x] TeX Live 2023
  - [ ] MiKTeX 
  - [ ] CTeX 套装 2.9.2.164
  - [ ] 更早版本的 CTeX 套装

## 描述问题

为了实现知乎中 [用 LaTeX 的 enumerate 如何实现下面的效果？](https://www.zhihu.com/question/65040634/answer/227326051)一文提到效果，我尝试使用minipage的顶部对齐配合enumerate来实现，无意中发现，如果引入hyperref宏包，将会导致minipage的顶部对齐失效。
## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
% \usepackage{hyperref}
\begin{document}
迷你页：\begin{minipage}[t]{20em}
\begin{enumerate}
    \item 每位参加比赛的同学现在两类问题中
    \item 选择一类并从中随机抽取一个问题回答
\end{enumerate}
\end{minipage}
\end{document}
```

用 XeLaTeX 编译后，生成的效果是正常的：
![政务微信截图_16816926399730](https://user-images.githubusercontent.com/1868266/232354357-5403a610-a6c6-4134-bb8e-a54a8b49e769.png)

但是，同样的代码，如果引入hyperref宏包：
```latex
\documentclass{ctexart}
 \usepackage{hyperref}
\begin{document}
迷你页：\begin{minipage}[t]{20em}
\begin{enumerate}
    \item 每位参加比赛的同学现在两类问题中
    \item 选择一类并从中随机抽取一个问题回答
\end{enumerate}
\end{minipage}
\end{document}
```
编译结果则会变成这样（变化如红线框所示）：

![政务微信截图_1681693081226](https://user-images.githubusercontent.com/1868266/232354798-d6774013-ca67-4cc3-804d-62eae90fe134.png)

请问这是什么原因？该如何消除引入hyperref后出现的“间距”？

**Comment by note286** [comment]
[spacing - Hyperref insert spurious space before list and minipage - TeX - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/423014/hyperref-insert-spurious-space-before-list-and-minipage)

**Comment by djunhao** [comment]
感谢 @note286 ，明白了！
