### ISSUE TITLE
TeX Live 2019 中 xdvipdfmx 出现 typecheck: Invalid object type 问题

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/forum#29]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [x] macOS
  - [x] Linux

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

```latex
% test.tex
\documentclass{article}
\usepackage{pdfpages}
\begin{document}
\includepdf[pages={4}]{cover.pdf} 
\end{document}
```

使用 `xelatex -no-pdf test && xdvipdfmx -vv test` 编译，结果如下：

```
xdvipdfmx:warning: Trying to include PDF file with version (1.7), which is newer than current output PDF setting (1.5).
xdvipdfmx:warning: PDF file is tagged... Ignoring tags.
xdvipdfmx:fatal: typecheck: Invalid object type: -1 7 (line 2161)

No output PDF file written.
```

原来的 [`cover.pdf`](https://github.com/CTeX-org/forum/files/3144331/cover.pdf) 使用 pdfinfo 查看信息，结果为

```
Title:          
Author:         hitgs
Creator:        Microsoft� Word 2016
Producer:       Microsoft� Word 2016
CreationDate:   Sat Apr 27 20:51:31 2019
ModDate:        Sat Apr 27 20:51:31 2019
Tagged:         yes
Form:           none
Pages:          6
Encrypted:      no
Page size:      595.32 x 841.92 pts (A4) (rotated 0 degrees)
File size:      301533 bytes
Optimized:      no
PDF version:    1.7
```

使用 pdflatex 会有警告（版本号 1.7 高于当前版本号 1.5），而 lualatex 可正常编译。在 TeX Live 2018 中，据原提问者称虽有类似的警告但可编译通过。

注意该 PDF 中 2、4、6 页为空白，而只在插入页数包含 2、4 时会无法编译。

**Comment by muzimuzhi** [comment]
使用 texlive2019，在 xetex 下能复现

```latex
\XeTeXpdffile cover.pdf page 2 % or 4
\bye
```

**Comment by clerkma** [comment]
确实是texlive 2018里面的dvipdfmx可以编译通过。
主要的代码变动在这里：[epdf.c](http://tug.org/svn/texlive/trunk/Build/source/texk/dvipdfm-x/epdf.c?r1=48595&r2=48663)
引起这个问题的原因，就是Office组件输出的PDF里面的空页面有可能真是空的数组。
上面的代码，第二页内容如下：
```
17 0 obj
<<
  /Type /Page
  /Parent 2 0 R
  /MediaBox [ 0 0 595.32 841.92 ]
  /Resources <<
    /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]
  >>
>>
endobj
```
第四页的内容如下
```
41 0 obj
<<
  /Type /Page
  /Parent 2 0 R
  /MediaBox [ 0 0 595.32 841.92 ]
  /Resources <<
    /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]
  >>
>>
endobj
```
为什么第六页就可以呢？看内容如下：
```
44 0 obj
<<
  /Type /Page
  /Parent 2 0 R
  /Resources <<
    /Font <<
      /F1 5 0 R
    >>
    /ProcSet [ /PDF /Text /ImageB /ImageC /ImageI ]
  >>
  /MediaBox [ 0 0 595.32 841.92 ]
  /Contents 45 0 R
  /StructParents 3
>>
endobj
```
也就是说，能够插入成功的页面，是有Contents的。出现问题的地方，是代码变动后，C源码里面的`contents`直接变为了`NULL`，而代码变动前，`contents`的内容如果为`NULL`的话，会调用`pdf_new_stream`得到一个新的`pdf_stream`对象，从而保证不是`NULL`。

这个问题比较好修正。等几天就修了。

**Comment by muzimuzhi** [comment]
补充：根据 PDF Ref. v1.7, table 3.27, 页面对象中的 `/Contents` 项是可选的。也就是说，当前 issue 提及的 pdf 文件是合法的。

**Comment by hanwen** [comment]
你好 !

@stone-zeng 

apologies for commenting in English. My Mandarin is close to non-existent.

We are seeing a problem with xdvipdfmx that seems like it's the same:

  https://gitlab.com/lilypond/lilypond/-/merge_requests/176
  https://lists.gnu.org/archive/html/lilypond-devel/2020-06/msg00129.html

You closed this bug on Oct 18, 2019; can you tell me what change to dvipdfmx fixed the problem?

谢谢 !
