### ISSUE TITLE
How to draw an specific feynman diagram with TikZ (LaTeX)

### ISSUE THREAD

**Issue by gtg2000** [CTeX-org/forum#292]
Hi,
I was looking for a diagram such as shown in the first picture, but I just get the one that is in the second picture with this code:

\begin{tikzpicture}
\begin{feynman}[large]
\vertex (b);
\vertex [left=of b] (a);
\vertex [above right=of a] (i1);
\vertex [below right=of a] (i2);
\vertex (d);
\vertex [right=of d] (c);
\vertex [above left=of c] (j1);
\vertex [below left=of c] (j2);
\diagram* {
(a) [crossed dot] -- [double] (b)  -- [gluon] (j1),
(a) [crossed dot] -- [double] {(i1),(i2)},

(d) -- [double] (c) [crossed dot],
(j1) -- [double] (c) [crossed dot] -- [double] (j2),
};
\end{feynman}
\end{tikzpicture}

How can I separate the central lines and draw the correct vertex?

Thank you in advance!!

![feynman](https://user-images.githubusercontent.com/132346740/235631510-412ce62a-5a59-4af6-87e3-ffceff963e88.png)

![feynman tikz](https://user-images.githubusercontent.com/132346740/235631736-323b22aa-a02d-44e1-a446-7940aa69cfee.png)

**Comment by note286** [comment]
现在已经国际化了吗？

**Comment by SwitWu** [comment]
问错地方了吧

**Comment by note286** [comment]
@SwitWu 还是刚注册的账号。
