### ISSUE TITLE
安装了CTeX_3.0.215.2_Full.exe: 64位通用版本，打开软件或者使用中总是弹出要求注册的窗口，请问该如何处理

### ISSUE THREAD

**Issue by Heesophia** [CTeX-org/forum#295]
![1691725074351(1)](https://github.com/CTeX-org/forum/assets/127093562/6f8d6469-8c1a-45a0-876d-56e4d619a9af)

**Comment by Harry-Chen** [comment]
本 repo 的内容是 ctex 宏集，不是 CTEX 发行版。相关问题请到 https://github.com/Aloft-Lab/CTeX-Installer 提出。

对于此问题友情提醒，WinEdt 是付费软件，要求购买是正常行为。

**Comment by muzimuzhi** [comment]
这里是 CTeX-org/forum 仓库，根据 [readme](https://github.com/CTeX-org/forum/blob/88e6f052f671973ef1cc91dcd1018716a3a6afd9/README.md)

> # CTeX 临时论坛
>
> 由于 [原 CTeX 论坛](http://bbs.ctex.org/) 因故无限期关闭，我们在此建立临时论坛，通过 GitHub Issues 进行提问、回答与讨论。

可以在这里提问 CTEX 发行版相关的事。
