### ISSUE TITLE
希望在同一 tabular 的多个 cell 内生成不同的多个脚注

### ISSUE THREAD

**Issue by Mikachu2333** [CTeX-org/forum#303]
## 检查
- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10

- TeX 发行版
  - [X] TeX Live 2023
## 描述问题

1. 在试图在同一tabular的不同单元格内生成内容不同的脚注时失败
2. 表现为 `\footnote` 无法使用，`\footnotemark` 与 `\footnotetext{}` 只能生成序号相同的脚注
3. 已经尝试了通过 `%` 分隔的方法然而无效。
4. 未能找到与之相关的其他可行方法

![图片](https://github.com/CTeX-org/forum/assets/63829496/fd596c44-1600-4510-bdbd-ca78a3cb2d18)

## 最小工作示例（MWE）

```
\documentclass[a4paper]{ctexrep}
\usepackage{ulem,float}
\usepackage{multirow,booktabs,makecell}
\begin{document}
\begin{table}[H]
    \centering
    \begin{tabular}{|c|c|}
        \Xhline{1.2pt}
        地点  & 习惯称呼                            \\
        \Xhline{1.2pt}
        XXX & A啊啊AA       \footnotemark   \\
        \Xhline{1.2pt}
        \multirow{3}{*}{YYY}
            & BBBB斌BBBBBB \footnote{2贰2222222} \\
        \cline{2-2}
            & C草CC      \footnotemark        \\
        \cline{2-2}
            & D贷D \footnotemark                %
        \footnotetext{444肆4444}                \\
        \Xhline{1.2pt}
    \end{tabular}
\end{table}
\footnotetext{1111壹111111}
\footnotetext{3333333叁3}
\end{document}
```

## 其他尝试
1. [footnotes-in-tabulars](https://tex.stackexchange.com/questions/35200/footnotes-in-tabulars) ，但是均无法在中文环境下工作，而我也不想把我所有的tabular换成其他的例如 supertabular 之类……因为过大的工作量

## 其他：
1. 脚注位于表格底部或页面底部均可，脚注内容支持使用 `\href` 超链接
2. 单元格与脚注均为中英混杂

**Comment by muzimuzhi** [comment]
> 描述问题
> 2\. [...] `\footnotemark` 与 `\footnotetext{}` 只能生成序号相同的脚注

传统上，（要为多个 `\footnotemark` 添加对应的 `\footnotetext` 时），得使用 `\footnotetext[<number>]{<text>}` 手动指定序号。
https://latexref.xyz/_005cfootnotetext.html

> 其他尝试
> 1\. [footnotes-in-tabulars](https://tex.stackexchange.com/questions/35200/footnotes-in-tabulars) ，但是均无法在中文环境下工作

好像 https://tex.stackexchange.com/a/35327 里提到的 `tablefootnote` 包就能在中文环境下工作。

```tex
% !TeX TS-program = xelatex
\documentclass{ctexart}
\usepackage{float}
\usepackage{multirow,makecell}
\usepackage{tablefootnote}

\usepackage[colorlinks]{hyperref}

\begin{document}
\begin{table}[H]
    \centering
    \begin{tabular}{|c|c|}
        \Xhline{1.2pt}
        地点  & 习惯称呼          \\ \Xhline{1.2pt}
        XXX & A啊A\footnotemark \\ \Xhline{1.2pt}
        \multirow{3}{*}{YYY}
            & B斌B\footnotemark \\ \cline{2-2}
            & C草C\footnotemark \\ \cline{2-2}
            & D贷D\footnotemark \\ \Xhline{1.2pt}
    \end{tabular}
\end{table}
\footnotetext[1]{1壹1}
\footnotetext[2]{2贰2}
\footnotetext[3]{3叁3}
\footnotetext[4]{4肆4}

\begin{table}[H]
    \centering
    \begin{tabular}{|c|c|}
        \Xhline{1.2pt}
        地点  & 习惯称呼                \\ \Xhline{1.2pt}
        XXX & A啊A\tablefootnote{A啊A} \\ \Xhline{1.2pt}
        \multirow{3}{*}{YYY}
            & B斌B\tablefootnote{B斌B} \\ \cline{2-2}
            & C草C\tablefootnote{C草C} \\ \cline{2-2}
            & D贷D\tablefootnote{D贷D} \\ \Xhline{1.2pt}
    \end{tabular}
\end{table}

\newpage
content % 为了点击超链接后有跳转空间
\end{document}
```

![image](https://github.com/CTeX-org/forum/assets/6376638/d5180b1d-4129-4203-8594-740810ecc28b)
![image](https://github.com/CTeX-org/forum/assets/6376638/44c71f2b-1e9f-4e1c-892e-ffbb9c2bae11)

**Comment by Mikachu2333** [comment]
啊，发现了问题所在，昨天在生成的时候虽然没有报错，但是实际上并没有安装 tablefootnote 宏包，估计是由于忘记清理缓存文件所致。
今天清除缓存并重新安装宏包生成以后问题解决！

**Comment by muzimuzhi** [comment]
> 昨天在生成的时候虽然没有报错，但是实际上并没有安装 tablefootnote 宏包

怎么会呢……
