### ISSUE TITLE
如何实现源代码和生成的表格都出现在生成的pdf文件上？

### ISSUE THREAD

**Issue by xuicst** [CTeX-org/forum#305]
![1](https://github.com/CTeX-org/forum/assets/122449450/22376b50-158b-4920-81fa-2497c03cd6af)
看对应[文件代码](https://github.com/CTeX-org/lshort-zh-cn/blob/bd6fc83c9d7f8a535b68dcfec177dfbd9fe99094/src/chap/chap.03.elements.tex#L737)(点击跳转源)是
```
\begin{example}
\begin{tabular}{|c|c|c|}
 \hline
 a & b & c \\ \hline
 a & \multicolumn{1}{@{}c@{}|}
 {\begin{tabular}{c|c}
   e & f \\ \hline
   e & f \\
  \end{tabular}}
       & c \\ \hline
 a & b & c \\ \hline
\end{tabular}
\end{example}

\pkgindex{makecell}
```
🆘 请教各位大佬，我想**复现**上图情况，具体代码该如何编写？

**Comment by xuicst** [comment]
👍明白了，非常感谢大佬热心相助😄

**Comment by sikouhjw** [comment]
也可以看我当年写的《[用 minted 宏包制作 example 环境](https://sikouhjw.github.io/2020/04/29/2020-04-29-Make-an-example-environment-with-minted/)》和《[让 example 环境带上导言区](https://sikouhjw.github.io/2021/03/03/2021-03-03-preamble-verbatim-example/)》

**Comment by xuicst** [comment]
👍 谢谢
