### ISSUE TITLE
给特殊符号设置xeCJKsetcharclass，并打开CJKmath，特殊符号仍不能直接用于数学模式

### ISSUE THREAD

**Issue by DailyShana** [CTeX-org/forum#313]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 操作系统

Windows 11

### TeX 发行版

TeX Live 2024

### 描述问题

想在公式中直接使用宋体的符号≌ (U+224C)（字形与国内教科书一致），利用\xeCJKsetcharclass将其设置为CJK字符，再设置\xeCJKsetup{CJKmath=true}，在数学模式使用\symbol{"224C}，仍有找不到字体的错误。

我知道用\mbox或\text可以解决，但想看看能不能避免用这些workaround
不想用unicode-math，因为很多符号的外形与之前不一样

### 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\xeCJKsetcharclass{"224C}{"224C}{1}
\xeCJKsetup{CJKmath=true}
\begin{document}
$\triangle ABC\symbol{"224C}\triangle DEF$
\end{document}
```

用 XeLaTeX 编译后，日志文件输出：

```latex
Missing character: There is no ≌ (U+224C) in font [lmroman10-regular]:mapping=t
ex-text;!
```

### 链接

- TeX.SX:
- GitHub:

**Comment by OsbertWang** [comment]
考虑用 `unicode-math` 来满足你的需求。
```
\documentclass{ctexart}
\xeCJKsetcharclass{"224C}{"224C}{1}
\xeCJKsetup{CJKmath=true}
\usepackage{unicode-math}
\setmathfont{XITS Math}
\begin{document}
$\triangle ABC\symbol{"224C}\triangle DEF$
\end{document}
```
![image](https://github.com/CTeX-org/forum/assets/37971080/1243192a-8125-40db-9385-89b3609a567c)

**Comment by muzimuzhi** [comment]
你用的命令 `\xeCJKsetcharclass` 没有用户文档，是怎么知道它和它的用法的？

用有用户文档的 `\xeCJKDeclareCharClass{CJK}{"224C}`，能让公式里的 `\symbol{"224C}` 用中文字体渲染（见末尾 `\showbox` 输出的 `\TU/SongtiSCLight(0)/m/n/10.53937 glyph#18892`。

```tex
\documentclass{ctexart}
\xeCJKDeclareCharClass{CJK}{"224C}
\xeCJKsetup{CJKmath=true}

\begin{document}
$\triangle ABC\symbol{"224C}\triangle DEF$

\showboxbreadth=\maxdimen
\showboxdepth=\maxdimen
\setbox0=\hbox{$\triangle ABC\symbol{"224C}\triangle DEF$}
\showbox0
\end{document}
```

![image](https://github.com/CTeX-org/forum/assets/6376638/5bee0466-a406-48d6-935c-22a2cdf7f9e9)

```tex
> \box0=
\hbox(7.319+2.04932)x79.63737
.\mathon
.\OMS/cmsy/m/n/10.53937 4
.\OML/cmm/m/it/10.53937 A
.\OML/cmm/m/it/10.53937 B
.\kern0.52878
.\OML/cmm/m/it/10.53937 C
.\kern0.75385
.\TU/SongtiSCLight(0)/m/n/10.53937 glyph#18892
.\OMS/cmsy/m/n/10.53937 4
.\OML/cmm/m/it/10.53937 D
.\kern0.29276
.\OML/cmm/m/it/10.53937 E
.\kern0.60747
.\OML/cmm/m/it/10.53937 F
.\kern1.4638
.\mathoff
```

**Comment by DailyShana** [comment]
@muzimuzhi 多谢，网上搜索尝试解决本issue的问题知道`\xeCJKsetcharclass`的用法的

**Comment by muzimuzhi** [comment]
看起来 `\xeCJKsetcharclass` 是老版本的 xeCJK 里提供的命令，比如刘海洋 2012 年的 [TeX-SX 回答](https://tex.stackexchange.com/a/42681/79060)里用到了它。而后面随着内部实现的调整，它要不废弃了（从没有用户文档的角度），要不没有跟进所需的更改。

比较 `\xeCJKDeclareCharClass` 和 `\xeCJKsetcharclass` 的实现，并手动补上后者缺的逻辑后，`\xeCJKsetcharclass` 也能生效了。可以看到，还是 `\xeCJKDeclareCharClass` 方便。
```tex
\documentclass{ctexart}
% \xeCJKDeclareCharClass{CJK}{"224C}

\ExplSyntaxOn
% equivalent to \xeCJKDeclareCharClass{CJK}{"224C}
\clist_gput_right:cn { g__xeCJK_CJK_range_clist } { "224C }
\xeCJKsetcharclass {"224C} {"224C} { \xeCJK_class_num:n {CJK} }
\ExplSyntaxOff
\xeCJKsetup{CJKmath=true}

\begin{document}
$\triangle ABC\symbol{"224C}\triangle DEF$
\end{document}
```

**Comment by muzimuzhi** [comment]
> @muzimuzhi 多谢，网上搜索尝试解决本issue的问题知道`\xeCJKsetcharclass`的用法的

@DailyShana 具体是从哪里搜到的？可以去添加回复，提供现在有效的设置方式。

**Comment by DailyShana** [comment]
@muzimuzhi 知乎上一个输入特殊符号的问题，非数学模式，使用`\xeCJKsetcharclass`在非数学模式下是正常的

**Comment by muzimuzhi** [comment]
（提供链接啊……）

顺带，`\xeCJKDeclareCharClass` 的文档在 xeCJK 文档（v3.9.1，2022-08-05）的 sec. 3.4 "设置 CJK 字符范围"。

顺带 2，特殊字符也可以直接输入，如 `≌`。Unicode codepoint 到符号的转换可以在 https://r12a.github.io/app-conversion/ 完成。

**Comment by DailyShana** [comment]
感谢指点，链接在这： https://www.zhihu.com/question/298056786/answer/508515745


这个问题背景是主要是不同字体的`≌`符号字形相差比较大，想要的宋体的那个字形，不知道有没有什么地方可以方便查看各个字体的字形

**Comment by muzimuzhi** [comment]
我昨天也搜到这个回答，已经添加了评论，提示 `\xeCJKsetcharclass` 的缺陷了。

macOS 内置的 "Show Emoji & Symbols" 有这样的功能，Win 下可以找找第三方字体管理器。
