### ISSUE TITLE
安装ctex时报错

### ISSUE THREAD

**Issue by caofract** [CTeX-org/forum#316]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 操作系统

Win10

### TeX 发行版

Ctex套装CTeX_3.0.215.2_Full.exe

### 描述问题

ctex安装结束时出现：执行以下命令时发现错误，请检查安装日志! (Exitcode: 1)"D:\CTEX\MiKTeXymiktex\bin\x64\miktex.exe" --admin--disable-installer --verbose packages update

### 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\begin{document}
Hello, \LaTex!
\end{document}
```

用 XeLaTeX 编译后，日志文件输出：

```latex
! Undefined control sequence.
l.3 Hello, \LaTex
                !
?
```

### 链接

- TeX.SX:
- GitHub:

**Comment by muzimuzhi** [comment]
> 用 XeLaTeX 编译后，日志文件输出：
> 
> ```
> ! Undefined control sequence.
> l.3 Hello, \LaTex
>                 !
> ?
> ```

`\LaTeX`，"X" 大写。
