### ISSUE TITLE
\newtheorem和amsthm冲突问题

### ISSUE THREAD

**Issue by caofract** [CTeX-org/forum#319]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 操作系统

Win10

### TeX 发行版

Texlive2024

### 描述问题

引入amsthm宏包后，导言区输入\newtheorem{theorem}{定理}[section]。报错document.tex: 错误: 14: Command \theorem already defined. \newtheorem{theorem}{定理}[section]

### 最小工作示例（MWE）

```tex
\documentclass[11pt]{ctexbeamer}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usetheme{Madrid}
\usepackage{amsthm}
\usepackage{thmtools}
\usepackage{amsmath}

\newtheorem{theorem}{定理}[section]

\title[数学]{数学}
\date{2024年5月2日}
\author{李}
\institute[NU]{李}


\begin{document}

	 \frame{ \titlepage }
	 
	\section{论文研究背景}
	\begin{frame}
		\frametitle{nbjkbk科技部空间}
		vdvfvfrbr不然被万方
		\begin{theorem}[R. S.]
			E=c^2
		\end{theorem}
	\end{frame}
\end{document}
```

### 其他信息

我希望定理环境随章节编号，所以将\newtheorem{thm}{定理}[section]改为\newtheorem{thm}{定理}[section]。正文使用\begin{thm}.....\end{thm}。但是定理环境仍然没有编号。

**Comment by SwitWu** [comment]
你的问题 Beamer 手册里都讲了，具体见 https://www.beamer.plus/Structuring-Presentation-The-Local-Structure.html#sec-12.4

**Comment by muzimuzhi** [comment]
报错是因为 `beamer` 预加载了 `amsthm` 且预定义了一套定理类环境，包括但不限于 `theorem` 环境。和你是否手动加载了 `amsthm` 无关。

因为 `beamer` 没有提供配置定理类环境标题的接口，`amsthm` 也只有 `\newtheorem` 没有 `\renewtheorem`，可以用 `\documentclass[notheorems]{beamer}` 抑制定理类环境的预定义，然后自己逐个定义。

虽然没有配置标题的接口，但如 "Theorem" 的环境标题都被包在 `\translate{Theorem}`（见 `translator` 宏包）里，所以（如果制作的是非个人使用的、定制的中文 beamer 样式）也可以自己定制一套到中文的翻译。

```tex
\documentclass[11pt,notheorems]{ctexbeamer}
\usepackage{lmodern}
\usetheme{Madrid}

\newtheorem{theorem}{定理}[section]

\title[数学]{数学}
\date{2024年5月2日}
\author{李}
\institute[NU]{李}


\begin{document}

	\frame{ \titlepage }
	 
	\section{论文研究背景}
	\begin{frame}
		\frametitle{nbjkbk科技部空间}
		vdvfvfrbr不然被万方
		\begin{theorem}[R. S.]
			$E=c^2$
		\end{theorem}
	\end{frame}
\end{document}
```

![image](https://github.com/CTeX-org/forum/assets/6376638/f4e1469b-6f71-4fdd-be87-624f19a9e5cc)

**Comment by caofract** [comment]
> 你的问题 Beamer 手册里都讲了，具体见 https://www.beamer.plus/Structuring-Presentation-The-Local-Structure.html#sec-12.4

嗯嗯，我现在看一下。谢谢

**Comment by caofract** [comment]
@muzimuzhi 你好，这样确实不会报错了。但是定理环境仍然没有跟随章节编号，你知道怎么解决吗？

**Comment by caofract** [comment]
@muzimuzhi 刚刚看来一下别人的评论，我添加\setbeamertemplate{theorems}[numbered]解决了定理环境不编号的问题。感谢

**Comment by muzimuzhi** [comment]
是我之前没注意到。

在 `beamer` 里给定理类环境编号不是常见需求，因为一般 slides 的内容是另一个文档内容的摘录和重组，定理在原文档中按出现次序编号，在 slides 中则未必，一个定理可能出现多次、出现顺序和原文档可能不一致。可以定义一个排版定理 note 时不加小括号（`\begin{thm}[note]`）的 `amsthm` theorem style，然后手动编号。

**Comment by caofract** [comment]
@muzimuzhi 嗯嗯，我试一下。感谢
