### ISSUE TITLE
如何优雅的让行内公式换行？

### ISSUE THREAD

**Issue by caofract** [CTeX-org/forum#320]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 操作系统

Win10

### TeX 发行版

Texlive2024

### 描述问题

我使用$....$定义了一个行内公式，但是公式比较长，跑到下一行了。使上一行后面留下了大段的空白。
![image](https://github.com/CTeX-org/forum/assets/168255188/c46c8e47-a9b9-4d9e-bdbb-f603c2583852)
后来我在$....$手动添加了\allowbreak，完成了换行，但是这样做比较麻烦，而且后续修改会更加麻烦。
![image](https://github.com/CTeX-org/forum/assets/168255188/0f0e61d6-cef3-4daa-9a63-e33f333bb4c7)

所以想请教一下，有哪些优雅的方法可以全局设置，使$.....$定义的行内公式在公式自动换行，不让上一行留下大段的空白。达到手动添加\allowbreak的效果？

感谢！

### 最小工作示例（MWE）
```tex
\documentclass[aspectratio=169,notheorems,12pt]{ctexbeamer}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usetheme{Madrid}
\usepackage{amsthm}
\usepackage{amsmath}
\begin{document}
数学数学数学数学数学数学数学数学$a=b=c=a=b=c=a=b=c= \allowbreak a=b=c=a=b=c=$.
\end{document}

```

**Comment by muzimuzhi** [comment]
恐怕没有通用且自动的办法。全局设置 `\binoppenalty=0 \relpenalty=0` 也只能在最外层的关系符号和二元运算符号后自动换行，参考 `texdoc texbytopic`, sec. 23.9 Line breaking in math formulas. 反例比如，你输入 `$<200 个 "a">$` 是不会自动换行的。

从样式风格上，较长的行内公式就可以转换为行间公式了。当然非常长的行间公式也需要换行，多数时候是手动，也有 `breqn` 包等自动化尝试。行间公式的换行位置要比行内公式稳定些。

```tex
\documentclass[aspectratio=169,notheorems,12pt]{ctexbeamer}
\usepackage{lmodern}
\usetheme{Madrid}
\begin{document}
\begin{frame}
  数学数学数学数学数学数学数学数学$a=b=c=a=b=c=a=b=c= \allowbreak a=b=c=a=b=c=$.
  
  \binoppenalty=0
  \relpenalty=0
  数学数学数学数学数学数学数学数学$a=b=c=a=b=c=a=b=c=a=b=c=a=b=c=$.
\end{frame}
\end{document}
```

![image](https://github.com/CTeX-org/forum/assets/6376638/7a9f9d62-5fa9-4dc3-95c9-a011856dad8b)

------

PS：请把代码放进 markdown 的 [Fenced code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) 里，类似

````markdown
```tex
\documentclass{...}
```
````

这样有很多好处：高亮代码、保留缩进、让特殊字符（如 `#1`）维持原样。之前我帮你修改了 https://github.com/CTeX-org/forum/issues/319#issue-2286783838 ，把多行代码放进了 fenced code block。这回请尝试自己编辑帖子。

**Comment by caofract** [comment]
@muzimuzhi 好的，谢谢。因为我之前用的cetx2.9，在beamer文档下对中文+行内公式的编译结果支持自动换行，所以以为texlive也支持行内公式自动换行，但是目前看来好像不太行，我关注一下后续的更新。

我一直无法打开Markdown，在网上搜索了很多教程，修改域名之类的方法也不行。很抱歉。
![image](https://github.com/CTeX-org/forum/assets/168255188/22202637-d37c-499f-8d94-33f11171f9b1)

**Comment by caofract** [comment]
```tex
{
\documentclass[aspectratio=169,notheorems,12pt]{ctexbeamer}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usetheme{Madrid}
\usepackage{amsthm}
\usepackage{amsmath}
\begin{document}
数学数学数学数学数学数学数学数学$a=b=c=a=b=c=a=b=c= \allowbreak a=b=c=a=b=c=$.
\end{document}
}
```

**Comment by caofract** [comment]
@muzimuzhi 好的，谢谢。因为我之前用的cetx2.9，在beamer文档下对中文+行内公式的编译结果支持自动换行，所以以为texlive也支持行内公式自动换行，但是目前看来好像不太行，我关注一下后续的更新。

**Comment by muzimuzhi** [comment]
额，是想让你编辑 https://github.com/CTeX-org/forum/issues/320#issue-2287893684 ，而不是重发一遍。
![image](https://github.com/CTeX-org/forum/assets/6376638/5956f6a5-1e40-41f2-9848-8f59d0460dd4)

> 因为我之前用的cetx2.9，在beamer文档下对中文+行内公式的编译结果支持自动换行

不了解 CCT，等了解的人来回答。
