### ISSUE TITLE
Ctex如何设置页边距，另外，类似论文中的项目资助的脚注 如何实现？

### ISSUE THREAD

**Issue by fuysgit** [CTeX-org/forum#324]
请教下高手，如何在ctex下实现A4纸的设置，以及页边距的设置？     在latex中，用geometry包就行，但geometry包在ctex中无法使用。

![3](https://github.com/CTeX-org/ctex-kit/assets/93901766/ae8d2bba-5cd3-42e3-83a9-d676e7172b13)

另外，我想请教下，Ctex如何实现上图中框出的，作者信息及论文项目信息的展示功能？

**Comment by fuysgit** [comment]
额，分栏搞定了，我命令输错了。

**Comment by Liam0205** [comment]
都是基础问题。建议先去完整地看一遍入门材料。

----

`geometry` 宏包无法使用。该命题为假。

```
\documentclass[a4paper]{ctexart}
\usepackage{geometry}
\geometry{margin = 1in}
\usepackage{blindtext}
\begin{document}
\blindtext
\end{document}
```

![image](https://github.com/CTeX-org/ctex-kit/assets/3348485/f4961a81-9dbb-471a-8c1f-0f2e9d3b2ee4)

----

有个东西叫做“脚注”。用 `\footnote` 命令来实现。

**Comment by fuysgit** [comment]
> 都是基础问题。建议先去完整地看一遍入门材料。
> 
> `geometry` 宏包无法使用。该命题为假。
> 
> ```
> \documentclass[a4paper]{ctexart}
> \usepackage{geometry}
> \geometry{margin = 1in}
> \usepackage{blindtext}
> \begin{document}
> \blindtext
> \end{document}
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/3348485/344913406-f4961a81-9dbb-471a-8c1f-0f2e9d3b2ee4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDUzMTgsIm5iZiI6MTcxOTkwNTAxOCwicGF0aCI6Ii8zMzQ4NDg1LzM0NDkxMzQwNi1mNDk2MWE4MS05ZGJiLTQ3MWEtOGMxZi0wZjJlOWQzYjJlZTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDJUMDcyMzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTBmZmM4MzIyYjYyYjdjYWMwMGI1YTRkYzMwZWQ1NjQxNmFhNWYxMjI4ZjZhYmZkNzJjMDA4NDg2OTdmZTA4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r7F4X_vyFhOVlx6RcxinIzaF21P-BBslLYPTp5e7J6s)
> 
> 有个东西叫做“脚注”。用 `\footnote` 命令来实现。

谢谢，我研究下脚注， 那个页边距我搞定过了， 输错了一个字母。

**Comment by zepinglee** [comment]
建议按照官方的模板填写。不推荐新人去实现模板的格式。

**Comment by fuysgit** [comment]
> 建议按照官方的模板填写。不推荐新人去实现模板的格式。

不是额，是我自己要弄个模板翻译个文章。
