### ISSUE TITLE
Ubuntu 18.04 更换清华源无法安装 texstudio

### ISSUE THREAD

**Issue by OsbertWang** [CTeX-org/forum#33]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x] Linux

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

我在使用 ubuntu 18.04 时，更换了清华源，即将 `/etc/apt/sources.list` 替换为 [清华镜像网站](https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/) 提供的内容。
然后执行 `sudo apt install texstudio` 系统提示 Unable to locate package texstudio.
这是因为清华源没有包含它吗？

**Comment by stone-zeng** [comment]
清华源是有的：<https://mirrors.tuna.tsinghua.edu.cn/ubuntu/pool/universe/t/texstudio/>

是不是没跑 `sudo apt-get update`？

**Comment by OsbertWang** [comment]
看来是，我把这个忘掉了
