### ISSUE TITLE
是否有办法临时避免tblr环境内note命令导致的标点重叠问题

### ISSUE THREAD

**Issue by Mikachu2333** [CTeX-org/forum#330]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 操作系统

任意系统均可复现 Windows10 22h2

### TeX 发行版

texlive 2024

### 描述问题

如题，在使用tblr表（long）时，如果在单元格的cell的右括号之前使用了一个表注，此时将出现脚注的角标与右括号重叠的问题，是否有办法临时避免？

我给tblr提的issue见此
https://github.com/lvjr/tabularray/issues/511

没有找到与之相关的描述或解决方案

![1](https://private-user-images.githubusercontent.com/63829496/360289364-3520ba3e-7bb5-454f-b680-d9c1a60c6fdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMTExNDksIm5iZiI6MTcyNDMxMDg0OSwicGF0aCI6Ii82MzgyOTQ5Ni8zNjAyODkzNjQtMzUyMGJhM2UtN2JiNS00NTRmLWI2ODAtZDljMWE2MGM2ZmRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA3MTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjN2QzZDFkYzA0ZDdhYzc1MzI1ZDVlODNhZGZlMzNkZmY0ZmM2ZGMyMjg1NzM5NGU4NWQwMmRjYmMxYWE0YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Duf4N7B5vd9rmPe9wgddH-0p9UWc_tQyvlYZGhPRqjs)

### 最小工作示例（MWE）

```latex
% !TeX encoding = UTF-8
\documentclass[UTF8]{ctexrep}
\usepackage{tabularray}

\begin{document}

\begin{tblr}[
		long,
		note{1} = {脚注测试。Footnote test.},
	]{
		cells = {c,m},
		hlines,
		vlines,
	}
	Chinese-English & （测试Test\TblrNote{1}) \\
	English-Chinese & (Test测试\TblrNote{1}） \\
	Chinese         & （测试\TblrNote{1}）    \\
	English         & (Test\TblrNote{1})

\end{tblr}

\end{document}
```

用 XeLaTeX 编译后，日志文件输出：

[output.log](https://github.com/user-attachments/files/16706809/output.log)

### 链接

- TeX.SX:
- GitHub: https://github.com/lvjr/tabularray/issues/511

**Comment by muzimuzhi** [comment]
见 https://github.com/lvjr/tabularray/issues/511#issuecomment-2305132321
