### ISSUE TITLE
请问有没有可能单独设置中文和英文之间的间距，但是保留中文和中文之间的间距

### ISSUE THREAD

**Issue by asmwarrior** [CTeX-org/forum#332]
### 检查清单

- [X] 我已在 issues 中进行搜索（包括已关闭的问题）

### 操作系统

Windows 10

### TeX 发行版

TexLive 2022

### 描述问题

我只想调整中文和英文字符之间的那个空格，比如去掉这个空格，或者让中文和英文之间的间距变小点。
但是中文和中文之间的间距不调整，请问这个怎么办？

### 最小工作示例（MWE）

\documentclass[UTF8]{ctexart}
\begin{document}
{
中文English。
English中文。
}
\end{document}

**Comment by muzimuzhi** [comment]
调整中文和西文之间的间距
  - 用 xelatex 编译 `ctexart` 时可以看 `xeCJK` 包提供的选项 `CJKecglue` 和 `xCJKecglue`
  - 用 lualatex 编译时，`luatexja` 包似乎也有功能类似的选项 `xkanjiskip`（我不熟）
  - 用其他方式编译时（见 `texdoc ctex`, sec. 4.1 编译方式），可以在对应的支持宏包文档里尝试找设置项。

你提供的示例，大括号不配对，也没有展示「中文和中文之间的间距」。

**Comment by asmwarrior** [comment]
Oh, 多谢，之前笔误了，我修订了。
下面的代码效果不错，在xelatex下结果如后面的图片。


~~~
\documentclass[UTF8]{ctexart}
\begin{document}
{
中文English。
English中文。

% 有办法使 xCJKecglue 随着字体而变化吗？ · Issue #31 · CTeX-org/forum — https://github.com/CTeX-org/forum/issues/31
\xeCJKsetup{ xCJKecglue = {\hskip 0.05em plus 0.05em minus 0.05em\relax} }

中文English。
English中文。
}
\end{document}
~~~

![image](https://github.com/user-attachments/assets/d41d0b0c-13bd-42f3-8133-2d7c666ecddc)

我参考的是这个帖子：

[有办法使 xCJKecglue 随着字体而变化吗？ · Issue #31 · CTeX-org/forum](https://github.com/CTeX-org/forum/issues/31)
