### ISSUE TITLE
xetex 中 fandol 字体 script 的问题

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/forum#34]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 7/8/10
  - [x] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

用 xetex 编译如下代码：

```latex
\documentclass{article}
\usepackage{xeCJK}
\begin{document}
你好
\end{document}
```

会得到警告信息

```latex
Package fontspec Warning: Font "FandolSong-Regular" does not contain requested
(fontspec)                Script "CJK".
```

检查后发现问题来自于 xetex 本身：

```latex
\font\1="[FandolSong-Regular.otf]/OT" at 10pt
% \font\1="[XITS-Regular.otf]/OT" at 10pt
\showthe\XeTeXOTcountscripts\1
\bye
```

得到的结果是 0，显然是不应该的。其他字体：中易宋体=1，思源=7，苹方=6。不知道这是字体的问题，还是 xetex 引擎的问题？@clerkma

## 链接

- TeX.SX:
- GitHub:

**Comment by RuixiZhang42** [comment]
字体的锅，用 `opentype-info.tex` 通过 plain XeTeX 跑出来的 PDF 长这样：
> ![fandolsong](https://user-images.githubusercontent.com/39968857/58291203-8ca39380-7d8a-11e9-84f9-845196a340ec.png)

话说这个短小精悍的文档真的好好玩（通过 `kpsewhich opentype-info.tex` 即可获取）……

**Comment by clerkma** [comment]
主要是没有GSUB表造成了警告。GPOS表是有的，当时还做了一些自己想玩的东西。
GSUB表，如果针对于的是汉字的排版，其实作用不是特别大，很多字体也就带了vert。
其实加一个带script/language而没有lookup的表估计都能让这个表的警告没了。
不过，这意义没那么大。我当时没加GSUB表的原因就在于我似乎没啥需要写在GSUB里面的。

GSUB/GPOS表其实不是必须要存在的表。
只有一些所谓复杂语言（abugida/abjad）才需要写满才能让shaper正常显示。

**Comment by muzimuzhi** [comment]
ctex 宏集定义的 `ctex-fontset-macnew.def` 中 ，用到的 `Songti SC` 系列和 `STFangsong`，也满足条件
 - 在 `fontspec` 中使用时，会得到警告信息 `does not contain requested Script "CJK"`
 - `\showthe\XeTeXOTcountscripts\1` 输出 0

**Comment by stone-zeng** [comment]
> 主要是没有GSUB表造成了警告。GPOS表是有的，当时还做了一些自己想玩的东西。
> GSUB表，如果针对于的是汉字的排版，其实作用不是特别大，很多字体也就带了vert。

为什么检查 language/script 只看 `GSUB` 而不看 `GPOS` 呢？

**Comment by clerkma** [comment]
因为很多语言的渲染，都是按照OTF的处理规则：先处理glyph替换，后处理glyph位置。
所以肯定是先选择检查GSUB啊。

**Comment by 1900011604** [comment]
Linux 也会这样，但 Windows 不会，是不是可以把 Linux 和 Mac 上面默认的粗体中文改成跟 Windows 一样（黑体）？

**Comment by sikouhjw** [comment]
> Linux 也会这样，但 Windows 不会，是不是可以把 Linux 和 Mac 上面默认的粗体中文改成跟 Windows 一样（黑体）？
> 
> Linux + TeX Live 2020

Linux 和 Mac 默认有中易黑体？

**Comment by 1900011604** [comment]
> > Linux 也会这样，但 Windows 不会，是不是可以把 Linux 和 Mac 上面默认的粗体中文改成跟 Windows 一样（黑体）？
> > Linux + TeX Live 2020
> 
> Linux 和 Mac 默认有中易黑体？

那怎么改呢？改哪个文件？Linux和Windows上面编译出来粗体的中文是不一样的，Linux是粗体的serif宋体，Windows是sans-serif的黑体

**Comment by Liam0205** [comment]
@1900011604 我能给你说的就是不要纠结。

Windows 上的粗体是黑体，是因为 Windows 默认的宋体（中易宋体）没有提供 bold 字重，所以只好用黑体来代替。

Linux 上的宋体有，于是就是真正的粗宋体。

真的那么纠结，就自己选好一套宋楷仿黑，然后自己写一个 ``fontset`` 文件，到哪个系统都用这个文件就好了。

**Comment by sikouhjw** [comment]
> 
> 
> > > Linux 也会这样，但 Windows 不会，是不是可以把 Linux 和 Mac 上面默认的粗体中文改成跟 Windows 一样（黑体）？
> > > Linux + TeX Live 2020
> > 
> > 
> > Linux 和 Mac 默认有中易黑体？
> 
> 那怎么改呢？改哪个文件？Linux和Windows上面编译出来粗体的中文是不一样的，Linux是粗体的serif宋体，Windows是sans-serif的黑体

`texdoc ctex` 第 4 节 编译方式、编码与中文字库，先读完再来讨论吧，Win 下也是可以使用 Fandol 的，都一样

**Comment by 1900011604** [comment]
谢谢！`\documentclass{}`加入`[fontset=windows]`即可。

**Comment by micfan** [comment]
看了几位的讨论, 我在 ArchLinux 下没有装 Windows 字体, 
查了下支持下列字体集:
```
ctex-fontset-adobe.def,
ctex-fontset-fandol.def,
ctex-fontset-founder.def,
ctex-fontset-mac.def,
ctex-fontset-macnew.def,
ctex-fontset-macold.def,
ctex-fontset-ubuntu.def,
ctex-fontset-windows.def,
```

写成 `\documentclass[fontset=founder]{ctexart}` 真不报这个 warning 了!

**Comment by Freed-Wu** [comment]
> 看了几位的讨论, 我在 ArchLinux 下没有装 Windows 字体, 查了下支持下列字体集:
> 
> ```
> ctex-fontset-adobe.def,
> ctex-fontset-fandol.def,
> ctex-fontset-founder.def,
> ctex-fontset-mac.def,
> ctex-fontset-macnew.def,
> ctex-fontset-macold.def,
> ctex-fontset-ubuntu.def,
> ctex-fontset-windows.def,
> ```
> 
> 写成 `\documentclass[fontset=founder]{ctexart}` 真不报这个 warning 了!

我改完后还是报错。。。

```
/usr/share/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-founder.def||  (Package fontspec)  FoZShuSong-Z01" does not contain requested Script "CJK".
```

**Comment by stone-zeng** [comment]
> > 写成 `\documentclass[fontset=founder]{ctexart}` 真不报这个 warning 了!
> 
> 我改完后还是报错。。。
> 
> ```
> /usr/share/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-founder.def||  (Package fontspec)  FoZShuSong-Z01" does not contain requested Script "CJK".
> ```

说明不是只有 fandol 有这个问题，方正的字体也会有（这里是书宋）。所以建议你忽略掉，反正不会有任何事实上的影响。

**Comment by islent** [comment]
奇了怪了，2021年11月底写的tex还能正常编译，之后没改动，顶多vscode latex workshop升过版本，今天重新编译就报了这个错

**Comment by zepinglee** [comment]
> 奇了怪了，2021年11月底写的tex还能正常编译，之后没改动，顶多vscode latex workshop升过版本，今天重新编译就报了这个错

这只是警告，不是报错。

**Comment by Firestar-Reimu** [comment]
所以我觉得应该直接放弃内置的Fandol字体，直接换成内置Adobe字体/Noto字体，要知道Fandol字体还有一个最大的问题是**字库欠缺**，比如没有“浛”字（室友的名字里面有，每次他写实验报告都要手动改PDF）

在作者的博客上也能一窥究竟：

https://stone-zeng.github.io/2019-07-06-use-opentype-fonts-ii/#ctex-%E5%AE%8F%E9%9B%86%E6%8F%90%E9%AB%98%E7%AF%87

**Comment by sikouhjw** [comment]
> 所以我觉得应该直接放弃内置的Fandol字体，直接换成内置Adobe字体/Noto字体，要知道Fandol字体还有一个最大的问题是**字库欠缺**，比如没有“浛”字（室友的名字里面有，每次他写实验报告都要手动改PDF）

你能给一个 Linux 下好的解决方案吗？什么操作系统内置“Adobe字体/Noto字体”？

> 在作者的博客上也能一窥究竟：
> 
> https://stone-zeng.github.io/2019-07-06-use-opentype-fonts-ii/#ctex-%E5%AE%8F%E9%9B%86%E6%8F%90%E9%AB%98%E7%AF%87

fandol 的作者不是 stone-zeng

**Comment by syvshc** [comment]
> 所以我觉得应该直接放弃内置的Fandol字体，直接换成内置Adobe字体/Noto字体，要知道Fandol字体还有一个最大的问题是**字库欠缺**，比如没有“浛”字（室友的名字里面有，每次他写实验报告都要手动改PDF）
> 
> 在作者的博客上也能一窥究竟：
> 
> https://stone-zeng.github.io/2019-07-06-use-opentype-fonts-ii/#ctex-%E5%AE%8F%E9%9B%86%E6%8F%90%E9%AB%98%E7%AF%87

嗯……如果是 Ubuntu 系统的话, 直接 `[fontset=ubuntu]` 就可以使用 Noto 字体, 如果是 windows, 默认也不会用到 fandol, 如果用到了 fandol, 那说明你应该更新一下宏包 https://github.com/CTeX-org/ctex-kit/issues/569

**Comment by Firestar-Reimu** [comment]
我说的是CTeX现在内置的是Fandol（也就是没有设定fontset的默认值），因为凑齐了宋、黑、仿、楷

作者是CTeX的作者（之一），不是Fandol的作者

我现在是思源黑体+中易宋体+楷体+仿宋（因为我有一个windows），你可以把中易宋体换成思源宋体

**Comment by syvshc** [comment]
> 我说的是CTeX现在内置的是Fandol（也就是没有设定fontset的默认值），因为凑齐了宋、黑、仿、楷

没有设置 fontset 的默认值可以看 [ctex 的文档](http://mirrors.ctan.org/language/chinese/ctex/ctex.pdf) 

![image](https://user-images.githubusercontent.com/38098591/150283473-4b47cbea-0ccb-4341-9ece-095a31a14116.png)

只有识别不出系统的时候才会使用 fandol

**Comment by syvshc** [comment]
> 原来是2021年（而不是更早）的issue啊

嗯, 这是 texlive2021 更新后 windows 上二进制文件的一个 bug

**Comment by sikouhjw** [comment]
> 我说的是CTeX现在内置的是Fandol（也就是没有设定fontset的默认值），因为凑齐了宋、黑、仿、楷

1. “内置的是Fandol”和“没有设定fontset的默认值”有什么关系？
2. 你觉得 fandol 不好，你可以去传字体到 ctan，你得看人家接不接收

> 原来是2021年（而不是更早）的issue啊，那确实应该更新一下，毕竟texlive是年羹尧

你如果想解决问题，你得说你室友的操作系统是什么、发行版是什么，如果是没有阅读手册带来的问题，何必怪在 fandol 上面呢

**Comment by Firestar-Reimu** [comment]
```
\documentclass[a4paper,fontset=none]{ctexart}
\setCJKmainfont{SimSun}[BoldFont=Noto Sans CJK SC Medium]
```

那我用的是manjaro（包括之前@micfan 用的是archlinux），确实会默认用fandol

我室友用的是windows而且texlive绝对不会新于2021年，他那个主要是因为要用学校代代相传的垃圾模板，我直接给他重新配了一个fontset（见上）就解决了

**Comment by syvshc** [comment]
> 我室友用的是windows而且texlive绝对不会新于2021年，他那个主要是因为要用学校代代相传的垃圾模板，我直接给他重新配了一个fontset（见上）就解决了

那需要提供一下具体的发行版信息和模板信息了, 不适合在此处讨论了……可以开一个新的 issue.

**Comment by Firestar-Reimu** [comment]
> “内置的是Fandol”和“没有设定fontset的默认值”有什么关系？

没有设定fontset的默认值，电脑不是已知的系统，没有装过fandol字体，它能给我显示出来字说明什么，说明内置了个fandol字体啊

> 你觉得 fandol 不好，你可以去传字体到 ctan，你得看人家接不接收

这个可以有！

我刚刚查了一下，fontset=adobe调用的应该不是source han字体而是Adobe Song Std等字体，这些字体可能是商用的

**Comment by syvshc** [comment]
> 这些字体可能是商用

我印象中这些字体随 Adobe Acrobat (Pro) 分发

**Comment by Firestar-Reimu** [comment]
是的，是adobe软件自带的字体，例如Adobe Reader和Adobe Acrobat

**Comment by syvshc** [comment]
> 而且足够完整美观

并且开源使用合法 并且 CTAN 有接受并且包含在 texlive 中

**Comment by Liam0205** [comment]
考虑到 issue 最初的问题已近得到解决，并且近期讨论已经偏离 issue 原题，此 issue 将被 lock。

相关讨论可以另起一个新的 thread。
