### ISSUE TITLE
参数中用换行符进行换行

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/forum#35]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 描述问题

```latex
\begingroup
  \catcode`\^^M=13% 
  \def^^M{\par\leavevmode}%
  A
  B
  C
\endgroup
```

可以打印出

```
A
B
C
```

那么，可否定义一个命令 `\test`，使得

```tex
\test{%
  A
  B
  C
}
```

也实现这一效果？

**Comment by stone-zeng** [comment]
貌似参数吃进去之前，`^^M` 就会转换成空格，所以不知道怎么做了。

**Comment by qinglee** [comment]
这种一般是分两步，第一步开一个分组，改变 `\catcode`，第二步再把参数读进来，结束分组。

```TeX
\outer\def\test{\begingroup\obeylines\testaux}
\def\testaux#1{\endgroup#1}

\test{%
A
B
C
}

\bye
```

当然 `\test` 不能出现在参数中，所以用 `\outer`。

**Comment by stone-zeng** [comment]
还有一处不明白，这边 `\endgroup` 和 `#1` 的顺序是不是可以互换的？

**Comment by qinglee** [comment]
可以，`#1` 读进来以后，他们的 `\catcode` 就被固定了，我那么写只是是为了避免把 `#1` 放在分组里。

**Comment by stone-zeng** [comment]
如果要允许 `\test` 在参数中使用，有没有什么办法呢？

**Comment by qinglee** [comment]
比较麻烦，得具体看你的使用场景，或许 `cprotect` 包会有帮助。

**Comment by rch2008** [comment]
\documentclass{article}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{amsmath}
\usepackage{ifthen}
\newif\ifteacher    
\usepackage{ctex}
\usepackage{color}
\usepackage{cprotect}

\def\test{\begingroup\obeylines\testaux}
\def\testaux#1{#1\endgroup}%

\def\testF#1#2#3{\item[5.]%
	\ifteacher{#1\\#2\\\begingroup\obeylines\testaux{\color{red}#3}}%
	\else{#1\\#2\\}\fi}
\def\testA#1{#1}
\begin{document}
\teachertrue
%这个\test放到参数中就不起作用了
\testA{\test{
		A
		B
		C
}}
%这个保护一下，\test就起作用了
\cprotect\testA{\test{
A
B
C
}}
%这个是我实际使用的一个实例，略作了简化\cprotect[mmm]的可选参数必须带着才起作用
%尝试%\def\testB{\cprotect[mmm]\testF}%未成功
\begin{itemize}
	 \cprotect[mmm]\testF{ID}{已知$a>0$，$b>0$，$c>0$，若点$P(a$，$b)$在直线$x+y+c=2$上，则$\dfrac{4}{a+b}+\dfrac{a+b}{c}$的最小值是\mbox{\underline{~~~~~~~~}}.}{解：点$P(a$，$b)$在直线$x+y+c=2$上，
			${\therefore}a+b+c=2$，
			${\therefore}2a+2b+2c=4$，
			${\because}a>0$，$b>0$，$c>0$，
			${\therefore}\dfrac{4}{a+b}+\dfrac{a+b}{c}=\dfrac{2a+2b+2c}{a+b}+\dfrac{a+b}{c}=2+\dfrac{2c}{a+b}+\dfrac{a+b}{c}\geqslant 2+2\sqrt{\dfrac{2c}{a+b}\cdot \dfrac{a+b}{c}}=2+2\sqrt{2}$，
			当且仅当$\dfrac{2c}{a+b}=\dfrac{a+b}{c}$时，即$a+b=\sqrt{2}c$时取等号，
			故$\dfrac{4}{a+b}+\dfrac{a+b}{c}$的最小值是$2+2\sqrt{2}$，
			\color{blue}故答案为：$2+2\sqrt{2}$
	}
\end{itemize}
\end{document}

**Comment by qinglee** [comment]
@rch2008 按你的实例，没必要这么复杂，请理解代码的意思后再使用。你的实例可以简化为：

```TeX
\newif\ifteacher

\makeatletter
\newcommand\testF[2]{\item[5.]#1\par#2\par
  \ifteacher\begingroup\obeylines\expandafter\testFaux
  \else\expandafter\@gobble\fi}
\newcommand\testFaux[1]{\indent\color{red}#1\par\endgroup}
\makeatother
```

**Comment by rch2008** [comment]
\expandafter能够理解，@gobble不大明白什么意思，之前没见过，也不知道去哪里能查到像这种带@命令的含义，希望李老师指点一下，。得到李老师亲手帮助，有点激动，谢谢李老师的耐心解答。

**Comment by rch2008** [comment]
感谢李老师的帮助，我已经知道@gobble的作用了，万分感谢 @qinglee
