### ISSUE TITLE
obeylines实现在参数中换行导致cases，aligned等环境出错

### ISSUE THREAD

**Issue by rch2008** [CTeX-org/forum#37]
```latex
\documentclass{article}
\usepackage{amsfonts}
\usepackage{amssymb}
\usepackage{amsmath}
\usepackage{ifthen}
\newif\ifteacher    
\usepackage{ctex}
\usepackage{color}

\makeatletter
\newcommand\testE[2]{\item[5.]#1\par#2\par
	\ifteacher\begingroup\obeylines\expandafter\testEaux
	\else\expandafter\@gobble\fi}
\newcommand\testEaux[1]{\indent\color{red}#1\par\endgroup}
\makeatother
%这里进行了全局修改，修补了cases环境的断行问题，
%修改"的类别码存在隐患，
%有没有别的方法解决这个问题，
%能定义一个宏代替实现换行也行，
%最好是能够通过重定义cases环境实现
\catcode`\"=5
\begin{document}
	\teachertrue

	\begin{itemize}%\cprotect[mmm]
		\testE{ID}{题干.}{解：由于更改了行结束符号的catcode，导致数学环境出错
			$\begin{cases}"
			\log _{a}4<3\\"
			\log _{a}8>3"
			\end{cases}$
		}
	\end{itemize}
\end{document}
```

**Comment by qinglee** [comment]
问题出在 `\par` 用在数学环境中会出错，需要对 `\obeylines`  的定义稍加调整。

```TeX
\makeatletter
\begingroup
\catcode\active\active
\protected\gdef\mathobeylines{%
  \catcode\active\active \let^^M\math@obeylines}
\endgroup
\protected\def\math@obeylines{%
  \unless\ifmmode\expandafter\par\fi}

\newcommand\testE[2]{\item[5.]#1\par#2\par
	\ifteacher\begingroup\mathobeylines\expandafter\testEaux
	\else\expandafter\@gobble\fi}
\newcommand\testEaux[1]{\indent\color{red}#1\par\endgroup}
\makeatother
```

**Comment by rch2008** [comment]
十分感谢李老师的再次耐心解答，真心感谢！

**Comment by rch2008** [comment]
李老师，您好，最近用您写的代码有发现了一个新问题，之前我没有考虑到tabular环境，现在如果答案中包含tabular环境且用了\hline就会报错，不知道该怎么解决，尝试了一下用\@currenvir去做判定，但是我没有做成功，不知道李老师有没有好办法能解决，麻烦您了。
\begin{itemize}
	 \testE{15}{设实数$x$，$y$满足约束条件$\begin{cases}%
	 	x\geqslant 0\\
	 	x\leqslant y\\
	 	x+y\geqslant 2
	 	\end{cases}%
	 	$，则$z=2x+y$的取值范围为 ．
	 }%
	 {解：由约束条件$\begin{cases}%
	 	x\geqslant 0\\
	 	x\leqslant y\\
	 	x+y\geqslant 2
	 	\end{cases}%
	 	$作出可行域如图，
	 	化$z=2x+y$为$y=-2x+z$，由图可知，当直线$y=-2x+z$过$A$时，直线在$y$轴上的截距最小，$z$有最小值为$2$．
	 	${\therefore}z=2x+y$的取值范围为$[2$，$+\infty)$．
	 	\hh\color{blue}故答案为：$[2$，$+\infty)$．
	 	\begin{tabular}{|c|c|c|c|}%\hline
	 		$x$ & $(0$，$\ln (2k))$ & $\ln (2k)$ & $(\ln (2k)$，$k) $\\
	 		%\hline
	 		$f'(x)$ & $-$ & $0$ & $+ $\\
	 		%\hline
	 		$f(x)$ & ${\searrow}$ & 极小值 & ${\nearrow} $\\
	 		%\hline
	 	\end{tabular}
}

**Comment by rch2008** [comment]
李老师，您好，最近用您写的代码有发现了一个新问题，之前我没有考虑到tabular环境，现在如果答案中包含tabular环境且用了\hline就会报错，不知道该怎么解决，尝试了一下用@currenvir去做判定，但是我没有做成功，不知道李老师有没有好办法能解决，麻烦您了。
\begin{itemize}
\testE{15}{设实数$x$，$y$满足约束条件$\begin{cases}%
x\geqslant 0\
x\leqslant y\
x+y\geqslant 2
\end{cases}%
$，则$z=2x+y$的取值范围为 ．
}%
{解：由约束条件$\begin{cases}%
x\geqslant 0\
x\leqslant y\
x+y\geqslant 2
\end{cases}%
$作出可行域如图，
化$z=2x+y$为$y=-2x+z$，由图可知，当直线$y=-2x+z$过$A$时，直线在$y$轴上的截距最小，$z$有最小值为$2$．
${\therefore}z=2x+y$的取值范围为$[2$，$+\infty)$．
\hh\color{blue}故答案为：$[2$，$+\infty)$．
\begin{tabular}{|c|c|c|c|}%\hline
$x$ & $(0$，$\ln (2k))$ & $\ln (2k)$ & $(\ln (2k)$，$k) $\
%\hline
$f'(x)$ & $-$ & $0$ & $+ $\
%\hline
$f(x)$ & ${\searrow}$ & 极小值 & ${\nearrow} $\
%\hline
\end{tabular}
} @qinglee

**Comment by muzimuzhi** [comment]
既然是新问题，建议使用新标题、开一个新 issue。

这样，既能方便用户「读标题以了解 issue 大意」，也可能提高搜索准确率。如果需要在新 issue 中引用当前 issue（#37），GitHub 也提供了多种[便利方式](https://help.github.com/en/articles/autolinked-references-and-urls)。
