### ISSUE TITLE
请问刘海洋老师书的配套代码有吗？

### ISSUE THREAD

**Issue by JJMLeo** [CTeX-org/forum#38]
2491625092@qq.com多谢

**Comment by stone-zeng** [comment]
不要做伸手党，网上资源多得很：

![image](https://user-images.githubusercontent.com/18233088/58691726-5b951580-83bf-11e9-9996-e13594ffd4b9.png)

**Comment by muzimuzhi** [comment]
水木清华[这个帖子](https://www.newsmth.net/nForum/#!article/TeX/318108)的附件部分，有全书例题的源码。

**Comment by CyrusYip** [comment]
这个github仓库有 [ljvblfz/LaTeXinPractice](https://github.com/ljvblfz/LaTeXinPractice)，直接git clone或者下载下来就可以了。
