### ISSUE TITLE
如何在word插入latex编写的伪代码算法 

### ISSUE THREAD

**Issue by gaocaiLi** [CTeX-org/forum#39]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 
  - [ ] CTeX
  - [ ] MiKTeX 

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\begin{document}
Hello, \LaTex!
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
! Undefined control sequence.
l.3 Hello, \LaTex
                 !
?
```

## 链接

- TeX.SX:
- GitHub:

**Comment by muzimuzhi** [comment]
1. 关于你的 MWE，注意大小写，使用 `\LeTeX`
1. 关于你的 issue 标题，
  1. 你是已经在 LaTeX 里排好了伪代码吗，然后想保留格式地插入 Word？
  1. 如果只是想插入代码（而非伪代码），可以试试这里提到的办法 https://stackoverflow.com/q/387453/8590320

**Comment by stone-zeng** [comment]
现在最新版 Word（我记得是 2016 之后）可以 [插入 SVG](https://support.office.com/zh-cn/article/%E5%9C%A8-microsoft-office-%E4%B8%AD%E6%8F%92%E5%85%A5%E5%9B%BE%E6%A0%87-e2459f17-3996-4795-996e-b9a13486fa79)，而 LaTeX 生成的 PDF 也可以通过 `dvisvgm` 转换到 SVG，因此事实上就扫清障碍了：

1. 写好代码（用 `standalone` 可以只留下算法部分）：

    ```latex
    \documentclass{standalone}
    \usepackage{algorithm2e}

    \begin{document}
    \begin{algorithm}[H]
      \SetAlgoLined
      \KwData{this text}
      \KwResult{how to write algorithm with \LaTeXe}
      initialization\;
      \While{not at end of this document}{
        read current\;
        \eIf{understand}{
          go to next section\;
          current section becomes this one\;
          }{
          go back to the beginning of current section\;
          }
      }
      \caption{How to write algorithms}
    \end{algorithm}
    \end{document}
    ```

2. 执行 `pdflatex 1.tex && dvisvgm -P 1.pdf` （假设文件名是 `1.tex`）以生成 SVG（如果从 DVI 出发好像不会嵌入字体）。

3. 把生成的 SVG 拖到 Word 里面。

![image](https://user-images.githubusercontent.com/18233088/58772556-31746b00-85ec-11e9-948f-41885fd5144c.png)

试验了一下，数学公式、中文支持（用 XeLaTeX 编译）基本上都没有问题。

PS：@muzimuzhi 那个 MWE 只是提问时候的模版，他偷懒没有改掉罢了……

**Comment by muzimuzhi** [comment]
> 那个 MWE 只是提问时候的模版，他偷懒没有改掉罢了……
原来是这样

不能直接向 Word 插 PDF 吗？指，转换到 SVG 是否是必须的？

**Comment by stone-zeng** [comment]
似乎是不能的，只能作为对象插入，或者直接打开。参考 [Add a PDF to your Office file](https://support.office.com/en-us/article/add-a-pdf-to-your-office-file-74819342-8f00-4ab4-bcbe-0f3df15ab0dc)。

**Comment by zituitui** [comment]
> 

好像少了一个 -o指定输出文件吧 
这样弄完可能没有svg file
执行完加一句
dvisvgm --pdf 1.pdf -o 1.svg
就行

**Comment by note286** [comment]
@zituitui 实测Windows 10，TeX Live 2022，是没有问题的，可以直接输出`1.svg`。
```shell
>dvisvgm -P 1.pdf
processing PDF file
  graphic size: 344.999916pt x 160.433377pt (121.253603mm x 56.385883mm)
  output written to 1.svg
1 of 1 page converted in 1.5 seconds
```

在文档`dvisvgm.man1.pdf`中可以看到有如下表述：

![image](https://user-images.githubusercontent.com/16207292/212209352-6cd210f1-9544-48ae-86a2-eff857cd2c59.png)
