### ISSUE TITLE
为什么\cleardoublepage之后\hypersetup失效

### ISSUE THREAD

**Issue by DangeRS2** [CTeX-org/forum#42]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2017
  - [ ] MiKTeX 
  - [ ] CTeX

## 最小工作示例（MWE）

文档结构比较特殊，需要在\cleardoublepage之后调用\hypersetup，但是为什么\cleardoublepage之后\hypersetup失效？

```latex
\documentclass[UTF8]{ctexbook}

\usepackage{hyperref}
\usepackage{blindtext}

\begin{document}
	
\blindtext

\cleardoublepage

\blindtext

\hypersetup{pdftitle={test}}

\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
编译正常，但是查看PDF Metadata没变化。
```

## 链接

- TeX.SX:
- GitHub:

**Comment by muzimuzhi** [comment]
在使用上，根据 `hyperref` 的源码，PDF Metadata 仅在第一次分页时设置一次。在这之后，选项 `pdftitle` 接受的值将不被实际使用，且「应当触发警告」。宏包文档里没有说明这点，有所不足。

在实现上，受制于 `keyval` 宏包的 `\define@key` 只能局部重定义 key-value，警告没有出现。

一个「恢复警告」的 fix：

```latex
\documentclass{article}
\usepackage{hyperref}
\hypersetup{pdftitle={preamble}}

\makeatletter
\def\Hy@DisableOption#1{%
  \ltx@ifundefined{KV@Hyp@#1@default}{%
    \define@key@g{Hyp}{#1}%
  }{%
    \define@key@g{Hyp}{#1}[]%
  }%
  {\Hy@WarnOptionDisabled{#1}}%
}

%% add global version of \defin@key
\def\define@key@g#1#2{%
  \@ifnextchar[{\KV@def@g{#1}{#2}}{\global\long\@namedef{KV@#1@#2}####1}}

%% add global version of \KV@def
\def\KV@def@g#1#2[#3]{%
  \global\long\@namedef{KV@#1@#2@default\expandafter}\expandafter
  {\csname KV@#1@#2\endcsname{#3}}%
  \global\long\@namedef{KV@#1@#2}##1}
\makeatother

\begin{document}
%% this one succeeds in changing the Title field
\hypersetup{pdftitle={before first newpage}}
a
\newpage

%% this one raises warning
\hypersetup{pdftitle={after first newpage}}
\end{document}
```

------

以上描述，适用于这些选项：
```
pdfauthor
pdftitle
pdfsubject
pdfcreator
addtopdfcreator
pdfcreationdate
pdfmoddate
pdfproducer
pdfkeywords
pdftrapped
pdfinfo
```

**Comment by DangeRS2** [comment]
> 在使用上，根据 `hyperref` 的源码，PDF Metadata 仅在第一次分页时设置一次。在这之后，选项 `pdftitle` 接受的值将不被实际使用，且「应当触发警告」。宏包文档里没有说明这点，有所不足。
> 
> 在实现上，受制于 `keyval` 宏包的 `\define@key` 只能局部重定义 key-value，警告没有出现。
> 
> 一个「恢复警告」的 fix：
> 
> ```
> \documentclass{article}
> \usepackage{hyperref}
> \hypersetup{pdftitle={preamble}}
> 
> \makeatletter
> \def\Hy@DisableOption#1{%
>   \ltx@ifundefined{KV@Hyp@#1@default}{%
>     \define@key@g{Hyp}{#1}%
>   }{%
>     \define@key@g{Hyp}{#1}[]%
>   }%
>   {\Hy@WarnOptionDisabled{#1}}%
> }
> 
> %% add global version of \defin@key
> \def\define@key@g#1#2{%
>   \@ifnextchar[{\KV@def@g{#1}{#2}}{\global\long\@namedef{KV@#1@#2}####1}}
> 
> %% add global version of \KV@def
> \def\KV@def@g#1#2[#3]{%
>   \global\long\@namedef{KV@#1@#2@default\expandafter}\expandafter
>   {\csname KV@#1@#2\endcsname{#3}}%
>   \global\long\@namedef{KV@#1@#2}##1}
> \makeatother
> 
> \begin{document}
> %% this one succeeds in changing the Title field
> \hypersetup{pdftitle={before first newpage}}
> a
> \newpage
> 
> %% this one raises warning
> \hypersetup{pdftitle={after first newpage}}
> \end{document}
> ```
> 
> 以上描述，适用于这些选项：
> 
> ```
> pdfauthor
> pdftitle
> pdfsubject
> pdfcreator
> addtopdfcreator
> pdfcreationdate
> pdfmoddate
> pdfproducer
> pdfkeywords
> pdftrapped
> pdfinfo
> ```

那是不是就意味着我想在分页之后设置PDF Metadata是不可能的了？

**Comment by muzimuzhi** [comment]
> 那是不是就意味着我想在分页之后设置PDF Metadata是不可能的了？

不是。

有多种修改方式。下面的例子，是通过「把 PDF Metadata 的写入延后到文档末尾」来实现的。

```latex
\documentclass{article}
\usepackage{hyperref}
\hypersetup{pdftitle={preamble}}

\makeatletter
\let\PDF@FinishDoc@old\PDF@FinishDoc
\let\PDF@FinishDoc\ltx@empty

%% or, manually execute \PDF@FinishDoc@old in any position, 
%% once and only once
\AtEndDocument{\PDF@FinishDoc@old}
\makeatother

\begin{document}
\hypersetup{pdftitle={before first newpage}}
a
\newpage

%% this one succeeds
\hypersetup{pdftitle={after first newpage}}
\end{document}
```

**Comment by DangeRS2** [comment]
我在[stackexchange的提问](https://tex.stackexchange.com/questions/495171/hypersetup-does-not-work-well-after-cleardoublepage/495174?noredirect=1#comment1250019_495174)，他们说还可以通过aux操作，这个怎么弄...?

**Comment by muzimuzhi** [comment]
从我的角度，当前 issue 的问题已经得到解答，追问也有了补答。
通过 aux 操作，已经和当前 issue 没有之间关联。建议开新的 issue，重新提问。

**Comment by DangeRS2** [comment]
顺便问一句，`aux`的例子会对默认行为之类的东西有影响吗？

**Comment by muzimuzhi** [comment]
> 顺便问一句，`aux`的例子会对默认行为之类的东西有影响吗？

开新 issue

**Comment by u-fischer** [comment]
Delaying with \AtEndDocument can fail in xelatex - in some cases the specials are on an empty page and so not output. Try as an example with the beamer class (or your own example where there is nothing on page 2 and so the title is lost).

**Comment by muzimuzhi** [comment]
@u-fischer 
Yes, I have observed the situation you mentioned when preparing the given "delay with `\AtEndDocument`" example. (And I guess this has something to do with why `hyperref` append `\PDF@FinishDoc` into `\Hy@FirstPageHook`.) Hence the "delay with `\AtEndDocument`" attempt is not a universal one, and whether it fails depends on where it will been used.

Thanks for explicitly pointing out this.
