### ISSUE TITLE
为什么调用openany选项之后还有额外的空白页？

### ISSUE THREAD

**Issue by DangeRS2** [CTeX-org/forum#43]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2017
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

在MWE中，为什么调用openany选项之后还有额外的空白页（PDF第4、6页）？

## 最小工作示例（MWE）

```latex
\documentclass[UTF8, openany]{ctexbook}

\usepackage{blindtext}
\usepackage{fancyhdr}
\fancypagestyle{mystyle}{\fancyhf{}\fancyhead[C]{Test}\fancyfoot[C]{\thepage}}

\makeatletter
\def\test{%
	\blindtext
	\if@openright
		\cleardoublepage
	\else
		\clearpage
	\fi}
\let\test@frontmatter\frontmatter
\def\frontmatter{\pagestyle{mystyle}\test@frontmatter\renewcommand\thepage{\Roman{page}}}
\makeatother

\AtBeginDocument{\pagestyle{empty}}
\ctexset{chapter = {pagestyle = mystyle}}

\begin{document}

\test
\test
\test
% 注释第三个\test不会有多余的PDF第4页

\frontmatter
\blindtext

\mainmatter
\blindtext

\backmatter
\blindtext
	
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
编译正常，注释第三个\test不会有多余的PDF第4页。
```

## 链接

- TeX.SX:
- GitHub:

**Comment by DangeRS2** [comment]
应该是\pagenumbering导致的问题，重定义\frontmatter和\mainmatter解决问题。

```latex
\documentclass[UTF8, openany]{ctexbook}

\usepackage{blindtext}
\usepackage{fancyhdr}
\fancypagestyle{mystyle}{\fancyhf{}\fancyhead[C]{Test}\fancyfoot[C]{\thepage}}

\makeatletter
\def\test{%
	\blindtext
	\if@openright
		\cleardoublepage
	\else
		\clearpage
	\fi}
\def\frontmatter{%
	\if@openright
		\cleardoublepage
	\else
		\clearpage
	\fi
	\@mainmatterfalse
	\setcounter{page}{1}
	\renewcommand\thepage{\Roman{page}}
	\pagestyle{mystyle}}
\def\mainmatter{%
	\if@openright
		\cleardoublepage
	\else
		\clearpage
	\fi
	\@mainmattertrue
	\setcounter{page}{1}
	\renewcommand\thepage{\arabic{page}}
	\pagestyle{mystyle}}
\makeatother

\AtBeginDocument{\pagestyle{empty}}
\ctexset{chapter = {pagestyle = mystyle}}

\begin{document}

\test
\test
\test

\frontmatter
\chapter{test}
\blindtext

\mainmatter
\chapter{test}
\blindtext

\backmatter
\chapter{test}
\blindtext
	
\end{document}
```

**Comment by muzimuzhi** [comment]
> 应该是\pagenumbering导致的问题

并非如此。在标准文档类 `book` 中，
  *  文档类选项 `openright/openany` 只控制 `\part` 和 `\chapter` 是否只从奇数页开始
  * 而命令 `\frontmatter`, `\mainmatter` 内部总是调用 `\cleardoublepage`，不受文档类选项的影响。

```latex
%% 具体见 latexdef 的使用，下同

% $ latexdef -c book -s frontmatter
% book.cls, line 284:
\newcommand\frontmatter{%
    \cleardoublepage
  \@mainmatterfalse
  \pagenumbering{roman}}

% $ latexdef -c book -s mainmatter 
% book.cls, line 288:
\newcommand\mainmatter{%
    \cleardoublepage
  \@mainmattertrue
  \pagenumbering{arabic}}
```

所以，你提问的例子中，额外的空白页是 `\test@frontmatter` 导致的，不是 `\pagenumbering` 带来的。你自答中的例子，是因为重定义后增加了对 `\if@openright` 的判断，所以避免了额外的空白页。

------

PS：
  1. 从实践的角度，在书籍中，一般在 `\begin{document}` 之后就立即使用 `\frontmatter` 命令，中间没有「先输出一些内容」的需求。
  1. 因为 `\pagenumbering` 与空白页无关，建议在重定义时恢复使用 `\pagenumbering`。当然，你现在这么写，也是可以的。

**Comment by DangeRS2** [comment]
因为我发现在我的例子中，只有调用`\frontmatter`和`\mainmatter`时才会引入额外的空白页，而`\backmatter`并不会。所以我去查了标准文档类的实现，发现他们之间的差别，除了`\@mainmatterfalse`之外，就是`\pagenumbering`了，`\if@openright` 的判断是原本就定义的。

<img width="661" alt="屏幕快照 2019-06-10 15 44 05" src="https://user-images.githubusercontent.com/49086184/59226110-e92eed00-8b97-11e9-8c22-bef6d2171d82.png">
<img width="648" alt="屏幕快照 2019-06-10 15 44 14" src="https://user-images.githubusercontent.com/49086184/59226115-eaf8b080-8b97-11e9-84b7-2ee2668082a3.png">

**Comment by muzimuzhi** [comment]
> `\if@openright` 的判断是原本就定义的

注意百分号，`\if@openright` 等行在源码中是被注释的。

**Comment by DangeRS2** [comment]
哈哈，好的，多谢啦，我的意思是我借鉴了一下标准文档类的实现。

```latex
\makeatletter
\def\test{%
	\blindtext
	\if@openright
		\cleardoublepage
	\else
		\clearpage
	\fi}
\def\frontmatter{%
	\if@openright
		\cleardoublepage
	\else
		\clearpage
	\fi
	\@mainmatterfalse
	\pagenumbering{Roman}
	\pagestyle{mystyle}}
\def\mainmatter{%
	\if@openright
		\cleardoublepage
	\else
		\clearpage
	\fi
	\@mainmattertrue
	\pagenumbering{arabic}}
\makeatother
```

**Comment by muzimuzhi** [comment]
你的重定义方法，能满足你的需求。只是，你中间过程的一些判断，有失误的地方。要当心，不是每一次都能歪打正着。

**Comment by DangeRS2** [comment]
哈哈，是的，我完全没注意到那个`%`，所以当时我也很差异。
