### ISSUE TITLE
pgfpages 缩印功能造成超链接失效

### ISSUE THREAD

**Issue by OsbertWang** [CTeX-org/forum#45]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

在使用 pgfpages 包的 \pgfpagesuselayout 功能进行缩印，发现原本在页眉处的超链接失效。页眉用 fancyhdr 设置。

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\usepackage{pgfpages}
\usepackage{fancyhdr}
\usepackage{hyperref}
\usepackage{zhlipsum}
\pagestyle{fancy}
\fancyhf{}
\rhead{--\thepage/\pageref{LastPage}--}
\lhead{\href{github.com}{github}}
\pgfpagesuselayout{2 on 1}  % 注释掉这里，页眉处可显示超链接
\begin{document}
\zhlipsum[-]
\label{LastPage}
\end{document}
```

## 链接

- TeX.SX:
- GitHub:

**Comment by muzimuzhi** [comment]
根据 `texdoc tikz`, sec. 90，缩印会导致超链接的跳转位置不准确。这是 `pgfpages` 和 `hyperref` 的兼容性问题。
![image](https://user-images.githubusercontent.com/6376638/59699834-d3b76400-9224-11e9-9661-43f78796ac1a.png)

**Comment by OsbertWang** [comment]
好的，明白了。

**Comment by muzimuzhi** [comment]
一些后续尝试

### pdf 之前，在 latex 内部
hyperref 生成的超链接区域坐标，在 pdftex（`\pdf(start|end)link`）和 xetex（`\special{pdf:...}`）里都是引擎自动生成的，hyperref 没有指定。pdfcomment 宏包采取的是直接写入坐标的方案，但它没写 `/GoTo` 的功能，要去调整也不容易。

### pdf 之后，修改 pdf 文件
我试了试用 PyPDF2 修改生成的 PDF 文件，
 - 对 link to url，修正超链接区域坐标
 - 对 link to label，同时修正超链接区域坐标和 label 位置坐标

之后，超链接就正常了。

缩印版 PDF 中不储存缩印前的页码信息，对获取到的原始坐标，需要人工判断缩印后位置（例如，对 `2 on 1`，是在左侧还是右侧的逻辑页面），然后进行相应的坐标变换。如果要做自动修复，准备缩印和不缩印的两份（同源）PDF 是必要的，可能也是充分的。

### 其他
完美的解决方案可能需要从头改写 latex2e kernel 的 output routine，直接支持缩印功能。缩印主要面向印刷，超链接面向电子文档阅读，不能用就忍忍吧。

**Comment by muzimuzhi** [comment]
> 如果要做自动修复，准备缩印和不缩印的两份（同源）PDF 是必要的，可能也是充分的。

利用 PyPdf2 库写了一个修复超链接位置的脚本，[Gist - fix PDF hyperlinks](https://gist.github.com/muzimuzhi/7d4060ac3b772fe80bb70952e6d6adcf)，验证了「充分性」。

**Comment by muzimuzhi** [comment]
又及，提供的 MWE 里有两个问题：
 - `\pageref{LastPage}` 只在引入 `lastpage` 宏包后才正确生效
 - `\href{github.com}{github}` 里的 `github.com` 不是 full URL（例如 `https://github.com`，见 `texdoc hyperref`, sec. 4），这样生成的链接将指向同目录下名为 `github.com` 的本地文件。

**Comment by OsbertWang** [comment]
的确是，这个 MWE 当初写的时候没仔细检查，所以出现了很多纰漏
