### ISSUE TITLE
Color error of paper template of IEEE transaction.

### ISSUE THREAD

**Issue by majiagouxiaoxueduizhang** [CTeX-org/forum#46]
When I use the IEEE Transaction paper template, the color of the text behind the title will change to blue whenever the title is linked to the image.
![image](https://user-images.githubusercontent.com/24507415/60381696-92784d00-9a8b-11e9-9110-4a64d9e9e019.png)
I have uploaded a project file, which contains the code I made a mistake. Can someone try to modify it for me?
[MWE.zip](https://github.com/CTeX-org/forum/files/3341710/MWE.zip)

**Comment by muzimuzhi** [comment]
### Short answer

Add following lines into file `generic-color.tex`, after `\documentclass` and before `\begin{document}`:
```latex
\makeatletter
\def\fnum@figure{\textcolor{subsectioncolor}{\sf Fig.~\thefigure}}
\def\fnum@table{\textcolor{subsectioncolor}{\sf TABLE~\thetable}}
\makeatother
```

### Long answer

Firstly, a relative simpler MWE could be:
```latex
\documentclass[twoside, web]{ieeecolor}
\usepackage{generic}
\usepackage{lipsum}

%% uncomment following line to fix the main problem
%\makeatletter
%\def\fnum@figure{\textcolor{subsectioncolor}{\sf Fig.~\thefigure}}
%\def\fnum@table{\textcolor{subsectioncolor}{\sf TABLE~\thetable}}
%\makeatother

\begin{document}
\lipsum[1-5]

\section{title b}
\lipsum[1]

\begin{figure}
  \rule{1pt}{40pt}
  \caption{title 2}
\end{figure}

\lipsum
\end{document}
```

The triggering conditions seems to be:
 - a slight under-full column (or page) naturally broke by a section command, and
 - a top float at the next column (or page)

The impacts of the problem are:
 1. the color (if any) of the first section command at next column is unset, 
 1. the color of text following that section command is set to the color of number part of float caption, and
 1. the warning `pdfTeX warning: /Library/TeX/texbin/pdflatex: pop empty color page stack 0` is written multiple times into the log.

The solution mentioned in *Short answer* solves impact 2 and partly of impact 3, but not impart 1. To solve them entirely, one need to modify the template more deeply. If you are an author using the template to prepare your article and submit it to the journal, the current solution maybe enough. If you are the maintainer of that template, more work need to be done.

The cause of your problem relates to
 - the color scheme used by, and the restriction exists in LaTeX engine and its color packages (see [this question](https://tex.stackexchange.com/q/316689/79060) on TeX-SX for more info), and
 - the abuse of declarative command `\color` used in `ieeecolor.cls`

**Comment by majiagouxiaoxueduizhang** [comment]
> ### Short answer
> Add following lines into file `generic-color.tex`, after `\documentclass` and before `\begin{document}`:
> 
> ```
> \makeatletter
> \def\fnum@figure{\textcolor{subsectioncolor}{\sf Fig.~\thefigure}}
> \def\fnum@table{\textcolor{subsectioncolor}{\sf TABLE~\thetable}}
> \makeatother
> ```
> 
> ### Long answer
> Firstly, a relative simpler MWE could be:
> 
> ```
> \documentclass[twoside, web]{ieeecolor}
> \usepackage{generic}
> \usepackage{lipsum}
> 
> %% uncomment following lines to fix the main problem
> %\makeatletter
> %\def\fnum@figure{\textcolor{subsectioncolor}{\sf Fig.~\thefigure}}
> %\def\fnum@table{\textcolor{subsectioncolor}{\sf TABLE~\thetable}}
> %\makeatother
> 
> \begin{document}
> \lipsum[1-5]
> 
> \section{title b}
> \lipsum[1]
> 
> \begin{figure}
>   \rule{1pt}{40pt}
>   \caption{title 2}
> \end{figure}
> 
> \lipsum
> \end{document}
> ```
> 
> The triggering conditions seems to be:
> 
> * a slight under-full column (or page) naturally broke by a section command, and
> * a top float at the next column (or page)
> 
> The impacts of the problem are:
> 
> 1. the color (if any) of the first section command at next column is unset,
> 2. the color of text following that section command is set to the color of number part of float caption, and
> 3. the warning `pdfTeX warning: /Library/TeX/texbin/pdflatex: pop empty color page stack 0` is written multiple times into the log.
> 
> The solution mentioned in _Short answer_ solves impact 2 and partly of impact 3, but not impart 1. To solve them entirely, one need to modify the template more deeply. If you are an author using the template to prepare your article and submit it to the journal, the current solution maybe enough. If you are the maintainer of that template, more work need to be done.
> 
> The cause of your problem relates to
> 
> * the color scheme used by, and the restriction exists in LaTeX engine and its color packages (see [this question](https://tex.stackexchange.com/q/316689/79060) on TeX-SX for more info), and
> * the abuse of declarative command `\color` used in `ieeecolor.cls`

Thank you very much for your reply, I have changed my project according to your reply, and have improved, as you said, the import of 1 problem not solve, and I found that my friends don't have this problem, this is let me feel anxious problem. I do not know whether the import 1 problem affect my articles published,once again thank you for your reply.

**Comment by muzimuzhi** [comment]
> I found that my friends don't have this problem, this is let me feel anxious problem.

The triggering conditions of your problem are rather strict, and are not necessary meet by every paper. So, be relax.

**Comment by majiagouxiaoxueduizhang** [comment]
> > I found that my friends don't have this problem, this is let me feel anxious problem.
> 
> The triggering conditions of your problem are rather strict, and are not necessary meet by every paper. So, be relax.

OK,Thank you very much.
