### ISSUE TITLE
希伯来文与符号反转

### ISSUE THREAD

**Issue by Ranqumn** [CTeX-org/forum#48]
## 检查

- [X] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- TeX 发行版
  - [X] TeX Live 2019

## 复现条件

- 希伯来文

这似乎是希伯来文从右往左的书写方式，产生的？（我猜的）

这是 bug 还是 feature？

## 样例

**样例1**

```latex
% ! xelatex
\documentclass{article}

\begin{document}

 י  % U+05D9

(

\end{document}
```

![issue-hebrew-1](https://user-images.githubusercontent.com/48835452/61257440-887b6d00-a760-11e9-99d9-f3334c120ab9.png)

**样例2**

```latex
% ! xelatex
\documentclass{article}

\begin{document}

 י  % U+05D9

`'

\end{document}
```

![issue-hebrew-2](https://user-images.githubusercontent.com/48835452/61257453-8fa27b00-a760-11e9-8ab4-7a7efeba51bc.png)

如果有英文字母在这些符号前面，就不会有这个问题。

还有，单个引号似乎没有这个问题，而成对引号有问题。

如果用 `fontspec` 宏包加载字体，把希伯来文显示出来，就没有这个问题了。

**Comment by stone-zeng** [comment]
> That is a XeTeX “feature”, it detects tat the text is right to left (it does not fully apply the BiDi algorithm, though, as this operates on word level not paragraph level) and tell HarfBuzz to shape the text in the RTL direction which in turn activates BiDi mirroring.
>
> _Originally posted by @khaledhosny in https://github.com/latex3/latex2e/issues/157#issuecomment-511861543_

所以，是「feature」。

**Comment by Ranqumn** [comment]
@stone-zeng 可能没有这么简单吧。

`XeLaTeX` 好像并没有自动判断 CJK 文字、还有中间插入一个命令的情况，所以，如果有如下情况：

```latex
\documentclass{ctexart}

\begin{document}

  {「 ביבליה 」} （《圣经》） (\emph{Biblia})

  {「 ביבליה 」} （《圣经》） (Biblia)

  {「 ביבליה 」} （《圣经》） ({Biblia})

  {「 ביבליה 」} （《圣经》） (\texttt{Biblia})

\end{document}
```

效果是：

![issue-hebrew-3](https://user-images.githubusercontent.com/48835452/61348839-96f58180-a851-11e9-86b9-83af1a3522ee.png)


这个 feature 会让萌新感觉很迷……

**Comment by stone-zeng** [comment]
正常来说你肯定得用个支持这些的字体对吧：

```latex
\documentclass{ctexart}
\setmainfont{FreeSerif.otf}
\begin{document}

{\addfontfeatures{Script=Arabic}「ביבליה」} （《圣经》） (\emph{Biblia})

{\addfontfeatures{Script=Arabic}「ביבליה」} （《圣经》） (Biblia)

{\addfontfeatures{Script=Arabic}「ביבליה」} （《圣经》） ({Biblia})

{\addfontfeatures{Script=Arabic}「ביבליה」} （《圣经》） (\texttt{Biblia})

\end{document}
```

![image](https://user-images.githubusercontent.com/18233088/61349677-85cf6380-a897-11e9-8171-c832e89890d9.png)

不管怎么样这个问题反正是超出我能力范围了，而且那有「盟新」会这么玩……具体还是取问 Khaled Hosny 吧。
