### ISSUE TITLE
soul宏包相关问题

### ISSUE THREAD

**Issue by DangeRS2** [CTeX-org/forum#51]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2017
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

在使用soul宏包时遇到两个问题：
1）按照MWE运行，发现第一次调用`\mycom`，将计数器赋值为5；
2）如果将此处`AAA`替换为`Comment`，编译不通过。

## 最小工作示例（MWE）

```latex
\documentclass[12pt, draftclsnofoot, journal, onecolumn]{IEEEtran}

\usepackage{soul}
\newcounter{MYitemresp}[section]
\renewcommand{\theMYitemresp}{\arabic{MYitemresp}}
\newcommand{\respitem}{%
	\refstepcounter{MYitemresp}%
	\textbf{\textsc{AAA}~\theMYitemresp}:}
\newcommand{\mycom}[1]{\ul{\respitem~#1}}

\begin{document}

\section{Test}

\theMYitemresp

\respitem

\mycom{Test.

Test.}

\end{document}

```

（用 XeLaTeX 编译后）输出

```latex
Package soul Error: Reconstruction failed. Test.}
```

## 链接

- TeX.SX:
- GitHub:

**Comment by muzimuzhi** [comment]
1. `IEEEtran` 模板需要用 pdflatex 编译，否则字体会出现问题
2. 计数器多次自增的问题，和 `\ul` 的实现有关，可以把自增命令移出 `\ul`
3. `Reconstruction failed.` 的原因是 "Comment" 单词内部有断词点，用 `\mbox` 抑制断词点后可修复。详见 `texdoc soul`, sec. 2.2

试试下面的例子：
```latex
\documentclass[12pt, draftclsnofoot, journal, onecolumn]{IEEEtran}
\usepackage{soul}

\newcounter{MYitemresp}[section]
\renewcommand{\theMYitemresp}{\arabic{MYitemresp}}

\newcommand{\respitem}{%
  % change 2: add \mbox
  \textbf{\textsc{\mbox{Comment}}~\theMYitemresp}:}
\newcommand{\mycom}[1]{%
  % change 1: % move \refstepcounter from inside \ul
  \refstepcounter{MYitemresp}%
  \ul{\respitem~#1}}

\begin{document}
\refstepcounter{MYitemresp}
\theMYitemresp

\respitem

\mycom{Test.

Test.}
\end{document}
```

用 pdflatex 编译后，得到
![image](https://user-images.githubusercontent.com/6376638/63531749-c461d900-c53b-11e9-9158-6d4b6f9966e7.png)

**Comment by DangeRS2** [comment]
感谢 @muzimuzhi 的解答~

另外，如果用`xelatex`编译，需要改变字体编码`\usepackage[T1]{fontenc}`才能保证字体不变。这好像是高版本`texlive`的小问题。

**Comment by muzimuzhi** [comment]
1. 修改了上条评论中修复后的例子，增加了 `\@respitem` 的定义，使得单独使用 `\respitem` 也能递增计数器
2. 引擎 xetex 和 luatex 使用字体编码 TU，而 pdftex 使用 OT1，这是由 latex2e 格式设置的。这个功能是由提交 https://github.com/latex3/latex2e/commit/9e69c7be78778cd80b79bf3e82e9c5847746e002 加入的（见其中的 `fontdef.dtx` 文件），包含该提交的最早正式版本是 texlive 2017 包含的 latex2e。
