### ISSUE TITLE
论坛关闭后，哪里可以找到最新的CTex宏集使用手册

### ISSUE THREAD

**Issue by YP-Li** [CTeX-org/forum#52]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [x] CTeX

## 描述问题

- 当前我在overleaf的环境下编写毕业论的cls，基于CTex宏集。

- 现在出现一些疑问，希望能找到`《CTex宏集手册》`需求帮助。

- 当前论坛已经关闭，请问是否可以提供最新手册的链接？

谢谢！

## 最小工作示例（MWE）

无

## 链接

无

**Comment by miRoox** [comment]
http://mirrors.ctan.org/language/chinese/ctex/ctex.pdf

**Comment by YP-Li** [comment]
非常感谢！
