### ISSUE TITLE
\item对齐的问题

### ISSUE THREAD

**Issue by bupt-renpei** [CTeX-org/forum#55]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

 需要将test与下一行的hhh前的小圆点对齐，使用\!的方式，文字会向上移动而非向左

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\begin{document}
\begin{itemize}
\item[] test
\item hhh
\end{itemize}
\end{document}
```

**Comment by Liam0205** [comment]
https://liam.page/2013/12/02/LaTeX-How-to-start-itemize-on-same-line-as-text/

这篇应该有些帮助。
