### ISSUE TITLE
无法加载eps格式图片

### ISSUE THREAD

**Issue by kuku1993** [CTeX-org/forum#58]
[无法加载eps图片.zip](https://github.com/CTeX-org/forum/files/3665153/eps.zip)

**Comment by muzimuzhi** [comment]
改
```latex
\includegraphics[scale=.25]{physical-model.eps}
```
为
```latex
\includegraphics[scale=.25]{physical-model}
```

**Comment by kuku1993** [comment]
好像不行?

**Comment by kuku1993** [comment]
去掉.eps还是没成功

**Comment by kuku1993** [comment]
删除辅助文件后依然不行

**Comment by kuku1993** [comment]
清理辅助文件后,依然抱=报相同的错误

**Comment by muzimuzhi** [comment]
使用 pdflatex 编译，在我本机和 overleaf.com 网站都编译成功，无报错，eps 图片在转换为 pdf 后成功插入。

你本地编译有报错，具体是什么报错呢？
你提供的 zip 文件里未包含 log，无法知道你遇到的是什么错误。

**Comment by kuku1993** [comment]
[manuscripts.log](https://github.com/CTeX-org/forum/files/3665406/manuscripts.log)
这是log,麻烦有时间看一下.不好意思,下午有事离开了电脑

**Comment by muzimuzhi** [comment]
在 eps 文件所在文件夹里，手动执行
```
repstopdf --outfile=physical-model-eps-converted-to.pdf physical-model.eps
```
试试，看能否转换成功。

**Comment by kuku1993** [comment]
能说的再详细不,这步操作我不知道怎么实现(⊙o⊙)…

**Comment by muzimuzhi** [comment]
0. 根据 log，待转换的 eps 文件是 `physical-model.eps`
1. 使用这则[百度经验](https://jingyan.baidu.com/article/25648fc1826aa99191fd00d9.html)里的方法，在文件 `physical-model.eps` 所在文件夹打开 cmd.exe
2. 输入 `repstopdf --outfile=physical-model-eps-converted-to.pdf physical-model.eps`，按回车，观察 cmd.exe 里的输出信息，反馈到这里

**Comment by kuku1993** [comment]
![image](https://user-images.githubusercontent.com/54982333/65816388-5a6cdb80-e22d-11e9-98eb-61c332a3fce6.png)
fa发现生成了对应的physical-model-eps-converted-to.pdf文件,然后正常编译了,但不知道这是什么原因导致这样的问题?

**Comment by kuku1993** [comment]
[manuscripts.log](https://github.com/CTeX-org/forum/files/3665447/manuscripts.log)
这是编译成功后的log文件

**Comment by kuku1993** [comment]
大神们有时间指点一下良策吧

**Comment by kuku1993** [comment]
CMD窗口按回车键后生成了pdf文件,这是cmd窗口信息
![image](https://user-images.githubusercontent.com/54982333/65825064-d9512b00-e2a4-11e9-9c64-63603a40519b.png)

**Comment by muzimuzhi** [comment]
目前能知道的是，
 - 在编译时，自动调用 repstopdf（是一个 ghostscript 脚本）把 eps 转换为 pdf，无法生成转换后的 pdf。
 - 手动执行格式转换命令，成功。说明 ghostscript 能用。

具体了解「为什么出错」，估计还需要交流很多个回合，例如测试受限的 \write18 是否能用。先这么凑合用吧。

**Comment by kuku1993** [comment]
替换\write 18是怎么实现呢?我上次用还没问题,这次不知道怎么就突然出现这样的问题,再问一下有没有批量处理把eps图片转化成对应的pdf图片呢?

**Comment by kuku1993** [comment]
错误日志里显示d: using draft setting.,能告诉我这句话是什么意思吗

**Comment by muzimuzhi** [comment]
> 替换\write 18是怎么实现呢?

不是替换，而是测试（那个功能能不能用）。因为在使用 pdflatex 编译时，eps 到 pdf 的转换依赖 \write18 的功能。

> 再问一下有没有批量处理把eps图片转化成对应的pdf图片呢?

如果图片张数不多，手动一张张执行 `repstopdf` 就行；特别追求批量的，可以在 cmd、powershell 里写循环。

> 错误日志里显示d: using draft setting.,能告诉我这句话是什么意思吗

（因为找不到要插入的 pdf 文件，所以不得不）启用 graphicx 宏包的 draft 模式，
> draft 
> suppress all the `special' features. In particular graphics les are not
included (but they are still read for size info) just the lename is printed
in a box of the correct size.
> `texdoc graphicx`, sec. 4.1 

------
顺便，你有没有试过，在不包含中文的路径中编译文档时，插入 eps 图片能否成功？
