### ISSUE TITLE
怎么自动控制浮动体图片,表格不会跨越它所在的节?

### ISSUE THREAD

**Issue by kuku1993** [CTeX-org/forum#59]
怎么做到让图片，表格这样的浮动体的位置不会越到它所在节的上一节和下一节中去，目的就是避免它的位置和它相对应的叙述内容不会离的太远。目前我已知 `\usepackage[section]{placeins}` 貌似是解决这个事的，但是实践后发现效果并不是很好，有时候图片还是跨越到了它所在的节外。我觉得这是一个很普遍的问题，希望大神们瞧瞧。

**Comment by stone-zeng** [comment]
请提供一下「有时候图片还是跨越到了它所在的节外」的具体例子。

**Comment by muzimuzhi** [comment]
除了使用 `placeins` 宏包，还可以手动调整「浮动体对应输入」在 tex 文件中的位置。

**Comment by kuku1993** [comment]
好的,谢谢
