### ISSUE TITLE
如何设置整段缩进

### ISSUE THREAD

**Issue by liuzhaoming5954** [CTeX-org/forum#61]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [ ] TeX Live 
  - [x] MiKTeX 
  - [ ] CTeX

## 描述问题
段落都是首行缩进，怎样才能让段落整段都缩进。
尝试使用了adjustwidth环境，失败了
\begin{adjustwidth}{1cm}{3cm}
\end{adjustwidth}

请问如何才能让一个段落整体都缩进，或者是否有一个可以整体缩进的列表

非常感谢您的帮助

**Comment by mohuangrui** [comment]
见 https://latex.org/forum/viewtopic.php?t=547

1. 如果想要整段左右都缩进，可以用
```
\begin{quote}
整段左右都缩进的一段文字
\end{quote}
```
2. 如果想要整段左边缩进右边不缩进，可以用
```
\hangindent 2em
\hangafter=0
整段左边缩进右边不缩进的一段文字
```

**Comment by liuzhaoming5954** [comment]
非常感谢您的帮助

**Comment by muzimuzhi** [comment]
建议总是使用环境（例如 `quote` 和 `quotation`），而非 tex primitive（例如 `\hangindent`）。
如果既有的环境不满足要求，可以自定义新环境。

**Comment by muzimuzhi** [comment]
（补充）

1. 在 tex primitive 层面，用 `\hangindent` 和 `\hangafter` 调整单个段落的两侧缩进，用 `\leftskip` 和 `\rightskip` 调整从插入位置往后所有段落的两侧缩进。
1. 在 latex2e 层面，可以定义一个内部使用列表的新环境，通过 `\leftmargin` 和 `\rightmargin` 调整列表内容的的两侧缩进。

后者的一个例子是标准文档类中 `quote` 环境的定义方式。
```tex
% article.cls, line 404:
\newenvironment{quote}
               {\list{}{\rightmargin\leftmargin}%
                \item\relax}
               {\endlist}
```
其中 `\leftmargin` 有默认值 2.5em（单栏模式）或 2em（双栏模式）。

以下两个例子都实现了环境内容两侧各缩进 2em
```tex
\newenvironment{xQuote}{%
  \par
  \setlength{\leftskip}{2em}%
  \setlength{\rightskip}{2em}%
}{%
  \par
}

\newenvironment{xQuote}{%
  \list{}{%
    \setlength{\listparindent}{2em}%
    \setlength{\itemindent}{\listparindent}%
    \setlength{\leftmargin}{2em}%
    \setlength{\rightmargin}{2em}%
  }
  \item\relax
}{%
  \endlist
}
```

**Comment by JaroChen** [comment]
thanks, it's very useful

**Comment by muzimuzhi** [comment]
> 段落都是首行缩进，怎样才能让段落整段都缩进。
> 尝试使用了adjustwidth环境，失败了
> \begin{adjustwidth}{1cm}{3cm}
> \end{adjustwidth}

我发现当时没有追问题主「为什么（`changepage` 包的）`adjustwidth` 环境失败」。

`\begin{adjustwidth}{<leftmargin>}{<rightmargin>}` 就是一个两侧缩进可设置的 `quote` 环境，`\begin{adjustwidth}{\leftmargin}{\leftmargin}` 应当和 `quote` 的输出一致。
