### ISSUE TITLE
texlive跨版本安装/更新宏包问题

### ISSUE THREAD

**Issue by dnsilence** [CTeX-org/forum#62]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

请在此处描述清楚您所遇到的问题：
跨版本无法安装宏包有没有可以避开重新安装的方法呢，否则每年都要更新就得重新安装。https://liam.page/2015/06/02/fake-tlpretest-to-update-packages/
上面的链接说了一种方法，但是这里的环境变量不知如何操作

## 链接

- TeX.SX:
- GitHub:https://github.com/dnsilence

**Comment by stone-zeng** [comment]
简而言之，就是把「该重命名」的地方都改掉。

> 环境变量不知如何操作

具体是哪一步，请指出，那篇文章里面已经说得很清楚了。如果不知道、看不懂，那么按照 tug 的意思，就不要这么玩，**请老老实实每年重装**。

我也觉得这样很反人类，但是如果你有靠谱的包管理器（比如 homebrew 这样），其实也就一行命令的事情。
