### ISSUE TITLE
怎么把字体调整大，不只是huge等命令

### ISSUE THREAD

**Issue by hui9611** [CTeX-org/forum#64]
```tex
\documentclass[serif]{beamer}

\usepackage[UTF8,noindent]{ctexcap}
\begin{document}
\begin{frame}{练习讲解}
\begin{itemize}
\item [1.] 已知二次函数$f(x)$满足$f(2)=-1,f(-1)=-1$,且$f(x)$的最大值为8，求$f(x)$的解析式？
\item[2.]函数$f(x)=4x^2$的图像经过怎样的平移变换得到函数$g(x)=4x^2-2x-1$的图像？
\item[3.]将二次函数的图像向左平移2个单位长度，再向上平移3个单位长度，得到函数$y=x^2-2x+1$的图像，求b c的值为多少？
\end{itemize}
\end{frame}
\end{document}
```

**Comment by OsbertWang** [comment]
我记得在 `ctex`  手册第 8 节介绍过 `\zihao` 命令

**Comment by hui9611** [comment]
think you such as?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "OsbertWang"<notifications@github.com&gt;; 
发送时间: 2019年11月20日(星期三) 下午4:52
收件人: "CTeX-org/forum"<forum@noreply.github.com&gt;; 
抄送: "辉"<1005254597@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CTeX-org/forum] 怎么把字体调整大，不只是huge等命令 (#64)




我记得在 ctex  手册第 8 节介绍过 \zihao 命令

**Comment by hui9611** [comment]
能够把书籍给我看看？谢谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"OsbertWang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午4:52
收件人:&nbsp;"CTeX-org/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"辉"<1005254597@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CTeX-org/forum] 怎么把字体调整大，不只是huge等命令 (#64)




我记得在 ctex  手册第 8 节介绍过 \zihao 命令

**Comment by OsbertWang** [comment]
> 能够把书籍给我看看？谢谢您
在命令行里执行
```
texdoc ctex
```

**Comment by hui9611** [comment]
突然感觉你们好厉害，谢谢您哦




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "OsbertWang"<notifications@github.com&gt;; 
发送时间: 2019年11月20日(星期三) 下午4:56
收件人: "CTeX-org/forum"<forum@noreply.github.com&gt;; 
抄送: "辉"<1005254597@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CTeX-org/forum] 怎么把字体调整大，不只是huge等命令 (#64)



 
能够把书籍给我看看？谢谢您
 在命令行里执行
  texdoc ctex

**Comment by hui9611** [comment]
，系统报错，这可怎么办呢？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"OsbertWang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午4:56
收件人:&nbsp;"CTeX-org/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"辉"<1005254597@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CTeX-org/forum] 怎么把字体调整大，不只是huge等命令 (#64)



 
能够把书籍给我看看？谢谢您
 在命令行里执行
  texdoc ctex

**Comment by stone-zeng** [comment]
> ，系统报错，这可怎么办呢？

请每次评论把话讲完，好不好呀？

**Comment by hui9611** [comment]
好的好的





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiangdong Zeng"<notifications@github.com&gt;; 
发送时间: 2019年11月20日(星期三) 下午4:59
收件人: "CTeX-org/forum"<forum@noreply.github.com&gt;; 
抄送: "辉"<1005254597@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CTeX-org/forum] 怎么把字体调整大，不只是huge等命令 (#64)



 
，系统报错，这可怎么办呢？
  
请每次评论把话讲完，好不好呀？

**Comment by hui9611** [comment]
可以电子稿给我看看？谢谢啦




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiangdong Zeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午4:59
收件人:&nbsp;"CTeX-org/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"辉"<1005254597@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CTeX-org/forum] 怎么把字体调整大，不只是huge等命令 (#64)



 
，系统报错，这可怎么办呢？
  
请每次评论把话讲完，好不好呀？

**Comment by stone-zeng** [comment]
找文档这种问题请自己解决：

<img width="809" alt="Screen Shot 2019-11-20 at 17 02 09" src="https://user-images.githubusercontent.com/18233088/69224426-7f3f5880-0bb7-11ea-8204-a445777091d8.png">

**Comment by OsbertWang** [comment]
> ，系统报错，这可怎么办呢？

请告诉我：
- 你具体做了什么？
- 系统具体反馈了什么？

当然你还可以到 [texdoc 网站](http://texdoc.net/texmf-dist/doc/latex/ctex/ctex.pdf) 查阅。

**Comment by hui9611** [comment]
大哥翻墙翻不出去，最近墙的很腻害


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiangdong Zeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午5:02
收件人:&nbsp;"CTeX-org/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"辉"<1005254597@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CTeX-org/forum] 怎么把字体调整大，不只是huge等命令 (#64)




找文档这种问题请自己解决：

**Comment by stone-zeng** [comment]
> 大哥翻墙翻不出去，最近墙的很腻害

这不是借口：

<img width="728" alt="Screen Shot 2019-11-20 at 17 04 35" src="https://user-images.githubusercontent.com/18233088/69224614-d5ac9700-0bb7-11ea-829b-c915574b82a7.png">

**Comment by hui9611** [comment]
大哥批评的是，好好学习，多多提问


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiangdong Zeng"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 下午5:05
收件人:&nbsp;"CTeX-org/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"辉"<1005254597@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CTeX-org/forum] 怎么把字体调整大，不只是huge等命令 (#64)



 
大哥翻墙翻不出去，最近墙的很腻害
  
这不是借口：

**Comment by hui9611** [comment]
在win7系统下，谢谢，我搞定了

**Comment by hui9611** [comment]
![@M1_{C J%4NYLMMW`{QL4_L](https://user-images.githubusercontent.com/57984711/69225933-4654b300-0bba-11ea-86f7-0b1d1abaa04b.png)
怎么这样没用呢

**Comment by Liam0205** [comment]
OMG……

```tex
\documentclass[serif]{ctexbeamer}
\begin{document}
\begin{frame}{练习讲解}
\zihao{3}
123
\end{frame}
\end{document}
```

**Comment by Liam0205** [comment]
`ctexcap` 是过时宏包，仅做兼容性保留。

对于 `beamer` 建议用 `ctexbeamer`；如同 `article` 之于 `ctexart`。

**Comment by Liam0205** [comment]
> > ，系统报错，这可怎么办呢？
> 
> 请每次评论把话讲完，好不好呀？

好温柔。

**Comment by hui9611** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liam Huang"<notifications@github.com&gt;; 
发送时间: 2019年11月20日(星期三) 下午5:26
收件人: "CTeX-org/forum"<forum@noreply.github.com&gt;; 
抄送: "辉"<1005254597@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CTeX-org/forum] 怎么把字体调整大，不只是huge等命令 (#64)




ctexcap 是过时宏包，仅做兼容性保留。
 
对于 beamer 建议用 ctexbeamer；如同 article 之于 ctexart。

**Comment by hui9611** [comment]
低调低调




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liam Huang"<notifications@github.com&gt;; 
发送时间: 2019年11月20日(星期三) 下午5:26
收件人: "CTeX-org/forum"<forum@noreply.github.com&gt;; 
抄送: "辉"<1005254597@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CTeX-org/forum] 怎么把字体调整大，不只是huge等命令 (#64)



  
，系统报错，这可怎么办呢？
  
请每次评论把话讲完，好不好呀？
  
好温柔。
