### ISSUE TITLE
在尝试让《计算数学》期刊模板能够在 TeXLive 中编译通过时遇到的问题

### ISSUE THREAD

**Issue by OsbertWang** [CTeX-org/forum#65]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

受 [【LaTeX Tips】国内期刊 CCT 模板编译经验](https://liam.page/2013/10/15/LaTeX-CCT-template/) 及其下评论启发，我开了一个小项目 [CCTinTeXLive](https://github.com/OsbertWang/CCTinTeXLive)。
这个项目的初衷是让用户投稿时可直接下载对应期刊模板，在 TeXLive 中编译通过（可能需要用户改一下编辑器的编码）。
目前遇到的问题是，[cjcm](https://github.com/OsbertWang/CCTinTeXLive/tree/master/cjcm) 模板中引用 `changes` 包就会报错，目前还不清楚该如何解决。
我将附件添加在这里。

## 最小工作示例（MWE）

见附件
[cjcm.zip](https://github.com/CTeX-org/forum/files/3877534/cjcm.zip)

**Comment by Liam0205** [comment]
@stone-zeng 有这么一篇文章，你是否有参考过？
https://stone-zeng.github.io/2019-10-26-compile-cct-template/

**Comment by OsbertWang** [comment]
> @stone-zeng 有这么一篇文章，你是否有参考过？
> https://stone-zeng.github.io/2019-10-26-compile-cct-template/

嗯，这篇文章读过，他改得比我高明多了。可惜他这样的改法也会碰到 `changes` 包被引入后编译不通过的问题（原因还跟我不太一样）。
《中国科学：信息科学》和《计算数学》的模板还有一些不同的地方，例如《中国科学：信息科学》是没有引 `CJKCCT` 的，而《计算数学》引了。当然还有其他的一些地方，就不展开对比了。

**Comment by Liam0205** [comment]
@OsbertWang @stone-zeng @xdzeng96 轮到你接茬了。

**Comment by OsbertWang** [comment]
算了，这个问题就姑且关闭吧，CCT 魔改太多，一时间也不可能做出通用的东西来。
另外今年中科院期刊分区把一些中国期刊的英文版提区了，可能未来投稿中文核心的用户会越来越少。
