### ISSUE TITLE
tikz和tabu（负宽度参数） 冲突，求临时补救方法

### ISSUE THREAD

**Issue by maboloshi** [CTeX-org/forum#66]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [ ] TeX Live 
  - [x] MiKTeX  周二 十一月 12 06:29:05 2019
  - [ ] CTeX

## 描述问题

当加载`tikz`宏包，若`tabu`宏包使用`负宽度参数` 就会发生编译错误。
## 示例

```latex
% -*- coding: utf-8 -*-
%!TEX program = xelatex
\documentclass[12pt]{article}
\usepackage{tabu}
\usepackage{tikz}
\begin{document}

\begin{table}[htb]
    \centering
    \begin{tabu}to.87\textwidth{*3{X[c]|}X[-2.5,c]*2{|X[c]}} 
        XX & X    & X    & X        & X    & X    \\
           & XX & XX & XXXXXX & XX & XX \\
    \end{tabu}
\end{table}
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
! Misplaced \cr.
<inserted text> \cr 
                    
l.13     \end{tabu}
                   
```

## 链接

- TeX.SX: https://tex.stackexchange.com/questions/517544/tikz-and-tabu-negativ-width-coe%EF%AC%83cients-conflict
- GitHub: tabu-issues-for-future-maintainer/tabu#23

**Comment by stone-zeng** [comment]
See https://github.com/tabu-issues-for-future-maintainer/tabu/issues/23.

**Comment by muzimuzhi** [comment]
一种可能的临时补救方式：使用较早版本的 `tabu.sty`、`array.sty` 和 `color.sty`。
三个文件都在 [2017-packages.pdf](https://github.com/CTeX-org/forum/files/3882273/2017-packages.pdf) 的附件中，PDF 是在 overleaf.com 上的 texlive 2017 版本项目中，使用 pdflatex 命令编译下面的例子生成的。
```tex
\documentclass[12pt]{article}
\usepackage{tabu}
\usepackage{tikz}

\usepackage{embedfile} % support pdftex only
\embedfile{tabu.sty}
\embedfile{array.sty}
\embedfile{color.sty}

\begin{document}

\begin{table}[htb]
    \centering
    \begin{tabu}to.87\textwidth{*3{X[c]|}X[-2.5,c]*2{|X[c]}} 
        XX & X    & X    & X        & X    & X    \\
           & XX & XX & XXXXXX & XX & XX \\
    \end{tabu}
\end{table}
\end{document}
```

半年前试过有效，刚才测试了对你的例子仍然有效。未做更多测试。

**Comment by maboloshi** [comment]
@muzimuzhi  你好，能否帮忙提取一个老版`longtable.sty`。

**Comment by muzimuzhi** [comment]
@maboloshi 
这是一个使用 texlive 2017 编译的 [overleaf 项目](https://www.overleaf.com/9115579395xmkmfypxppdq)，允许编辑。项目内容是我前面提供的 latex 例子。修改例子即可从生成的 pdf 中获取 texlive 2017 里的几乎任何文件。

**Comment by maboloshi** [comment]
经测试发现`MiKTeX`中的`tabu`版本为2.9 自动更新获取不到新版本,手动更新到2.10 后 问题解决

**Comment by maboloshi** [comment]
@muzimuzhi 
问句题外话，您是怎么设置使得`overleaf`使用`texlive 2017版本`编译的。我自己创建了一个默认用`texlive 2018版本`编译，也没看到哪里可以设置。

**Comment by stone-zeng** [comment]
Overleaf 不会更改已存在的项目的编译配置，所以在他们更改为 2018 之前创建的项目默认依然还是用 2017。

**Comment by muzimuzhi** [comment]
@maboloshi 
需要项目是在 overleaf 升级到 texlive 2018 之前创建的。参考 overleaf 的升级日志

> The upgrade to TeX Live 2018 will not affect your existing projects because those projects will continue to use the TeX Live image they were created with and should continue to work as normal.
> https://www.overleaf.com/blog/tex-live-upgrade-september-2019

也许可以邮件联系维护团队，说明特殊需求，要求「把新建的项目改为使用 texlive 2017」。

**Comment by maboloshi** [comment]
> 经测试发现`MiKTeX`中的`tabu`版本为2.9 自动更新获取不到新版本,手动更新到2.10 后 问题解决

今天再次尝试，事实上没有修复。
之前的尝试，我可能弄错了什么
