### ISSUE TITLE
在\begin{figure}中，caption一直报错

### ISSUE THREAD

**Issue by Andretwu** [CTeX-org/forum#67]
## 编译环境

- 操作系统
  - [ ] Windows 7/8/10

- TeX 发行版
  - [ ] CTeX10.0

## 描述问题
1. \begin{figure}中，编译之后caption一直报错
    2. 主要问题是caption{}这一行有三个报错信息
a.   undefined control sequence
b.   missing number ,treated as zero
c.   illegal unit of measure(pt inserted)
3，主要需要解决caption出错的问题，其他都是没问题的

## 最小工作示例（MWE）

```latex
\documentclass{ieeeaccess}
\usepackage{cite}
\usepackage{amsmath,amssymb,amsfonts}
\usepackage{algorithmic}
\usepackage{graphicx}
\usepackage{textcomp}
\usepackage{subfigure}
\usepackage{multirow}
\begin{document}
\begin{figure}[htbp]
% Use the relevant command to insert your figure file.
% For example, with the graphicx package use
\caption{edge intensities, skeleton chain, and profile of the example network}
\centering
\subfigure[Example network]
{
\includegraphics[width=6.8cm]{figure1a.jpg}
}
\quad
\subfigure[ calculated edge intensities(P=2)]
{
\includegraphics[width=6.8cm]{figure1b.jpg}
}
\quad
\subfigure[skeleton chain]
{
\includegraphics[width=6.8cm]{figure1c.jpg}
}
\quad
\subfigure[skeleton chain-based profile]
{
\includegraphics[width=6.8cm]{figure1d.jpg}
}

\label{fig:1}% Give a unique label
\end{figure}
\EOD
\end{document}
```

（用 PDFLaTeX 编译后）输出

```latex
caption{}这一行有三个报错信息
a.   !undefined control sequence
b.   !missing number ,treated as zero
c.   !illegal unit of measure(pt inserted)
?
```
模板连接：https://journals.ieeeauthorcenter.ieee.org/create-your-ieee-journal-article/authoring-tools-and-templates/ieee-article-templates/templates-for-ieee-access/

**Comment by muzimuzhi** [comment]
- `ieeeaccess.cls` 提供了新的浮动体命令 `\Figure` 和 `\Table`，它们能根据浮动体内容宽度，自动选择以单栏/通栏模式排版浮动体。可惜 `\Figure` 只支持每次插入一张图（参考知乎专栏文章《[[LaTeX 期刊模板] ieeeaccess 文档类中 \Figure 和 \Table 的用法](https://zhuanlan.zhihu.com/p/60960611)》）。
 - `\Figure` 的大致逻辑是，先试排插图内容，把宽度存入 `\xfigwd`，然后根据 `\xfigwd` 的大小决定使用 `figure` 还是 `figure*` 环境、决定 `\caption` 怎么排。
 - 为了配合 `\Figure`，`ieeeaccess.cls` 在 212--241 行重定义了 `\caption` 的内部命令 `\@makecaption`。重定义后，`\caption` 需要使用 `\xfigwd`。如果没有定义，就会在 `ieeeaccess.cls` 的 227 行 `\ifdim \xfigwd >\columnwidth` 处报 `illegal unit of measure (pt inserted)` 的错误。其他错误都是衍生的。
 - 这导致无法直接使用 `figure(*)` 环境。解决方案可以是，手动（重）定义 `\xfigwd`。

```tex
\documentclass{ieeeaccess}
\usepackage{graphicx}
\usepackage{subfigure}

\usepackage{mwe}
\usepackage{lipsum}
\begin{document}

\begin{figure*}[htbp]
  \xdef\xfigwd{\textwidth}% 通栏浮动体，把它定义为 \textwidth
  \caption{edge intensities, skeleton chain, and profile of the example network}
  \centering
  \subfigure[Example network]
    {\includegraphics[width=6.8cm]{example-image}}
  \qquad
  \subfigure[calculated edge intensities (P=2)]
    {\includegraphics[width=6.8cm]{example-image}}
  \label{fig:1}
\end{figure*}


\begin{figure}[htbp]
  \xdef\xfigwd{\columnwidth}% 单栏浮动体，把它定义为 \columnwidth
  \caption{edge intensities, skeleton chain, and profile of the example network}
  \centering
  \subfigure[Example network]
    {\includegraphics[width=6.8cm]{example-image}}
  \\
  \subfigure[calculated edge intensities (P=2)]
    {\includegraphics[width=6.8cm]{example-image}}
  \label{fig:2}
\end{figure}
\lipsum[1-20]

\EOD
\end{document}
```

![image](https://user-images.githubusercontent.com/6376638/69697869-c03aee00-111e-11ea-877a-df27a9905fd9.png)

以上是简略的做法，若想完全遵循 `ieeeaccess.cls` 里的用法，应该写成

```tex
\begin{figure}[!h]
  \savebox\figbox{<figure content>}
  \xdef\xfigwd{\the\wd\figbox}
  \usebox\figbox
  \caption{text}
\end{figure}
```
