### ISSUE TITLE
在别人那里看到的安装问题

### ISSUE THREAD

**Issue by OsbertWang** [CTeX-org/forum#68]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

昨天和今天分别在两个人那里见到了安装问题，问题反馈几乎一样。
原以为是 mingw 造成的影响，但其中一人表示系统中并未有安装 mingw。
后又猜测是镜像文件下载不完整，查 MD5 后也未发现异常。
![windowsinstalltexlive2](https://user-images.githubusercontent.com/37971080/69945547-bbae7500-1524-11ea-9a03-cc2990a66335.jpg)
![windowsinstalltexlive1](https://user-images.githubusercontent.com/37971080/69945548-bbae7500-1524-11ea-9425-a08518d3a02f.jpg)
在附件处提供两个截图，它们源自其中一人今天上午的反馈。
昨晚后续反馈是其中一人又成功安装，但并未记得采取什么手段。
是否有人关注过类似问题，知道解决方法？

**Comment by muzimuzhi** [comment]
根据第一条错误信息
```
TLPDB::_install_package: unsupported container format xz
```
搜到的相关信息

> The installer should contain an unpacker xz.exe for xz files, so
either the downloaded installer was corrupt or something strange is
going on.
> 
> The installer ended with writing a logfile, according to your second
screenshot. Maybe it contains better clues?
> https://tug.org/pipermail/tex-live/2019-July/043939.html

搜索 texlive 源码得，生成报错信息的是[这里](https://github.com/TeX-Live/installer/blob/b3a4a35b9caf86b78665d009e04f90e153443e78/tlpkg/TeXLive/TLUtils.pm#L2258-L2261)
```perl
  # make sure that the found uncompressor type is also available
  if (!member($decompressorType, @{$::progs{'working_compressors'}})) {
    return(0, "unsupported container format $decompressorType");
  }
```

综上，像是识别解压程序时出现了问题。

**Comment by OsbertWang** [comment]
有些人碰到这样的问题提示，检查一下有没有 mingw 也就解决了。这次的用户声称操作系统是刚装的，没安装 mingw，就很奇怪。

**Comment by 404wu** [comment]
添加一个环境变量，所以需要在path那里加上cmd.exe所在位置，即这样一句话：C:\Windows\System32
我的电脑这样做就成功安装了 希望有帮助！

**Comment by OsbertWang** [comment]
> 添加一个环境变量，所以需要在path那里加上cmd.exe所在位置，即这样一句话：C:\Windows\System32
> 我的电脑这样做就成功安装了 希望有帮助！

这是很常见的处置方法，但对目前的问题无效。
目前已知除 mingw，预装了 java 和国产 2345 好压软件同样会影响 texlive 的安装，比较无奈。

**Comment by Liam0205** [comment]
@OsbertWang 预装 JAVA 为什么会对 TeX Live 的安装造成影响？TL 的安装会用到 JRE 的东西吗？「2345 好压」又是什么情况？

**Comment by muyuuuu** [comment]
> 有些人碰到这样的问题提示，检查一下有没有 mingw 也就解决了。这次的用户声称操作系统是刚装的，没安装 mingw，就很奇怪。

我安装了`mingw`，但对`texlive2019 (Windows)` 和 `texlive 2020(Linux)`的安装并没有造成什么影响呀

**Comment by OsbertWang** [comment]
> @OsbertWang 预装 JAVA 为什么会对 TeX Live 的安装造成影响？TL 的安装会用到 JRE 的东西吗？「2345 好压」又是什么情况？

Java 的那个是在 QQ 群里有人反馈的。在清除 jdk 的环境变量前安装一直提示失败，之后就神奇地好了。不过这目前来看是孤证。
好压 2345 是我给师妹装 texlie 2019 时碰到的情形。同样，卸载 2345 前安装失败了2次，我没有做其他的处理，只是将其卸载就神奇地装上了。这里还有个小插曲，本想在她电脑上实验在线安装，第一次出错后，查环境变量，好像也没缺少什么或者多了什么。第二次用镜像，同样出错。最后我就猜可能是什么软件影响了安装，蒙答案蒙到了 2345 身上。

**Comment by OsbertWang** [comment]
> > 有些人碰到这样的问题提示，检查一下有没有 mingw 也就解决了。这次的用户声称操作系统是刚装的，没安装 mingw，就很奇怪。
> 
> 我安装了`mingw`，但对`texlive2019 (Windows)` 和 `texlive 2020(Linux)`的安装并没有造成什么影响呀。（两个系统都有`mingw`）

这样不是很好吗 XD

**Comment by Liam0205** [comment]
感觉起来，基本上此类问题可以归结于在环境变量 `PATH` 中，没有正确找到目标命令行工具。可能原因有：

1. TL 自带了工具，但丢失或损坏了；
2. TL 自带了工具，工具本身完好，但在 `PATH` 之前的目录找到了不兼容的同名命令行工具；
3. 引用 Windows 的工具，但无法找到（例如 `system32` 不在 `PATH` 当中）；
4. 引用 Windows 的工具，但丢失或损坏了；
5. 引用 Windows 的工具，工具本身完好，但在 `PATH` 之前的目录找到了不兼容的同名命令行工具。

因为安装时会临时修改 `PATH`，将自带工具的目录置于最前方。所以对 `(2)` 表示怀疑。

mingw/JAVA 等第三方可能有条件地引发 `(2)` 或者 `(5)`，导致错误。

**Comment by OsbertWang** [comment]
> 感觉起来，基本上此类问题可以归结于在环境变量 `PATH` 中，没有正确找到目标命令行工具。可能原因有：
> 
> 1. TL 自带了工具，但丢失或损坏了；
> 2. TL 自带了工具，工具本身完好，但在 `PATH` 之前的目录找到了不兼容的同名命令行工具；
> 3. 引用 Windows 的工具，但无法找到（例如 `system32` 不在 `PATH` 当中）；
> 4. 引用 Windows 的工具，但丢失或损坏了；
> 5. 引用 Windows 的工具，工具本身完好，但在 `PATH` 之前的目录找到了不兼容的同名命令行工具。
> 
> 因为安装时会临时修改 `PATH`，将自带工具的目录置于最前方。所以对 `(2)` 表示怀疑。
> 
> mingw/JAVA 等第三方可能有条件地引发 `(2)` 或者 `(5)`，导致错误。

同意。

目前来看，安装时 `system32` 的影响可能不大。就我接触的情况而言，大部分人是在用 texstudio 时才发觉 `system32` 丢失了。
