### ISSUE TITLE
ctexbeamer中出现某些字与周边的字大小、颜色深度不一致

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#69]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

2019/11/28更新过所有宏包
在ctexbeamer中发现某些字与周边的字大小、颜色深度不一致

## 最小工作示例（MWE）

```latex
\documentclass{ctexbeamer}
\begin{document}
	\begin{frame}
		读⾳、⽤于
	\end{frame}
\end{document}
```

（用 XeLaTeX 编译后）输出的“⾳”和“⽤”与周围文字不一致

**Comment by muzimuzhi** [comment]
输入的字符（在语义上）有错
```
例子 读⾳、⽤于 U+8BFB U+2FB3 U+3001 U+2F64 U+4E8E
正常 读音、用于 U+8BFB U+97F3 U+3001 U+7528 U+4E8E
```
例子中的「音」和「用」两个字，在编码上属于 [Kangxi Radicals Block](https://www.compart.com/en/unicode/block/U+2F00)（康熙字典部首）。字体为它们设计了不同的字符，可以理解。（我不使用 windows，无法得到与你相似的效果，只是猜测）

**Comment by RuixiZhang42** [comment]
请试一试下面这个例子：
```latex
\documentclass{ctexbeamer}
\begin{document}
	\begin{frame}
		\char"8BFB \char"2FB3 \char"3001 \char"2F64 \char"4E8E %
		
		\char"8BFB \char"97F3 \char"3001 \char"7528 \char"4E8E %
	\end{frame}
\end{document}
```
第一行的「⾳」与「⽤」其实不是汉字，而是「康熙字典部首」。应该是字体内部把「康熙字典部首」故意做得比正常汉字小，所以输出的时候就有明显的问题。

第二行的「音」于「用」是货真价实的汉字，所以应该不会出现大小、深浅不一的问题了。

问题来源：
- 是不是你使用的输入法有问题？是不是输入法不能正确地将 yin 与 yong 转成正确的汉字编码？
- 这两个字是不是你从别的 PDF 复制粘贴过来的？复制过来的文档可能嵌入了错误信息。

**Comment by stone-zeng** [comment]
`ctexbeamer` 默认使用 sans font，windowsnew 就会调用微软雅黑。不过微软雅黑并不含有「康熙部首」这些字符，因此「⾳（U+2FB3）」和「⽤（U+2F64）」没有用它显示，而是似乎回退到了系统字体：

<img width="520" alt="Screen Shot 2019-12-09 at 23 14 49" src="https://user-images.githubusercontent.com/18233088/70447463-b4193e00-1ad9-11ea-870a-3ba73b77a7d9.png">

用 pdffonts 检查结果如下：

```
name                                           type              emb sub uni prob object ID
---------------------------------------------- ----------------- --- --- --- ---- ---------
QDBCEP+LMSans8-Regular-Identity-H              CID Type 0C       yes yes yes           7  0
SXPSEY+MicrosoftYaHei                          CID TrueType      yes yes yes          30  0
```

（并不知道什么时候会发生回退，什么时候又是 tofu

**Comment by sikouhjw** [comment]
> 请试一试以下这个例子：
> 
> ```
> \ documentclass { ctexbeamer }
>  \ begin { document }
> 	 \ begin { frame }
> 		 \ char “ 8BFB \ char ” 2FB3 \ char “ 3001 \ char ” 2F64 \ char “ 4E8E ％
> 		
> 		\ char “ 8BFB \ char ” 97F3 \ char “ 3001 \ char ” 7528 \ char “ 4E8E ％
> 	 \ end { frame }
>  \ end { document }
> ```
> 
> 应该是字体内部把「康熙字典部首」随意做得跟正常汉字不一样，所以输出的时候就有个第一行的「⾳」与「物件」其实不是汉字，而是「康熙字典部首」。明显的问题。
> 
> 第二行的「音」于「用」是货真价实的汉字，所以应该不会出现「大小，深浅不一」的问题了。
> 
> 问题来源：
> 
> * 是不是你使用的输入法有问题？是不是输入法不能正确地将yin与yong转成正确的汉字编码？
> * 这两个字是不是你从别的PDF复制粘贴过来的？复制过来的文档可能嵌入了错误信息。

尝试了您的例子，生成如下结果
![结果](https://user-images.githubusercontent.com/49770925/70447575-e32faf80-1ad9-11ea-970a-df3f6b97ac74.png)
我是通过输入法输入的，尝试了您说的「从别的PDF复制粘贴过来」，成功了，应该是输入法的问题，看来我该换输入法了...

**Comment by sikouhjw** [comment]
> 请试一试以下这个例子：
> 
> ```
> \ documentclass { ctexbeamer }
>  \ begin { document }
> 	 \ begin { frame }
> 		 \ char “ 8BFB \ char ” 2FB3 \ char “ 3001 \ char ” 2F64 \ char “ 4E8E ％
> 		
> 		\ char “ 8BFB \ char ” 97F3 \ char “ 3001 \ char ” 7528 \ char “ 4E8E ％
> 	 \ end { frame }
>  \ end { document }
> ```
> 
> 应该是字体内部把「康熙字典部首」随意做得跟正常汉字不一样，所以输出的时候就有个第一行的「⾳」与「物件」其实不是汉字，而是「康熙字典部首」。明显的问题。
> 
> 第二行的「音」于「用」是货真价实的汉字，所以应该不会出现「大小，深浅不一」的问题了。
> 
> 问题来源：
> 
> * 是不是你使用的输入法有问题？是不是输入法不能正确地将yin与yong转成正确的汉字编码？
> * 这两个字是不是你从别的PDF复制粘贴过来的？复制过来的文档可能嵌入了错误信息。

尝试了您的例子，生成如下结果
![结果](https://user-images.githubusercontent.com/49770925/70447575-e32faf80-1ad9-11ea-970a-df3f6b97ac74.png)
我是通过输入法输入的，尝试了您说的「从别的PDF复制粘贴过来」，成功了，应该是输入法的问题，看来我该换输入法了...
