### ISSUE TITLE
使用 ctexbeamer 时碰到的问题

### ISSUE THREAD

**Issue by OsbertWang** [CTeX-org/forum#70]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x] Linux

- TeX 发行版
  - [x] TeX Live  2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

win 10 下面使用 wsl，装的系统是 ubuntu 18.04，在使用 `ctexbeamer` 时，系统提示我
```
! LaTeX Error: Command `\acute' already defined.
```
后来我重新在 win 10 里面编译了一下，没有复现问题。
P.S. 两套系统中 texlive 均从清华镜像升级到最新版本。

## 最小工作示例（MWE）

```latex
\documentclass{ctexbeamer}
\usepackage{zhlipsum}
\listfiles
\begin{document}
  \begin{frame}
    \zhlipsum[1]
  \end{frame}
\end{document}
```
用 XeLaTeX 编译后产生的 log 文件，我放附件吧。
这里分别上传了在 WSL 和 win 中的 log 文件。
[win.log](https://github.com/CTeX-org/forum/files/3932917/win.log)
[wsl.log](https://github.com/CTeX-org/forum/files/3932918/wsl.log)

**Comment by muzimuzhi** [comment]
在 QQ 群沟通后，问题已解决
 - 突破点：日志显示，win 和 wsl 上的 latex2e 版本不同
 - 解决方式：重新生成 fmt 文件，例如在 wsl 上执行 `tlmgr install --reinstall latex`
 - 补充描述：wsl 上，tlmgr package latex、`latex.ltx` 都是最新版本，但 fmt 文件不是。报错信息就是由旧版本 latex2e + 新版本文档类和宏包混用导致的。

**Comment by OsbertWang** [comment]
解决方法记录一下。
从 log 文件中能够看出来 latex2e 的版本不对。最终证明 fmt 没重新生成。
在慕子帮助下，经过以下步骤解决问题。
执行
```
tlmgr option formats
```
发现结果显示
```
Create formats on installation (formats): 1
```
这说明系统允许自动重建。
再执行
```
kpsewhich latex.ltx
```
找到文件，查看 `latex.ltx` 中的内容，发现存在
```
\edef\fmtversion
   {2019-10-01}
```
这与我上面提供的 `wsl.log` 中的内容不符。
这时执行
```
fmtutil-user --byfmt xelatex
```
之后问题得到解决。
最终执行
```
sudo tlmgr install —reinstall latex
```
时发现有重新生成 fmt 的过程。
```
running fmtutil-sys --no-error-if-no-engine=luahbtex,luajittex,mfluajit --no-error-if-no-format --byengine luatex ...
done running fmtutil-sys --no-error-if-no-engine=luahbtex,luajittex,mfluajit --no-error-if-no-format --byengine luatex.
running fmtutil-sys --no-error-if-no-engine=luahbtex,luajittex,mfluajit --no-error-if-no-format --byengine pdftex ...
done running fmtutil-sys --no-error-if-no-engine=luahbtex,luajittex,mfluajit --no-error-if-no-format --byengine pdftex.
```

**Comment by OsbertWang** [comment]
今早来单位电脑里面看了一下，发现单位电脑中的 WSL 无此问题。
目前在单位电脑和个人电脑中的不同包括 texlive 的安装位置。
单位电脑中，我将安装位置移到了 `/mnt/d/texlive-wsl`，而个人电脑中，安装位置是默认的。
或许还是权限造成了这个问题，未来我再多关注一下升级时带来的权限影响吧。
