### ISSUE TITLE
texdoc doesn't work and returns error

### ISSUE THREAD

**Issue by muyuuuu** [CTeX-org/forum#71]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x] Linux

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

### 问题情况
命令行中输入`texdoc`报错，错误信息如下：

```bash
>>>texdoc ctex
texdoc error: No texlive.tlpdb nor shipped tlpdb data found.
```

但是`ctex.pdf`文件在电脑内是有的，首先`find`查找文件，`cd`过去然后可以打开，情况如下：

![2019-12-06 23-56-37屏幕截图](https://user-images.githubusercontent.com/43681138/70337595-5e992300-1886-11ea-91ed-f2aa9df24980.png)
![2019-12-06 23-57-38屏幕截图](https://user-images.githubusercontent.com/43681138/70337601-648f0400-1886-11ea-8209-a5ccf50a6426.png)

## 我尝试过的

https://github.com/clearlinux/distribution/issues/968
https://trac.macports.org/ticket/58615
https://bbs.archlinux.org/viewtopic.php?id=241012    (猜测与问题无关)
https://bugs.archlinux.org/task/60013   (猜测与问题无关)

## 结果

毫无进展.png

**Comment by muyuuuu** [comment]
## 补充信息：（斗胆截图了）

Texlive2019版本

![2019-12-07 13-40-21屏幕截图](https://user-images.githubusercontent.com/43681138/70369627-870d3580-18f7-11ea-847c-fbca9f132869.png)

texdoc版本 

![2019-12-07 13-41-14屏幕截图](https://user-images.githubusercontent.com/43681138/70369631-8f657080-18f7-11ea-9348-a1ce7c889018.png)

linux发行版版本

![2019-12-07 13-42-34屏幕截图](https://user-images.githubusercontent.com/43681138/70369634-968c7e80-18f7-11ea-9525-7f3a2b52f391.png)

**Comment by Liam0205** [comment]
后来问题解决了么？

**Comment by muyuuuu** [comment]
> 后来问题解决了么？

没有解决，之后重装了`telive2020`也并没有遇到此类问题。

**Comment by Liam0205** [comment]
https://tex.stackexchange.com/questions/541075/what-is-texlive-tlpdb-and-how-to-fix-its-missing

提了个问。

**Comment by muyuuuu** [comment]
看到了，但我没有 50 reputation 去在后面追加评论。。。。

**Comment by stone-zeng** [comment]
> 看到了，但我没有 50 reputation 去在后面追加评论。。。。

你再去一个 community 就有 100 了

**Comment by muyuuuu** [comment]
引用一个回答：https://wenda.latexstudio.net/q-1528.html

我已经换了电脑和系统，实在无法验证答案是否正确，抱歉。但按回答者的描述应该可以。
