### ISSUE TITLE
Alpine Linux 上出现字符重叠的问题

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/forum#73]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ ] Windows 7/8/10
  - [ ] macOS
  - [x] Alpine Linux 3.10

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

使用 Source Code Pro 字体时，字符出现重叠。此外默认载入的字重为 SemiBold 而非 Regular。

## 最小工作示例（MWE）

```latex
\documentclass[fancyhdr,bookmark]{ctexbook}
\usepackage{verbatim}
\setmainfont[]{Source Serif Pro}
\setsansfont[]{Source Sans Pro}
\setmonofont[]{Source Code Pro}

\begin{document}
\begin{verbatim}
I like several of their flavors of ice cream:
#22, for example, and #5.
\end{verbatim}
\end{document}
```

用 XeLaTeX 编译后得到：

![image](https://user-images.githubusercontent.com/18233088/71303275-7679b680-23f1-11ea-8c15-9d9986bfe802.png)

## 有关信息

版本：

![image](https://user-images.githubusercontent.com/18233088/71303296-da9c7a80-23f1-11ea-92bb-36ba99751432.png)

字体：

![image](https://user-images.githubusercontent.com/18233088/71303301-df612e80-23f1-11ea-907c-a3f58ed7cd75.png)

## 链接

- TeX.SX:
- GitHub:

**Comment by muzimuzhi** [comment]
怀疑和字体文件有关。如果有出错时的 log 和字体文件，会比较好。

**Comment by annProg** [comment]
解决了，是字体文件的问题，alpine texlive 2019中  Source Code Pro 版本较低
```
# fc-query -f '%{fontversion}\n' ./SourceCodePro-Regular.otf  | perl -E 'printf "%.3f\n", <>/65536.0'
2.010
```

删除自带字体，使用 alpine 3.11 ， 安装 `font-adobe-source-code-pro` ， 这个包是 `2.030` 版本
