### ISSUE TITLE
如何在circuitikz中输入分式？

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#74]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

我想在`circuitikz`环境中输入分式，但是没成功，`MWE`是我的尝试，来源见下面的链接

## 最小工作示例（MWE）

```latex
\documentclass{article}
\usepackage[siunitx,RPvoltages]{circuitikz}
\begin{document}
\SI[quotient-mode=fraction]{3/4}{\meter/\second}
\begin{circuitikz}[european]
	\draw (0,0) to[R,R=\SI[quotient-mode=fraction]{3/4}{\ohm}] (0,2);
\end{circuitikz}
\end{document}
```

（用 XeLaTeX 编译后）第一个报错为

```latex
Package tikz: (, +, coordinate, pic, or node expected.
```
第二个报错为
```latex
Package pgf: No shape named  is known.
```

## 链接

- TeX.SX:https://tex.stackexchange.com/questions/348836/print-frac43-m-s-using-the-si-unit-package

**Comment by muzimuzhi** [comment]
应该是和内部展开顺序有关。还没有搞明白 why 的部分。

如果需要在 circuitikz 中输入的公式不多，可以试试下面的「先展开并储存、再使用」的历史办法。
```tex
\documentclass{article}
\usepackage[siunitx,RPvoltages]{circuitikz}
\begin{document}
\SI[quotient-mode=fraction]{3/4}{\meter/\second}

\edef\xSI{\SI[quotient-mode=fraction]{3/4}{\ohm}}
\begin{circuitikz}[european]
	\draw (0,0) to[R, R={\xSI}] (0,2);
\end{circuitikz}
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/71309235-8bca0180-2440-11ea-835a-a699670cb7b3.png)

**Comment by muzimuzhi** [comment]
根据 `texdoc circuitikz`, sec. 4.9，下面的用法能通过编译，个人更为推荐。

```tex
\documentclass{article}
\usepackage[siunitx,RPvoltages]{circuitikz}

\begin{document}
\sisetup{quotient-mode=fraction}
\begin{circuitikz}[european]
	\draw (0,0) to[R, R=$\SI{3/4}{\ohm}$] (0,2);
\end{circuitikz}
\end{document}
```

如果把 `R=$\SI{3/4}{\ohm}$` 改成 `R=$\SI[]{3/4}{\ohm}$`，错误复现。

------
`\SI` 是使用 xparse 宏包提供的命令定义的，它的可选参数接受的是配对的中括号（见 `texdoc xparse`, sec. 1 后半段），而 pgfkeys 宏包的可选参数不检测中括号是否匹配。可能和这一处有关。

**Comment by muzimuzhi** [comment]
下面的两种用法都能通过编译。

```tex
\documentclass{article}
\usepackage[siunitx,RPvoltages]{circuitikz}

\begin{document}
% 方法1：通过 \sisetup 进行设置，在 circuitikz 环境内的 \SI 避免使用可选参数
% 参考 `texdoc circuitikz`, sec. 4.9
\sisetup{quotient-mode=fraction}
\begin{circuitikz}[european]
	\draw (0,0) to[R, R=\SI{3/4}{\ohm}] (0,2);
\end{circuitikz}

% 方法2：允许 circuitikz 环境内的 \SI 使用可选参数，但增加两组额外的大括号来避免解析错误
% 额外大括号的增加位置：第一组，R={...}；第二组，\SI[{...}]{<num>}{<unit>}
\begin{circuitikz}[european]
	\draw (0,0) to[R, R={\SI[{quotient-mode=fraction,number-unit-product=\quad}]{1234/4}{\ohm}}] (0,2);
\end{circuitikz}
\end{document}
```

**Comment by muzimuzhi** [comment]
「为什么」的部分

第一组大括号：可选参数的结束标记，是第一个 `]`，而不是配对的 `]`。于是输入 `[R, R=...[...]...]` 会被解析为 `[R, R=...[...]<end of opt arg>...]`。增加一组大括号后，`[R, R={...[...]...}]` 匹配正常。

第二组大括号：circuitikz 使用的是 pdfkeys 宏包提供的 key-value 功能。pgfkeys 接受的参数列表 `<key1>=<value1>, <key2>=<value2>, ...` 的 `<value n>` 部分不能包含逗号或等号 [1]。

输入的可选参数 `R={<value>}` 中的 `<value>`，经过几次传递 [2]，最终会传给 `<key path>/name=<value>`。因为示例中的 `<value>` 为 `\SI[quotient-mode=fraction]{1234/4}{\ohm}`，包含等号，所以会导致被解析为 `<key path>/name=\SI[quotient-mode<end of value>=fraction]{1234/4}{\ohm}`。增加一组大括号后，`R={\SI[{...}]{...}{...}}` 匹配正常。

------

[1] 相关文档

> Especially putting the <value> in curly braces needs to be done quite often, namely whenever the <value> contains an equal-sign or a comma.
> texdoc tikz, sec. 87.3

[2] 相关定义是
```tex
% pgfcircpath.tex:662
\compattikzset{R/.style= {\comnpatname resistor = #1}}

% pgfcircpath.tex:367
\compattikzset{resistor/.style= {\circuitikzbasekey, /tikz/to path=\pgf@circ@resistor@path, l=#1}}

% pgfcirclabel.tex:32
\ctikzset{l/.code = {
    \pgfkeys{/tikz/circuitikz/bipole/label/name=#1}
    \ctikzsetvalof{bipole/label/unit}{}
    \ifpgf@circ@siunitx
        \pgf@circ@handleSI{#1}
        \ifpgf@circ@siunitx@res
            \edef\pgf@temp{\pgf@circ@handleSI@val}
            \pgfkeyslet{/tikz/circuitikz/bipole/label/name}{\pgf@temp}
            \edef\pgf@temp{\pgf@circ@handleSI@unit}
            \pgfkeyslet{/tikz/circuitikz/bipole/label/unit}{\pgf@temp}
        \else
        \fi
    \else
    \fi
}}
```
提问例子中，导致报错的例子可以简化为
```tex
\pgfkeys{/tikz/circuitikz/bipole/label/name=\SI[quotient-mode=fraction]{3/4}{\ohm}}
\ctikzvalof{bipole/label/name}
```

**Comment by sikouhjw** [comment]
> 
> 
> 下面的两种用法都能通过编译。
> 
> ```
> \documentclass{article}
> \usepackage[siunitx,RPvoltages]{circuitikz}
> 
> \begin{document}
> % 方法1：通过 \sisetup 进行设置，在 circuitikz 环境内的 \SI 避免使用可选参数
> % 参考 `texdoc circuitikz`, sec. 4.9
> \sisetup{quotient-mode=fraction}
> \begin{circuitikz}[european]
> 	\draw (0,0) to[R, R=\SI{3/4}{\ohm}] (0,2);
> \end{circuitikz}
> 
> % 方法2：允许 circuitikz 环境内的 \SI 使用可选参数，但增加两组额外的大括号来避免解析错误
> % 额外大括号的增加位置：第一组，R={...}；第二组，\SI[{...}]{<num>}{<unit>}
> \begin{circuitikz}[european]
> 	\draw (0,0) to[R, R={\SI[{quotient-mode=fraction,number-unit-product=\quad}]{1234/4}{\ohm}}] (0,2);
> \end{circuitikz}
> \end{document}
> ```

感谢！
