### ISSUE TITLE
修改标题字体

### ISSUE THREAD

**Issue by hui9611** [CTeX-org/forum#77]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

希望将标题的字体调大，谢谢

## 最小工作示例（MWE）

```tex
\documentclass[serif ]{beamer}
\usepackage[UTF8,noindent]{ctexcap}
\usepackage{amsmath}
\usetheme{AnnArbor}%%%可以更换主题AnnArbor.CambridgeUS，等

\usecolortheme{crane}
\usepackage{multirow}
\usepackage{graphicx}

\title{不要强求不可知}%标题
\author{ 小明}
\institute{XX中学\\高一竞赛组}
\date{\scriptsize {\today}}

\begin{document}
%%标题页
  %\frame{\titlepage}  
\begin{frame}
     \titlepage
  \end{frame}
%%目录页
  \begin{frame}\frametitle{目录}
  	\tableofcontents[hideallsubsections]%[part=1,pausesections]
  \end{frame}
 \end{document}
```

## 链接

- TeX.SX:
- GitHub:

**Comment by stone-zeng** [comment]
如下图，使用 `\setbeamerfont*{<beamer-font name>}{<attributes>}` 命令设置：

![image](https://user-images.githubusercontent.com/18233088/71369825-e69d5d80-25e6-11ea-8190-1d31c762835f.png)

参考 Beamer User Guide 18.3.3 小节（`texdoc beamer`）。

**Comment by hui9611** [comment]
think you very much&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiangdong Zeng"<notifications@github.com&gt;; 
发送时间: 2019年12月24日(星期二) 凌晨0:49
收件人: "CTeX-org/forum"<forum@noreply.github.com&gt;; 
抄送: "辉"<1005254597@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [CTeX-org/forum] 修改标题字体 (#77)




如下图，使用 \setbeamerfont*{<beamer-font name&gt;}{<attributes&gt;} 命令设置：
 

 
参考 Beamer User Guide 18.3.3 小节（texdoc beamer）。
