### ISSUE TITLE
论文没有第二导师，如何删除这多余的一行

### ISSUE THREAD

**Issue by yangimp** [CTeX-org/forum#78]

**Comment by zepinglee** [comment]
能不能加个 label 叫“bad issue”

**Comment by yangimp** [comment]
老师，
&nbsp; &nbsp; &nbsp; 您好。虽然我也知道这个问题可能很简单，但我通过删除Advisors这一行之后，编译出来的pdf仍然有，所以才想到去求助，但没想到被泼了冷水。我也用过LaTex写过四篇文章，也有一定经验，所以想着用LaTex去写大论文，这样排版肯定是比word更好，质量更高。我感谢你们的努力，让国科大的LaTeX成为可能，方便广大学子。但对于每一个问题，有困难有简单，对你所说的bad
issue实在不敢苟同。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Zeping Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月23日(星期一) 晚上11:33
收件人:&nbsp;"CTeX-org/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"杨尧"<664063429@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [CTeX-org/forum] 论文没有第二导师，如何删除这多余的一行 (#78)




能不能加个 label 叫“bad issue”

**Comment by zepinglee** [comment]
> 老师， &nbsp; &nbsp; &nbsp; 您好。虽然我也知道这个问题可能很简单，但我通过删除Advisors这一行之后，编译出来的pdf仍然有，所以才想到去求助，但没想到被泼了冷水。我也用过LaTex写过四篇文章，也有一定经验，所以想着用LaTex去写大论文，这样排版肯定是比word更好，质量更高。我感谢你们的努力，让国科大的LaTeX成为可能，方便广大学子。但对于每一个问题，有困难有简单，对你所说的bad issue实在不敢苟同。
> […](#)

1. 国科大的模板应该去 [mohuangrui/ucasthesis](https://github.com/mohuangrui/ucasthesis) 提问；
2. 在 CTeX-org/forum 问“论文没有第二导师，如何删除这多余的一行”，你期待别人从这句话里读懂什么？
2. “LaTeX” 的拼写注意大小写。

**Comment by Liam0205** [comment]
@yangimp 

你没有理解 @zepinglee 的意思。bad issue 不是说你的问题不重要或者太简单了，而是说你这个问题本身没有提好。

「论文没有第二导师，如何删除这多余的一行」你回过头来看看你这个标题。如果你是一个完全跟你的陌生人，跟你唯一的共同点是「都会用 LaTeX」。你看到这个标题，你是什么感受？

信息缺少太多了，以至于根本不构成一个可以回答的问题。所以 invalid。

**Comment by stone-zeng** [comment]
除非知道自己在干什么，否则请不要无视提问模板。

**Comment by yangimp** [comment]
好的，谢谢，是我没有注意规范，抱歉添堵了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Liam Huang"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月25日(星期三) 下午3:30
收件人:&nbsp;"CTeX-org/forum"<forum@noreply.github.com&gt;;
抄送:&nbsp;"杨尧"<664063429@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [CTeX-org/forum] 论文没有第二导师，如何删除这多余的一行 (#78)




@yangimp
 
你没有理解 @zepinglee 的意思。bad issue 不是说你的问题不重要或者太简单了，而是说你这个问题本身没有提好。
 
「论文没有第二导师，如何删除这多余的一行」你回过头来看看你这个标题。如果你是一个完全跟你的陌生人，跟你唯一的共同点是「都会用 LaTeX」。你看到这个标题，你是什么感受？
 
信息缺少太多了，以至于根本不构成一个可以回答的问题。所以 invalid。

**Comment by RuixiZhang42** [comment]
@yangimp 看看这个有没有帮助：https://github.com/mohuangrui/ucasthesis/issues/206

**Comment by RuixiZhang42** [comment]
@yangimp 关于「如何提问」，请看
https://zhuanlan.zhihu.com/p/94837029
https://www.zhihu.com/question/312135358
