### ISSUE TITLE
加载newtxmath与ctex宏包，在matrix环境下使用\vec命令冲突

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#79]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2019（2019/11/28更新过所有宏包）
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

当`ctex`宏包在`newtxmath`宏包之前加载，并在`matrix`环境下使用`\vec`，会报错

## 最小工作示例（MWE）

```latex
\documentclass{article}
\usepackage{ctex}
\let\lvert\relax\let\rvert\relax\let\lVert\relax\let\rVert\relax
\usepackage{newtxmath}
\begin{document}
$\begin{matrix}
	\vec a
\end{matrix}$
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
Package amsmath: \vec allowed only in math mode.
```

调换顺序加载则可以编译

```latex
\documentclass{article}
\let\lvert\relax\let\rvert\relax\let\lVert\relax\let\rVert\relax
\usepackage{newtxmath}
\usepackage{ctex}
\begin{document}
$\begin{matrix}
	\vec a
\end{matrix}$
\end{document}
```

## 链接

- TeX.SX:
- GitHub:https://github.com/marquistj13/TongjiThesis/pull/27 （不知道相不相关）

**Comment by stone-zeng** [comment]
See <https://github.com/CTeX-org/ctex-kit/issues/470>.
