### ISSUE TITLE
TeX 的作用域、生存期、合法性问题

### ISSUE THREAD

**Issue by stone-zeng** [CTeX-org/forum#80]
> 原问题：https://wenda.latexstudio.net/q-1605.html

这是一个从我一开始接触这门语言就产生的问题。一般而言，基于厚积薄发原理，我们学习一门编程语言都会进行按如下顺序进行：

1. 先跑一个 `Hello World`，一方面是检验编译环境搭建好没，另一方面是感受该语言风格魅力；
1. 数据类型、变量合法性；
1. 基本语法；
1. 顺序、条件、循环；
1. 作用域、生存期；
1. 语言高级特性；
1. 语法糖；
1. ……

然而不幸的是，我最初接触 TeX 语言仅仅是直接套模板，根本没有也不需要考虑任何以上问题。然而这种知其然，却不知其所以然的学习方式极大地限制了我后期对它的控制能力。当我试图去高度定制化模板和接触更底层的命令时，我时常觉得举步维艰。**本文仅讨论 2 和 5 的疑惑。**

### 命令与环境

对于变量命名的合法性，在 Java 语言中

```java
int $a1 = 2;
```

定义了一个合法的变量 `$a_1`，在 TeX 语言中

```tex
\newcommand{\$a_1}{2}
```

却不能定义出一个合法的命令 `$a_1`，这是因为 `$` 和在数学环境中有特殊含义。如果 `\$a_1` 命令合法，那么 `$\$a_1$` 将会发生歧义。

另外 `\@` 在 TeX 中是一个合法的命令，但是却不能自定义出

```tex
\newcommand{\@a}{1}
\newcommand{\a@}{1}
```

这样的命令。那么这个@究竟是不是合法的命名符号？文档中大量形如 `\@xxx` 的命令是怎么来的？

### 标记

起初我以为 `\label{}` 和 `\bibitem{}` 的使用原理是，先在 `{}` 中命名一个新“变量”，例如 `\label{a}`、`\bibitem{b}`。然后在引用位置调用这个“变量”即可：`\ref{va}`、`\cite{b}`。

但事实是，这里面放的并不是一个“变量”，或者说，其命名规则与我们平常所理解的变量有所出入。因为它可以出现一些特殊符号，如 `\label{fig:a}`。更一般地，`\label{: +-*/}` 也是一个合法的标记名。

`\node{};` 的标记名 `xxx` 也有与上类似的命名法则。

## 作用域

有一些命令的作用域只是后面紧跟的 `{}`。例如

```tex
\section{变成sec的格式}
正文内容格式
```

有一些命令的作用域是这个命令所在的整个区域。例如数学环境中的 `\rm` 命令，其作用域包含于该命令所在的 `{}` 内。

```tex
$斜体 {斜体 \rm{正体} 正体} 斜体$
```

听群友说

> `\def` 出来的东西是局部有效的，但可以加 `\global` 修饰（或等价 `\gdef`）使他全局生效。

能否基于这类问题详细介绍一下作用域的控制与识别？

## 生存期

对 Python 来说

```python
for i in [1,2,3]:
    pass
```

退出循环后 `i` 的值仍存在；对 C++ 来说

```cpp
for(int i=0; i<3; i++);
```

退出循环后i被释放；那么对 TeX 来说

```tex
\foreach \i in {1,2,3}{}
```

退出循环后，编译器又会对 `\i` 如何处理呢？退出 `tikzpicture` 环境后呢？

上面列出列出的这些问题我只是举个例子，旨在**抛砖引玉**，希望能得到不囿于以上所述的、更精细的解答。

**Comment by OceanS2000** [comment]
TeX是一个宏语言，其语言模型与一般的编程语言有很大不同。如果需要详细了解的话，可以阅读TeX的作者 Kunth 所写的 The TeXBook 和 Victor Eijkhout 所写的 TeX By Topic，而关于LaTeX的工作原理，可以直接使用 `texdoc source2e` 查阅LaTeX的源代码。

以下我根据我的理解简单讲一讲，由于我也是刚开始了解 TeX 底层，其中的错漏之处还需要大家指出。

## 关于命名合法性
TeX 中，所有的字符在读入的时候都会被赋予一个「分类码」， TeX 中共有 16 种分类，LaTeX的默认分类码（也是大多数 TeX 格式的分类码）的部分安排如下：

| 分类码 | 解释 | LaTeX的默认设定 |
|-----|----|----|
| 0 | 宏名称开始 | `\` |
| 1 | 分组开始 | `{` |
| 2 | 分组结束 | `}` | 
| 10 | 空格 | ` ` |
| 11 | 普通字符 | `A-Z` `a-z` |
| 12 | 其他字符 | `@` `0-9` 以及所有不属于其他分类的字符 |
| 13 | 活动字符 | `~` |

一个合法的宏名字可以是
- 一个分类码为 0 的字符，后跟
  - 若干个分类码为 11 的字符，或
  - 一个分类码**不是** 11 的字符
- 单个分类码为 13 的字符

注意分类码是可以在 TeX 的输入文件中利用 `\catcode` 改变的。一般格式文件的开发者会把 `@` 的分类码设定为 11 （如果使用 LaTeX 的话，读取宏包文件 `.sty` `.cls` 时 LaTeX 默认就会这么做），这样在格式文件中就可以定义含有 `@` 的宏而不用担心会干扰使用者自己的命令定义。

### 标记
标记的定义原理是：在遇到 `\label` 的时候， LaTeX会把相应的 `\newlabel` 命令写入 `.aux` 文件中，后者会在下一次运行时被 LaTeX 读取。 `\newlabel` 的定义如下：
```
\def\@newl@bel#1#2#3{{%
  ... % 删去了一些错误检查方便理解
  \global\@namedef{#1@#2}{#3}}}
\def\newlabel{\@newl@bel r}
\@onlypreamble\@newl@bel
\def\@namedef#1{\expandafter\def\csname #1\endcsname}
```
可以看到， `\label{fig:1+-!}{Figure 1}` 最终成为了以下形式的宏定义 
```
\global\expandafter\def\csname r@fig1+-!\endcsname{Figure 1}
```
其中，`\expandafter`命令的作用在于指示 TeX 首先处理 `\csname r@fig1+-!\endcsname`， `\csname ...\endcsname`简单来说就是无视命名规则，把其中的字符串作为宏名字处理。这样为什么其中可以出现各种字符也就可以明了。

## 作用域
`\section` 和 `\rm` 的语义不同：`\section`是要把**其第一个参数做一些处理之后输出**；而`\rm`是**将当前字体设定为 roman 字体**，其修改的是 LaTeX 的运行状态。

> \def 出来的东西是局部有效的，但可以加 \global 修饰（或等价 \gdef）使他全局生效。
这里说的是宏定义的有效性。宏的定义也是一种对运行状态的修改，也受到同样分组规则的制约。如
```
\def\test{Outer}
{ \def\test{Inner} } 
\test
```
中第三行的 `\test` 会成为 `Outer`，因为第二行的定义此处已经无效。

## 生存期
TeX 中的宏没有生存期概念，也没有变量释放的概念。 

此处的 `\foreach` 是 TikZ 利用宏展开实现的， TikZ 的底层我不了解，其相關代码在 `/usr/local/texlive/2019/texmf-dist/tex/generic/pgf/utilities/pgffor.code.tex` 中。比较复杂，我就不乱讲了。

**Comment by muzimuzhi** [comment]
问到的点很多、特别宽泛，暂时放弃作逐一的、完整的回答。

使用 latex 时，一般是先把它当成标记语言来理解和使用的。这时，只需要知道标记应该怎么用、会产生什么效果，不怎么编写逻辑。如果到了需要详细了解如何在 (la)tex 中编写逻辑的阶段，
 - 原理方面可以阅读 `texdoc texbytopic` 和 _The TeXbook_，
 - 实践方面就是 latex2e kernel、工具宏包（如 `etoolbox`）和 latex3 相关的一些， https://zhuanlan.zhihu.com/p/42278823 指南部分的文章列出了不少资料。

学习编程语言，重点是学
 - 语言的语法、语义（对应 tex）
 - 语言的标准库（对应 latex2e kernel）和第三方库（对应各宏包）
 - 语言的最佳实践

命名规范只是其中很小的一部分。

### 命名合法性
1. tex 里没有「变量」，只有控制序列。在直接输入时，后者的定义是
    ```abnf
    control-sequence ::= escape-char non_letter-char | escape_char letter-char*
    escape-char      ::= "char with category code 0"
    letter-char      ::= "char with category code 11"
    non-letter-char  ::= "char with category code other than 11"
    ```
    默认值为
    ```abnf
    escape-char      ::= "backslash symbol"
    letter-char      ::= [a-zA-Z]
    ```
1. 形如 `\@a` 和 `\a@` 这样的控制序列，有两种获取方式：
 - 通过 `\csname @a\endcsname` 间接输入，在展开后得到 `\@a`。这么用时，经常需要手动控制展开顺序。
`\label{...}` 和 `\newenvironment{...}` 内部都是 `\csname ...\endcsname`，所以看起来拥有了更宽松的合法命名范围
 - 通过 `\catcode` 修改符号的 category code，然后直接输入。例如 ``\catcode`\@=11 \def\@a{...}``。
latex2e kernel 约定以命名中包含 `@` 的为内部控制序列，并提供了 `\makeatletter` 和 `\makeatother`，以简化操作「把 `@` 的 category code 改为 letter、再改回去」。

### 作用域
1. 作用域大致指「各类绑定（binding）的有效范围」。对通用编程语言来说，绑定可能是变量、函数、类型等；对 tex 来说，绑定主要指宏和寄存器。在 tex 里，作用域和生存期是一回事。
    1. 宏（macro）在 tex 里通过 `\def` 家族和 `\let` 绑定，latex2e 提供了 `\newcommand` 家族
    1. 寄存器（registor）在 latex2e 里基本不直接接触，略过
    1. tex 提供的唯一数据结构是 token list，定义新 token list 也是一种绑定。
1. tex 里控制作用域的唯一方式是分组（grouping），普通情况是，局部绑定在当前分组在当前分组结束后失效。`\global` 用于让某个绑定变成全局的。
1. 一个能完整展开的最小 latex 输入单元（例如 `\section{...}` 和 `\label{...}`），可能有两种作用：进行输出和改变状态。
 - `\section{...}` 是进行输出的，它还会改变计数器 section（对应寄存器 `\c@section`）的状态。
 - `\rm` 不进行输出，只改变状态，即修改当前字体。这个状态是储存在宏里的，于是受到分组的影响
 - `\foreach` 是宏包 `pgffor` 提供的，参考 `texdoc tikz`, sec. 89。

**Comment by zepinglee** [comment]
我觉得更应该去考虑怎么淘汰掉 TeX 的语言

**Comment by muzimuzhi** [comment]
长时间无新回复，暂时关闭。
