### ISSUE TITLE
如何在*.bib文件中添加样式为国家标准的参考文献

### ISSUE THREAD

**Issue by SerendipitousAurorae** [CTeX-org/forum#81]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题
请教各位大佬，想在bibtex中添加国标形式的参考文献应该怎么设置和书写呢？例如：
[1] GB/T 7714-2015,文后参考文献著录规则[S].
[2] JB/T 623-2005,集装箱吊具[S].北京:人民交通出版社出版,2005. 
这样的参考文献，怎么编辑bibtex？
谢谢！

**Comment by miRoox** [comment]
你需要的可能是 [gbt7714](https://ctan.org/pkg/gbt7714) 或者 [biblatex-gb7714-2015](https://ctan.org/pkg/biblatex-gb7714-2015).

**Comment by SerendipitousAurorae** [comment]
> 你需要的可能是 gbt7714 或者 biblatex-gb7714-2015.

请问您指的是是添加宏包吗？有没有代码示例参考一下呢？

**Comment by stone-zeng** [comment]
`.bib` 文件只负责提供数据，不处理样式。然后，

- 如果你用的是 BibTeX 的流程，那么请用 `gbt7714` 宏包；
- 如果你用的是 biber+`biblatex` 的流程，那么请给 `biblatex` 宏包加上 `style=gb7714-2015` 选项（或者类似的东西）；
- 如果你不知道我在说啥，那么请阅读 [`lshort-zh-cn`](http://mirrors.ctan.org/info/lshort/chinese/lshort-zh-cn.pdf)。

**Comment by SerendipitousAurorae** [comment]
> .bib 文件只负责提供数据，不处理样式。然后，
> 
> 如果你用的是 BibTeX 的流程，那么请用 gbt7714 宏包；
> 如果你用的是 biber+biblatex 的流程，那么请给 biblatex 宏包加上 style=gb7714-2015 选项（或者类似的东西）；
> 如果你不知道我在说啥，那么请阅读 lshort-zh-cn。

您好，在阅读了帮助文档后我仍有以下问题：

- 在*.bib文件中，使用
`@article{xxx,...
}%`
可以得到，`xxx[J]. `的参考文献。
如何能得到`[S]`为后缀的参考文献呢？

**Comment by stone-zeng** [comment]
你显然没有看全：

![image](https://user-images.githubusercontent.com/18233088/71544560-1cae5900-29bc-11ea-9151-dea7363167a9.png)

**Comment by SerendipitousAurorae** [comment]
> 你显然没有看全：
明白了，看见了
[CTAN://biblio/bibtex/base/btxdoc.pdf](url)
多谢指点！
