### ISSUE TITLE
目录共2页，第一页的页眉用 \thispagestyle{noheaderstyle} 去不掉，特求帮助

### ISSUE THREAD

**Issue by wqb-123** [CTeX-org/forum#82]
## 检查

- [ x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x ] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [ ] TeX Live 
  - [ x] MiKTeX 
  - [ ] CTeX

## 最小工作示例（MWE）

```latex
\documentclass[twoside]{Style/ucasthesis}%
%- Multiple optional arguments:
%- [<oneside|twoside|print>]% oneside eprint, twoside eprint, or paper print
%- [fontset=<adobe|...>]% specify font set to replace automatic detection
%- [scheme=plain]% thesis writing of international students
%- [draftversion]% show draft version information
%- [standard options for ctex book class: draft|paper size|font size|...]%
%---------------------------------------------------------------------------%
%->> Document settings
%---------------------------------------------------------------------------%
\usepackage[authoryear,list]{Style/artratex}% document settings
%- usage: \usepackage[option1,option2,...,optionN]{artratex}
%- Multiple optional arguments:
%- [bibtex|biber]% set bibliography processor and package
%- [<numbers|super|authoryear|alpha>]% set citation and reference style
%- <numbers>: textual: Jones [1]; parenthetical: [1]
%- <super>: textual: Jones superscript [1]; parenthetical: superscript [1]
%- <authoryear>: textual: Jones (1995); parenthetical: (Jones, 1995)
%- <alpha>: textual: not available; parenthetical: [Jon95]
%- [geometry]% reconfigure page layout via geometry package
%- [lscape]% provide landscape layout environment
%- [xhf]% disable header and footer via fancyhdr package
%- [color]% provide color support via xcolor package
%- [background]% enable page background
%- [tikz]% provide complex diagrams via tikz package
%- [table]% provide complex tables via ctable package
%- [list]% provide enhanced list environments for algorithm and coding
%- [math]% enable some extra math packages
%- [xlink]% disable link colors
\usepackage{Style/artracom}% user defined commands
%---------------------------------------------------------------------------%
%->> Document inclusion
%---------------------------------------------------------------------------%
%\includeonly{Tex/Chap_1,...,Tex/Chap_N}% selected files compilation
%---------------------------------------------------------------------------%
%->> Document content
%---------------------------------------------------------------------------%
%-
%-> Titlepage information
%-
\input{Tex/Frontinfo}%
\begin{document}
%-
%-> Frontmatter: title page, abstract, content list, symbol list, preface
%-
\frontmatter% initialize the environment
\input{Tex/Frontmatter}% title page, abstract
{% content list region
\linespread{1.2}% local line space
\intobmk*{\cleardoublepage}{\contentsname}% add link to bookmark
\thispagestyle{noheaderstyle}% 如果需要移除当前页的页眉
\tableofcontents% content catalog
%
\intobmk*{\cleardoublepage}{\listfigurename}% add link to bookmark
\thispagestyle{noheaderstyle}% 如果需要移除当前页的页眉
\listoffigures% figure catalog
%
\intobmk*{\cleardoublepage}{\listtablename}% add link to bookmark
\thispagestyle{noheaderstyle}% 如果需要移除当前页的页眉
\listoftables% table catalog
}
%\thispagestyle{noheaderstyle}% 如果需要移除当前页的页眉
%\pagestyle{noheaderstyle}% 如果需要移除整章的页眉
\input{Tex/Prematter}% symbol list, preface content
%-
%-> Mainmatter
%-
\mainmatter% initialize the environment
\input{Tex/Mainmatter}% main content
%-
%-> Appendix
%-
\cleardoublepage%
\appendix% initialize the environment
\input{Tex/Appendix}% appendix content
%-
%-> Backmatter: bibliography, glossary, index
%-
\backmatter% initialize the environment
\intotoc*{\cleardoublepage}{\bibname}% add link to toc
\bibliography{Biblio/ref}% bibliography
\input{Tex/Backmatter}% other information
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
                                         目录
-------------------------------------------------------------------
```

**Comment by wqb-123** [comment]
## 描述问题
    1. 描述出现的情况
我的目录有2页，想去掉第一页的页眉，同时保留第二页的页眉。我把代码
\thispagestyle{noheaderstyle}
加到 Thesis.tex 中，如下
\intobmk*{\cleardoublepage}{\contentsname}% add link to bookmark
\thispagestyle{noheaderstyle}% 如果需要移除当前页的页眉
\tableofcontents% content catalog
但是，目录第一页的页眉还存在。

    2. 给出复现步骤
复现只需要两步。
在模板中，第一步是在 Chap_Intro.tex 中把 \section{研究背景} 复制 4 次，得
\section{研究背景}
\section{研究背景}
\section{研究背景}
\section{研究背景}
\section{研究背景}

运行后，可以看到目录页变成 2 页了。

第二步是在 Thesis.tex 中添加 \thispagestyle{noheaderstyle}， 如下
\intobmk*{\cleardoublepage}{\contentsname}% add link to bookmark
\thispagestyle{noheaderstyle}% 如果需要移除当前页的页眉
\tableofcontents% content catalog

运行后会发现目录页的第一页仍然有页眉。

    3. 给出您解决问题所进行的尝试
尝试一： 把 \thispagestyle{noheaderstyle} 往下移动一行，即
\intobmk*{\cleardoublepage}{\contentsname}% add link to bookmark
\tableofcontents% content catalog
\thispagestyle{noheaderstyle}% 如果需要移除当前页的页眉

运行后发现，目录部分第一页的页眉仍然存在，但第二页的页眉消失不见了。这与我期望的结果正好相反。

尝试二：在 artratex.sty 中发现了一段说明：
    %- Some Latex commands, like \chapter, use the \thispagestyle command
    %- to automatically switch to the plain page style, thus ignoring the
    %- page style currently in effect. To customize such pages you must
    %- redefine the plain pagestyle. If you want the plain style inherits
    %- the current style, comment all the lines in plain style definition.
感觉  \thispagestyle{noheaderstyle} 再 \chapter 后面使用的时候才有用，在目录部分使用时不起作用。烦请帮忙指点一下目录页第一页的页眉去除办法，谢谢啦。

**Comment by OsbertWang** [comment]
你使用的是 [国科大学位论文模板](https://github.com/mohuangrui/ucasthesis) 吗？
你是打算只让目录的首页不显示页眉，还是所有章标题的首页也不显示页眉？

**Comment by muzimuzhi** [comment]
### 问题分析

因为
 - `\tableofcontents` 的内部包含一个 `\chapter*` 命令（模板 ucasthesis 继承了 ctexbook 文档类），用于输出目录部分的标题（\listoffigures` 和 `\listoftables` 的情况与此相同）
 - `\chapter*` 内部会调用 `\thispagestyle{plain}`

所以，输入
```tex
\thispagestyle{noheaderstyle}
\tableofcontents
```
相当于
```tex
\thispagestyle{noheaderstyle}
\thispagestyle{plain}
<title of toc>
<contents of toc>
```
`\thispagestyle{noheaderstyle}` 的效果被后面的 `\thispagestyle{plain}` 覆盖了，所以页眉仍然显示。

### 解决方案
因为有定义
```tex
% book.cls, line 588:
\newcommand\tableofcontents{%
    \if@twocolumn
      \@restonecoltrue\onecolumn
    \else
      \@restonecolfalse
    \fi
    \chapter*{\contentsname
        \@mkboth{%
           \MakeUppercase\contentsname}{\MakeUppercase\contentsname}}%
    \@starttoc{toc}%
    \if@restonecol\twocolumn\fi
    }
% latex.ltx, line 6225:
\def\@starttoc#1{%
  \begingroup
    \makeatletter
    \@input{\jobname.#1}%
    \if@filesw
      \expandafter\newwrite\csname tf@#1\endcsname
      \immediate\openout \csname tf@#1\endcsname \jobname.#1\relax
    \fi
    \@nobreakfalse
  \endgroup}
```
考虑向 `\@starttoc` 插入 `\thispagestyle{...}`，见下方示例
```tex
\documentclass[twoside]{Style/ucasthesis}
\usepackage[authoryear,list]{Style/artratex}
\usepackage{Style/artracom}
\input{Tex/Frontinfo}

\makeatletter
\patchcmd\@starttoc
  {\begingroup}
  {\thispagestyle{noheaderstyle}\begingroup}
  {}{\fail}
\makeatother

\begin{document}
\frontmatter
\tableofcontents
\listoffigures
\listoftables
\end{document}
```

**Comment by wqb-123** [comment]
@OsbertWang 我用的模板是您指出的 国科大学位论文模板。我想去掉目录和各章的首页页眉，这样这些首页更简洁。我模仿致谢部分\thispagestyle的用法，成功去掉了各章首页的页眉。

**Comment by wqb-123** [comment]
@muzimuzhi 谢谢您的指点，目录部分首页的页眉成功去掉了

**Comment by muzimuzhi** [comment]
> 我用的模板是您指出的 国科大学位论文模板。我想去掉目录和各章的首页页眉，这样这些首页更简洁。

如果是这样的需求，应该统一修改 `\chapter` 所在页面的 page style，而不是每一处都手动操作。例如通过
```tex
\ctexset{
  chapter/pagestyle = noheaderstyle
}
```

另外，如在撰写学位论文，需注意遵从校方的样式规定。

**Comment by mohuangrui** [comment]
> ### 问题分析
> 
> 因为
> 
>     * `\tableofcontents` 的内部包含一个 `\chapter*` 命令（模板 ucasthesis 继承了 ctexbook 文档类），用于输出目录部分的标题（\listoffigures`和`\listoftables` 的情况与此相同）
> 
>     * `\chapter*` 内部会调用 `\thispagestyle{plain}`
> 
> 
> 所以，输入
> 
> ```
> \thispagestyle{noheaderstyle}
> \tableofcontents
> ```
> 
> 相当于
> 
> ```
> \thispagestyle{noheaderstyle}
> \thispagestyle{plain}
> <title of toc>
> <contents of toc>
> ```
> 
> `\thispagestyle{noheaderstyle}` 的效果被后面的 `\thispagestyle{plain}` 覆盖了，所以页眉仍然显示。
> ### 解决方案
> 
> 因为有定义
> 
> ```
> % book.cls, line 588:
> \newcommand\tableofcontents{%
>     \if@twocolumn
>       \@restonecoltrue\onecolumn
>     \else
>       \@restonecolfalse
>     \fi
>     \chapter*{\contentsname
>         \@mkboth{%
>            \MakeUppercase\contentsname}{\MakeUppercase\contentsname}}%
>     \@starttoc{toc}%
>     \if@restonecol\twocolumn\fi
>     }
> % latex.ltx, line 6225:
> \def\@starttoc#1{%
>   \begingroup
>     \makeatletter
>     \@input{\jobname.#1}%
>     \if@filesw
>       \expandafter\newwrite\csname tf@#1\endcsname
>       \immediate\openout \csname tf@#1\endcsname \jobname.#1\relax
>     \fi
>     \@nobreakfalse
>   \endgroup}
> ```
> 
> 考虑向 `\@starttoc` 插入 `\thispagestyle{...}`，见下方示例
> 
> ```
> \documentclass[twoside]{Style/ucasthesis}
> \usepackage[authoryear,list]{Style/artratex}
> \usepackage{Style/artracom}
> \input{Tex/Frontinfo}
> 
> \makeatletter
> \patchcmd\@starttoc
>   {\begingroup}
>   {\thispagestyle{noheaderstyle}\begingroup}
>   {}{\fail}
> \makeatother
> 
> \begin{document}
> \frontmatter
> \tableofcontents
> \listoffigures
> \listoftables
> \end{document}
> ```
> 
> 也可以局部 patch `\chapter`。

如果只是局部修改目录或是章的样式，可以有更简单的实现，即局部重定义 plain 样式即可，比如目录：

```Tex
{%
\fancypagestyle{plain}{%
    \fancyhf{}% clear fields
    \renewcommand{\headrulewidth}{0pt}% header rule
    \renewcommand{\footrulewidth}{0pt}% footer rule
}
\tableofcontents% content catalog
}

```
