### ISSUE TITLE
如何消除ctex文档类中证明环境前后的间距

### ISSUE THREAD

**Issue by DangeRS2** [CTeX-org/forum#85]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2017
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

如何消除ctex文档类中证明环境前后的间距？如图所示，将MWE在`article`文档类运行可达到期望效果，但是在`ctexbook`中并不起作用。

## 最小工作示例（MWE）

```latex
%\documentclass[UTF8,a4paper,zihao=-4,fontset=fandol]{ctexbook}

\documentclass{article}

\usepackage{blindtext}
\pagestyle{empty}
\usepackage{geometry}
\geometry{left=3.2cm,right=3.2cm,top=2.54cm,bottom=2.54cm}

\usepackage{amsthm}
\newtheoremstyle{test}
	{\parskip}{\parskip}
	{\upshape}{10pt}
	{\bfseries}{:}
	{10pt}{}
\theoremstyle{test}
\newtheorem{theorem}{Theorem}

\makeatletter
\renewenvironment{proof}[1][\proofname]{\par
	\pushQED{\qed}%
	\normalfont \topsep0\p@\@plus1\p@\relax
	\trivlist
	\item\relax
	{\itshape
		#1\@addpunct{.}}\hspace\labelsep\ignorespaces
}{%
	\the\topsep\popQED\endtrivlist\@endpefalse
}
\makeatother

\begin{document}

\blindtext

\begin{theorem}
\blindtext
\end{theorem}

\begin{proof}
\blindtext
\end{proof}

\the\topsep

\the\partopsep

\the\parsep

\the\parskip

\blindtext
	
\end{document}
```

（用 XeLaTeX 编译后）输出

![image](https://user-images.githubusercontent.com/49086184/71763754-7a8df400-2f1a-11ea-880c-e0f366a556fa.png)
![image](https://user-images.githubusercontent.com/49086184/71763765-9ee9d080-2f1a-11ea-98df-b4a3fecec88f.png)

## 链接

- TeX.SX:
- GitHub:

**Comment by muzimuzhi** [comment]
证明环境在 article 和 ctexbook 文档类中的定义是相同的。输出效果不同，是因为两个文档类下的页面纵向对齐方式不同
 * article 文档类默认顶部对齐
 * ctexbook 继承自 book 文档类，默认两端对齐

在使用 ctexbook 的同时加上 `\raggedbottom` 切换到顶部对齐，就能得到与 article 一致的「证明环境前后间距」。

我的知乎文章《[[LaTeX 漫谈] 被无限拉伸的纵向间距，和页面纵向对齐方式](https://zhuanlan.zhihu.com/p/99672019)》提供了更多分析。

**Comment by RuixiZhang42** [comment]
来来来，让我们分析一下版心的合理性。

```latex
\documentclass[UTF8,a4paper,zihao=-4,fontset=fandol]{ctexbook}

\usepackage{blindtext}
\usepackage{geometry}
\geometry{left=3.2cm,right=3.2cm,top=2.54cm,bottom=2.54cm}

\begin{document}

\the\topskip

\the\baselineskip

\blindtext

\end{document}
```

在上面的例子中：
- `a4paper` 设定页面高度为 `297mm`，约 `11.69in`=`841.89bp`。
- `top=2.54cm,bottom=2.54cm` 设定天头、地脚为一英寸，精确值（Word 的默认设置吧？A4&nbsp;纸的页面跟英寸的页边距混用）。
- 结果是版心的高度为 `246.2mm`，约 `9.69in`=`697.89bp`。

往版心里填内容：
- `zihao=-4` 设定字号大小为 `小四`，即 `12bp`。
- 版心内第一行的（西文）基线与版心顶部的距离为 `\topskip`，这个从 `book` 继承过来。但是 `ctexbook` 延用了 `12pt`（而非 `12bp`），换算之后约为 `11.955bp`。
- 放完第一行之后，版心还剩 `697.89bp - 11.955bp = 685.935bp` 的高度。
- 从第二行起直到版心底部，每一行占据 `\baselineskip` 的高度，在此例中，该值为 `18.72bp`（精确换算会是 `18.7902pt`，小数点后第五位存在舍入误差是正常现象）。

### `685.935bp` 除以 `18.72bp` 是不可能除得整数的
事实上，按照例子中的设定，除开第一行之后，还要再放 `685.935bp/18.72bp = 36.64` 行。这是不可能的，所以只能再放 36 行（加上第一行，每页一共 37 行）。

多出来 `0.64` 行的空白，会在 `\flushbottom` 的控制下，分散在一切可以拉伸的垂直弹性距离中去。

### 解决方案
1. 方案一，按 @muzimuzhi 建议，在导言区声明 `\raggedbottom`，结果是末行可能会参差不齐。此方案用于书籍文档类可能效果不佳，因为书籍会偏好每一页的首行末行都对齐。
2. 方案二，往 `\documentclass[...]{ctexbook}` 里加一项可选参数 `linespread=1.323`，稍微扩大行距（默认是 `linespread=1.3`）。效果是每页正好 37 行。
3. 方案三，把天头、地脚设稍微小一点 `\geometry{...,vmargin=2.751cm}`，效果也是每页正好 37 行。

**Comment by RuixiZhang42** [comment]
关于版面设计再啰嗦几句（感觉跑偏了）。

`left=3.2cm,right=3.2cm` 又是来自 Word 的设定（从 1.25&nbsp;英寸近似过来的，个人无条件抵制），跟 `a4paper` 与 `zihao=-4` 的综合结果是，每一行可以放 `34.488` 个汉字。

强烈建议 `hmargin=3.303cm` 或者 `hmargin=3.091cm` 让行长恢复成字号的整数倍（我不信校方能看出左右页边距一毫米的区别），自然段的末行错位看着辣眼睛……参见《[从「行长为字号的整数倍」说起](https://thetype.com/2017/07/12513/)》。

**Comment by DangeRS2** [comment]
感谢两位的解答~~
