### ISSUE TITLE
如何控制浮动体与前后文的间距？

### ISSUE THREAD

**Issue by krisfans** [CTeX-org/forum#86]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2019 
  - [ ] MiKTeX 
  - [ ] CTeX

### 想要效果
`here`浮动体与上下文的间距为`6pt`。
### 尝试
想调整图片和上下文的距离，后面了解到`here`浮动体与前后文的距离用`\intextsep`调整，其默认值为`12.0pt plus 2.0pt minus 2.0pt`，我调整`\intextsep`这个为`6pt`后发现`here`浮动体与前后文的距离不一样，但是他们都受到一个参数`\intextsep`控制？

## 最小工作示例（MWE）

```latex
\documentclass[a4paper,12pt,UTF8]{ctexart}
\usepackage[left=3.18cm,right=3.18cm,top=2.54cm,bottom=2.54cm]{geometry}%页面设置
\usepackage[draft]{graphicx}
\pagestyle{plain}
\usepackage{zhlineskip}
\usepackage{zhlipsum}
\usepackage{caption,subcaption}%图表标题
\DeclareCaptionFont{kaishu}{\kaishu}
\captionsetup{font=small,skip=6pt,textfont=kaishu}%修改题注间距和字体
\renewcommand{\figurename}{{\kaishu 图}}
\renewcommand{\tablename}{{\kaishu 表}}

\setlength{\textfloatsep}{6pt}%注释这两行
\setlength{\intextsep}{6pt}%注释这两行

% \textfloatsep= 10pt plus 1pt minus 1pt
\usepackage{etoolbox} % 载入宏包

\begin{document}

\zhlipsum*[1][name=aspirin]
\begin{figure}[h]

  \centering
  \includegraphics[width=0.4\textwidth]{figure/woj.png}
  \caption{微欧计使用方法}
  % \vspace*{-12pt}
  \label{fig:woj}
\end{figure}

\zhlipsum*[1][name=aspirin]

\showthe\intextsep
\end{document}



```
### `MWE`中用到的插图
[![l0WyTA.md.png](https://s2.ax1x.com/2020/01/04/l0WyTA.md.png)](https://imgchr.com/i/l0WyTA)

（用 XeLaTeX 编译后）输出
### 初始状态
[![l0RlVA.md.png](https://s2.ax1x.com/2020/01/04/l0RlVA.md.png)](https://imgchr.com/i/l0RlVA)
### `\intextsep=6pt`
[![l0WKzT.md.png](https://s2.ax1x.com/2020/01/04/l0WKzT.md.png)](https://imgchr.com/i/l0WKzT)
## 链接

- TeX.SX:
- GitHub:

**Comment by muzimuzhi** [comment]
你圈出来的这段纵向间距，由四部分组成：
![image](https://user-images.githubusercontent.com/6376638/71769100-78965600-2f57-11ea-9a5f-6fe20ad9a1de.png)

1. 由 `caption` 宏包添加的、在 `\caption` 的文字下方加入的 `\@finalstrut\strutbox`（见`\caption@@@make` 命令的定义）。这部分的实际大小和字号有关，具体到你的例子，是 5.06487pt（向例子加入 `\loggingoutput` 再编译，然后在 log 文件中搜索 `\caption` 中的最后一个字「法」，在下方第四行能找到 `\rule(0.0+5.06487)x0.0`，表示此处插入了一个高度为 0pt、深度为 5.06487pt、宽度为 0pt 的 rule）
1. 在 `\caption` 下方加入的 `\belowcaptionskip`，对 figure 浮动体类型而言，`caption` 宏包将其设为 `0pt`
1. 在浮动体与下方文字之间加入的 `\intextsep`
1. 正常的行距

之前你调整的是其中的第 2、3 部分，通过 `struc=off` 可以取消第 1 部分。
```tex
\documentclass{article}
\usepackage[strut=off]{caption}
\usepackage{lipsum}
\usepackage{mwe}

\captionsetup[figure]{skip=6pt}

\newcommand\test{
  \textbf{\texttt{\textbackslash intextsep}: \the\intextsep}\par
  \lipsum[75]
  \begin{figure}[h]
    \centering
    \includegraphics[width=3cm]{example-image}
    \caption{ZZZZ}
  \end{figure}
  \par
  \lipsum[75]
}

\begin{document}
\setlength{\intextsep}{0pt}
\test

\setlength{\intextsep}{6pt}
\test
\end{document}
```
![image](https://user-images.githubusercontent.com/6376638/71769181-a5973880-2f58-11ea-912a-d5ef635f4db8.png)

取消第 4 部分要更困难一些。

**Comment by krisfans** [comment]
谢谢。原来`\caption` 引入了额外的距离。这个`caption`宏包并没有把`strut`选项放在`Option`一节，这个参数很难发现啊

**Comment by muzimuzhi** [comment]
> 谢谢。原来`\caption` 引入了额外的距离。这个`caption`宏包并没有把`strut`选项放在`Option`一节，这个参数很难发现啊

我昨天给 caption 项目提了 issue，维护者回应「会在 2020 年第一季度更新文档，增加对 `strut` 的介绍」。详见 https://gitlab.com/axelsommerfeldt/caption/issues/71
