### ISSUE TITLE
如何把参考文献和引用改为数字模式？

### ISSUE THREAD

**Issue by wqb-123** [CTeX-org/forum#87]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [ ] TeX Live 
  - [x] MiKTeX 
  - [ ] CTeX

## 描述问题

    1. 描述出现的情况
最新版 https://github.com/mohuangrui/ucasthesis 的参考文献和引用没继承旧版的数字模式。

新版的参考文献：LAMPORT L. Document preparation system [M]. Addison-Wesley Reading, MA, 1986.
新版参考文献的引用只有两种方式：Lamport (1986) 或者 (Lamport, 1986)

旧版的参考文献：[1] Thesis Template of the Universicty of Chinese Academy of Sciences, 2014.
旧版的参考文献引用方式： 如何继承旧版毕业论文模板 [1] 中的参考文献和引用模式？

    2. 给出复现步骤
直接运行模板 https://github.com/mohuangrui/ucasthesis 即可复现参考文献和引用的模式。

    3. 给出您解决问题所进行的尝试
在 artratex.sty 中，把原有 alpha 都改成了 abbrv，但是我没尝试成功。修改的部分代码如下（用%注释的代码为原有代码）
%    \ifartx@alpha% enable alpha citation style
    \ifartx@abbrv% enable abbrv citation style
        \RequirePackage[square,comma,numbers]{natbib}% alpha citation mode
%        \bibliographystyle{alpha}% alpha scheme
        \bibliographystyle{abbrv}% alpha scheme
    \fi

## 最小工作示例（MWE）

```latex
\documentclass{ctexart}
\begin{document}
Hello, \LaTex!
\end{document}
```

（用 XeLaTeX 编译后）输出

```latex
! Undefined control sequence.
l.3 Hello, \LaTex
                 !
?
```

## 链接

- TeX.SX:
- GitHub:

**Comment by wqb-123** [comment]
提问页面中 New issue 按钮附近的 Edit 按钮是灰色，我不能再编辑一下，去掉最小工作示例和链接（不需要提供）。

**Comment by hushidong** [comment]
应该可以改的，参考一下模板的wiki，如果没有答案，问一下模板作者。

最后还有另一个ucas模板好像用的顺序编码制。就是数字式的。

**Comment by RuixiZhang42** [comment]
多查查资料：https://github.com/mohuangrui/ucasthesis/wiki

你开的这个 issue，问题跟 MWE 完全不搭嘛（笑）。

**Comment by wqb-123** [comment]
@RuixiZhang42 嗯，谢谢您，我以后都先在这些网址上多看看，多查一下。

**Comment by OsbertWang** [comment]
```tex
\usepackage[authoryear,list]{Style/artratex}
```
换成
```tex
\usepackage[numbers,list]{Style/artratex}
```

**Comment by muzimuzhi** [comment]
提问者在模板项目下有相同提问，模板作者已回复，见 https://github.com/mohuangrui/ucasthesis/issues/222#issuecomment-571095985 。这里的 issue 先关闭了。
