### ISSUE TITLE
如何去掉参考文献部分第一页的页眉？

### ISSUE THREAD

**Issue by wqb-123** [CTeX-org/forum#88]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [ ] TeX Live 
  - [x] MiKTeX 
  - [ ] CTeX

## 描述问题

    1. 描述出现的情况
我的参考文献有多页，想去掉第一页的页眉。不知道如何修改代码？

    2. 给出复现步骤
在模板 https://github.com/mohuangrui/ucasthesis 中的  /Biblio/ref.bib 中增加5篇新的参考文献，运行后可以看到参考文献由1页变成了2页。

附我新增的参考文献，共测试用。
@article{zhang2019image,
	title={Image de-raining using a conditional generative adversarial network},
	author={Zhang, He and Sindagi, Vishwanath and Patel, Vishal M},
	journal={arXiv preprint arXiv:1701.05957},
	month={Jun.},
	year={2019},
}
@inproceedings{zhang2018density,
	title={Density-aware single image de-raining using a multi-stream dense network},
	author={Zhang, He and Patel, Vishal M},
	booktitle=CVPR,
	pages={695--704},
	month={Jun.},
	year={2018}
}
@article{zhang2019joint,
	title={Joint Transmission Map Estimation and Dehazing using Deep Networks},
	author={Zhang, He and Sindagi, Vishwanath and Patel, Vishal M},
	journal={arXiv preprint arXiv:1708.00581},
	month={Apr.},
	year={2019},
}
@article{ren2019single,
	title={Single Image Dehazing via Multi-scale Convolutional Neural Networks with Holistic Edges},
	author={Ren, Wenqi and Pan, Jinshan and Zhang, Hua and Cao, Xiaochun and Yang, Ming-Hsuan},
	journal={Int. J Comput. Vis.},
	pages={1--20},
	year={2019},
}
%
@article{fattal2008single,
	title={Single image dehazing},
	author={Fattal, Raanan},
	journal=TOG,
	volume={27},
	number={3},
	pages={72},
	month={Aug.},
	year={2008},
}

    3. 给出您解决问题所进行的尝试
在模板的 Thesis.tex 中，把一句新代码 \thispagestyle{noheaderstyle} 嵌入到原代码 \bibliography{Biblio/ref}的前面和后面，即

\thispagestyle{noheaderstyle}
\bibliography{Biblio/ref}

和

\bibliography{Biblio/ref}
\thispagestyle{noheaderstyle}

这两种尝试都不能消除参考文献第一页的页眉。我不清楚 \bibliography{} 的内部写法， 烦请高手指点迷津，非常感谢。

## 最小工作示例（MWE）
见复现步骤和解决问题的尝试。

**Comment by OsbertWang** [comment]
你以前问过类似问题，“想去掉目录和各章的首页页眉”，当时提供的手段是
```latex
\ctexset{
  chapter/pagestyle = noheaderstyle
}
```
这个方法能适用于参考文献

**Comment by wqb-123** [comment]
@OsbertWang 谢谢您。添加这行代码后达到了效果。

**Comment by muzimuzhi** [comment]
> 你以前问过类似问题，“想去掉目录和各章的首页页眉”，当时提供的手段是

是在这条评论中提供的 https://github.com/CTeX-org/forum/issues/82#issuecomment-569593233

**Comment by zepinglee** [comment]
这问题为何不去 https://github.com/mohuangrui/ucasthesis/issues 问？通常模板作者是最清楚模板的

**Comment by muzimuzhi** [comment]
- #82，提问者是先在模板项目下提问，然后被模板作者回复应该发来这里的，见 https://github.com/mohuangrui/ucasthesis/issues/219#issuecomment-569472288
    > Q: 目录共2页，第1页的页眉如何去掉？
    > A: 关于 LaTeX 的知识性问题，请前往 CTeX Forum 发问
 - 当前 issue 其实是 #82 的延伸

**Comment by mohuangrui** [comment]
@zepinglee  这个问题本质上并非关于 ucasthesis 的，所以让来这里问更加合适点 :)
