### ISSUE TITLE
绘制表格时用 \multirow 合并两个 cells, 遇到了  ! Undefined control sequence. <recently read> \multirow 的错误

### ISSUE THREAD

**Issue by wqb-123** [CTeX-org/forum#89]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [ ] TeX Live 
  - [x] MiKTeX -- 版本号2.9 --
  - [ ] CTeX

## 描述问题

请在此处描述清楚您所遇到的问题：

1. 描述出现的情况
在绘制表格时，我想用 `\multirow` 实现两个 cells 的合并，却遇到了报错。`Thesis.log` 中记录的错误是

```tex
! Undefined control sequence.
<recently read> \multirow 
                          
l.169         \multirow
                       {2}{*}{琛屽彿} & \multicolumn{8}{c}{璺ㄥ鍒楃殑鏍囬}\\
?
```

2. 给出复现步骤

问题可以通过编辑模板 <https://github.com/mohuangrui/ucasthesis> 中的 `Chap_Guide.tex` 实现。

`Chap_Guide.tex` 中有一段制表的源码：

```tex
\begin{table}[!htbp]
    \bicaption{这是一个样表。}{This is a sample table.}
    \label{tab:sample}
    \centering
    \footnotesize% fontsize
    \setlength{\tabcolsep}{4pt}% column separation
    \renewcommand{\arraystretch}{1.2}%row space 
    \begin{tabular}{lcccccccc}
        \hline
        行号 & \multicolumn{8}{c}{跨多列的标题}\\
        %\cline{2-9}% partial hline from column i to column j
        \hline
        Row 1 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$\\
        Row 2 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$\\
        Row 3 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$\\
        Row 4 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$\\
        \hline
    \end{tabular}
\end{table}
```

修改其中两行代码（如下）就能复现问题。

```tex
\begin{table}[!htbp]
    \bicaption{这是一个样表。}{This is a sample table.}
    \label{tab:sample}
    \centering
    \footnotesize% fontsize
    \setlength{\tabcolsep}{4pt}% column separation
    \renewcommand{\arraystretch}{1.2}%row space 
    \begin{tabular}{ccccccccc}
        \hline
        %
%        行号 & \multicolumn{8}{c}{跨多列的标题}\\
        \multirow{2}{*}{行号} & \multicolumn{8}{c}{跨多列的标题}\\
        \cline{2-9}% partial hline from column i to column j
        & 方法1 & 方法2 & 方法3 & 方法4 & 方法5 & 方法6 & 方法7 & 方法8
        \hline
        Row 1 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$\\
        Row 2 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$\\
        Row 3 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$\\
        Row 4 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$\\
        \hline
    \end{tabular}
\end{table}
```

3. 给出您解决问题所进行的尝试

尝试 1：在 CTeX Forum 上的 issues (包括open 和 closed) 中都没有找到类似的问题，在 https://github.com/mohuangrui/ucasthesis/wiki 和 https://en.wikibooks.org/wiki/LaTeX 也没找到类似问题。

尝试 2: 通过 Google 找到了类似的问题
https://groups.google.com/forum/#!topic/comp.text.tex/WvydbjnzDKM
但该网址的解决办法不是很清楚，因为 \multirow 包含在哪个 package 中没讲清楚。

多说一点。在问题复现中，原代码中的 `\multicolumn` 能运行成功，但我也没能找到 `\multicolumn` 包含在了哪个包中。有可能是 `artratex.sty` 中 Line 523 的 `\RequirePackage{ctable}`，但不确信。

**Comment by wqb-123** [comment]
复现步骤中的
行号 & \multicolumn{8}{c}{跨多列的标题}
Row 1 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
Row 2 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
Row 3 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
Row 4 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
\multirow{2}{*}{行号} & \multicolumn{8}{c}{跨多列的标题}
后面分别只有一个反斜杠 \\, 其实在代码中有两个 \\\

**Comment by wqb-123** [comment]
补充一下复现步骤中的
行号 & \multicolumn{8}{c}{跨多列的标题}
Row 1 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
Row 2 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
Row 3 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
Row 4 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
\multirow{2}{*}{行号} & \multicolumn{8}{c}{跨多列的标题}
后面分别只有一个反斜杠 \, 其实在代码中有两个 \\

**Comment by wqb-123** [comment]
补充一下复现步骤中的
行号 & \multicolumn{8}{c}{跨多列的标题}
Row 1 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
Row 2 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
Row 3 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
Row 4 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
\multirow{2}{*}{行号} & \multicolumn{8}{c}{跨多列的标题}

这几行的后面分别只有一个反斜杠 \\ , 其实在代码中有两个 \\\

**Comment by wqb-123** [comment]
补充一下复现步骤中的
行号 & \multicolumn{8}{c}{跨多列的标题}
Row 1 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
Row 2 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
Row 3 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
Row 4 & $1$ & $2$ & $3$ & $4$ & $5$ & $6$ & $7$ & $8$
\multirow{2}{*}{行号} & \multicolumn{8}{c}{跨多列的标题}

这几行的后面分别只有一个反斜杠 \\ , 其实在代码中有两个，即 \\\

**Comment by stone-zeng** [comment]
请了解一下 markdown 的语法：代码块应该放在 ```...``` 里面。

**Comment by wqb-123** [comment]
谢谢! 怎么可以避免使用 \multirow 引起的问题 (! undefined control sequence. <recently read> \multirow) 呢?

**Comment by wqb-123** [comment]
谢谢! 怎么可以避免使用 \multirow 引起的问题 (! undefined control sequence. \<recently read\> \multirow) 呢?

**Comment by muzimuzhi** [comment]
需加载 `multirow` 宏包。
与 issue https://github.com/mohuangrui/ucasthesis/issues/35 重复
