### ISSUE TITLE
有关插入eps文件的问题

### ISSUE THREAD

**Issue by muyuuuu** [CTeX-org/forum#9]
操作系统： windows10
编译方式：xelatex
发行版：texlive2018
其实一直想问这个问题(莫笑，可能有点low，但困扰了我很久)，latex如何插入eps文件，一直插入一直错，曾经也去搜索过，但一直没有好的解决方案。

问题描述如下：
在Lshort中，对插入eps文件描述如下：
![default](https://user-images.githubusercontent.com/43681138/51915982-47dca100-2417-11e9-81cd-94201134b934.PNG)

MWE如下：

```latex
\documentclass{ctexart}

\usepackage{graphicx}

\begin{document}
	\includegraphics[width=8cm, height=10cm]{1.eps}
\end{document}
```

命令行编译 出错信息如下：
``` 
xdvipdfmx:fatal: pdf_ref_obj(): passed invalid object.

Output file removed.

Error 1 (driver return code) generating output;
file test.pdf may not be valid.
Transcript written on test.log.
```

**Comment by Liam0205** [comment]
@muyuuuu eps 图档传一下，另外执行下面命令编译，log 贴一下。

```
xelatex -output-driver="xdvipdfmx -vv" test.tex
```

**Comment by muyuuuu** [comment]
eps传不上来还是我不会用。。。

![default](https://user-images.githubusercontent.com/43681138/51972688-fb48a280-24b6-11e9-955a-117ece7b2a02.PNG)

```命令行信息如下
xdvipdfmx:warning: Image format conversion for "./1.eps" failed...
,Page:1)
xdvipdfmx:fatal: pdf_ref_obj(): passed invalid object.

Output file removed.

Error 1 (driver return code) generating output;
file test.pdf may not be valid.
Transcript written on test.log.
```

**Comment by muyuuuu** [comment]
对了，问下楼上大佬不太相关的问题。

![default](https://user-images.githubusercontent.com/43681138/51972867-5ed2d000-24b7-11e9-87c5-bca30e3ea126.PNG)

是不是克隆以后就能抄袭偷窃你博客的模板风格了，做的太漂亮了，然后我就把我之前的hexo模板扔了。

另外还有个浮动体的问题：
原谅我此时可能提供不了MWE。
操作系统：windows10，编译方式：xelatex，发行版texlive2018，文档类：ctexart。
在一页中使用了较多的浮动体的情况下，为什么有点图片没显示出来，没有报错但是就是不显示。我在那堆浮动体中央强行`\newpage`了一下，那个不显示的图片才重新显示出来。
当时在比赛，没来得及问，后来代码也被修改了，实在提供不了MWE，抱歉。可否讨论下这种现象出现的原因？

**Comment by muyuuuu** [comment]
[1.zip](https://github.com/CTeX-org/forum/files/2811948/1.zip)

日常眼瞎没看见支持zip文件

**Comment by Liam0205** [comment]
@muyuuuu 我的有修改：<https://github.com/Liam0205/hexo-theme-next>

**Comment by muyuuuu** [comment]
![image](https://user-images.githubusercontent.com/43681138/51973808-7612bd00-24b9-11e9-8d16-999b9f792616.png)

这个操作姿势对不(如果这里讨论hexo不合适的话我就，就，就，换个地方？)。

**Comment by muzimuzhi** [comment]
> 对了，问下楼上大佬不太相关的问题。

> 另外还有个浮动体的问题：

一个 issue 讨论一个问题。已经知道补充问题与主问题不相关时，应该新开 issue 提问。

**Comment by muzimuzhi** [comment]
你提供的 `1.eps` 文件，我本地能正常转换和插入。

xelatex + graphicx 对 eps 的「支持」，依赖 ghostscript（见[这篇文章](https://zhuanlan.zhihu.com/p/50829212)的注释 4）。建议检查本地 ghostscript 能否正常使用。

**Comment by muyuuuu** [comment]
@Liam0205 log文件如下：
[log.zip](https://github.com/CTeX-org/forum/files/2834697/log.zip)

**Comment by muyuuuu** [comment]
@muzimuzhi 话说弱弱的问一下咋检查，在texlive2018的安装环境中发现了ghostscript的压缩包和readme文件。。。啊，好像真不会检查能不能正常用。
![image](https://user-images.githubusercontent.com/43681138/52318349-fd52ba00-29fe-11e9-8e05-3f0d319b3016.png)

**Comment by Liam0205** [comment]
> xelatex + graphicx 对 eps 的「支持」，依赖 ghostscript（见[这篇文章](https://zhuanlan.zhihu.com/p/50829212)的注释 4）。建议检查本地 ghostscript 能否正常使用。

XeLaTeX 插入 EPS 需要 GS，这个有别的引用来源吗？跟我的印象不太一致。

**Comment by Liam0205** [comment]
疑似与 sjtug/SJTUThesis#82 以及 https://tex.stackexchange.com/questions/319571/error-1-driver-return-code-works-on-old-computer-but-not-new-one 是同一个问题。@yihui 在他的 tinytex 项目中，也有用户报告了疑似同一个问题 yihui/tinytex/#57。

这些问题看起来都和 `xDVIPDFMx` 的一个 [bug](https://bugs.launchpad.net/ubuntu/+source/ghostscript/+bug/1449875) 有关。

目前看来，这和 `xDVIPDFMx` 在插入 EPS 时，找不到 EPS 所需的字体有关系。考虑：

```bash
xelatex -no-pdf test
xdvipdfmx -q -E -vv test
```

之后给更详细的日志（特别是 `xDVIPDFMx` 的日志）。

**Comment by muzimuzhi** [comment]
> > xelatex + graphicx 对 eps 的「支持」，依赖 ghostscript（见[这篇文章](https://zhuanlan.zhihu.com/p/50829212)的注释 4）。建议检查本地 ghostscript 能否正常使用。
> 
> XeLaTeX 插入 EPS 需要 GS，这个有别的引用来源吗？跟我的印象不太一致。

@Liam0205 你的印象是正确的，我误导了你。

这个 [overleaf 的只读项目](https://www.overleaf.com/read/hrznnypqthnc)展示了 xelatex + graphicx 能直接插入[题主上传的 eps 图片](https://github.com/CTeX-org/forum/issues/9#issuecomment-460884510)。下面两段 log 证明了「插入的是 eps，而非经过转换的 pdf」，所以就这个问题里的 xelatex + `1.eps` 的情况，不涉及 ghostscript。

```
File: 1.eps Graphic file (type eps)
<1.eps>
```

```
 *File List*
 article.cls    2014/09/29 v1.4h Standard LaTeX document class
  size10.clo    2014/09/29 v1.4h Standard LaTeX file (size option)
graphicx.sty    2017/06/01 v1.1a Enhanced LaTeX Graphics (DPC,SPQR)
  keyval.sty    2014/10/28 v1.15 key=value parser (DPC)
graphics.sty    2017/06/25 v1.2c Standard LaTeX Graphics (DPC,SPQR)
    trig.sty    2016/01/03 v1.10 sin cos tan (DPC)
graphics.cfg    2016/06/04 v1.11 sample graphics configuration
   xetex.def    2017/06/24 v5.0h Graphics/color driver for xetex
       1.eps    Graphic file (type eps)
 ***********
```

实际上，在 overleaf 的 texlive 2017，和我本地的 texlive 2018 上，无论是使用 xelatex 还是 pdflatex，都能正常插入 `1.eps`。怀疑问题出在题主本地的发行版上，建议提供更多版本信息。@muyuuuu

**Comment by muzimuzhi** [comment]
我的上一个评论基本是错误的。

使用 xelatex 时，会由 xdvipdfmx 调用 ghostscript，进行 eps 到 pdf 的转换。因为是先生成 log 再由 xdvipdfmx 做转换，所以在 log 里看起来是「直接」插入了 eps 图片。

使用 pdflatex 时，会由 graphicx 宏包（间接）调用 epstopdf 宏包的核心功能，先使用 ghostscript 进行转换（把文件 `xxx.eps` 转换为 `xxx-converted-to.pdf`），再插入。

总之，在非 dvi 模式下，插入 eps 都需要调用 ghostscript。 题主遵循 https://github.com/CTeX-org/forum/issues/9#issuecomment-462602116 里的建议做即可，可以忽略我的上条和本条评论。

**Comment by clerkma** [comment]
你们都把事情想复杂了，我给你们缕一缕：
* pdfTeX (PDF模式)
   * `*.png`，`*.jpg`，`*.jbig`，`*.pdf`都直接支持写入到输出的PDF文件之中。
   * `*.ps`，`*.eps`是直接不支持的，但是可以用黑魔法（`\write18`）。也就是所谓的`epstopdf`包。你们要是仔细看源代码的话，会发现一个命令`\pdf@system`。这是`pdftexcmds`包对于`\write18`的封装。这个命令背后是管道（系统调用`popen`），通过**Ghostscript**将`ps/eps`文件转换为PDF文件后插入的
* pdfTeX (DVI模式，输出PDF需要`dvipdfmx`)
   * 这就是你们敲`latex`命令时候运行的模式。这个模式下原则上只把图像文件的尺寸信息和文件名写到`*.dvi`文件里面去了，包括`ps/eps`。
* XeTeX (DVI模式，输出PDF需要`dvipdfmx`)
   * 支持读文件尺寸信息，实际上也是把图像文件的尺寸信息和文件名写到`*.xdv`文件里面去了。
* pTeX系 (DVI模式，输出PDF需要`dvipdfmx`)
   * 不支持读文件尺寸信息，但是可以通过`\write18`调用`extractbb`命令获取图像尺寸，最后也是把图像文件的尺寸信息和文件名写到`*.xdv`文件里面去了。
* dvipdfmx的支持
   * `*.bmp`，`*.jp2`，`*.jpg`，`*.png`，`*.pdf`都直接支持插入。
   * `*.ps`，`*.eps`是直接不支持的，但是可以用黑魔法（`popen`）。你们可以直接去看看`spc_dvips.c`文件里面的`calculate_PS`函数，背后还是跑不掉**Ghostscript**的支持。

所以啊，条条大路通Ghostscript，以及天下何人不通Ghostscript？！
既然提到了`bmpsize`包，那么我可以给你们讲一讲这个包到底干了什么。这个包的核心是pdfTeX 1.3以后加入的`\pdffiledump`命令，作用是可以直接读取一部分文件到pdfTeX里面来。然后这个包的骚操作就来了，Heiko Oberdiek直接在这个包里暴力实现了各种位图文件的二进制解析（类似于python及ruby的`unpack`操作），然后就把位图的尺寸算出来了。暴力，但有效，所以这个包我也建议大家读一读。（跑

**Comment by Liam0205** [comment]
@clerkma 有一种官宣的感觉。

**Comment by muyuuuu** [comment]
刚才在overleaf上玩耍了一下，一切正常，看来是我本地发行版的原因，发行版是从TUNA下载的，texlive2018.

`xelatex -no-pdf test`log如下：
[test.log](https://github.com/CTeX-org/forum/files/2858577/test.log)

`xdvipdfmx -E -vv test`l报错信息如下：
![default](https://user-images.githubusercontent.com/43681138/52682826-c5f28900-2f7b-11e9-829d-a4f73a7e0574.PNG)
log如下：
[test.log](https://github.com/CTeX-org/forum/files/2858581/test.log)

**Comment by Liam0205** [comment]
> 刚才在overleaf上玩耍了一下，一切正常，看来是我本地发行版的原因，发行版是从TUNA下载的，texlive2018.

这个显然。

> `xelatex -no-pdf test`log如下：
> [test.log](https://github.com/CTeX-org/forum/files/2858577/test.log)

符合预期

> `xdvipdfmx -E -vv test`l报错信息如下：
> ![default](https://user-images.githubusercontent.com/43681138/52682826-c5f28900-2f7b-11e9-829d-a4f73a7e0574.PNG)
> log如下：
> [test.log](https://github.com/CTeX-org/forum/files/2858581/test.log)

唔，`xDVIPDFMx` 默认不会写 log 文件的；所以你上传的两个 log 文件一模一样。你可能需要重定向到文件。

```cmd
xdvipdfmx -E -vv test >xdx.log 2>&1
```

从截图来看，果然还是 GhostScript 的锅。

**Comment by Liam0205** [comment]
我突然有个大胆的想法……
会不会是用户名包含中文，然后临时文件目录也包含中文导致的问题……？

**Comment by Liam0205** [comment]
@Liam0205 试了一下，不会是这个原因。 xDVIPDFMx 在临时目录路径包含中文时工作良好。

**Comment by bujianbusan** [comment]
现在的eps和当初开发LaTeX时候的eps已经发生了很大的不同，在eps内部也可以嵌入点阵图，而且可以选择它的压缩模式。

**Comment by m20069876** [comment]
我有另一个问题，就是在导入图片时候，图片名中有中文字符，结果就出现了Unable to load picture的情况，全部改成英文的就能成功，这个问题的原因是什么呢？怎么处理？

**Comment by muzimuzhi** [comment]
@m20069876 
> 一个 issue 讨论一个问题。已经知道补充问题与主问题不相关时，应该新开 issue 提问。
> https://github.com/CTeX-org/forum/issues/9#issuecomment-459063699
