### ISSUE TITLE
如何用 `tikz` 生成只有箭头的方向箭头？

### ISSUE THREAD

**Issue by sikouhjw** [CTeX-org/forum#91]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

想用 `tikz` 生成只有箭头的方向箭头，意思是：正常的方向箭头去掉直线部分，只剩箭头本身，我做了一些尝试，用白色的直线去覆盖，但不完美，见 `MWE`

## 最小工作示例（MWE）

```latex
\documentclass{article}
\usepackage{tikz}
\begin{document}
	\begin{tikzpicture}
		\node (a) at (0,0) {A};
		\node (b) at (1,1) {B};
		\draw[->] (a) -- (b);
		\draw[draw=white] (a) -- (b);
	\end{tikzpicture}
\end{document}
```

（用 XeLaTeX 编译后）输出
![1](https://user-images.githubusercontent.com/49770925/72245579-dbf54780-362b-11ea-84f3-f331c5e34be7.png)
发现直线还有淡淡的灰色线，如何去除？并且箭头部分也被覆盖了，如何解决？

## 链接

- TeX.SX:
- GitHub:

**Comment by muzimuzhi** [comment]
只剩箭头：
```tex
\draw[white, {->[black]}] (a) -- (b);
```
你看到的淡淡的线，是 `\draw[->] (a) -- (b);` 生成的。

**Comment by stone-zeng** [comment]
一种暴力做法：

```tex
\documentclass{article}
\usepackage{tikz}
\begin{document}
  \begin{tikzpicture}[line width=4pt]
    \draw[->] (0, 0) -- (.1, .1);
  \end{tikzpicture}
\end{document}
```

![image](https://user-images.githubusercontent.com/18233088/72254636-a5c1c300-363f-11ea-952d-15986ccdb090.png)
