### ISSUE TITLE
在VScode里xelatex出现乱码应当如何解决

### ISSUE THREAD

**Issue by LiuZJ2019** [CTeX-org/forum#94]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [ ] TeX Live 
  - [ ] MiKTeX 
  - [ ] CTeX
  - [x] VScode x64 1.41.1

## 描述问题

（https://paste.ubuntu.com/p/MX2nt2bS69/）
在VScode以xelatex方式编译如上链接的文本时，section部分中文变成□，而正文部分中文没有问题。
当采用PDFlatex编译时，则没有问题。
已检查编码的打开和保存格式均为UTF-8，系统win10，版本号1903，操作系统版本18362.592。

具体相关文件如下：

[快速做题草稿.log](https://github.com/CTeX-org/forum/files/4128545/default.log)
[快速做题草稿.pdf](https://github.com/CTeX-org/forum/files/4128546/default.pdf)
[快速做题草稿.txt](https://github.com/CTeX-org/forum/files/4128552/default.txt)

由于tex无法上传，我将.tex改成了.txt上传

详细代码备份如下：
```
\documentclass{ctexart}
\newtheorem{definition1}{定义}[section]
\begin{document}
	\section{傅里叶变换}
	\begin{definition1}
		\begin{tabular}{l}
			我们称变换...为傅里叶变换\\
			我们称变换...为傅里叶逆变换
		\end{tabular}
	\end{definition1}
\end{document}
```

**Comment by muzimuzhi** [comment]
你是否在使用 [CTEX 套装/发行版](http://www.ctex.org/CTeXDownload)？

从上传的 log 看，怀疑是你电脑上的 SimHei 字体有问题。你运行下面的例子，问题是否复现？
```tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{SimHei}

\begin{document}
中文测试
\end{document}
```

------
log 中的相关错误信息
```
Requested font "SimHei/ICU:script=latn;language=DFLT;mapping=tex-text;" at 15.06pt
 -> C:/WINDOWS/Fonts/font.ttf
Requested font "SimHei/ICU:script=latn;language=DFLT;mapping=tex-text;" at 15.06pt
 -> C:/WINDOWS/Fonts/font.ttf
Missing character: There is no 傅 in font SubahibiFont/ICU:script=latn;language=DFLT;mapping=tex-text;!
Missing character: There is no 里 in font SubahibiFont/ICU:script=latn;language=DFLT;mapping=tex-text;!
Missing character: There is no 叶 in font SubahibiFont/ICU:script=latn;language=DFLT;mapping=tex-text;!
Missing character: There is no 变 in font SubahibiFont/ICU:script=latn;language=DFLT;mapping=tex-text;!
Missing character: There is no 换 in font SubahibiFont/ICU:script=latn;language=DFLT;mapping=tex-text;!


Requested font "SimHei/ICU:script=latn;language=DFLT;mapping=tex-text;" at 10.54pt
 -> C:/WINDOWS/Fonts/font.ttf
Requested font "SimHei/ICU:script=latn;language=DFLT;mapping=tex-text;" at 10.54pt
 -> C:/WINDOWS/Fonts/font.ttf
Missing character: There is no 定 in font SubahibiFont/ICU:script=latn;language=DFLT;mapping=tex-text;!
Missing character: There is no 义 in font SubahibiFont/ICU:script=latn;language=DFLT;mapping=tex-text;!
```

**Comment by sikouhjw** [comment]
补充信息：在 Q 群中交流得知，他用 `pdflatex` 不会乱码，`xelatex` 会乱码
发行版信息要等他来补充了

**Comment by LiuZJ2019** [comment]
是采用的CTEX套装，版本为CTeX_2.9.2.164。

采用上例（中文测试）编译，问题确实复现，“中文测试”四字变成了□□□□。

```
Missing character: There is no 中 in font SubahibiFont/ICU!
Missing character: There is no 文 in font SubahibiFont/ICU!
Missing character: There is no 测 in font SubahibiFont/ICU!
Missing character: There is no 试 in font SubahibiFont/ICU!
```
[快速做题草稿.log](https://github.com/CTeX-org/forum/files/4132849/default.log)
[快速做题草稿.txt](https://github.com/CTeX-org/forum/files/4132856/default.txt)
[快速做题草稿.pdf](https://github.com/CTeX-org/forum/files/4132858/default.pdf)


补充信息：

采用PDFlatex编译时，不会有任何问题。采用xelatex编译时，仅有section和我定义的definition有问题，正文部分、subsection等部分是没有问题的

**Comment by sikouhjw** [comment]
把 `CTEX套装` 卸了，安装 `TeXLive2019` 吧，参考[https://gitee.com/OsbertWang/install_latex/releases](https://gitee.com/OsbertWang/install_latex/releases)

**Comment by LiuZJ2019** [comment]
已经卸载CTEX套装，并且重新安装最新版本的TeXLive2019。再次编译楼上“中文测试”样例后，直接报错了。

以下是VScode的报错信息
```
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/W32TeX) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `c:/Users/l3z4j/Desktop/NewLaTeX/1¡¢¿팙ض͢²ݸ㯿팙ض͢²ݸ⾀'.
<*> ...ers/l3z4j/Desktop/NewLaTeX/1¡¢¿팙ض͢²ݸ㯿팙ض͢²ݸ⾀
                                                  
(Press Enter to retry, or Control-Z to exit)
Please type another input file name
! Emergency stop.
<*> ...ers/l3z4j/Desktop/NewLaTeX/1¡¢¿팙ض͢²ݸ㯿팙ض͢²ݸ⾀
                                                  
No pages of output.
Transcript written on texput.log.
```

[texput.log](https://github.com/CTeX-org/forum/files/4135708/texput.log)
[快速做题草稿.pdf](https://github.com/CTeX-org/forum/files/4135710/default.pdf)
[快速做题草稿.txt](https://github.com/CTeX-org/forum/files/4132856/default.txt)

**Comment by stone-zeng** [comment]
在你没有完全清楚全部细节的情况下，请不要使用中文文件名。

**Comment by muzimuzhi** [comment]
issue 长时间无回应，暂时关闭。
