### ISSUE TITLE
\f@encoding 的变化情况

### ISSUE THREAD

**Issue by DangeRS2** [CTeX-org/forum#95]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [x] TeX Live 2019
  - [ ] MiKTeX 
  - [ ] CTeX

## 描述问题

1）为何`\f@encoding`在第二行中文环境中变成了T1，而不是TU？

2）MWE中修改Adobe Times的方法是否标准？

## 最小工作示例（MWE）

```latex
\documentclass[UTF8,a4paper,zihao=-4,fontset=fandol]{ctexbook}

\usepackage[T1]{fontenc}
\renewcommand\sfdefault{phv}
\renewcommand\rmdefault{ptm}
\renewcommand\ttdefault{pcr}

\makeatletter
\newcommand{\printenc}{\f@encoding}
\makeatother

\begin{document}

\makeatletter

\f@encoding

\f@family

\CJK@family

\UnicodeEncodingName

\makeatother

你好\printenc 你好~test \printenc

你好\printenc 你好~test \printenc

\end{document}
```

（用 XeLaTeX 编译后）输出

<img width="273" alt="屏幕快照 2020-02-13 23 47 40" src="https://user-images.githubusercontent.com/49086184/74451906-4ca5b300-4ebb-11ea-932d-37804d83c610.png">

## 链接

- TeX.SX:
- GitHub:

**Comment by muzimuzhi** [comment]
> 1）为何`\f@encoding`在第二行中文环境中变成了T1，而不是TU？

根据 `texdoc fntguide`，sec. 5.1，
> The `fontenc` package has options for encodings; the last option becomes the default encoding.

所以你例子中的默认字体编码是 T1。xecjk v3.8.1 修复了一些问题。更新后，你例子中四处 `\printenc` 的输出都是 T1 了，与预期一致。

**Comment by DangeRS2** [comment]
> > 1）为何`\f@encoding`在第二行中文环境中变成了T1，而不是TU？
> 
> 根据 `texdoc fntguide`，sec. 5.1，
> 
> > The `fontenc` package has options for encodings; the last option becomes the default encoding.
> 
> 所以你例子中的默认字体编码是 T1。xecjk v3.8.1 修复了一些问题。更新后，你例子中四处 `\printenc` 的输出都是 T1 了，与预期一致。

谢谢~@muzimuzhi，我还有一个疑问，如果默认的编码是T1，那么xecjk是怎么在TU和T1之间切换的呢？

**Comment by muzimuzhi** [comment]
> 2）MWE中修改Adobe Times的方法是否标准？

使用非 otf/ttf 字体，建议通过调用相应字体包；使用 otf/ttf 字体，建议通过 fontspec 宏包提供的命令（中文字体可通过 xecjk 或 luatexja 包）修改正文字体，通过 unicode-math 宏包修改公式字体。

字体调用没有什么「标准用法」。使用相应字体包，能在修改 `\[rm|sf|tt]default` 之外，较大限度了解各种可配置项。

以你例子中的用法为例，
 - 衬线字族 `ptm` 提供 Times 风格的字体，最早提供它的是 `times` 字体包。该字体包已淘汰（参考 `texdoc psnfss`, sec. 9.1），推荐使用的后继者是 `newtx` 字体包提供的 `newtxtext` 和 `newtxmath` 宏包，分别修改正文和公式字体。字体包里提供了不少可配置项。
 - 无衬线字族 `phv` 提供 Helvetica 风格的字体，对应 `helvet` 字体包。该字体包额外提供了 `scale` 选项，以使小写字母高（x-height）与衬线字族相匹配。
 - 等宽字族 `pcr` 提供 Courier 风格的字体，对应 `courier` 字体包。这个包只包含 `\renewcommand\ttdefault{pcr}` 一行，和你例子里的做法相同。

如果使用 xetex 或 luatex 引擎，有风格类似的 otf 字体可供选择
 - Times 风格的正文字体有多个选择，例如 TeX Gyre Termes；数学字体参考 unicode-math 宏包的文档之一 `texdoc unimath-symbols`
 - Helvetica 风格的有 TeX Gyre Heros
 - Courier 风格的有 TeX Gyre Cursor 和商业操作系统自带的 Courier (New)

**Comment by muzimuzhi** [comment]
> 如果默认的编码是T1，那么xecjk是怎么在TU和T1之间切换的呢？
> from [this comment](https://github.com/CTeX-org/forum/issues/95#issuecomment-586713275)

 - 利用 xetex 引擎的 character classes 机制，xecjk 会自动在英文-汉字和汉字-英文的交界处插入字体切换命令。于是输入 `test 中文 test` 会变成 `test <use cn font, e.g., FandolSong> 中文 <use en font, e.g., Latin Modern> test`
 - 切换中文字体的命令里直接储存了字体编码 TU，不受当前默认字体编码的影响

不清楚上述的简化描述是否合适。

**Comment by DangeRS2** [comment]
> > 如果默认的编码是T1，那么xecjk是怎么在TU和T1之间切换的呢？
> > from [this comment](https://github.com/CTeX-org/forum/issues/95#issuecomment-586713275)
> 
> * 利用 xetex 引擎的 character classes 机制，xecjk 会自动在英文-汉字和汉字-英文的交界处插入字体切换命令。于是输入 `test 中文 test` 会变成 `test <use cn font, e.g., FandolSong> 中文 <use en font, e.g., Latin Modern> test`
> * 切换中文字体的命令里直接储存了字体编码 TU，不受当前默认字体编码的影响
> 
> 不清楚上述的简化描述是否合适。

That sounds very clear for the newer~~Thanks! @muzimuzhi

**Comment by muzimuzhi** [comment]
> 如果默认的编码是T1，那么xecjk是怎么在TU和T1之间切换的呢？

补一句。如果当前引擎支持 unicode（xetex、luatex 和 uptex），那么 latex2e 会设置默认字体编码为 TU（否则为 T1，如使用 pdftex 引擎时），参考 `texdoc source2e`, sec. 45.1。又因为 xecjk 只支持 xetex 引擎，所以在能使用 xecjk 的文档里，默认字体编码总是 TU。
