### ISSUE TITLE
twocolumn 两列不等高问题

### ISSUE THREAD

**Issue by muyuuuu** [CTeX-org/forum#97]
## 检查

- [x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [x] Windows 10

- TeX 发行版
  - [x] TeX Live <2019>

## 描述问题

我想画一条横线，区分作者和目录，然后，两栏的目录右侧貌似有点高，被横线划过。

![image](https://user-images.githubusercontent.com/43681138/75340567-b071a800-58cd-11ea-9684-2c68bc2c20e8.png)

## MWE
```tex
\documentclass[14pt]{ctexart}
\title{多维随机变量}
\author{兰铃}
\begin{document}
\twocolumn
\maketitle
\rule{\textwidth}{1mm}
\tableofcontents
\onecolumn
\section{多维随机变量的定义}

\section{二维随机变量的联合分布函数及性质}

\subsection{性质}

\section{联合分布律的概念及性质}

\section{联合概率密度的概念及性质}

\subsection{边缘概率密度}

\subsection{性质}

\section{随机变量的独立性}

\subsection{等价条件}

\subsection{判断条件}

\section{离散型条件分布}

\subsection{条件分布律}

\subsection{条件分布函数}

\section{连续型条件分布}

\subsection{条件分布函数}

\subsection{条件概率密度}

\section{随机变量函数的分布}

\section{凑字数}

\section{凑字数1}

\section{凑字数2}

\section{凑够了}

\end{document}
```

**Comment by muyuuuu** [comment]
```tex
\maketitle
\twocolumn
```
这个顺序会另起一页，暂时不太想这样，第一页想放标题、作者和目录，第二页开始正文。

**Comment by muzimuzhi** [comment]
> 两栏的目录右侧貌似有点高

这是预期效果。若需要左右栏等高，用 `multicol` 宏包。

```tex
\documentclass[14pt]{ctexart}
\usepackage{multicol}
\title{多维随机变量}
\author{兰铃}

\begin{document}
\maketitle
\noindent\rule{\textwidth}{1mm}\par
\begin{multicols}{2}
  \tableofcontents
\end{multicols}

% sections

\end{document}
```

**Comment by muyuuuu** [comment]
解决了，多谢。

**Comment by muyuuuu** [comment]
![image](https://user-images.githubusercontent.com/43681138/75364044-00646500-58f6-11ea-8bee-cf6c6a2d17fa.png)

oh no，我问的问题lshort里面居然有，。。。。。十分抱歉。。。。。

**Comment by muzimuzhi** [comment]
多栏目录也可看看 `multitoc` 宏包，一则介绍在 https://texblog.org/2013/08/14/tidy-and-compact-table-of-contents-with-multitoc/
