### ISSUE TITLE
关于subfigure宏包冲突

### ISSUE THREAD

**Issue by li-yu-qiang** [CTeX-org/forum#98]
## 检查

- [ x] 已在 issues 中进行搜索（包括已关闭的问题）

## 编译环境

- 操作系统
  - [ x] Windows 7/8/10
  - [ ] macOS
  - [ ] Linux

- TeX 发行版
  - [ ] TeX Live 
  - [ x] MiKTeX 
  - [ ] CTeX

## 描述问题

 1. 我在编译的时候一直出现LaTeX Error: Command \c@subfigure already defined.
 2. 我尝试把其他导入的宏包都去掉还是这样。
 3. subfigure宏包不可以去掉，去掉会导致后面子图编号错误。
## 最小工作示例（MWE）

```latex
%!TEX program =XeLatex+MakeIndex+BibTex
\documentclass[referee]{raa}           
\usepackage{graphicx,times}
\usepackage{natbib}
\usepackage{amssymb,amsmath}
\bibpunct{(}{)}{;}{a}{}{,}
\usepackage{multirow}
\usepackage{url}
\usepackage{booktabs}
\usepackage{threeparttable}
\usepackage{multirow}
\usepackage{longtable}
\usepackage{listings}
\usepackage{graphicx}
\usepackage{subfigure}
\renewcommand{\thesubfigure}{}
\usepackage{caption}
\usepackage[titletoc]{appendix}
\usepackage[version=4]{mhchem}
\usepackage{appendix}

\usepackage[a4paper=true,dvipdfm=true,pagebackref=true]{hyperref}
\hypersetup{pdftitle = The title of my PDF, pdfauthor = My name, pdfsubject= The subject, pdfkeywords = keyword1 keyword2 keyword3} 
\hypersetup{colorlinks = true, linkcolor = green, anchorcolor = red, citecolor = blue, filecolor = red, pagecolor = red, urlcolor = red}
```

（用 XeLaTeX 编译后）输出

```latex
! LaTeX Error: Command \c@subfigure already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
```

## 链接

- TeX.SX:
- GitHub:https://github.com/li-yu-qiang/subfigure.git

**Comment by OsbertWang** [comment]
MWE 给错了……

**Comment by muyuuuu** [comment]
题目是宏包冲突，建议把导言区代码来一下。

**Comment by li-yu-qiang** [comment]
> MWE 给错了……

那可以修改吗...

**Comment by li-yu-qiang** [comment]
> MWE 给错了……

那可以修改吗...

> 题目是宏包冲突，建议把导言区代码来一下。

我放在了下面链接的压缩包里面，不知道这里可不可以修改。

**Comment by OsbertWang** [comment]
> 我放在了下面链接的压缩包里面，不知道这里可不可以修改。

抱歉，我没注意到这个链接。
在 `raa.cls` 文件中已经引用了 `subcaption`，因此你可以直接使用环境 `subfigure`，具体用法请参考它的手册。其他子图包不要用。

**Comment by li-yu-qiang** [comment]
> > 我放在了下面链接的压缩包里面，不知道这里可不可以修改。
> 
> 抱歉，我没注意到这个链接。
> 在 `raa.cls` 文件中已经引用了 `subcaption`，因此你可以直接使用环境 `subfigure`，具体用法请参考它的手册。其他子图包不要用。

所以是直接去掉subfigure这个宏包吗，我去掉之后后面生成子图的时候编号会出问题而且一直报错。

**Comment by muyuuuu** [comment]
第一步，打开链接代码，发现括号不匹配
![image](https://user-images.githubusercontent.com/43681138/75363040-897a9c80-58f4-11ea-9191-03d317aca100.png)
抛开其他问题一路回车勉强吧
![image](https://user-images.githubusercontent.com/43681138/75363277-db232700-58f4-11ea-8079-a0a49314e298.png)

**Comment by li-yu-qiang** [comment]
> 第一步，打开链接代码，发现括号不匹配
> ![image](https://user-images.githubusercontent.com/43681138/75363040-897a9c80-58f4-11ea-9191-03d317aca100.png)
> 抛开其他问题一路回车勉强吧
> ![image](https://user-images.githubusercontent.com/43681138/75363277-db232700-58f4-11ea-8079-a0a49314e298.png)

不好意思，可能是我删减的时候删错了什么。我导师要求编译的时候不要出错，所以一直回车不太好吧...

**Comment by muzimuzhi** [comment]
@li-yu-qiang 
> > > 我放在了下面链接的压缩包里面，不知道这里可不可以修改。
> > 
> > 
> > 抱歉，我没注意到这个链接。
> > 在 `raa.cls` 文件中已经引用了 `subcaption`，因此你可以直接使用环境 `subfigure`，具体用法请参考它的手册。其他子图包不要用。
> 
> 所以是直接去掉subfigure这个宏包吗，我去掉之后后面生成子图的时候编号会出问题而且一直报错。

是。根据 `subcaption` 宏包文档的首页，
> This package is incompatible with the `subfigure` and `subfig` packages.

**Comment by li-yu-qiang** [comment]
> @li-yu-qiang
> 
> > > > 我放在了下面链接的压缩包里面，不知道这里可不可以修改。
> > > 
> > > 
> > > 抱歉，我没注意到这个链接。
> > > 在 `raa.cls` 文件中已经引用了 `subcaption`，因此你可以直接使用环境 `subfigure`，具体用法请参考它的手册。其他子图包不要用。
> > 
> > 
> > 所以是直接去掉subfigure这个宏包吗，我去掉之后后面生成子图的时候编号会出问题而且一直报错。
> 
> 是。`subcaption` 宏包文档的第一页就写了，
> 
> > This package is incompatible with the `subfigure` and `subfig` packages.

主要是我想让子图不显示编号，所以加了\renewcommand{\thecaption}{}，如果删掉subfigure这个宏包的话后面就没办法正常编号一直报错。

**Comment by OsbertWang** [comment]
> 主要是我想让子图不显示编号，所以加了\renewcommand{\thecaption}{}，如果删掉subfigure这个宏包的话后面就没办法正常编号一直报错。

让子图不显示编号，可以考虑引用 `caption` 包。
```LaTeX
\documentclass[referee]{raa}
\usepackage{graphicx}
\usepackage{caption}
\begin{document}
\section{The spectrum of $NH_2D$}\label{app1}
\begin{figure}[htbp]
  \centering
  \begin{subfigure}{0.45\linewidth}
    \includegraphics[width=\linewidth]{1.pdf}
    \caption*{G000.67-00.03}
  \end{subfigure}
  \begin{subfigure}{0.45\linewidth}
    \includegraphics[width=\linewidth]{2.pdf}
    \caption*{G005.88-00.39}
  \end{subfigure}
  \caption{A figure}
\end{figure}
\end{document}
```
我在 windows 系统下，利用 `epstopdf` 先把 `.eps` 文件变成了 `.pdf` 文件。结果如下：
![例子](https://user-images.githubusercontent.com/37971080/75364988-83d28600-58f7-11ea-89e1-355aedde7e14.png)

**Comment by li-yu-qiang** [comment]
> > 主要是我想让子图不显示编号，所以加了\renewcommand{\thecaption}{}，如果删掉subfigure这个宏包的话后面就没办法正常编号一直报错。
> 
> 让子图不显示编号，可以考虑引用 `caption` 包。
> 
> ```
> \documentclass[referee]{raa}
> \usepackage{graphicx}
> \usepackage{caption}
> \begin{document}
> \section{The spectrum of $NH_2D$}\label{app1}
> \begin{figure}[htbp]
>   \centering
>   \begin{subfigure}{0.45\linewidth}
>     \includegraphics[width=\linewidth]{1.pdf}
>     \caption*{G000.67-00.03}
>   \end{subfigure}
>   \begin{subfigure}{0.45\linewidth}
>     \includegraphics[width=\linewidth]{2.pdf}
>     \caption*{G005.88-00.39}
>   \end{subfigure}
>   \caption{A figure}
> \end{figure}
> \end{document}
> ```
> 
> 我在 windows 系统下，利用 `epstopdf` 先把 `.eps` 文件变成了 `.pdf` 文件。结果如下：
> ![例子](https://user-images.githubusercontent.com/37971080/75364988-83d28600-58f7-11ea-89e1-355aedde7e14.png)

这样的话如果我要插入几十张子图，都可以通过控制图片的尺寸，来控制每行图片的数目吗

**Comment by OsbertWang** [comment]
> 这样的话如果我要插入几十张子图，都可以通过控制图片的尺寸，来控制每行图片的数目吗

修改 `subfigure` 环境的尺寸吧

**Comment by li-yu-qiang** [comment]
> > 这样的话如果我要插入几十张子图，都可以通过控制图片的尺寸，来控制每行图片的数目吗
> 
> 修改 `subfigure` 环境的尺寸吧

对，就是修改width

**Comment by OsbertWang** [comment]
> 对，就是修改width

只要你不怕麻烦，修改 `subfigure` 环境的尺寸，能够手动控制每行图片的数目。自行尝试吧。

**Comment by muzimuzhi** [comment]
@li-yu-qiang 
> 这样的话如果我要插入几十张子图，都可以通过控制图片的尺寸，来控制每行图片的数目吗
> https://github.com/CTeX-org/forum/issues/98#issuecomment-591521020

可以。可以单独控制每一张图片的宽度。

**Comment by muzimuzhi** [comment]
@li-yu-qiang 
请问，你的问题是否已得到解决？若已解决，可关闭当前 issue。

**Comment by li-yu-qiang** [comment]
> @li-yu-qiang
> 请问，你的问题是否已得到解决？若已解决，可关闭当前 issue。

已解决
